### ISSUE TITLE
Dealing with undesirable posters.

### ISSUE THREAD

**Issue by remcopeereboom** [exercism/exercism#3753]
I was reading through some people's comments and came across some troll posts. Do we have any way to deal with that?

**Comment by kytrinyx** [comment]
I'd be most interested in some sort of "shadow deleting":

- give comments an is_visible column and a is_reported column
- only show if is_visible is true or it's your own comment
- add a "report" feature that literally sets is_reported to true
- have a page where trusted folks can review and set visibility to false on troll-y posts

**Comment by kotp** [comment]
Having "private" comments available on the problem comment so "trusted folks" can make themselves known to the problem poster, and hopefully get the behavior corrected.

**Comment by iHiD** [comment]
@remcopeereboom Sorry I missed this. Links to the posts here or if you feel safer over email (jez.walker@gmail.com) would be appreciated.

@kytrinyx We could do a batch delete of any known bad comments at the end of ETL?

**Comment by kytrinyx** [comment]
> We could do a batch delete of any known bad comments at the end of ETL?

Yes, absolutely.

**Comment by remcopeereboom** [comment]
@iHiD Thanks for the reply. I'll link to any questionable posts on the github issue tracker from now on.

**Comment by guygastineau** [comment]
Should first-time trolls be referred to the Code of Conduct

https://github.com/exercism/mentors/blob/master/CODE_OF_CONDUCT.md

Should this only be invoked after review by trusted folks, or is it appropriate for any community member to link the CoC when they see inappropriate posts?

**Comment by iHiD** [comment]
@guygastineau Thanks for discussing this. It's important to us.

If you see things, 
1) Please email abuse@exercism.io with a link. We will keep this confidential, but it is important that we know so we can take action quickly.
2) Everyone should feel free to refer people to the COC, but it's probably best to do that in a question form "Do you feel like that comment is aligned to Exercism's COC" rather than "You're in violation of the COC". The former makes less judgement and puts you in a less uncomfortable position. 

(cc @kytrinyx)

**Comment by guygastineau** [comment]
@iHiD hey thanks for the response!

` refer to the CoC as a question`
I think that is a great strategy for diffusing instead of antagonizing.

` email abusive@exercism.io with a link`
I like the idea of this protocol for passing it along for serious review.

Is there somewhere that these things are documented?  Or is it just here for now?

**Comment by iHiD** [comment]
There's a page linked to on the bottom of the site:
https://exercism.io/report-abuse

Any extra stuff you want to add via a PR would be super appreciated though.

**Comment by guygastineau** [comment]
Great, I'll take a look and see if I think it is clear.  I really appreciate all the work that has been done in moving to V2. I'm sure it hasn't been easy. I'm glad to help with any small role like this.

**Comment by guygastineau** [comment]
exercism/website-copy#178

This is my pull request with the additions I proposed to the report_abuse.md based off of the advice from @iHiD.

**Comment by mbbroberg** [comment]
Hey all 👋. I'm helping out the team by reviewing open issues. I see a few options that I'll work through confirming are completed: 

- [ ] Reporting abuse option is available on the website
- [ ] Batch deleting of abusive comments completed 
- [ ] Report abuse webpage and recommended phrasing is on easy to find

The third item looks complete thanks to @guygastineau's PR merging (thank you for that!). I'll work through the rest.

**Comment by sshine** [comment]
I'm going to close this issue because it seems that it's been partially dealt with.
