### ISSUE TITLE
Release linux packages and update instructions accordingly

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3765]
The current order of instructions implies, that installing from a release tarball per user is the recommended way of installing the CLI.

Usually on every system it should be prefered to use the systems package manager and install globally.

**Comment by kytrinyx** [comment]
Would you please link to the installation instructions in question? Is this the instructions currently on exercism.io? Or on v2 in https://github.com/exercism/interactive-cli-walkthrough?

**Comment by NobbZ** [comment]
I'm talking about the current instructions **and** the v2 walkthrough.

Both do imply the per-user installation in `~/bin` is the prefered way of installation.

This should **never** be the case.

Unless you are actively developing a software or using custom builds, you should always prefer to use the systems package manager and do global installs.

Therefore, in my opinion, we need packages for major platforms:

Debian, Ubuntu, RedHat, Fedora, openSuSE, Arch and maybe Gentoo and Funtoo.

**Comment by kytrinyx** [comment]
Thanks @NobbZ.

> Unless you are actively developing a software or using custom builds, you should always prefer to use the systems package manager and do global installs.

I can see using `/usr/local/bin` instead of `~/bin`, since that means you wouldn't have to edit the shell config / `PATH`. Can you say more about why you should always prefer this? I have not heard any arguments yet that would suggest that this is the case.

> we need packages for major platforms:
> 
> Debian, Ubuntu, RedHat, Fedora, openSuSE, Arch and maybe Gentoo and Funtoo.

I don't have the bandwidth to manage packages. As evidenced by the lack of progress on Exercism itself in the past few months, I don't have bandwidth to do even the bare minimum. I've even considered cutting out the homebrew install for mac users.

Unless someone else can help set this up so that it is

- scripted, and
- any of the users who cut releases can update the packages

this is just not a viable solution for Exercism, no matter how philosophically pure and correct it might be

**Comment by NobbZ** [comment]
"Out of tree" or "out of repo" installations always have the downside, that they are not tracked by the systems package manager and therefore might create orphan files (configs, executables, assets, etc) that are invisible to the systems package manager and might create conflicts in a worst case scenario.

Also when removing a software, a proper package can be easily removed, without worrying to miss some of the orphan files spread through the systems filesystem.

In case of exercism, where we just have a single binary with nearly no dependencies (except for libc), orphans aren't such a big problem, but in my opinion it remains important for a clean system to only allow clean installations.

Another part is the administrativ question on corporate systems, were users aren't even allowed to write to `/usr/local/bin` and need to ask their IT departement to do so (which in turn will usually ask for properly packaged software).

And even though I am short on time at the moment, I can try to set something up, which builds RPM- and DEB-packages in a docker container, which can then be uploaded together with the prebuild tarballs to github releases page.

I do see though, that it would be hard (and near to impossible) to maintain proper repositories for all systems.

ARCH has a user maintained package, gentoo/funtoo is easily doable too, and from my days using a funtoo, [I could at least link to my old package description which might then be used as a template](https://github.com/NobbZ/gentoo-overlay/blob/master/app-misc/exercism-cli/exercism-cli-2.4.1-r3.ebuild) (but I am unable to test it, since I do not use that system anymore).

**Comment by kytrinyx** [comment]
@NobbZ Thanks for elaborating, this is very helpful.

I agree that the ideal would be to have properly managed packages. I am not sure we can manage it right now, but this should be a stretch-goal for nextercism.

**Comment by geckon** [comment]
FWIW, there is a package in openSUSE. Unfortunately it's outdated (version 2.4.0) and thus it doesn't work. There is a bug reported but with no reaction yet:
https://bugzilla.opensuse.org/show_bug.cgi?id=1106476

**Comment by kytrinyx** [comment]
Thanks @geckon, this sort of emphasises my point--we need these to be managed properly if we are to have them.

Is there a way to deprecate the existing openSUSE package so that people don't use it?

**Comment by geckon** [comment]
I'm not sure. It should be possible to delete the package but it might be better to update it which isn't necessarily hard. I suppose that now the new versions won't introduce backward incompatibility (or at least not as significant as this one) and it would be really useful to have the CLI tool distributed via the official repositories as it will be much easier to install especially for new users who want to learn programming with exercism.

**Comment by kytrinyx** [comment]
> It should be possible to delete the package but it might be better to update it which isn't necessarily hard.

Do you know how this is done? What sort of authorization process is there, give that the exercism CLI maintainers did not submit the original package?

**Comment by geckon** [comment]
Not sure about deleting the package. As for update, I think anyone can do the update and submit the updated package and then any of the maintainers can simply approve and that's it. 

I could do the update but it seems that there are some dependencies missing in OpenSUSE and I would need to add those as well which would (I believe) make me their maintainer which is not something I'm particularly willing to do (because then I would be responsible for updating them etc. and I might not have time to maintain some Go libraries not even being a Go programmer myself).

BTW, are these new dependencies for exercism 3?
golang.org/x/text/transform
github.com/blang/semver
github.com/inconshreveable/go-update
github.com/spf13/cobra
github.com/spf13/pflag
github.com/spf13/viper

**Comment by kytrinyx** [comment]
> which is not something I'm particularly willing to do

Yes, this is understandable (and it's the reason we're not actually excited about the idea of having exercism distributed via 3rd party package managers in the first place--the maintenance cost adds up).

> BTW, are these new dependencies for exercism 3?

Yes, however the CLI is distributed as a binary. We package it up and upload the binary, so the dependency only affects the maintainer who is compiling it, not the downstream users.

**Comment by NobbZ** [comment]
As there is active work happening in #700 to actually fix this issue by providing an official `snap` image which will cover most of the linux platforms mentioned above I will close this issue.
