### ISSUE TITLE
Show extra track info pages on External Track page

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#3802]
@nobbz said "I think they should be accessible without joining a track. I might choose my next track after reading install instructions and then deciding which might to get kicked off easiest"

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
