### ISSUE TITLE
In-dev tracks are not accessible anymore

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3806]
After the update to v2 the tracks which are still in development (eg. ReasonML, Haxe, Idris, etc.) are not accessible.

This makes them hard to discover for interested students and potential contributors.

We should bring them back, but perhaps with a big warning, that they can only be joined in “independant mode” and progress will be reset when going active?

**Comment by sshine** [comment]
I'm going to close this issue because I experienced, when building the Tcl track with @glennj, that it was possible to let an upcoming track either be available without being linked to (as it is the case for Tcl at the time of writing), or be available in general. So tracks that are in development are free to choose.
