### ISSUE TITLE
How to remove solutions?

### ISSUE THREAD

**Issue by karpinovsky** [exercism/exercism#3814]

**Comment by iHiD** [comment]
Hi @karpinovsky.

Please could you provide some more information on what you want to achieve and why, please?

Thanks!

**Comment by NobbZ** [comment]
In v1 you were able to remove already submitted solutions, maybe because of accidentally submitted binaries or because of other reasons.

**Comment by felixbuenemann** [comment]
Why was this issue closed? I think this is an important feature.

For example I just submitted a lot of iterations on an exercise because I didn't look too close at my terminal and ran `exercism s` a couple of times from the shell history, instead of the spec command.

Another reason as stated before could be sensitive information submitted by accident.

**Comment by iHiD** [comment]
It was closed because the OP didn't reply with more information after a 3 month wait. 

There is an issue tracking what you discussed here: https://github.com/exercism/backlog/issues/16
