### ISSUE TITLE
Let me preview my profile

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3824]
Is there a way to take a look at my profile in a visitor mode?

I want to see how people see it, who aren't logged in or other users of exercism.

Eg. on Facebook I am able to edit my profile and add stuff and modify visibility and then put myself into a visitor mode, which makes me able to check if all settings are correct by actually seeing the filtered profile.

**Comment by iHiD** [comment]
The suboptimal answer. https://exercism.io/profiles/nobbz

I've renamed this to and set it as a feature request, which we'll do once the essential stuff is all sorted.

**Comment by nickborromeo** [comment]
Looks like the question was answered 👍 but the label was added, does that mean we cannot close this out yet because it being tracked as a potential feature to be implemented later?

**Comment by iHiD** [comment]
Yes. I'd like to keep this as a feature-request for future.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
