### ISSUE TITLE
Ability to sort community solutions by # of Comments and other fields.

### ISSUE THREAD

**Issue by TravisBumgarner** [exercism/exercism#3828]
I'd like to be able to look at most recent so that I can help out anyone having trouble or look at most commented on so I can see where great discussion is occurring/has occurred so I can learn more.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
