### ISSUE TITLE
Iterating a legacy solution removes legacy status and publishes it

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3830]
I iterated a solution of mine (elixir/bank-account) which was in legacy mode before.

After submitting the new iteration, both iterations are published, and I have no choice anymore to move it to the mentors queue.

Is this by design? My expectation was that it either inherits legacy status or counts as unapproved such that it needs to receive mentoring.

**Comment by ErikSchierboom** [comment]
I have also ran into this problem.

**Comment by iHiD** [comment]
Interesting. Yeah - I'd not planned for that behaviour. Will look into it. Thanks.

**Comment by Cohen-Carlisle** [comment]
I ran into this situation as well. I was hoping to update my very old solutions and then enter them for mentorship, but after submitting a new iteration for Bob (in elixir), I lost the option to receive mentorship on it.

**Comment by iHiD** [comment]
We'll remove legacy status altogether in v3.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
