### ISSUE TITLE
Delete a solution

### ISSUE THREAD

**Issue by coriolinus** [exercism/exercism#3832]
This was previously solved by https://github.com/exercism/exercism.io/issues/2720, but with the new site that no longer appears to be possible.

I've figured for a while that once the new site went live, I'd go back and redo all my Rust track exercises. To accomplish this, I need to get rid of the old implementations. How do I do this now?

**Comment by guygastineau** [comment]
If you download the exercise again, then it should store it in a directory called `my-exercise-2` if there is already a directory with the name in your workspace.

Or do you mean that you want to delete it from the site?  I don't think that is necessary for submitting a new iteration.

**Comment by coriolinus** [comment]
I know I could just go back and re-iterate through each of them, but what
I'm looking for is the experience of being guided through the tree of
exercises defined by config.json. So yes, what I would like is to remove it
from the site.

**Comment by guygastineau** [comment]
I understand, hopefully someone who actually knows will see this.  Good luck ;)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by coriolinus** [comment]
I appear not to have sufficient permissions in this repo to just reopen this issue. Nevertheless, this appears to still be a relevant issue.

**Comment by angelikatyborska** [comment]
@coriolinus This will be possible in v3. There's a "reset track" option:
![Screen Shot 2021-08-31 at 08 22 56](https://user-images.githubusercontent.com/7852553/131452444-fbcfedd3-1fff-4ff5-8923-842eae0d8f79.png)

**Comment by coriolinus** [comment]
Great, thanks! In that case, this issue should remain closed.
