### ISSUE TITLE
As a student I want to know which of my solutions are waiting for mentoring and other stats

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3834]
As a student (and a polyglot) chances are high, that I have more than one solution awaiting mentorship. Sidetracks do even potentially increase that number further.

So I'd like to have a students dashboard, where I can check mentoring status of current solutions in the queue.

* which solutions are waiting for a mentor
* which solutions got mentored and require an action by me
* which solutions got mentored and approved

Especially for the first status, age of the item is of special interest and perhaps a possibility to alert track maintainers or site admins about not getting mentored.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
