### ISSUE TITLE
Missing track completion message

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#3839]
I just completed the Delphi track on the new site.  I was presented with the following message

Ipsum lorem......

Ok so there is some message I need to create that the site will display at this point....  At the moment I don't know what document needs to be created in the Delphi track.

**Comment by jackhughesweb** [comment]
(For reference: this message is at https://github.com/exercism/website/blob/2c2bd691297c0990fba68d1b53803d8303f6f6e9/app/views/my/tracks/_finished_modal.html.haml#L5 )

**Comment by rpottsoh** [comment]
@jackhughesweb thanks for locating....  It would seem that a better message is needed there.  To me the issue is is it a canned message that is displayed to everyone on all tracks or can this point to some file maintained by the maintainers of each track?

**Comment by sshine** [comment]
So when you complete a track, do you get an empty dialog?

**Comment by sshine** [comment]
We could just replace it with *any* positively sounding message, like

> Congratulations for completing the track!

But I'm a bit puzzled that it isn't the case.

Could it be that this stuff is actually fixed, but neither this particular issue nor exercism/website#385 was referenced?

**Comment by iHiD** [comment]
It says:

> Well done!
> You've completed the XXX Track

But we just need the extra sentence I guess. I'll try and do that this week.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
