### ISSUE TITLE
students: When im on my profile and click the language field, I can not type (initially)

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3845]
On my profile there is a language filter, per default it shows “All”. When I click that box, I have a blinking cursor in that box and a dropdown.

My expection from similar UI elements is, that I can either type to narrow down the list and **add** a language to the filter or that I can type to narrow down and **replace** the current filter.

The way it is implement now, requires me to hit <kbd>Backspace</kbd> (<kbd>⌫</kbd>) first to delete the old content, before I can type to filter the list of filters. Typing before deleting the old content, does not do anything. Explicitely deleting feels superflous, since we have no choice either.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
