### ISSUE TITLE
Add button to delete iteration

### ISSUE THREAD

**Issue by daverick** [exercism/exercism#3848]

**Comment by NobbZ** [comment]
You can't, just fix the error and resubmit.

**Comment by Cohen-Carlisle** [comment]
I think it would be useful to have the delete option back. It ends up being less noise, especially if you do something really silly like submit the wrong file(s) entirely like the tests instead of the solution, etc. In my case I submitted the tests and solution and would like the replace it with just the solution.

**Comment by remcopeereboom** [comment]
There is also a privacy/security issue where someone may have submitted a wrong file or whatever. It seems useful to be able to delete a submission in such a case.

I do remember being annoyed in the old exercism if I wrote useful feedback and then someone takes that on board but deletes the old submission "to erase" any bad code and then my hard work commenting would be deleted as well...

**Comment by Cohen-Carlisle** [comment]
Bumping this because I made yet another bad submit. I guess I'm clumsier than the average exercist? :smiling_imp:

**Comment by stevensonmt** [comment]
I would echo the desire for a delete submission method.

**Comment by sshine** [comment]
@remcopeereboom wrote:
> *[...]* annoyed in the old exercism if I wrote useful feedback and then someone takes that on board but deletes the old submission "to erase" any bad code and then my hard work commenting would be deleted as well

Perhaps deleting an iteration could work in such a way that comments are not deleted:

- When an iteration is deleted, the submitted code is removed from the database (for privacy), and the iteration is marked as deleted.
- If a deleted iteration already has comments by anyone other than the exercist, the iteration is shown in the track, but clicking it only shows the comments and not any code (since there isn't any).
- If a mentor starts commenting on an iteration that then gets deleted, allow for adding the comment to that deleted iteration so that it's shown.

I don't know how this plays into how the UI works when exercists submit new iterations while you're commenting on an old one, but perhaps the same kind of notification one might get when commenting on something out-of-date is appropriate here, too.

**Comment by PatrickMcSweeny** [comment]
I was about to open a new issue for this before I found this one. This would be a nice feature to have.

**Comment by PatrickMcSweeny** [comment]
Woops, I didn't realize I had the power to unassign people lol.

**Comment by xianrusso** [comment]
YES!  I would be very inclined to work on this issue.

**Comment by rwz** [comment]
> I guess I'm clumsier than the average exercist? 

You really are not. Or at least not clumsier than me.

Every time I submit my first solution and go check out solutions by other people, I get a lot of ideas and start playing with my code. I normally jump between my tmux panes to edit the code and run tests, back and forth. I run tests by pressing up arrow or just typing `!!` in the terminal and re-running last command since it's usually the test command. However right after the submission, this pattern breaks and I end up accidentally re-running the submit command, but with some broken and half-written code instead. I have a lot of really broken solutions that are submitted by mistake that I'd really like to remove.

**Comment by mandrean** [comment]
I just did this as well 😩

Any progress on the roadmap?

**Comment by iHiD** [comment]
We're currently redesigning that whole section of the UI, so this will probably come as part of that :)

**Comment by Eddie-Hartman** [comment]
@iHiD Any activity on this? Could we potentially see it in V3?

**Comment by iHiD** [comment]
Yeah, coming in v3 (cc @taiyab)

**Comment by taiyab** [comment]
On it 👍

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
