### ISSUE TITLE
Make solutions accessible to non-mentors for discussion

### ISSUE THREAD

**Issue by ser1us** [exercism/exercism#3856]
For example: As a mentor I might have seen (or created myself) a nice solution for an exercise. I would like to copy the link into comments so people can have a look if they are stuck. 

Now, if I check out my solutions the URL always contains `/my` and in the mentor dashboard it contains `/mentor/`. It would be nice to have an easier way to copy a permalink to a solution than adjusting the URL by hand.

Cheers!

**Comment by NobbZ** [comment]
You need to complete and publish your solution.

You can find the link to a published solution via your profile or from the tracks overview and then going to the exercise page.

**Comment by ser1us** [comment]
thanks @NobbZ , but still quite a lot of work for such a simple task ;)

**Comment by iHiD** [comment]
I've renamed this to reflect the desire (allow non-mentors to see a non-published solution) rather than one of the implementation-details of the URL.

This is something we're actively discussing, but it's complicated as it has a wealth of tradeoffs and associated changes.

**Comment by iHiD** [comment]
This type of approval is disappearing in v3, so this will be fixed by that.

**Comment by ser1us** [comment]
Nice. Shall we close the issue then?

**Comment by iHiD** [comment]
No, I'll leave it open with the appropriate label, as a checkpoint to myself to make sure it actually does get fixed :) Thanks though!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
