### ISSUE TITLE
Student: make prerequisites for extra exercises discoverable

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3857]
As a student I want to know how far in the core I need to progress to open a certain set of extra exercises. Currently I have to look up the prerequisite in the track config on GitHub. It would be nice if the prerequisite would be displayed on an exercises card.

**Comment by ErikSchierboom** [comment]
This would be super nice!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
