### ISSUE TITLE
Access test suit through exercise webpage before submitting code

### ISSUE THREAD

**Issue by nmegrant** [exercism/exercism#3872]
This could be a purposeful change, so please ignore if so. It's just something that I find inconvenient when working on exercises.

I always found it useful to be able to look at the test suit from the exercise's webpage. Just more convenient than having to open up the file in my text editor. After migration the "Test Suit" tab is no longer present when I download the exercise. This is what it looks like after downloading the Allergies exercise, before submitting a solution.
![screen shot 2018-07-17 at 8 33 08 am](https://user-images.githubusercontent.com/37487734/42782102-09972ad4-899c-11e8-83a8-630d6220e3fc.png) 

The tab to look at the test suit only appears on the webpage after I've submitted a solution. For me, this is when it's least helpful. This is what it looks like after submitting a solution to the Bob exercise. I can now easily see the test suit I was using to test my code. 
![screen shot 2018-07-17 at 8 34 10 am](https://user-images.githubusercontent.com/37487734/42782184-3d2cbee0-899c-11e8-8edf-39a098cab774.png)

I'm wondering if the second view (with test suits) should be available as soon as the exercise is downloaded (or even before). I think it's good practice to have the tests easily available, so new coders get used to the idea of writing to tests. Just my thoughts on it!

**Comment by iHiD** [comment]
Thanks for your idea! Once we've got through all bugs I'll dive into this more with you and the exercism product team :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
