### ISSUE TITLE
New editor button: Spoiler

### ISSUE THREAD

**Issue by ser1us** [exercism/exercism#3879]
Hello

I thinkthis might be a very nice addition to the wysiwyg editor: A spoiler tag.

For example:
I'm reading an Elixir solution and I noticed the person calculates the same intermediate result three times in the same function. Now I want to challenge the person and ask if he/she can find a way to improve it. Without giving too much away of course, but it would be nice in my case to add a link to the `with` statement in the spoiler tag. 

Just a thought  :)

Cheers

**Comment by NobbZ** [comment]
Can't you use the HTML directly?

<details>
Details...
</details>

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
