### ISSUE TITLE
mentor: notifications do not display enough information

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3883]
As a mentor, when I receive a notification about a students reaction, that notification only tells me that the student has iterated or commented.

As a mentor of 2 tracks, I'd like to see in advance which track the notification belongs to.

As a mentor of at least one track with mor than a single exercise, I'd like to see in advance which exercise the notification belongs to.

**Comment by Le1gh** [comment]
Issue was fixed on July 19. Commit hash 5ebeccb2ebd1a122c51750a57f085323501ecdd0

**Comment by iHiD** [comment]
@Le1gh Thanks for helping. I think @NobbZ is talking about notifications rather than about emails, though.

**Comment by NobbZ** [comment]
Yes, I'm talking about on site notifications here. But as far as I remember a similar issue has been created for emails as well.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
