### ISSUE TITLE
mentor: age of a solution to mentor

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#3886]
As a mentor I'd like to roughly know the age of each iteration.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
