### ISSUE TITLE
mentorcism: Cannot clear star rating

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3896]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/205._
_Originally posted by @ErikSchierboom._

#

When one completes an exercise, you can give stars to rate your mentor:

![image](https://user-images.githubusercontent.com/135246/42570128-2918d3e0-8513-11e8-8c34-2605004de167.png)

However, once you select one or more stars, you cannot then unselect the stars.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
