### ISSUE TITLE
Add a few emojis on mentors comments

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3902]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/193._
_Originally posted by @oliakremmyda._

#

I thing it would be a nice add on if mentor comments could include a 👍 icon or a 😄 to react on a solution, for a more positive feedback!

**Comment by alexito4** [comment]
FWIW the input text and the system accept emojis without problem. If you can get them from your keyboard (ctrl+cmd+space in macOS) it works fine 😊

**Comment by SaschaMann** [comment]
It would be really nice to have tab-completable shortcuts like `:wave:` for 👋 in the editor, just like in Slack or on GitHub.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
