### ISSUE TITLE
[Mentors Dashboard] When non-default status is selected returning back to the dashboard discards the selected option

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3905]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/189._
_Originally posted by @oliakremmyda._

#

When non-default status is selected leaving the dashboard and returning back does not remember the selected option

I have noticed that when you are in 
the _mentors dashboard > Select status: `Waiting for them` > Open one solution > use back button_ 
to check the rest waiting solutions and they are disappeared. 
You have to choose another status and then back the _waiting_ one to see them again

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
