### ISSUE TITLE
Request: Additional exercise states

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3915]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/175._
_Originally posted by @melston._

#

This request applies predominately to the 'extra' exercises but it could also apply to the primary track exercises.

It is a bit annoying that the act of downloading an exercise marks it as "In Progress."  The problem is that it makes that exercise indistinguishable from all the other exercises that are also "In Progress."  If I have downloaded an exercise and not submitted a solution yet I can't tell this from the '/my/tracks/<language>' page as all exercises, whether downloaded or submitted (but not yet approved), are shown identically.

For my purposes, a better solution would be to identify all exercises with submitted solutions with a different state.  Perhaps "Submitted" or "Waiting Review", or something similar.  If a solution is submitted but is not accepted (e.g. the mentor believes more should be done) then it could be moved back to the "In Progress" state, indicating (at a glance) which exercises require further work on the student's part.

It might even be helpful for the student to mark a "Completed" solution as back to "In Progress" if s/he wishes to do some further work on it and get more feedback.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
