### ISSUE TITLE
Cannot easily continue to next solution to mentor

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3917]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/172._
_Originally posted by @ErikSchierboom._

#

When I have reviewed a solution, there is no easy way to go to the next solution, except for to go back to the completed list of solutions to review. I think it would help speed up things if there was such a link.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
