### ISSUE TITLE
Missing tooltip for extra exercise status icon

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3924]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/160._
_Originally posted by @ErikSchierboom._

#

The core exercises have text to show what their status is (in progress, etc.). The extra exercises have an icon, which is less obvious. To help understand which status the icon represents, it should probably have a tooltip of some sort containing the textual status.

**Comment by iHiD** [comment]
I wonder if we should set it in the html instead? I'm in meetings today but
will ask Nicole about it over the weekend to see if she wants to make a
design.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
