### ISSUE TITLE
Thoughts on Mentors -> Solution -> Instructions tab

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3934]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/141._
_Originally posted by @F3PiX._

#

`/mentor/solution/:id`
- On the Instructions tab: I'd prefer to have all the exercise related info together. Currently, the source of the exercise is at the bottom of the info, after the general submission info. (Which made me read all the submission info, to see if I missed other exercise related info.)
BTW I wouldn't mind if the submission info is omitted in this tab. 
- When reviewing a solution, I'd like to see (a link to) the student's other solutions (different exercises), to get a feel for their level and how they respond to feedback. So I can finetune my feedback.   
- As long as we don't have the 'community favorites', I'd like to have a link to my own solution, for a quick reference.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
