### ISSUE TITLE
How can I find my history of comments

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3939]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/131._
_Originally posted by @martinfreedman._

#

How does one find one's history of comments, presumably with metadata such as exercise, iteration and  addressee? (see #130)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
