### ISSUE TITLE
Publishing multiple iterations

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3940]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/129._
_Originally posted by @martinfreedman._

#

In some challenges I have different iterations and my comments refer to other iterations to make a discussion/comparison, often there not being ONE TRUE Way to solve the problem. How do you publish such sets of iterations for review and discussion?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
