### ISSUE TITLE
Upcoming or planned tracks not listed

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3945]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/114._
_Originally posted by @wolf99._

#

It's not possible to see upcoming or planned tracks. Maybe this is in the TODO work or something. 

I got started with Exercism on the C track, which still hasn't graduated from upcoming. If I came to the site wanting to do some C exercises and saw it wasn't listed I would leave again without even signing up, without knowing that there is in fact a C track, that is usable and that I could contribute to. 

This would probably end up with such tracks dying off or never coming to be in the first place because people would never see them and never contribute to them.

Thus I guess this is a feature request that the upcoming and planned language tracks be displayed somehow, both to users signed in and not signed in.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
