### ISSUE TITLE
Breadcrumb path is inconsistent

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3947]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/100._
_Originally posted by @ErikSchierboom._

#

If I view a [specific solution](https://v2.exercism.io/tracks/csharp/exercises/etl/solutions/723c6fe0cd3158dec06849bc), the crumb path is: Language Tracks -> C# Track -> Community Solutions -> This Solution

This makes sense, as the crumb path represents the hierarchy for the solution. However, if I click on the [Community Solutions link](https://v2.exercism.io/tracks/csharp/exercises/etl/solutions), the crumb path changes to: Language Tracks -> C# Track -> Your Solution to Etl -> Community Solutions

I think this should be: Language Tracks -> C# Track -> Community Solutions -> Your Solution to Etl

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
