### ISSUE TITLE
Add filtering to Solutions you've liked page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3948]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/99._
_Originally posted by @ErikSchierboom._

#

It would be convenient to be able to filter the Solutions you've liked page, to help find that one like you are looking for. Possible filters would be: track, exercise, submitter, status (well done, love, genius).

**Comment by kayn1** [comment]
@kytrinyx Is this issue still active?

**Comment by iHiD** [comment]
Nope :) If you'd like to help out with Exercism, [this issue](https://github.com/exercism/exercism/issues/5386) is a good place to start. Thank you! :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
