### ISSUE TITLE
Solutions you've liked page doesn't show track nor exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3949]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/98._
_Originally posted by @ErikSchierboom._

#

On the Solutions you've liked page, I can see an overview of which solutions I've liked. However, I can't see the solution's exercise name nor the solution's track, both of which are important pieces of information.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
