### ISSUE TITLE
There is a blinking cursor on the profile when choosing languages…

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3950]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/96._
_Originally posted by @NobbZ._

#

…that does imply the possibility to type and filter the list (which I really like to do, since my list is long…) but you can't filter or type

![blinking-cursor-suggests-editability](https://user-images.githubusercontent.com/58951/29794426-37835118-8c48-11e7-95c6-639ba0427d9e.png)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
