### ISSUE TITLE
Show my/commenters solution

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3951]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/95._
_Originally posted by @NobbZ._

#

When mentoring I'd like to quickjump to my own solution (if applicable) as I am able to with the big `</>` Button in the upper right corner of V1.

Also I really liked to be able to quickjump to a commenters solution when browsing other people submissions as it was possible via the `</>` button below ones comment.

Of course the student shouldn't be able to just peak into the mentors solution ;)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
