### ISSUE TITLE
Allow filtering on status/comments on profile page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3958]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/51._
_Originally posted by @ErikSchierboom._

#

The profile page shows my solutions. Perhaps it would be useful to be able to filter on the solution "status" (thumb, heart, genius) or on solutions that have one or more comments.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
