### ISSUE TITLE
Script a PR to each track's config.json which adds the relevant file extensions

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3961]
See issue in https://github.com/exercism/meta/issues/108

**Comment by iHiD** [comment]
Assigning you to this to work out, manage, close etc :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
