### ISSUE TITLE
Update the /api/v1/tracks/:track_id to include file extensions in the payload

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3962]
As part of https://github.com/exercism/meta/issues/107 we are ensuring that the track `config.json` file contains a list of extensions that the programming language uses for its files.

We will need to deliver those extensions as part of the payload that the CLI calls to store track-specific configuration locally. If the config file does not have an `extensions` key, then deliver an empty array.

The key will be named `extensions`, and it will be an array of bare extensions (no dot): `["cpp", "h"]`. Use the same thing in the payload for the API.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
