### ISSUE TITLE
Missing tooltip for extra exercise status icon

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#3967]
https://github.com/exercism/v2-feedback/issues/160

**Comment by iHiD** [comment]
No. This is for tooltips at the side exercises at the bottom of the page.

**Comment by LogaJ** [comment]
Hi @iHiD since [this PR](https://github.com/exercism/website/pull/324) has been merged, can this issue be closed?

**Comment by srishtiBajpai** [comment]
Hey! Is this issue closed already?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
