### ISSUE TITLE
Open a team and be the designated mentor

### ISSUE THREAD

**Issue by guygastineau** [exercism/exercism#3979]
Hi all,
  I have some science student friends I am trying to encourage to learn programming.
I know them well, and having had countless discussions on academic topics I think I would well suited to be their mentor.  I know teams aren't up and running yet in V2, but I was wondering if the idea of a team specific mentor had been thrown around at all.  I think it is worth considering.  I only consider myself qualified in bash, but I imagine there are others who would find this functionality appealing too.

**Comment by guygastineau** [comment]
Oh okay.

- If there is a repo I wouldn't mind taking a look at the documentation and seeing if there is anywhere that I could help review or expand documentation.  

- Also, after you respond to that question I guess I'll close this issue.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
