### ISSUE TITLE
Mentors commenting instead of validating

### ISSUE THREAD

**Issue by FabienTregan** [exercism/exercism#3987]
## What happened

I made this mistake at least once: I clicked the attractive "comment" button instead of the "validate and comment" button (the first one is bright green, the later is white / almost seems disabled).

I still could validate the Solution, but I did not notice I made this error until the Student added a comment to ask if I didn't forget to validate.

In the long term we could have automatic validation once the tests pass and the mentors would just make code review. But it may not be that simple to do (partly discussed in #3882)

## What we could do *(TL;DR)*

 * Add some place for a Mentor to list all the solutions s.he commented but did not validate
 * Make "validate and comment" the bright button
 * Add a warning when a Mentor comment without validating
 * Look in the database to see if tens or student are stuck waiting for missed validationg

**Comment by NobbZ** [comment]
I do much more comments without validating then the other way round, as often the solutions pass the tests but simply do not match the criteria of being tidy or idiomatic solutions or are otherwise not optimal.

**Comment by iHiD** [comment]
V3 will fix this as approval will change

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
