### ISSUE TITLE
Can't open notifications.

### ISSUE THREAD

**Issue by remcopeereboom** [exercism/exercism#3991]
I am getting notifications on people commenting on my submissions but their comments don't show up (a lot of the old comments are missing as well, but some do show up).

I am also getting notifications on people posting iterations on solutions that I am "mentoring", but I am not actually a mentor.

When I click on a notification about my own code I am brought to the right page, but the comments or likes or whatever don't show up (I can see some of the really old ones, but not all of them).

When I click on any of the mentoring notifications I am brought to a page with a redirect link but otherwise empty. The URL seems to be correct, e.g. "https://exercism.io/mentor/solutions/#{hash code}".

**Comment by remcopeereboom** [comment]
It's been a few months... I was wondering if someone could take a look or otherwise let me know and I'll just close the request.

**Comment by iHiD** [comment]
@remcopeereboom Hello. So sorry for the lack of response. I totally missed this.

So I presume people are commenting on solutions you commented on in v1, but because you're not a mentor you can no longer see those comments because the link doesn't work for you.

Does that sound feasible? If so, I'll mark this as a bug accordingly.

**Comment by remcopeereboom** [comment]
@iHiD No worries, and thanks for looking. I know everyone is busy and giving up there free time to help.

> I presume people are commenting on solutions you commented on in v1, but because you're not a mentor you can no longer see those comments because the link doesn't work for you.

Yes that's pretty much what I think is happening.

Note that I also can't see people's new comments on my own submissions and I feel like not all of the old comments made it over in the migration either. Those seem to me like they might be separate issues, however.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
