### ISSUE TITLE
Independent Mode: filtering by difficulty does not persist 

### ISSUE THREAD

**Issue by letakeane** [exercism/exercism#3997]
[imgur - link to demonstration of issue](https://imgur.com/9M3gRgr)

In the JavaScript independent mode (I have not tried this in other languages or modes), when filtering the difficulty of the displayed exercises using the dropdown, the exercises filter as expected.

However, when:
1. an exercise is clicked, and then 
2. the user navigates back to the previous page, 

the Difficulty dropdown menu still reflects the desired level, but the displayed exercises are no longer filtered. 

To get the exercises to display properly, a different difficulty level must be selected from the dropdown, and then the desired difficulty level must be selected again.

**Comment by iHiD** [comment]
Thanks for reporting this and suggesting the change. 

We will do this once all the bugs and v1-v2 migration issues are sorted :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
