### ISSUE TITLE
Show track backlog size in the Mentor Dashboard

### ISSUE THREAD

**Issue by pgaspar** [exercism/exercism#4032]
@iHiD shared some numbers recently pointing out how many solutions were waiting mentorship in all tracks. He separated solutions in 2 groups: core exercises and side exercises.

As a mentor it would be useful (to me at least) to have access to these numbers in real-time, so that I can better prioritize my time and better understand if I need to mentor more or less solutions in a given day.

Considerations:

* How can we show these numbers without discouraging and overwhelming mentors?

More details on this exercism mentors slack thread: https://exercism-mentors.slack.com/archives/CARRG4MNC/p1532211025000054

**Comment by devillexio** [comment]
I think this is a great idea, and I agree with the sensitivity with which this should be approached.

Information (possibly in chart format) that would be great to represent on the mentorship dashboard -

* number of pending exercises
* the split between core vs. extra exercises
* trend over time (to help determine whether we're keeping up)

I think the important part is how this data is _sold_ (lack of a better word) to the mentors. The idea is not to overwhelm folks with spectacular numbers of submissions, but to rather provide honest insight into how we're tracking. This may show that we are making progress, even if it is a bit slow, or even show that we are not coping at all. In the case of the latter, we should see the problem and try come up with a means of tackling the problem. Just because the numbers are hidden doesn't mean that a problem doesn't exist.

**Comment by iHiD** [comment]
This got done :)
