### ISSUE TITLE
Notification emails should have the student's comments in it or the iteration code.

### ISSUE THREAD

**Issue by corroded** [exercism/exercism#4034]
Since the emails are now threaded by UUID, I think a nice improvement would be to add the changed code or the student's comments if there are any. That way, mentors on the go can see in a quick glance if they can just approve the solution, make a quick reply/comment to a student's question or put it off for later when they have more time to write a lengthy/proper answer.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
