### ISSUE TITLE
Better handle ActiveRecord::RecordNotFound in solutions#show

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4038]
## Error in Exercism V2

**ActiveRecord::RecordNotFound** in **solutions#show**
Couldn't find Track without an ID

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b4e0060c09b1b0019d069b3?event_id=5b55bbf20027202e26610000&i=gh&m=ci)

## Stacktrace

    app/controllers/solutions_controller.rb:37 - show

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b4e0060c09b1b0019d069b3?event_id=5b55bbf20027202e26610000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::RecordNotFound** in **solutions#show**](https://app.bugsnag.com/exercism/exercism-v2/errors/5b4e0060c09b1b0019d069b3?event_id=5b55c19d002722e932910000&i=gh&m=ra)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
