### ISSUE TITLE
Update branding and copy on 3rd party websites

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4043]
Open source sites:
- [ ] http://24pullrequests.exercism.io
- [ ] https://www.codetriage.com/exercism/cli

Product sites:
- [ ] https://www.producthunt.com/posts/exercism

**Comment by pgaspar** [comment]
Just a quick :+1: and bump here as I just noticed http://24pullrequests.exercism.io myself.

Apart from the things mentioned in the title of this PR, I also noticed that it links to issues tagged with ["good first patch"](
https://github.com/exercism/exercism.io/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+patch%22), but there are none. I couldn't find that label in the label list, so I assume it was deprecated.

**Comment by sshine** [comment]
Status update:
- [x] http://24pullrequests.exercism.io no longer works
- [x] https://www.codetriage.com/exercism/cli doesn't contain any *wrong* branding, but it also doesn't look like we *use* this service. I've moved dealing with this to #5038 since there is branding to be updated.
- [ ] https://www.producthunt.com/posts/exercism still has old branding, so that is the only outstanding issue here.

@nicolechalmers: Do you know who *can* update the Exercism logo on Product Hunt?

**Comment by nicolechalmers** [comment]
@kytrinyx Are you the creator of the Exercism page on Product Hunt? If so, is it possible to add an extra admin person so I can add the new logo?

Thanks for updating the others @sshine

**Comment by kytrinyx** [comment]
I'm not the one who created the page, but it looks like maybe the first person who posted there is... and I met them a couple years ago (amazingly, they posted this several years before we met!).

**Comment by iHiD** [comment]
@kytrinyx Did you ever manage to speak to them?

**Comment by kytrinyx** [comment]
Yeah, but there didn't seem to be anything anyone was willing to do.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
