### ISSUE TITLE
New comment notification should link to relevant iteration

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4062]
Currently the new comment notification links to the latest iteration as default. I think it would be more useful to link to the iteration with the comment.

**Comment by TaylorBeeston** [comment]
Does this still happen? I believe it is fixed for me

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
