### ISSUE TITLE
I received a notification that leads to a 403 page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4064]
I received a notification today for solution with UUID `0ecef898d96c430ca8eb3a896f5f1be4`. 

It says:

```
iHiD posted a comment on a solution you are mentoring
```

When I click on the solution, I get a [403 Forbidden](https://httpstatuses.com/403).

**Comment by kytrinyx** [comment]
I believe what happened here is that I have previously mentored Ruby exercises (in v1), but am not a mentor on the Ruby track, and therefore am getting 403s on any exercises where I previously mentored.

I'm pretty sure we decided that you can always solutions that you've commented on, but we'll need to make sure that you can't approve anything if you've not chosen to mentor on the track explicitly, and that people aren't asked to rate you when they complete an exercise.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
