### ISSUE TITLE
Order of community solutions is suboptimal

### ISSUE THREAD

**Issue by katrinleinweber** [exercism/exercism#4067]
Hello!

As both a mentor, and learner, I find the current [`.../exercises/.../solutions/` pages](https://exercism.io/tracks/python/exercises/space-age/solutions) a bit strange. The solutions are ordered by number of comments, right?

I'm not sure whether sorting by likes, loves or geniuses is better, and would therefore like to suggest a clustering approach. Many solutions are similar, so it doesn't really matter whose version I select for viewing. I feel that the most instructive comparison is the one between differently _structured_ solutions. Might these different structures be determined automatically somehow?

If yes, how about some kind of [iPhoto-like visualisation](https://images.apple.com/ca/ilife/iphoto/images/laptop_gallery_04_20111018.jpg) of the "solution approaches" then? With one thumbnail per cluster that highlights that structure's main features (and maybe the comment, like, etc. stats of all individual solutions in that group summed up). And the thumbnails could be aligned like on a Pinterest-board: longer and shorter code-thumbnails tiled.

That latter display style could be used even without clustering, as an MVP so to speak for more informative solutions pages.

What do you think? Are there any other plans to update those pages?

**Comment by iHiD** [comment]
@katrinleinweber Thanks for raising this :)

We have a really productive internal discussion on this yesterday. We have two goals here: 
1) Show a good set of varied solutions to learners that will help them learn
2) Ensure that the solutions page doesn't become a leaderboard.

It's also worth noting that there are very few unique solutions to a problem on exercism. The volume of submissions (thousands per exercise) means that most things have duplicates where the only variance is the variable names.

We have the following working proposals.
1) We (probably mentors) hand-pick X solutions per exercise and create a page-type on exercise that is "example solution" and with some commentary on the RHS about why this is a good solution. There's no reference to the user and no link back to the person who solved it etc. These appear at the top of the page.

2) Below those, we order by some semi-random way that means it *can't* be a leaderboard and shows solutions with zero votes, but also brings some good solutions in each time.

I think that gets us somewhere as a short term solution. What do you think?

**Comment by nicolechalmers** [comment]
@iHiD I've started putting design at https://github.com/exercism/reboot/issues/355.

**Comment by gustavklopp** [comment]
I've got some suggestions:

1.  Code is the most important, not the github profile. I suggest that the page "community solutions" display directly the code, not the profiles of people (that you must click on it to get the code, adding extra steps)

2.  the sorting by mentor looks great, even if I don't know how it would work in practice. But, as said above, there are so many proposals that some very good ideas can be hidden in the multitude. Why not directly display 2 sorts: 

-  one, where the codes are graded by the number of like (or mentor choice in the future...)
- and in addition, automatically display random codes. 
A bit like on some online seller website, with the section "you may also be interested in...", but randomly. Who knows what the hidden gems can be found!

**Comment by Rots** [comment]
From #4381 
As a user, when browsing community solutions, it would be useful to have some basic stats about the solutions, e.g. lines of code, % of comments, number of files/functions so that it's easier to find interesting ones to investigate.

**Comment by katrinleinweber** [comment]
And number of iterations!

**Comment by mrtnmgs** [comment]
If we're trying to avoid a leaderboard, maybe it would be interesting to avoid presenting the solutions by users altogether?

Each block on the solutions page, rather than representing a user, could represent a solution. When a user wants to make her solution public, she has the choice to file it under one of the existing solutions or create a new one. In other words, this would create solutions "categories", making it very easy to clearly identify the different useful solutions people came up with and switch between them.

Because the solutions presented would not belong to a specific user, this would require some kind of system for editing. Maybe users could vote to decide whether a proposed improvement should be accepted or not?

Finally it'd be nice if in addition of upvoting solutions we could mark them as "clever" and "readable", as there's almost always a super short smart-ass unreadable answer and another longer, more readable one.

**Comment by katrinleinweber** [comment]
> […] would require some kind of system for editing. 

With my original idea of clustering by structure, hopefully not. Depends on the quality of automatic clustering, though. My wild idea would be to throw the ASTs into a random-forest model or something to discriminate `super short smart-ass unreadable`, `another longer, more readable` and other such categories.

**Comment by mrtnmgs** [comment]
Right. I guess my thought was that relying on the users' judgment rather than automatic clustering might provide more relevant results. I'm not sure that's true though...

**Comment by iHiD** [comment]
> Each block on the solutions page, rather than representing a user, could represent a solution. When a user wants to make her solution public, she has the choice to file it under one of the existing solutions or create a new one. In other words, this would create solutions "categories", making it very easy to clearly identify the different useful solutions people came up with and switch between them.

Because the solutions presented would not belong to a specific user, this would require some kind of system for editing. Maybe users could vote to decide whether a proposed improvement should be accepted or not?

I think this is basically my (1) above, which is the direction we're heading in, yeah.

> My wild idea would be to throw the ASTs into a random-forest model

This is also what we are doing :D

**Comment by katrinleinweber** [comment]
Awesome! I really only guessed :-)

> Because the solutions presented would not belong to a specific user, this would require some kind of system for editing. Maybe users could vote to decide whether a proposed improvement should be accepted or not?

Behind the 10k-feet-view-/stylised-/structure-like representation of the solution category, the current `/exercises/.../solutions/` pages could still be used.

Or, a maybe simpler way to present the different solutions is to distill a word cloud out of all the non-comment lines of a solution? This was already suggested for summarising the discussions](https://github.com/exercism/DEPRECATED.v2-feedback/issues/124#issuecomment-353942837).

**Comment by iHiD** [comment]
https://github.com/exercism/exercism/issues/4333 is a good read.

To paraphrase from there: 

> We're looking for key people to work on the [static analysis](https://exercism.io/blog/automated-mentoring-support-project) for each language track, so if any of y'all would like to volunteer for specific tracks, then we'll definitely share some anonymised data to get started on this stuff. I'm thinking that to start we could return profiles on solutions (number of lines, conditionals, methods, etc) and then both give users the option to filter themselves for solutions they're interested in based on those things, or use a more data-science model to do the automatic groupings (as you say with "Though there are 237 answers, really, they can be lumped into these 5 main approaches. Here is approach #1, which was the most popular with 37% of the answers, approach #2 was...").

**Comment by sshine** [comment]
On the subject of providing a better community solution overview, here is an idea:

We could automatically group solutions by their general structure and strategy and for the overview page display random solutions that are unlike one another. If you view any one solution, you may also be interested in viewing another solution that looks alike it.

Perhaps it would make sense to look into source code similarity detection. The abstract idea is that each solution is a vector in some vector space, and that solutions that look alike will have a close angle in this space. You can then group solutions by a k-nearest neighbor algorithm and pick a random element from either the same group or a different group.

I imagine that the best results are achieved with language-specific analysers. But I also imagine that we *may* be able to make something durable using character- or word-based algorithms since we simply have so many solutions to train on.

This would be suitable as a research project for anyone with some knowledge of machine learning. It could either focus on a general syntax-independent approach that only looks at characters and words. Or it could focus on a less-but-still-general approach with some lightweight syntax understanding, kind of like when you build syntax highlighters for programming editors. Or it could focus on a generic parser framework like [ANTLR](https://github.com/antlr/grammars-v4) to provide syntax trees of many languages in one framework.

There is a body of research related to measuring the "distance" between two syntax tree, but I can't seem to find it. A friend of mine did his BSc on something similar, restricted to detecting source code duplication in OCaml code ten years ago. Glancing for research by his former supervisor, [Cleaning up Copy-Paste Clones with Interactive Merging](https://www.researchgate.net/publication/326286634_Cleaning_up_Copy-Paste_Clones_with_Interactive_Merging) appears to be closest.

This could initially be the subject of a BSc or MSc thesis in computer science, and it could tilt either in the direction of machine learning or programming language theory, although there is a component of both.

**Comment by iHiD** [comment]
@sshine Really interesting - thanks. This is something we're planning on doing lots of as part of the Chicago/Sloan project, so great to re-kickstart this discussion! :)

> Perhaps it would make sense to look into source code similarity detection. The abstract idea is that each solution is a vector in some vector space, and that solutions that look alike will have a close angle in this space. You can then group solutions by a k-nearest neighbor algorithm and pick a random element from either the same group or a different group.

So one of the "quick wins" I envisage is that part of the automated-analysis, the analyzers return things like the number of methods, variables, LOCs, etc, and also a list of all stdlib methods used. That's a really quick win (like a few hours max for the existing analyzers) and then we can use some grouping algorithms based on those stats. We're hoping the James, Gary and their teams at Chicago will be able to apply some scientific vigour to this as part of their internal analysis of the data.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
