### ISSUE TITLE
Editor on website adds closing tags when using <type> notation

### ISSUE THREAD

**Issue by ptillemans** [exercism/exercism#4068]
When pasting a bit of rust code I noticed that the site added an extra **</u32>** to match the **<u32>** in the type info of the function:

```
pub fn find() -> Option<u32> {
    for a in 1..1000 {
        for b in a + 1..1000 - a {
            let c = 1000 - a - b;
            if a * a + b * b == c * c {
                return Some(a * b * c);
            }
        }
    }
    None
}
</u32>
```
Note the weird closing tag on the last line of the snippet.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
