### ISSUE TITLE
Line spacing too small on editing text

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4069]
In Mentor/student comments, I've noticed the "g" is cut off in "ago" - see below.

<img width="173" alt="screen shot 2018-07-25 at 12 49 38" src="https://user-images.githubusercontent.com/5421823/43196823-8618b60e-9009-11e8-94a9-d60253f3d724.png">

**Comment by iHiD** [comment]
Should be `font-size(14,17)` I imagine

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
