### ISSUE TITLE
Code block in comments is doing HTML escapes and automatically closing what it thinks are HTML tags

### ISSUE THREAD

**Issue by m-dango** [exercism/exercism#4075]
When entering the following as a code block in a comment:

```perl6
when / <:Lu> / && !/ <:Ll> / { 
  when .ends-with('?') { "Calm down, I know what I'm doing!" }
  default { 'Whoa, chill out!' }
}
```
The comment shows:

```
when / <:lu> / &amp;&amp; !/ <:ll> / { 
  when .ends-with('?') { "Calm down, I know what I'm doing!" }
  default { 'Whoa, chill out!' }
}
</:ll></:lu>
```

**Comment by NobbZ** [comment]
The same as #3890 and #4068.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
