### ISSUE TITLE
Closing statement of exercise_readme.go.tmpl seems inaccurate for v2

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4076]
@rpottsoh commented on [Fri Jul 20 2018](https://github.com/exercism/delphi/issues/246)

@kytrinyx or @iHiD the final statement of [exercise_readme.go.tmpl](https://github.com/exercism/delphi/blob/master/config/exercise_readme.go.tmpl) seems inaccurate to me
```
It's possible to submit an incomplete solution so you can see how others have completed the exercise.
```
Can a student still see solutions from other students simply by submitting a solution to that problem?  I presume that mentor approval and publishing of the solution would be necessary first.  Right?  I am not sure how to rewrite this statement or if should just be removed.

I am happy to move this to exercism/exercism.io if you would prefer.

**Comment by iHiD** [comment]
Nice point. Thank you. Will add that as a bug to fix.

**Comment by kytrinyx** [comment]
This is probably present in the template for most of the tracks.

It could be worth scripting a pull request to each of the tracks in question.

**Comment by rpottsoh** [comment]
When I originally opened this issue in Delphi I peeked in on a few other tracks and pretty much saw as you are suspecting.

**Comment by tmccombs** [comment]
I've seen this for several tracks, but I've also noticed something else related:

If I submit an "Extra Exercise". At first it shows me an info box that includes a link to look at other user's solutions. But if I then add a comment to my own solution, that info box goes away. This seems pretty inconsistent, that link should either always be there or never be there, it seems odd for it to depend on whether there is a comment. Also, even with a comment I can still get to the solutions page, there just isn't a link to it.

**Comment by iHiD** [comment]
This should get fixed as part of https://github.com/exercism/exercism/issues/4375

**Comment by iHiD** [comment]
So for side exercises, this is true. For core exercises, it's not true and "may receive assistance from a mentor" would be good. But that split makes it tricky. 

We could say "request help from a mentor" which is true for both?

**Comment by kytrinyx** [comment]
It should be a fairly straight forward thing to update the readme template to have a different statement for core/side exercises. I don't think we'll even need to make any big change to configlet, as long as the data type for the config exercise has a method for whether or not it is core. Then we can access that in the Go template and do a conditional.

**Comment by petertseng** [comment]
My suspicion remains that "request help from a mentor" is the correct choice, without introducing the complexity of having README generation check whether the exercise is core. I now discuss the disadvantages of two alternatives.

I didn't like having README generation check whether the exercise is core. Because then a change to config.json (toggling `core` for any exercise) also implies a README change. I don't like introducing that extra step.

Other alternative considered: Notice that https://exercism.io/tracks/$track/exercises/$exercise/solutions is available to anyone, even when the exercise has not been completed (or even when logged out). In that case, the README could simply link to it, saying "if you're stuck, you can take a look at the community solutions". But I think that messaging encourages giving up too soon and doesn't focus enough on learning.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
