### ISSUE TITLE
"Mentors" comments on migrated solutions appear backwards.

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4078]
I wanted to compare my solution to the solution of a student, so I opened my solution and wanted to re-read comments first, as they sometimes give me some more things I can ask the student or point him to.

But then I realized, that they do not make much sense read top-down. But when read bottom-up, they made.

I am sure I have more longrunning conversations throughout my submissions, but wasn't able to find oen quickly.

The conversation I realized this today is about my elixir/roman-numerals in the first iteration (UUID 03cd8b194a0743bfa3124c923b39528f)

**Comment by sshine** [comment]
@NobbZ: What could an action to address or resolve this be?

**Comment by NobbZ** [comment]
Order them properly by date, from oldest to newest, as its done with comments that have been made after the migration.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
