### ISSUE TITLE
mentoring: Provide copy button in code viewer

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4086]
@iHiD 
A nice to have feature....  Some are missing it from v1.

cc: @uzilan

**Comment by iHiD** [comment]
Can you explain a bit more about what you mean pls?

**Comment by NobbZ** [comment]
In v1 there was a button attached to a file, that, when clicked, pushed the files content to the clipboard, that one could use <kbd>Ctrl</kbd>+<kbd>V</kbd> to paste it into an editor or whereever one wanted.

I never used that feature as I prefered to use the `download` subcommand even in v1, but I know it was there.

**Comment by iHiD** [comment]
Understood. Thanks @nobbz.

**Comment by NobbZ** [comment]
Sadly, you currently can only download the latest iteration. To download specific iterations is another issue which has already been opened somewhere.

exercism/cli#688 is an incarnation I could find quickly, but I'm pretty sure there were some doubles on this, but maybe they are just memories of chats in the slack mixing into reality?

**Comment by rpottsoh** [comment]
> I'm not sure how copy&pasting from the website allows you offline mentoring

I wasn't clear, it allows the mentor to test run the solution is what I was trying to convey.

**Comment by NobbZ** [comment]
Which you can via downloading from the CLI as well.

**Comment by NobbZ** [comment]
Of course, beeing able to download a specific iteration via CLI would enhence that feature a lot.

**Comment by rpottsoh** [comment]
>Of course, beeing able to download a specific iteration via CLI would enhence that feature a lot.

I agree, it would.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
