### ISSUE TITLE
Community solution links.

### ISSUE THREAD

**Issue by mikoSL** [exercism/exercism#4089]
The community solution should show up after submit incomplete solution. 
However, it is not visible all the times. 
I saw the community solution twice, but now I can not find it anymore. 

May you please clarity how to find the community solution for each exercise?

Thank you very much!

**Comment by pranasas** [comment]
For some unknown reason the community solutions are hidden at all times. They are still accessible using a direct link which I forgot.

**Comment by pranasas** [comment]
Is nobody else affected by this? To me this is an essential part of the Exercism experience. And it's totally busted - no links, impossible to leave comments (even on hello-world).

**Comment by iHiD** [comment]
Thank you both for your thoughts.

> no links

@pranasas. You should find links to community solutions on all completed exercises now.

> impossible to leave comments (even on hello-world).

There is an issue open for this. 

> The community solution should show up after submit incomplete solution.

@mikoSL In mentored mode, they only show up once you've completed an exercise. This is a deliberate decision as we want learners to approach solving first through mentorship, then by looking at other solutions once they've gone through the first step. This is because otherwise learners can get into the habit of just copying+pasting what they've seen elsewhere without really understanding why or how things work.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
