### ISSUE TITLE
Mentors: Ability to view a student's submission history

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/exercism#4095]
Currently, the only way I know of to view a student's exercism history is to view their published solutions if they have a public profile.

As a mentor, I would like to be able to view their submission history to better understand their strengths and weaknesses.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
