### ISSUE TITLE
Travis isn't caching Bundler

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4098]
It's not working because:

<img width="884" alt="screen shot 2018-07-31 at 16 49 20" src="https://user-images.githubusercontent.com/286476/43467276-aa08aa24-94e1-11e8-9a6f-e8262a587930.png">

I've tried fixing this but it still currently fails with:

<img width="876" alt="screen shot 2018-07-31 at 16 47 56" src="https://user-images.githubusercontent.com/286476/43467246-96362242-94e1-11e8-983e-6234bf6a014c.png">

Info here: https://docs.travis-ci.com/user/caching/#Arbitrary-directories

**Comment by fabioperrella** [comment]
Hi @iHiD , is this problem related to this repo https://travis-ci.com/exercism/website ?

I've checked the [last build on travis](https://travis-ci.com/exercism/website) but I'm not shure this is the repo with problem. But I think it is, because the `bundle install` step took 162s to run!

**Comment by fabioperrella** [comment]
Could you assign to me pls?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
