### ISSUE TITLE
Can email threads just be one per student - problem?

### ISSUE THREAD

**Issue by corroded** [exercism/exercism#4100]
Currently email threads (in Gmail) are sorted by problem uuid as mentioned here https://github.com/exercism/exercism.io/issues/3984. The thing is, it still duplicates because Gmail thinks the comment email and the update code email are two separate things even though they have the same UUID.

Not sure how to fix it, but it is quite a bit 'spammy' in that regard. Very cool idea about the UUID though! Maybe it's just Gmail?

**Comment by iHiD** [comment]
For clarity, you're saying you want everything (comments, new iterations, etc) to do with one solution in one thread? Or to put it another way, a thread per solution?

**Comment by corroded** [comment]
Yup! What do you think? Is it a good idea?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
