### ISSUE TITLE
Add difficulty filter on mentor dashboard 

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4105]
Mentoring can get repetitive when working through the same easy core solutions. See screenshot - actual mentor's dashboard.

Suggestion: Add difficulty filter to "Solutions you're mentoring" so mentors can vary the exercises they give feedback on to make the process more varied and fun. 

Other related ideas for discussion:
- Have a random solution generator button which gives mentors a list of the most varied set of solutions to work through
- When mentors sign up we can ask if they would like to give feedback on "Easy" solutions or "All" solutions. I know some mentors aren't sure if they're ready to mentor so choosing Easy (at least to start with) would make sense and would make things more interesting for more experience mentors.

<img width="1077" alt="screen shot 2018-08-01 at 13 53 25" src="https://user-images.githubusercontent.com/5421823/43520526-164edcae-958b-11e8-9998-1f7bc901c513.png">

**Comment by nicolechalmers** [comment]
I think solutions for harder or less popular exercises are treated equal to all other exercises. @iHiD - can you confirm?

**Comment by iHiD** [comment]
Exercises marked as CORE are ordered by oldest first. So there's no particular thing in the software meaning that hard exercises are not showing up.

**Comment by frerich** [comment]
Are CORE exercises always preferred over the optional ones? If so, I wonder whether it can happen that some users submit solutions to optional exercises but never actually get any feedback since the mentoring queue is saturated by the CORE submissions (which are most certainly more numerous since everyone has to go through them and they are easier, so they are submitted at a higher rate).

**Comment by iHiD** [comment]
Yes. Because core exercises block students from progressing, whereas the extra ones don't.

I see the core as teaching opportunities and the extras as practice opportunities. And while mentoring is great for both, it's more essential on the former.

**Comment by frerich** [comment]
One crazy idea:

Instead of (or in addition to) using a one-dimensional chronological sorting, maybe it would be interesting to group the submissions by exercise and then display the exercises as tiles, i.e. in a two-dimensional grid. You could then use a 'heat map' to indicate where mentoring is needed. I.e. each exercise is a rectangular tile with a color ranging from e.g. white over green, yellow, red to purple. 
The color indicates the average response time for user submissions -- a higher temperature means a bigger response time, so more activity is needed.

The idea being that even if some exercises cause a lot of traffic, you still have the overview and -- if you like -- can choose to mentor on an entirely different solution.

It's just a crazy idea I wanted to throw into the room. :-)

**Comment by frerich** [comment]
I think it makes perfect sense to consider the core exercises as 'teaching opportunities'. However, since there are only a handful of core exercises (they are vastly outnumbered by the optional ones), I wonder whether maybe those teaching opportunities eventually become a bit repetitive as long as as core exercise submissions are preferred in the display over optional ones.

**Comment by frerich** [comment]
This may also just be an unfortunate consequence of the Haskell language track in which 3,802 students are distributed over 7 mentors. So assuming everyone is equally active, that would mean I have to look at 543 solutions to testing whether a year is a leap year; I wouldn't mind seeing some other code every now and then. :-)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
