### ISSUE TITLE
Create first-ever solution page

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4108]
We have a nice page that shows instructions before someone creates a solution, with links to walkthrough and guides. Many hello-worlds have good get starting info, but lots of links are broken since migration.

However, we can tell if this is someone's first *ever* solution and provide a much more focused page that says something like

> Welcome to your first exercise on Exercism. You need to install [track.title] and the CLI to make things work. Here are instructions to install [track.title] if you don't have it, and here is a link to a quick walkthrough to get the CLI installed. If you're an experienced developer, this will probably take 30secs. For less experienced developers this will normally take 5-15mins.

@nicolechalmers @kytrinyx Thoughts?

**Comment by kytrinyx** [comment]
I think this would make a ton of sense!

**Comment by nicolechalmers** [comment]
I like this too.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
