### ISSUE TITLE
List of unimplemented exercises page no longer exists

### ISSUE THREAD

**Issue by cmccandless** [exercism/exercism#4118]
Originally reported by @cmccandless at https://github.com/exercism/discussions/issues/235:

> Is there an equivalent page to the old http://exercism.io/languages/python/todo? Currently, that URL redirects to https://exercism.io/contribute.

**Comment by iHiD** [comment]
Is this a maintainer-only page?

**Comment by rpottsoh** [comment]
No.  On v1 anyone could see what exercises a given track had available,  but also a list of all the exercises that were not implemented. List with each unimplemented exercise were the icons of the tracks that have implemented the exercise.

**Comment by NobbZ** [comment]
Finding out how and where to contribute.

That page was linked from a status page when one had finished a given track. At least thats what I remember.

Aside from that the page was not linked anywhere, so if one didn't knew that it exists one was not able to find it.

**Comment by petertseng** [comment]
When such a page is created, please replace the link in https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/test-suites.md with the correct link (You will see it currently links to http://exercism.io/languages/vimscript/todo but the link target does not serve the stated purpose of finding other tracks that implemented a given exercise)

**Comment by petertseng** [comment]
EBWODP:

Further, when such a page is created, please replace the instructions in https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#finding-an-exercise-to-port. As https://github.com/exercism/docs/issues/131 noted.

**Comment by Stargator** [comment]
Seems like tracks.exercism.io serves this purpose now. Go to the respective track and click on Unimplemented

**Comment by iHiD** [comment]
@Stargator Thanks.

If someone would like to PR the URL to the place(s) @petertseng suggests, we can then close this.

**Comment by Stargator** [comment]
@iHiD I'll look to do that tomorrow, 10/21.

**Comment by Stargator** [comment]
@petertseng For the instructions, I am not sure that tracks.exercism.io will link to when displaying unimplemented exercises. I haven't seen any current lists display with content, so I guess the real implementation of that table is up in the air?

**Comment by SleeplessByte** [comment]
FWIW:

https://tracks.exercism.io/<trackid>/master/unimplemented shows this list. It is _the only thing in this dashboard_ that makes a Github API request (x2). You can refresh the page once every 30 seconds, and won't hit the rate limit.

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

If you've hit the rate limit, you must have refreshed/reloaded a lot. Clicking a _different track_ and then going to *unimplemented* does NOT trigger the XHR.

The API in question is: https://api.github.com/repos/exercism/problem-specifications/contents?ref=master

I purposefully have not authenticated this request, because if you're hitting the rate limit, something else is wrong.

**Comment by Stargator** [comment]
@SleeplessByte It may be due to being inside a corporate firewall, I look again when I get home.

**Comment by SleeplessByte** [comment]
Re: OP

> Listed with each unimplemented exercise were the icons of the tracks that have implemented the exercise.

This is coming (it's the _inverse_ of track specific page).

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
