### ISSUE TITLE
filter for solutions of a specific student

### ISSUE THREAD

**Issue by rachelhornung** [exercism/exercism#4120]
It would be great to have the possibility to search for a specific student's solutions that I already mentored.

I knew I had mentored a student before and wanted to check my comments, but I wasn't able to find the previous exercises.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
