### ISSUE TITLE
A way to tell how a track is doing

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4128]
Since the switch to V2, I've been churning along on the now "extra" exercises in my language track (rust) while waiting for mentor feedback on my existing "core track" work.  I have three submitted items, plus all my "extras".  I've now run out of "extras" with no movement on my core track items.

I understand that with the launch of the new site, the mentors are probably all overloaded with the existing content that got imported, etc.  So, what I think would be nice would be a way to see how much.  Like, "you are nth in the queue" or "there are n other solutions waiting for feedback" or similar -- just to give students a sense that progress is happening even if we're waiting for our own exercises.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
