### ISSUE TITLE
Allow downloading a specific iteration of a solution

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4138]
Right now the API only provides a way to download the latest iteration.

It would be great if we could have a way to specify which iteration we want.
This would require a change to the API, and afterwards we'd need to update the CLI:
https://github.com/exercism/cli/issues/688

**Comment by iHiD** [comment]
@kytrinyx Do you have opinions on how:
- The API request should be changed? Would you prefer a new param called `iteration_id` which specifies the uuid of the iteration, or `iteration_idx` which is a 1-based index? I prefer the first.
- The API response should be changed ([defined here](https://github.com/exercism/website/blob/master/app/models/api/solution_responder.rb#L10)).

**Comment by NobbZ** [comment]
When I switch between iterations on a solutions page, the UUID in the URL doesn't change, so all iterations have the same UUID from my point of view.

But we have a different iteration I'd as a query parameter. So I think just adding an index parameter which aligns with the visible part in the URL seems most natural.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
