### ISSUE TITLE
Choose your own adventure installation flow link text is difficult to click

### ISSUE THREAD

**Issue by hiimbex** [exercism/exercism#4142]
Screenshot of current behavior:
<img width="165" alt="screen shot 2018-08-03 at 9 39 07 am" src="https://user-images.githubusercontent.com/13410355/43655582-0a5b7518-9704-11e8-84e2-605edf6525c7.png">

I don't have a great proposed solution here, but I'd love to see these links become buttons or have more space between them. I'm a Mac user and it was particularly difficult to click the Mac installation option.

**Comment by rpottsoh** [comment]
I don't know about turning them in to buttons.  But inserting a line between each is simple to do.

task:

- create a PR to modify [welcome.tw2](https://github.com/exercism/interactive-cli-walkthrough/blob/master/contents/common/welcome.tw2) by inserting one blank line above `Mac` and a blank line below `Mac`.

turn:
```
## Which OS do you use?

- [[Linux->Linux Introduction]]
- [[Mac->Mac Introduction]]
- [[Windows->Windows Introduction]]
```
into:
```
## Which OS do you use?

- [[Linux->Linux Introduction]]

- [[Mac->Mac Introduction]]

- [[Windows->Windows Introduction]]
```
- use one of the available reserved words with in the comment of the PR to close this issue.

**Comment by sshine** [comment]
@hiimbex: Forgive my ignorance, but are they hard to click because the "active" area of the link is either too small or overlaps slightly? I think adding spacing here would probably be the easiest solution.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
