### ISSUE TITLE
mentor: In the exercise filter mark core exercises

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4149]
In the mentoring queue core-exercises are marked with a darker border and also tagged `core` in the upper right of the card.

WHen I want to filter on a track by exercise, I can not distinguish core from side exercises in the drop down.

Therefore I propose to either have labeled sections in the dropdown or have a `core` tag on the right of core exercises in the list.

**Comment by iHiD** [comment]
Agreed. Thanks.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
