### ISSUE TITLE
Open $Editor if set on exercise download completion

### ISSUE THREAD

**Issue by Jarvvski** [exercism/exercism#4154]
This is a suggestion on my part. How about being able to open the path printed at the end of the exercise download in whatever $editor is set, or via a custom command in the config?

For example:
```
» exercism download --exercise=two-fer --track=java
Downloaded to
/Users/jarvis/code/xcsm/java/two-fer
```

I've noticed the command does actually return the path as the output via stdin:
```
atom $(exercism download --exercise=two-fer --track=java)
```

It would be quite cool if I could just run the download command and immediately get stuck in, without having to wrap the command first.

Probably have to either be a config or some sort of setting and not default(?) as I'm not sure how many people would like this.

**Comment by NobbZ** [comment]
Thats in fact a nice idea, but instead of `$EDITOR` I'd prefer to use `$VISUAL`, others might still prefer `$EDITOR`, others again might have something configured as `$EDITOR` what would be better in `$VISUAL`…

But yes, I'd really like an `--edit` flag (or `--open`)!

**Comment by Jarvvski** [comment]
Certainly, as I'm sure many others would like to use whatever editor/IDE they use!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
