### ISSUE TITLE
When importing from legacy or independent mode have sepererate restricted queues for core and side exercises.

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4157]
At the moment, in mentored mode with independent or legacy solutions, you can only request one solution for mentoring. Change this so you can only request one core at at a time *and* one side at a time.

**Comment by NobbZ** [comment]
And please make it obvious if and which of those solutions are currently under mentoring (or are not mentored at all) from the track dashboard.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
