### ISSUE TITLE
Provide a way to see status (particularly useful when doing multiple tracks in parallel)

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4162]
_Imported from https://github.com/exercism/cli/issues/627._
_Originally posted by @jave._

#

I used "exercism fetch" a lot in the previous version, for its useful status display.
Can I get this status display back somehow?

**Comment by kytrinyx** [comment]
We're going to need to do product discussion around this one. It might be related to https://github.com/exercism/exercism.io/issues/4161

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
