### ISSUE TITLE
Allow submitting an exercise directory without submitting temp files, build artifacts, and other undesirable files

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4165]
_Imported from https://github.com/exercism/cli/issues/458._
_Originally posted by @kytrinyx._

#

When people submit an entire directory, e.g. `exercism submit hello-world`, we filter out a few things:

- the metadata file which caches some information from the site locally for the CLI to use
- any markdown files (e.g. README.md, GETTING_STARTED.md, etc)
- the test files (we get the pattern from the `prepare` command when called for a track)

In addition, we should let people have files that we ignore.

I think we should store this value in the `CLIConfig` rather than the `UserConfig`, however we need to be careful that we don't overwrite this when we auto-update a track.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
