### ISSUE TITLE
Mentors rating statistics or a score table (maybe)

### ISSUE THREAD

**Issue by withkittens** [exercism/exercism#4167]
**Slack context**

![image](https://user-images.githubusercontent.com/5273891/43689775-f06b701c-9907-11e8-9194-cc8079099d79.png)

**Expecting**

```c
m_motivation += 9000;
m_self_confidence += 146; // TODO: value is arbitrary, check later
```

😛

**Comment by hilary** [comment]
I think reporting a running average of the active mentors in the track is the most important stat, because I'd like mentors to be focused on their success as a team, first and foremost 😄 

Letting mentors know where they fall relative to the team as a whole also strikes me as a good idea, so long as we are careful to design the stat in such a way that it does not encourage gaming the stat. Things like 

"You are doing great! Students give you and your team consistently high marks!"
"You are doing fine. Your fellow mentors may be able to give you some suggestions to improve your mentoring."
...

But no hard numbers, etc., on the individual side of the stats.

**Comment by sshine** [comment]
I would very much like statistics on how a track is progressing.

I imagine a bar chart across time that contains:

- How many (non-)Core exercises are in the queue
- How many new (non-)Core exercises were put in the queue for each day in the last month.
- How many (non-)Core exercises were popped from the queue (across all mentors).

---

Wrt. @hilary's "average of active mentors": I don't think it's important how active you are as long as you mostly live up to the community minimum standard of 20 exercises per week. I think it's important to get a feel of how much we achieve collectively and not feel we're not doing enough as individuals. Turning numbers into

---

Wrt. individual ratings, I would be happy to see a bar chart of how many exercises I gave feedback to in the past. For example divided by exercise type, language track, and over time. But I don't think these statistics are nearly as important as the "track overview" statistics as they can be super helpful for tracks that are way behind on giving feedback to non-Core exercises.

For example, on the Haskell track, all I know is that there were ~500 exercises that didn't receive feedback three weeks ago, and perhaps this number has gone up, but I don't know how many new submissions were pushed to the queue and how many old submissions were popped. So I don't feel motivated to try and kill the queue, because I don't know if it's a winning or a losing game.

@iHiD: Perhaps if these statistics could be prioritised as an API feature, we can leave initial statistics renderings as user tools, since the bar for adding command-line tools to a language track is lower than adding production-value pages to the website.

**Comment by hilary** [comment]
I would really like to second the need to know throughput on a track. Without knowing throughput, the other stats are not particularly useful. The go track has been holding at a backlog of roughly 20 core exercises for some time now. This week we're at 110. Is that because we've had a bunch of new submissions (probably), or because we have mentors who have less time with the start of the academic year (maybe) or some combination of the two? 

It would be a lot less frustrating to see that constant backlog if our throughput were going steadily up. As it is, I just don't know. 

I would also have some idea of how much recruiting I need to do to actually get us to the point at which we would not have a backlog.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
