### ISSUE TITLE
Should mentors comments are at the bottom of the page on an approved solution.

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4174]
I am slowly progressing through getting all my legacy solutions mentored.

Yesterday I realized, that after the solution was approved, the comment of the mentor was at the bottom of the page, above that a huge box telling me what I can do next:

1. Complete/Publish my solution
2. Browse community solutions
3. Choose the next exercise

After that, another (lighter) paragraph tells me again to choose the next exercise.

Only then, I do see the mentors comments.

![down-below](https://user-images.githubusercontent.com/58951/43698140-b3c9e72e-9948-11e8-8a76-641f2c624812.png)

As a student though, I'd like to read the mentors comments **first** and perhaps iterate another time and incorporate latest nits before seeing any call to action.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
