### ISSUE TITLE
Extra exercises on last core exercise don't appear

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4177]
Notice this under possibly artificial conditions, but have a track with 1 core exercise (hello-world) and 1 extra exercise unlocked by hello-world. When I complete hello world, I get a congratulations for finishing the track but the extra exercise doesn't appear? 

I wonder if the fact that it thinks I'm finished prevents the extra's appearing?

**Comment by sshine** [comment]
@macta: Now that time has passed, can you confirm if a longer track allows unlocking side exercises after the last core exercise? I recall that this was addressed as a bug, and I don't remember where. If you can't say, I'll try and look for it.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
