### ISSUE TITLE
Completing a track and then adding a new exercise doesn't let you continue

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4180]
This might be artificial, but when developing a track - if you finish all the existing exercises while testing, if you then add another exercise you aren't able to try it as exercism says congratulations you are done.

The implication is that if you open a track but are still adding exercises, users might overtake you and get stuck?

My test case was just having a hello-world and an unlockable based on hello-world. Unable to try that, I modified config.json to make it a second core exercise and still I am unable to see it as exercism says I'm finished.

**Comment by cmccandless** [comment]
Confirmed.

The `rest-api` exercise was recently added to the Python track. I had already submitted solutions for all existing core exercises, but when the new exercise was added, it is not unlocked for me.

Screenshot:

![screenshot of issue](https://github.com/cmccandless/legendary-palm-tree/raw/master/exercism_io_core_not_unlocked.png)

Possibly related to #4177

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
