### ISSUE TITLE
Exercises with non-default capitalisation/punctuation in title should retain them (but currently don't)

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism#4183]
Currently, an `exercise-slug` is converted to an `Exercise Slug` (capitalise only the first letter of each hyphenated word) when displaying on e.g. https://exercism.io/my/tracks/csharp (a useful track to look at for its high number of implemented exercises).

This usually works, but there are better alternatives for exercises such as `rna-transcription` (should be "RNA Transcription" instead of "Rna Transcription").

One place where these non-default capitalisations and punctuation may be found is in https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/metadata.yml#L2 (as were added in https://github.com/exercism/problem-specifications/pull/901 and any other PRs adding a `title` field)

**Comment by rpottsoh** [comment]
Are the .yml files being utilized anywhere?

**Comment by iHiD** [comment]
Not by the website to my knowledge

**Comment by rpottsoh** [comment]
The site is pulling the blurb displayed for each core exercise from the first line of the description.md I think then?  The blurb is also available in the .yml files.  

In April of '17 exercism/problem-specifications#767 made the description.md self-sufficient in regards to conveying to the reader the intended goal of the exercise (the blurb).

I am not sure adding "title" to config.json is the best solution.  There is the potential of tracks making a mistake.  The .yml files already have the issue resolved.  An alternative suggestion would be to add "title"  to the canonical-data.json.  I assume it would be a lateral solution since the site seems to not be  using either file types anyway.

**Comment by petertseng** [comment]
I guess since it's a one-time investment it will be *bearable* if display titles go in config.json, but it will be *unfortunate* because of duplication. Unlike `unlocked_by` and `difficulty`, which could vary per track, it seems that not many tracks would want a differing title for an exercise.

I see that there are clear advantages if a track can stand by itself and not depend on any external sources of data for pieces such as title (here) or topics (https://github.com/exercism/exercism/issues/4186). It is an unfortunate disadvantage that each track's maintainers have to pay the price for those exercises that are drawn from the common pool.

**Comment by petertseng** [comment]
> change configlet to require it

if I may make a recommendation. Since the default title works for many exercises, it could be useful to have it be optional, and it would be only be added if a non-default capitalisation is needed.

**Comment by petertseng** [comment]
EBWODP:

I do not currently have a solution to offer that meets both these needs (a free-standing track, while not having duplication).

**Comment by kytrinyx** [comment]
The tracks already rely on shared metadata in problem specifications to produce the exercise README (when running configlet).

The title is in https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/metadata.yml

I think it would be ideal if the website could just read that.

**Comment by iHiD** [comment]
@kntsoriano Could you action this pls? We're already reading from that file but not using the title attribute.
