### ISSUE TITLE
exercism client doesn't output via stdout or stderr

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4187]
If you want to call exercism via an exec command and pipe its output to somewhere you can check it doesn't work as it exercism doesn't seem to use the normal stdout or stderr streams?

e.g. exercism submit hello-world/Hello.st > out.txt

doesn't give you any output into out.txt, it just writes to the screen directly.

for a cli executable this is not very standard and limits how you can use the client (e.g. the pharo track wants to exec exercism to allow easy submission from the ide, or if we get a way to reset progress in a track, a test script might want to do the same thing.

**Comment by NobbZ** [comment]
Most of the outputs are designed with scriptability in mind.

So the download command does print everything to `stderr` but the path, its printed to `stdout`, this way, we can do `cd $(exercism download …)` or `atom $(exercism download …)` and it will change the directory accordingly or open atom in that directory.

For the submit command though, there is currently no output to stdout.

But maybe you are right, the `submit` command should print the URL to stdout, such that we can open it directly in a browser of choice.

For IDE integration there is #4087. So if you are missing something concrete, add it there. In a perfect world, no IDE needs to shell out to the `exercism` CLI.

**Comment by NobbZ** [comment]
PS: If you want the combined output in a textfile, you need to `exercism … 2>&1 > output.txt`.

**Comment by kytrinyx** [comment]
> For the submit command though, there is currently no output to stdout.
>
> But maybe you are right, the submit command should print the URL to stdout, such that we can open it directly in a browser of choice.

The submit command prints the URL to stdout and everything to stderr. When I run the following:

```
open $(exercism submit hello_world.go)
```

The browser opens to my solution.

I'm not sure why you're getting a different result, @NobbZ.

@macta I'm going to close this, since we _do_ provide output to different streams. Would you subscribe to (and add your thoughts to) the issue in https://github.com/exercism/exercism/issues/4087 for the IDE integration, if these streams don't suit your needs well enough?
