### ISSUE TITLE
Allow to download the solution before deciding to mentor

### ISSUE THREAD

**Issue by withkittens** [exercism/exercism#4194]
**Slack context**

![image](https://user-images.githubusercontent.com/5273891/43773430-5e9c84da-9a4e-11e8-943a-9a81bcf09b04.png)

Maybe something like this?

![image](https://user-images.githubusercontent.com/5273891/43773450-6de76888-9a4e-11e8-8870-c636602f803e.png)

**Comment by iHiD** [comment]
@withkittens I'm not sure why looking at the code on the website isn't enough to decide whether to mentor it or not. Could you expand further pls? :)

**Comment by NobbZ** [comment]
If its spaghetti and passes the tests there is a lot more initial mentoring to do, compared to its not passing the tests...

But yes, I do usually decide on how the code looks like. And so far nobody has answered my question if manually building the command would work.

**Comment by iHiD** [comment]
I didn't realise that was a question for me. Yes - manually building it works.

**Comment by NobbZ** [comment]
No, it wasn't, it's originally to @skade, but he didn't answer in slack, nor did someone here.

But we should show the copy button, and if it's just to make sure that no mentor claims, downloads and then decides to not mentor, but it's not available to others.

Another problem many have Raised so far is poor readability on the webpage, because of the display width and the light background. I prefer to read code on darker background. Perhaps some have this preference that strong that even skimming isn't possible for them?

**Comment by iHiD** [comment]
> I prefer to read code on darker background. Perhaps some have this preference that strong that even skimming isn't possible for them?

New issue pls? :)

**Comment by skade** [comment]
@ihid sorry for missing this issue.

Yes, as @nobbz describes, there are cases where I _think_ the code has - for example - a bug but I'm not sure or I think there's a better way to express what the author wanted. In this case, I prefer downloading the code before claiming so that I can play around or add a test case.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
