### ISSUE TITLE
Solution model test not working as intended

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4202]
The [first test](https://github.com/exercism/website/blob/master/test/models/solution_test.rb#L4) in the solution model test file passes even if I change the instructions method on the Git::Exercise class to return random text. I came across this while working on a [pull request](https://github.com/exercism/website/pull/321) which I expected would break that test but the test kept passing despite my expectations.

**Comment by iHiD** [comment]
Hmm, so that test is testing that solution proxies to Git::Exercise correctly, it's not testing the functionality of Git::Exercise itself. The exercism is actively mocked to avoid testing that. I'm not sure this test is broken, but we should both have an integration test that tests the whole flow somewhere and a test within Git::Exercise. I can't remember if those are there (I didn't write this bit of code) but if not, I would appreciate them being added :)
