### ISSUE TITLE
Show copyable submit command for in-progress exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4208]
I was mentoring someone who was new to Exercism recently. I suggested some changes, asked a few questions, and they posted a comment containing a new version of the code. When I suggested they submit that as a new iteration they asked me what the command to submit was.

It would be great if the command to submit a new iteration was as easily accessible as the command to submit the first iteration.

**Comment by iHiD** [comment]
It's the same one they see on the initial screen before they submit the
first iteration.

I think we could do with a product discussion about this and then some
design work from Nicole. Let's look at this next time we're all online and
free, Katrina?

**Comment by NobbZ** [comment]
There is a command to copy and paste for submitting the exercise?

----

Ah, Okay, I looked it up. The command is a generic `exercism submit /path/to/file [/path/to/file2 ...]`.

Not worth that much in my opinion. After submitting `hello-world` for the first time a command simple as this should be remembered. One doesn't even need to know the slugs, but only the (relative) path to the files to submit.

**But** as after a first submission, we know which files the student had submitted the first time and how the are named (even though we still don't display the names on the webpage), so why don't we tell the student the **correct** submit command based on this knowledge?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
