### ISSUE TITLE
UI: Change default button colour in Settings

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4236]
Make default button colour grey with dark grey text. Only change to turquoise when user has changed something in the relevant section.

<img width="917" alt="screen shot 2018-08-14 at 16 32 20" src="https://user-images.githubusercontent.com/5421823/44101590-ab723476-9fdf-11e8-882e-5e25e135c756.png">

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
