### ISSUE TITLE
Feature request: Email notifications when a new solution is available for a particular track

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4252]
This will not be a popular feature request for those tracks that receive MANY new submissions/day.  I am thinking more about the "little guy" who's language track may only see a trickle of activity.  The occasional new submission could go for days before a mentor thinks about checking that one track they mentor that sees very little activity.

This should be a feature that mentors can opt out of if they so choose.

I consider this a "nice to have" feature and also low priority.

**Comment by sshine** [comment]
This feature request has, in part, been addressed by the "Weekly Mentoring Update" emails.

In light of that, would you consider this feature request as still relevant?

I would *love* this feature. I get requests to mentor the Standard ML track so rarely that I don't bother to check. If they get withdrawn again, I will know the next time I get the "Weekly Mentoring Update" email. Even in periods where I don't prioritize mentoring, I would still want to do it for that track because it's so low effort. The same may happen on the Tcl track.

This could also solve neglecting low-traffic tracks without active mentors, since active mentors can adopt a track with practically no submissions for a language they know but don't actively practice.

Still, I am content with the "Weekly Mentoring Update" email.

**Comment by iHiD** [comment]
I think will be covered by the [Changelog Project](https://github.com/exercism/wip/issues/35) FYI. (We can still leave this open for this specific bit of functionality though)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
