### ISSUE TITLE
TypeError in api/solutions#update

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4276]
## Error in Exercism V2

**TypeError** in **api/solutions#update**
no implicit conversion of String into Hash

[View on Bugsnag](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c687afcf32b001842052d?event_id=5b7c82d1002d65b0f9d80000&i=gh&m=ci)

## Stacktrace

    app/controllers/api_controller.rb:49 - merge
    app/controllers/api_controller.rb:49 - render_error
    app/controllers/api/solutions_controller.rb:107 - block in update
    app/controllers/api/solutions_controller.rb:105 - each
    app/controllers/api/solutions_controller.rb:105 - update

[View full stacktrace](https://app.bugsnag.com/exercism/exercism-v2/errors/5b7c687afcf32b001842052d?event_id=5b7c82d1002d65b0f9d80000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by iHiD** [comment]
@kytrinyx The API got the following where `"[OBJECT]"` literally came through as a string.

```	
{
  {   
    "files" : [
    "[OBJECT]"
  ],
  "controller": "api/solutions",
  "action": "update",
  "id": "dfa3306260be49e7b1407523e004626f"
}
```

This has occurred today for user 37229 and previously for user 157681

Any ideas?

**Comment by tejasbubane** [comment]
Regarding the `TypeError` in issue:

What I suspect from the short look at the code is these two lines: [one](https://github.com/exercism/website/blob/9b38dd3382f3284c48056fb414eff2dfb7c703a4/app/controllers/api_controller.rb#L43) and [two](https://github.com/exercism/website/blob/9b38dd3382f3284c48056fb414eff2dfb7c703a4/app/controllers/api/solutions_controller.rb#L107).

`render_error` method expects a `hash` to `merge`, but a `string` is being passed. The code seems to be changed now, and I don't know what commit is currently deployed. But above two links are from same snapshot, so that error must be present at some point.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
