### ISSUE TITLE
Mentor Dashboard: Filter multiple solutions / solutions that the mentor has solved themselves

### ISSUE THREAD

**Issue by kephas** [exercism/exercism#4279]
Both because I want to know what the problem is about and not to spoil myself, I only mentor solutions to problems I already did myself. I also prefer to mentor solutions when I have solved the problem in the same language.

Providing both those filters in the mentor dashboard would be useful.

- solutions to problems I have solved in any language track
- solutions to problems I have solved in the same language track

**Comment by tmccombs** [comment]
I'm just starting to mentor, but this would be very helpful. The getting started mentoring page even suggest that you should do exercises before mentoring them, so such filters would make a lot of sense.

**Comment by sshine** [comment]
@kephas: Since you posted this, the mentor overview has changed quite a lot.

In particular, you can easily choose among single exercises, but still not filter multiple exercises at once.

In light of the mentor overview rework, do you consider this feature request (nice or need) to have?

**Comment by kephas** [comment]
The need is still there.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by kephas** [comment]
@ErikSchierboom do you mean open a new issue?
