### ISSUE TITLE
Follow up after removing the versioning: potential confusing with mentor notes

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4282]
Removing the versioning https://github.com/exercism/ruby/issues/836  left me with some questions, partly answered [here](https://github.com/exercism/ruby/issues/836#issuecomment-414165727).

Still to be discussed:

> As a mentor, how will I be able to tell that my own solution (or my notes, or the mentor notes) is different from the version the student submitted?

A potential solution Katrina mentioned:

> What if the tests included a version number but we didn't include any assertions for them?

> Also: potentially we could make it so you can ask to see the test suite on the community part of the site...?

Issue opened on Katrina's request, to be discussed with product team.

**Comment by sshine** [comment]
It appears that this issue has not been addressed in a year.

If this is wrong, the issue can be closed. If not, how would you like to proceed?

A quick thought: What if the solution page warned on newly submitted solutions to old versions of the exercise? That would be much easier to implement and maintain than keeping track of which mentor notes match up with what solution over time.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
