### ISSUE TITLE
Links in mentor comments are not clickable anymore

### ISSUE THREAD

**Issue by mawis** [exercism/exercism#4291]
It seems to me links in the comments are not detected anymore. That way they cannot be clicked anymore. For an example see:

https://exercism.io/mentor/solutions/29454e3e71c84aafaeab7e252eab0311?iteration_idx=5#discussion-post-166779

**Comment by sshine** [comment]
I've marked this as "type/improvement".

Note that Markdown URLs with `[...](...)` still work.

**Comment by mawis** [comment]
If it's a link without title you can also just enclose it in angle brackets < and >. I know. It's just inconvenient to require added markup.

**Comment by sshine** [comment]
I didn't know that, thanks for adding it.

And yes, it is expected on all other Markdown-powered websites that I use that links get highlighted even without markup.

**Comment by NobbZ** [comment]
Personally I prefer to not have autogenerated links from looks-like-an-url-because-its-two-words-separated-by-a-dot-or-because-its-some-whitelisted-tld. One version is prone to false positives, the other to false negatives.

If we really want to add this feature, please require the schema to be part of the URL.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
