### ISSUE TITLE
[Javascript] Armstrong Numbers- mistake in introduction

### ISSUE THREAD

**Issue by brunnock** [exercism/exercism#4292]
*10 is not an Armstrong number, because 10 != 1^2 + 0^2 = 2*

1^2 + 0^2 is 1.

**Comment by rpottsoh** [comment]
Correct.  The statment should read:
10 is *not* an Armstrong number, because `10 != 1^2 + 0^2 = 1` as it does [here](https://github.com/exercism/problem-specifications/blob/master/exercises/armstrong-numbers/description.md).  This issue should be raised in the [Javascript](https://github.com/exercism/javascript/issues) track.

**Comment by rpottsoh** [comment]
The README was fixed here exercism/problem-specifications#1237 back in May.
