### ISSUE TITLE
[Python] JSON file

### ISSUE THREAD

**Issue by tardigrade23** [exercism/exercism#4298]
HI, i am newbie in Exercism. I  downloaded first task (hello world) to cmd. Then i upload this task to Jupyter Notebook and wrote my code and saved. Then i wrote on cmd 'exercism submit' and it gave Error: open .solution.json: The system cannot find the file specified.

What i must to do? I cant find .json file on my PC

**Comment by NobbZ** [comment]
When did you download the exercise? Was it during the old page or during the last couple of weeks?

Also, the `.solution.json` is a hidden file, so make sure you actually list them. `-a` as an option to `ls` will display it most unix-like systems, while I have no clue about how to do that on windows based systems (which I guess you are using), but google says that the option to `dir` is `/a`.

And if I recall correctly, there is/was a bug in some versions of the CLI that makes it unable to read hidden files on windows. I'm not sure if this is fixed in 3.0.8 yet. Anyway, I think showing us the output of `exercism version` might help the folks from @exercism/cli to tell you more about this.

Also, you really should download, solve and submit from the same computer, without any transferring back and forth to another one, a lot of stuff can go wrong thereby.

**Comment by tardigrade23** [comment]
I downloaded today and version is 3.0.8. Can you give me any instructions what to do after downloading task to cmd?

**Comment by NobbZ** [comment]
What is it you have problems with?

As I said, the usual steps are download, solve, submit, get mentoring <-> iterate, get approved, complete.

So with which of these steps do you have problems?

**Comment by NobbZ** [comment]
PS: Documentation of the track and especially the README of the `hello-world` usually guide you through those steps the first time.

**Comment by NobbZ** [comment]
And it seems as if the bug regarding hidden files has not been fixed yet, perhaps you are affected as well? Please make sure first that the file is actually there, as I have pointed out earlier.

**Comment by tardigrade23** [comment]
My problem is that i don`t know exactly what to do after downloading task to cmd. Please check if i wrong somewhere, i am writing steps. 

1) After downloading task to cmd, i upload hello_world.py file to Jupyter Notebook
2) I edit this file and write (print('Hello, World!') and save it.
3) After this step i copy submit link from exercism.io and past to cmd
4) But it gives me - Error: open .solution.json: The system cannot find the file specified.

BTW .json file actually in the folder.

Where i am doing mistake? I also tried with hello_world_test.py file, but the same errror.

**Comment by NobbZ** [comment]
First unhide the `.solution.json` and try again.

Also, only printing is not enough, your task is to `return` the greeting, not printing it. To make sure that your solution actually does what it meant to do, you are expected to run the testfiles on your computer before submitting. How to do this is part of your tracks documentation. For python it's `python *_tests.py` IIRC.

**Comment by iHiD** [comment]
Can this be closed?
