### ISSUE TITLE
Mentor notification persists for comment in unmentored track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4300]
The following situation leaves a persistent notification on my notifications page:

- I commented in a track in v1
- I did not sign up to mentor this track in v2
- a v2 mentor left a comment on the exercise
- I get a notification
- I can now navigate to the page and see the conversation
- I go back to my notification page, and the notification is still present

**Comment by yyyc514** [comment]
FYI I actually see both sides of this.  I signed up to mentor Python then had second thoughts but I'd like to finish with the users I started mentoring (which are still in my queue)... but I can't submit posts because I'm no longer a mentor of Python.  I'd like to be able to finish up without being included in NEW Python posts also.

Just my 0.02.

I fixed it by just rejoining Python for now and I'll just not take any new Python assignments and wait for the existing ones to quite down.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
