### ISSUE TITLE
Reaction notification persists, even after visiting the community solution page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4302]
I received a notification about someone reacting to one of my published solutions. I clicked the link, and then went back to my notifications and it was still there. I got rid of it by clicking the checkmark.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
