### ISSUE TITLE
Add a button for mentors to report learners

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4306]
We've had a few occasions recently where learners have been rude to mentors. I want to ensure that mentors can just hit one button that flags that up to admins immediately.

**Comment by kaiomagalhaes** [comment]
Did we make any progress with this issue definition? I would be glad to work on it

**Comment by kaiomagalhaes** [comment]
@iHiD awesome! please let me know if there is any other implementation that could use some work.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
