### ISSUE TITLE
Mentored solutions not visible enough on the community pages 

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4307]
On the Ruby Hamming community solutions pages solutions from the mentored age are rare.  
Does that mean that hardly no one added their solution since we're mentoring?  

https://exercism.io/tracks/ruby/exercises/hamming/solutions

For Raindrops it's the same.
On the TwoFer page https://exercism.io/tracks/ruby/exercises/two-fer/solutions there are lots of recent solutions.

Related: if we order the solutions  chronologically descending, a) the latest mentoring insights will be reflected on the front page, and b) it increases the chance that the version of the first pages of community solutions are the same as the one the student just submitted, and thus easier to compare and learn from.

**Comment by guygastineau** [comment]
I really like your suggestions in the related section at the bottom of your post.

I was under the impression that they are already ordered with a preference for currency, but I might be mistaken.

----
#### Thoughts about why there are more legacy solutions for hamming and raindrops

- I know I for one didn't want to wait for all of my legacy solutions to get mentored before advancing. I was mid track during the migration and initial mentoring took some time.
- It did however encourage me to refactor some of my legacy solutions.
- Ultimately most people probably felt pretty secure regarding the ultra easy earlier exercises like hamming, and therefore didn't feel like seeking mentoring on them.

----

As a counter argument to my points above:
- Even on the easier exercises I'm sure there are some fun little tricks we can learn.
- Due to the potential for code smells in legacy solutions I agree that it is really important to have mentored solutions presented before legacy solutions on the community pages.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
