### ISSUE TITLE
Put challenge back to mentor queue if mentor leaves conversation

### ISSUE THREAD

**Issue by ptillemans** [exercism/exercism#4308]
Currently when leaving the conversation, the challenge the student wants mentoring for dissappears in the void.

It should return to the queue to see if another mentor can maybe be more successfull with the student (after all the previous mentor was sufficiently desparate to leave the conversation).

Probably this submission should also be appropriately flagged to avoid passing trolls around the mentor community sapping their will to live. On the other hand we also cannot leave students out to dry because of an interpersonal chemistry mismatch.

**Comment by yaahallo** [comment]
I'd like to add to this issue. I've accidentally clicked leave conversation before and it doesn't seem like there's any remedy for this. I bring this up for this change because I want to mention that I think that the conversation should go back into the queue of the mentor who left the conversation, and if they actually want to remove it from their dashboard they then click skip solution. Bonus points if you don't go back to the mentor dashboard after clicking leave so that you can immediately afterwards click skip if you want to skip it.

**Comment by guygastineau** [comment]
This is an excellent idea.

**Comment by Emerentius** [comment]
If fixing this is a big task, the button should be deactivated in the meantime. Right now it's a trap.
