### ISSUE TITLE
Mentor Tools: show that I mentored a student before

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4313]
Most of the time I select an exercise that I want to focus on, and filter the queue for that exercise. Sometimes I think I recognise a name of a student that I mentored before. I'd prefer to avoid them (or at least postpone them), so that they get input from other mentors too. 

Can we have a badge that shows if I mentored a previous solution of a student in the queue?

**Comment by F3PiX** [comment]
Bump

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
