### ISSUE TITLE
Add a remember me option (login with github not remembered)

### ISSUE THREAD

**Issue by henricazottes** [exercism/exercism#4317]
Hi,

I log in with my github account but as soon as I leave my browser I get disconnected. Would it be possible to add a "remember me" option ?

[Edit]: I'm using firefox on Ubuntu 18.04.

Thanks

**Comment by NobbZ** [comment]
I do not have this problem on my desktops and laptops, using chrome under windows and linux.

I get logged out from exercism (and many others) on my mobile though.

The latter has a very restricitve cookie store, due to limited space and due to security considerations (I don't want that someone who brakes into my phone gets precious sessions for free).

Perhaps you have to check cookie settings on your browsers?

**Comment by henricazottes** [comment]
The thing is that I don't see this behavior for other websites (like github itself for example), never had this kind of issue. I'm using firefox on ubuntu 18.04.

**Comment by nealot** [comment]
I've also had this problem: logging in using Google Chrome, Chromium, or Firefox requires me to re-login after closing my browser session. It would be far more convenient if my state was saved so I wouldn't have to see the login page every single time.
