### ISSUE TITLE
public profile: Consider showing former-maintainer differently from current maintainer

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism#4323]
You may look at my public profile as an example; the URL component in https://exercism.io/profiles/url-component is the same as my GitHub username. It says I am a Go maintainer! This was once true, but not anymore! Y'all are being too kind. I think it would make more sense to show it differently somehow (greyed out? Show the word "Former" or "alumnus" or something?). Or I wouldn't mind having it not be shown at all.

(I confirmed by looking at another arbitrary current maintainer's profile and found no visually-discernible difference between the "X maintainer" badges)

I understand that for myself I can simply set https://github.com/exercism/go/blob/master/config/maintainers.json#L27 to false to not show it anywhere, but it's okay, I don't mind being shown on https://exercism.io/tracks/go/maintainers ! So it's just at the public profile where I think things might change.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
