### ISSUE TITLE
Select first track by default if the mentor only has one

### ISSUE THREAD

**Issue by kaiomagalhaes** [exercism/exercism#4326]
Right now if the mentor has only one track and wants to search for any specific exercise he needs to select the track and then type the exercise. It shouldn't be necessary since the mentor only has one track.

I would be glad to implement it if you guys agree.

**Comment by sfairchild** [comment]
I wonder if making the track and exercise search fields work independently might be a better option. As an example. Let's say I mentor both Ruby and JavaScript. I might want to search for all exercises of "Bob" regardless of track.

This would be a larger effort to change, but would make it more flexible for everyone.

What do others think?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
