### ISSUE TITLE
Mentor dashboard: filter for "not approved"

### ISSUE THREAD

**Issue by tehsphinx** [exercism/exercism#4336]
Having a few solutions I'm mentoring I want to make sure I did not by accident forget to approve a good solution. A filter for "not approved solutions" would be helpful.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
