### ISSUE TITLE
Adding a Makefile to the exercise

### ISSUE THREAD

**Issue by MartinDelille** [exercism/exercism#4338]
Hi,

I would like to propose to add a `Makefile` to each exercise in order to run the test with a simple `make` command.

I will tell you the reason why I make this proposal and maybe you may have other idea how to deal with my problem.

I'm coding on *Vim* and I want to use the `<leader>` key to run the test. Currently I have two shell and I need to save the file in *Vim*, switch to the second shell and run the following command (since I'm currently doing the go track:

```
$ go test -v --bench . --benchmem
```

The `Makefile` could be as simple as that:

```
test:
  go test -v --bench . --benchmem
```

**Comment by NobbZ** [comment]
`go test` is the idiomatic way to run tests in `go` and it since Vim is quite powerful, it should be easy to configure it in a way that it runs the correct command even without `make` available. Another way, if you want to stick with `make`, you can copy around a single `Makefile` from exercise to exercise, for `go` its static anyway.

For the windows users, `make` could become a very big problem to install and configure correctly.

**Comment by MartinDelille** [comment]
Yes you're right I should do that in my *Vim* configuration.

I face a problem but I created an issue here: https://github.com/fatih/vim-go/issues/1957

Thank you for the quick feedback!
