### ISSUE TITLE
Ubuntu via Windows: Error Permission Denied on Submit / Test

### ISSUE THREAD

**Issue by galcianuk** [exercism/exercism#4353]
Hi-

I'm getting permission denied errors when trying to run **npm test** and the **submit** commands via Ubuntu on Windows.

`Error: open /home/Galcianuk/exercism/javascript/hello-world/hello-world.js: permission denied`

**exercism debug** prints the following:

> `Version
> ----------------
> Current: 3.0.9
> Latest:  3.0.9
> 
> 
> Operating System
> ----------------
> OS:           linux
> Architecture: amd64
> 
> 
> Configuration
> ----------------
> Home:      /home/Galcianuk
> Workspace: /home/Galcianuk/exercism
> Config:    /home/Galcianuk/.config/exercism
> API key:   9800*****************************d8d
> 
> API Reachability
> ----------------
> 
> GitHub:
>     * https://api.github.com
>     * [connected]
>     * 153.666ms
> 
> Exercism:
>     * https://api.exercism.io/v1/ping
>     * [connected]
>     * 352.802ms`

I've tried removing the Read Only flag on the folders with no luck. Any ideas?

Thanks,

**Comment by guygastineau** [comment]
The error you posted is definitely happening in Linux and not in the exercism cli.

I wish I could be of more help, but I use arch on its own. No experience WSL.

While I wouldn't think it is advisable, you could try running those commands with sudo. That should circumvent the permission denied provlem.

Keep in mind that you will likely need the full path to the exercism binary with sudo. I think it uses the $PATH for root instead of the $USER $PATH.

I am assuming that `exercism download` worked to get the exercise.

**Comment by guygastineau** [comment]
Thanks for the info @rpalo

**Comment by iHiD** [comment]
Is this still an issue?
