### ISSUE TITLE
Allow  track mentors to find previous reviews of other solutions of the same exersize

### ISSUE THREAD

**Issue by dpolivaev** [exercism/exercism#4364]
As a mentor, when I review a solution I would like to see a list of links to all other solutions of the same exercise and track with mentor comments, so that I can learn from the solutions and discussions already happened and can review better and faster. 

Further, each exercise could have a link to its own discussion thread either on slack or somewhere else so that mentors can easier talk about it.

Probably, sorting solutions by time in descending order would be natural, so that the latest discussions could easier be found and mentors could exchange themselves about the newest cases.

I think that this feature would also enable mentors to get feedback from other mentors and to improve themselves as mentors.

**Comment by dpolivaev** [comment]
This issue relates to https://github.com/exercism/exercism/issues/3988 and they could probably be implemented together

**Comment by iHiD** [comment]
I've added this to the roadmap. I hope to get to it during October.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
