### ISSUE TITLE
[Mentor] Exercises in both "requires action" and "unsubscribed" filters

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/exercism#4373]
<img width="487" alt="screen shot 2018-10-01 at 9 48 18 am" src="https://user-images.githubusercontent.com/6425580/46292559-3796e100-c55f-11e8-8c2d-242ec22eee20.png">

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
