### ISSUE TITLE
multiple mentors for a single submission: feature or bug?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4379]
@iHiD 
I was asked to take a look at https://exercism.io/mentor/solutions/c5325aa51b724d079661ab5f64d82bf8.  Upon landing at that location the page offered the button for mentoring this submission.  I can clearly see that this exercise is already being mentored, there are two submissions and several comments between the student and mentor.  The solution was already accepted by the mentor before I came along...

I clicked the button to mentor.    I appear to now be a mentor along with the original mentor.  I have been able to leave comments...  I am not sure if this is a bug or a feature.

This is posted as a reminder to the conversation we had in `#track-delphi`.

**Comment by sfairchild** [comment]
This is only my opinion but I would think of this as a feature. Each mentor brings their own perspective to each problem so maybe another mentor could add to a discussion something that the first mentor missed.

I would hope that mentors who join beyond the first mentor would make their own determination if their input beyond what has already been commented on would really help the student or just add noise to the already started conversation.

+ @kytrinyx

**Comment by kytrinyx** [comment]
@sfairchild I agree. Right now we mostly don't have enough mentors to keep things in the queue when there is already someone giving feedback, though I think in the future we may want to have some functionality around "get other mentors' opinion" or some such thing.

My impression is that this is the result of us rushing to fix some workflow issues without having the proper time to really think through all the various parts of the user experience for mentors (rather than, say, an opinionated take on how it _should_ be).

**Comment by chriseyre2000** [comment]
Here is an instance of two mentors on one solution:

https://exercism.io/mentor/solutions/9e5f6edffddd4ff2b738ced01400e44c

The solution made it back into the queue so seemed abandoned, but now two mentors get notified.

**Comment by sshine** [comment]
If I understand correctly, it is currently a feature, but since this issue was posted, a proposal was made to let the same mentor the same student throughout the core track. I cannot find an issue that describes this feature, so it might've been on Slack. If this is correct, we could close this issue in favor of discussing that feature: While they're not exactly equivalent topics, it would resolve this issue.

**Comment by iHiD** [comment]
> I cannot find an issue that describes this feature, so it might've been on Slack.

https://github.com/exercism/discussions/issues/237

> I would hope that mentors who join beyond the first mentor would make their own determination if their input beyond what has already been commented on would really help the student or just add noise to the already started conversation.

I think this sums up the action.

> If this is correct, we could close this issue in favor of discussing that feature

This sounds ideal to me :)
