### ISSUE TITLE
Automate the release process of exercism/cli

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4384]
Right now releasing the CLI is a multi-step and manual process, as described in https://github.com/exercism/cli/blob/master/RELEASE.md

It would be great if we could script this.

The GitHub API has an endpoint to create releases:
https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
