### ISSUE TITLE
Update travis to pass track name to lint command explicitly

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4387]
```
configlet lint . --track=$TRACK_ID
```

This is not necessary for the track repositories themselves, but if you fork it to a repository with a different name  (e.g. if you already have a repository with the same name because you contribute to the core language, for example, then GitHub will name the your fork of the language track `$track-1`), then if you turn on Travis CI for the fork the lint command will fail.

Also, it will make it easier for people to troubleshoot if they name the repo something different locally (as happened here) https://github.com/exercism/elm/issues/219#issuecomment-396799575 since searching for the command will turn up the version that explicitly passes the track id.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
