### ISSUE TITLE
Update all track config.json to have a track-id

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4391]
I thought we didn't need it, but it turns out we have a perfectly valid reason to add this. Two in fact!

1. If someone forked the repository back when it was called `x$TRACK`, then the name of the directory does not match the track ID, but everything else works.
1. When forking a repository to an account that already has a repository by the same name, then you need to give the repository a different name. This is common for contributors who also contribute to the programming language itself, e.g. TypeScript, Julia, etc.

See the original discussion in https://github.com/exercism/configlet/issues/80

**Comment by iHiD** [comment]
Could we call it `slug` to match what the website uses?

**Comment by kytrinyx** [comment]
Yeah, no problem.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
