### ISSUE TITLE
Collapse file view for viewing files

### ISSUE THREAD

**Issue by PureRonin** [exercism/exercism#4394]
Sometimes mentees will upload an extremely large test file as part of their solution. There will be no content in it that I need to review but since I'm viewing this on my phone is it awkward to scroll past and find where their solution actually is. It would be nice if it was possible to collapse the file contents in the view so that I can just ignore that file.

Result of this conversation:
https://exercism-team.slack.com/archives/CAQP7JL3T/p1538636345000100

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
