### ISSUE TITLE
Track should signal in some way mentor activity

### ISSUE THREAD

**Issue by PureRonin** [exercism/exercism#4395]
It would be nice if along with saying X number of mentors for a track, it would also include how many were active in the last ${period}. I sometimes get the feeling that there might be a lot of other mentors who aren't doing much based on seeing the movement of the solution queue needing mentoring. It would be good to give the students some feedback for how many of us are actually reviewing solutions at the moment.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
