### ISSUE TITLE
Consider awarding open badges for completion of tracks

### ISSUE THREAD

**Issue by jwir3** [exercism/exercism#4396]
[Open Badges](openbadges.org) is a way of recognizing completion of a particular set of tasks or the learning of specific skills. The recipient can then display these badges in what is known as a "backpack".

We should consider issuing badges for completion of exercism courses. There is some dev work involved in this, detailed here: https://openbadges.org/get-started/issuing-badges/ so it's non-trivial, but it's something we should bring up for discussion.

**Comment by iHiD** [comment]
I'm 👍 on this but it involves dev that we probably don't have time for right now, so it'll be further down the line.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
