### ISSUE TITLE
How can I comment a solution?

### ISSUE THREAD

**Issue by jabbalaci** [exercism/exercism#4400]
In the old version of the site I could leave a comment on one's solution. This time I don't find this feature. I don't want to be a mentor, I just want to leave some comments. Is it possible?

**Comment by TobiasRoland** [comment]
I really enjoyed getting feedback and asking questions on my and other people's solutions on the older version of the site, too - would love for this feature to return!

**Comment by mitchossi** [comment]
Is exercism dying? My simple solution for „Leap“ is still in Progress – after 4 days. And all the comments I’ve seen so far are pretty old. Same on facebook... That would be very sad. I really like the idea behind exercism. And I couldn't find a comment button neither. That's a pitty not to be able to comment other solutions...

**Comment by iHiD** [comment]
No. It's not dying. Quite the opposite - it's too busy. Some tracks are fast and some are slow to receive feedback.

**Comment by mitchossi** [comment]
Is it somehow possible to support you? Like making a donation?

**Comment by iHiD** [comment]
Thanks for offering! :) The best thing you could do if you are experienced in a language would be to [become a mentor](http://exercism.io/become-a-mentor). If you're not experienced, then probably not in terms of speeding things up :)

If you just want to explore other people's solutions rather than wait for mentors, you might like to jump into Independent Mode rather than Mentored Mode.

**Comment by jabbalaci** [comment]
Why was the comment feature removed? If I'm in independent mode, why can't I leave comments? Without this the new site feels empty and I'm not motivated to solve exercises since I know I won't receive any useful feedbacks.

**Comment by iHiD** [comment]
Because we want learning to be in the context of private mentoring conversations as we believe that provides a much higher quality of learning (which has been confirmed since launch). There is [information here](https://github.com/exercism/DEPRECATED.v2-feedback#a-new-mentorship-model) for context.

FWIW we haven't permanently moved comments on exercises, but we are working out how to do it well before we add it back.

>  I don't want to be a mentor, I just want to leave some comments. Is it possible?

Out of interest, why do you want to leave comments?

**Comment by cpoile** [comment]
fwiw, I wanted to comment to help another community member improve their submission. I want to do that because I've received a lot of help from the mentors (and from looking at other community solutions) and wanted to give back. But I'm not good enough to be a mentor yet. :)

**Comment by NobbZ** [comment]
If you can see the submission, it has already been through mentoring, so there is not much to improve.

If it had not received mentoring, it's probably legacy and the user might be inactive for years now.

@ihid as a student I'd like to ask questions about a piece of code that uses a technique, that i haven't seen so far.

**Comment by iHiD** [comment]
> fwiw, I wanted to comment to help another community member improve their submission.

This is exactly the behaviour we want to avoid. As @NobbZ said, the student has already learnt something from that solution and a mentor has decided to move them forward. If you have stuff to give back, then we'd love you to be a mentor and help others within that framework :)

> As a student I'd like to ask questions about a piece of code that uses a technique, that i haven't seen so far.

So this is exactly what I **do** want us to encourage. My concern is how we do this without also overwhelming students with unsolicited comments about how they can improve.

**Comment by F3PiX** [comment]
Maybe a `Care to explain to me what you did?`-button ? So that @ nobbz can push the button at my interesting solution, and I can decide to add an explanation/start a conversation - or ignore.  The button text should make it very clear that it's to ask something, not to give feedback.

**Comment by mitchossi** [comment]
You guys want to avoid comments/feedback from users who are not mentors. That totaly makes sence. But you are still allowing feedback in the form of "likes" (well done, love it, genius). 

So this means code which for example just seems to be good (e. g. it's short and simply looks cool) but is very slow or has other disadvantages (which are not obvious) can get a lot of positive feedback from anybody. This way some students might think that the best rated code is really the best version which he or she should use in the real world. I think avoiding written comments but allowing giving likes is not consistent.

But that's just my opinion :)

**Comment by iHiD** [comment]
I agree it's inconsistent. As I said we haven't permanently moved comments on exercises, but we are working out how to do it well before we add it back.

However, Exercism's aim isn't to teach people how to write good code - it's to improve the fluency someone has. So right now, I can't write Hello World in Rust. If I learn to do that, then I've moved forward. My solution might be utterly shit, but I've moved forward and I'm happy. I don't want other people telling me it's wrong or could be better - I just want to move forward in little chunks. If people want to encourage me, then that's great and makes me happy. Once I've completed every exercise on a track, I would probably have learnt all the things that would make my code good/fast/whatever, and that will have naturally occurred by my improving my fluency.

Without a structured track with mentors trying to teach specific things, then the only way to achieve that is to solicit random comments from a community. With the system we have now, that's not  necessary.

Will we bring comments back - yes.
Is having likes but not comments weird - maybe a bit, although everyone that mentions it is used to the old commenting system. New people don't ever really suggest it.
Am I going to ensure that when we bring it back, we've thought it through really well and we execute it really well - definitely.

**Comment by cpoile** [comment]
> If you can see the submission, it has already been through mentoring, so there is not much to improve.

> This is exactly the behaviour we want to avoid. As @NobbZ said, the student has already learnt something from that solution and a mentor has decided to move them forward. 

Obviously you can design the site however you want, I'm just pointing out that there is a use case for this that you might be missing -- this was for a side exercise that hadn't been through mentoring.

As @mitchossi pointed out, this solution also had a thumbs-up, leading me to believe I could learn something from it. I did; it was a great solution and I learned something new. But the solution also missed something that could have been improved. If a learner sees this as an idiomatic example... Well, it might hurt more than help.

I can see why unsolicited feedback can be difficult for some learners -- especially given that many programmers feel the need to code golf, and enjoy feeling smarter than others. But consider: 

1) The student made their submission public. If they didn't want feedback or they can't handle unsolicited suggestions for improvement, they can keep their solution private. Otherwise why are they making it public? Do they only want public praise in the form of thumbs up? What kind of learning will they receive from that? Is this a social media site where we feel better with more 'likes', or a learning platform?

2) I (and others) are making our solutions public with the hopes that if there's a better way to do the solution someone can point it out. That's how we can learn. There are hundreds of public solutions, we can't check every existing solution to see if there's something we missed, or the best few are buried. Comments are one way to help us improve in the future. 

Anyway, like I said, of course it's totally up to you and your team's goals. But for me, I would question the assumption that comments are something you would want to avoid. Maybe I'm not seeing the whole picture?

**Comment by jippiee** [comment]
I can understand not having comments on mentored solutions, but especially for the side exercises that mostly aren't mentored I think they would add some value.

Some tracks have plenty non-core exercises (The java track has 86 but I can't speak for the others), but you can only have 3 of them mentored. So especially in the harder exercises, where you always come by the same handful of people, I think giving feedback to one another would be helpful.

**Comment by sbrichards** [comment]
> Out of interest, why do you want to leave comments?
@iHiD my 2 cents on your question: I came here looking for this feature because I wanted to ask a question about a user's submission. E.g. https://exercism.io/tracks/typescript/exercises/accumulate/solutions/910cfbcad7674359bdd979eb5585dd75 I want to understand why/how Typescript generic constraints accept multiple parameters. I've never seen that before & couldn't find much from Googling.

Thanks for your work! Great product & community overall.

**Comment by iHiD** [comment]
FYI: https://github.com/exercism/exercism/issues/4629

**Comment by TobiasRoland** [comment]
This is great news! I lost momentum on the Haskell track where I previously got a lot of really great feedback from the community at large, and being able to ask questions about solutions was really insightful and motivating. I'm super happy to see this return!

**Comment by jabbalaci** [comment]
This feature is back. Thank you!
