### ISSUE TITLE
It might be nice if the site indicated the current version and date of release of the CLI

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4405]
Often times I think people find out by accident that the version of the CLI they are using is not up to date.  Not even CLI tells you if it is up to date or not unless you invoke `upgrade` or `troubleshoot`.  Some might find it helpful to see posted somewhere on the website, doesn't have to very big, in a corner or something, what the current version is and possibly the date it was released.

**Comment by iHiD** [comment]
Nice idea. Any ideas how best to achieve this? (cc @kytrinyx)

**Comment by rpottsoh** [comment]
The information is here: https://api.github.com/repos/exercism/cli/releases/latest but you probably don't want the site banging this all the time.  I think when the CLI is released the pertinent information should be updated in a canned file that the site access....

**Comment by kytrinyx** [comment]
If we store it in the database, the release script could send an API call.
Or it could make a commit to master that would not be reviewed, push it up, and deploy.

I've not yet written the release script, but will as soon as it's easier to write the script than to do the release by hand.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
