### ISSUE TITLE
CLI downloaded solution does not match that shown in the UI

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/exercism#4410]
Here is a sample problem:

https://exercism.io/mentor/solutions/9bb1dba61a68430da79a43ad1bb8d9ac

This solution when downloaded does not include the finished article.
The poor student gets asked to fix errors that are not in their code.

**Comment by kannix** [comment]
A few details on what I did:
* I downloaded the solution using the cli (`exercism download --exercise=robot-simulator --track=elixir`)
* changed the file structure into a mix project (to try out e.g. `mix dialyzer`) After this change the downloaded files are in a subdirectory (`robot_simulator.ex` is now in `lib/robot_simulator.ex` and `robot_simulator_test.exs` moved to `test/robot_simulator_test.exs`)
* for uploading the solution I use `exercism submit lib/robot_simulator.ex`

**Comment by iHiD** [comment]
What solution do you get when you download that? There is only one file in the database and it's the one that is shown in the UI?

**Comment by sshine** [comment]
@chriseyre2000 wrote:
> This solution when downloaded does not include the finished article.
> The poor student gets asked to fix errors that are not in their code.

Could you clarify what you mean with "does not include the *finished article*"?

We do have a bug with synchronizing uploaded files across version changes of an exercise that manifests in many ways (#5052), and one side-effect is that new versions of files distributed to a student only get propagated all the way to the user once the test file, specifically, has seen changes (#4753). Is this an example of that?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
