### ISSUE TITLE
Community Solutions not showing the correct number of hearts

### ISSUE THREAD

**Issue by martinfreedman** [exercism/exercism#4413]
For example:

My solution has 3 hearts https://exercism.io/tracks/csharp/exercises/bracket-push/solutions/6bc795613efd4db398a1d120cad65149

whereas in the community solutions page it has none
https://exercism.io/tracks/csharp/exercises/bracket-push/solutions

**Comment by tejasbubane** [comment]
I can see 3 stars on community page:

![screen shot 2018-10-13 at 12 18 20 am](https://user-images.githubusercontent.com/980783/46888252-902e7e00-ce7d-11e8-8855-737a5e95c423.png)

Checked some other exercises and all counts look correct to me? @martinfreedman Can you point to another instance where the mismatch is seen?

**Comment by martinfreedman** [comment]
It has not changed using the link I provided - cache flushed. I do not know where you obtained that image from but it is not fixed,

**Comment by tejasbubane** [comment]
@martinfreedman Same link you shared:

![screenshot 2018-10-17 at 8 35 42 pm](https://user-images.githubusercontent.com/980783/47096172-444c5200-d24c-11e8-9e33-830527656154.png)

**Comment by iHiD** [comment]
You're (inadvertently) looking at different things. Your own solution appears at the top of this page, and has a different code-path to the other solutions on the page, which is why @martinfreedman sees one thing and @tejasbubane.

The offending line is [here](https://github.com/exercism/website/blob/master/app/controllers/solutions_controller.rb#L18) - it needs an extra thing adding for this solution.

I have a piece of work to refactor all this in my mind, but I've not typed it up.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
