### ISSUE TITLE
Show exercise concepts in mentor-mode

### ISSUE THREAD

**Issue by DocFogel** [exercism/exercism#4422]
The mentoring FAQ mentions that each exercise touches upon a few fundamental programming concepts. It would be nice to have this information easily available when mentoring. Currently I have to go to the list of exercises to get the concepts for the exercise I am mentoring. 

Listing the concepts under the Instructions tab would be "close enough" for me.

**Comment by jscheffner** [comment]
I'd love to have that. It's not always obvious which concepts the exercises touch upon even if you look through the list of exercises. Also, having a list of concepts an exercise touches upon requires the creator to think about what the exercise aims at which could lead to meaningful discussions and better exercises.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
