### ISSUE TITLE
Link to other mentors' mentored solutions

### ISSUE THREAD

**Issue by katrinleinweber** [exercism/exercism#4423]
As one mentor in a team, I would like to be able to easily find their comments to solutions they have mentored, in order to learn from them, and pass on advice which I didn't think of to my mentees.

related to #4083

**Comment by sshine** [comment]
@katrinleinweber: I'm a little unsure what this feature request involves.

Are you requesting that one mentor has access to the collected feedback of other mentors?

I think that would be very valuable.

**Comment by sshine** [comment]
Before the mentor dashboard got the nice right-hand queue overview, I ran a script that collected this information for printing in the Slack channel (Haskell track). A side-effect of doing this scanning is that one could technically extract the solution IDs and cache them. When other mentors pick them and they disappear from the overview, you still know what they're called; I wanted to make a scoreboard by extracting what mentors were active.

 for when other mentors pick them and they disappear.I thought that investigating what they wrote was a little invasive since it's not expected that you can do it, and so not part of the social contract, and I had little reason to pry because my mentoring was going very well.

But my point is that extracting this information is possible with the current website API for prototyping purposes without invoking @iHiD's resources, and at this point, I think the mentor's and the student's names are even redacted (but I could be wrong in the case where you're assigned as mentor for the course).

Besides anonymity, I don't know how relaying this works best: It would probably require website integration, since there is probably a large overlap between those mentors who stand to gain the most from watching review styles of others, and those mentors who aren't deeply involved with Exercism yet. (Complicated way of saying: Inexperienced mentors don't happen to find mentor notes in GitHub, and they probably won't explore some bootleg review evaluation tool that you and I reverse-engineer from the website API.) But it could be worth prototyping.

**Comment by sshine** [comment]
*(Side note: The reason I chose not to make a bootleg scoreboard was that it was borderline ethical for the same reasons outlined above, and that I figured it probably wouldn't motivate mentors when the Slack queue overview didn't. I could be wrong in the last part, though, because we have a much better churn rate these days. I know that @iHiD is cautious of using excessive gamification, but this is entirely unrelated to a the feedback learning tool that you propose.)*

**Comment by iHiD** [comment]
We're currently internally discussing a lot about some more fundamental changes to mentoring in general (part of Chicago project), which I think affects this discussion. I entirely agree with the general points raised here and feel its important to incorporate this sort of thing moving forward.

**Comment by katrinleinweber** [comment]
> …a little invasive since it's not expected that you can do it

Aaahhh! I think I didn't realize that mentor comments are hidden, even when a learner selects to publish their solution(s). Is that the case, being totally separate from [all those comments on published solutions](https://exercism.io/tracks/r/exercises/leap/solutions?order=num_comments&page=2).

**Comment by sshine** [comment]
Yes, public comments are distinct from mentor comments that are kept hidden.

Many of the public comments are imported from Exercism v1, I think.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
