### ISSUE TITLE
Limit amount of emails

### ISSUE THREAD

**Issue by tehsphinx** [exercism/exercism#4430]
## Problem description

- Personally I have turned off emails completely as they spam my inbox. I rather look on exercism for new comments/solutions. If there comes a time I am not able to check exercism that often any more turning of my emails can be a problem.
- If a student for some reason turns into an "angry student" he can start spaming a mentor with emails. If the emails contain the content of the angry comments Issue #4428 that can be a real issue as it is not so easy to just ignore the student.

## Possible solutions

1) It might be good to limit the amount of emails a mentor receives on a solution to 1 (one eMail with comment) until the mentor looks at that exercise again.

2) Another suggestion would be to have a option to get a daily report email only. That is more work though as the email needs a completely different layout.

**Comment by NobbZ** [comment]
In the current situation where there is basically not much of content in a single email I tend to confirm your opinion, a single mail is enough until I actually read the conversation I got notified about.

If though we add the actual content of the reply to the email, I'd be happy if I get an email per response **and** then I'd like to get notified even about what I write myself, such that my inbox contains a copy of the full conversation after I entered it.

So for my this suggestion as in the OP is contrary to #4428.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
