### ISSUE TITLE
Independent Mode: automatic mentorship bug?

### ISSUE THREAD

**Issue by pgaspar** [exercism/exercism#4432]
A student of mine is reporting a bug where they see a message saying “A mentor will leave you feedback as soon as possible” in Independent Mode. They say they sent @iHiD an email, but I’m following up with this issue as well.

Here’s the solution link: https://exercism.io/mentor/solutions/4e9510d934f44875a35410be96bf97d8

Could be related to #3809.

**Comment by iHiD** [comment]
@pgaspar Do you know if this is still an issue?

**Comment by pgaspar** [comment]
@iHiD I don't 😕 You can find the student's username on the link. Maybe reach out directly?

**Comment by int-index** [comment]
I'm facing the same issue with https://exercism.io/my/solutions/91163d8141d447b8822f57cd17440598

**Comment by iHiD** [comment]
@int-index Could you give me some background on how you got here pls? The system says that you clicked the "Request Mentoring" button at "2018-12-15 21:23:19" (GMT). Is that incorrect?

**Comment by int-index** [comment]
That's incorrect, I ran `exercism submit src/SumOfMultiples.hs` from the command line and that's it. Here's version info:

```
~$ exercism version
exercism version 3.0.9
```

**Comment by iHiD** [comment]
OK. Thanks. I'll try and debug it.

**Comment by texastoland** [comment]
Same here. I'm going through 3 tracks mentored and TypeScript independent. On the [second exercise](https://exercism.io/my/solutions/ba572727f605483097a85e3ec3c18b1e) I receive the same message as the OP. I'm not necessarily blocked because it appears all exercises are unlocked in Independent. I wasn't expecting that and kind of miss the game mechanic in my other tracks.

**Comment by iHiD** [comment]
@texastoland @confidentidiot Could you post screenshots please. It will help me debug. Thanks :)

**Comment by texastoland** [comment]
<img width="1295" alt="screen shot 2019-02-17 at 21 33 13" src="https://user-images.githubusercontent.com/48431/52924688-bf596e00-32fb-11e9-9bd8-6dc7015b85dc.png">

**Comment by texastoland** [comment]
<img width="1295" alt="screen shot 2019-02-17 at 21 35 27" src="https://user-images.githubusercontent.com/48431/52924730-fb8cce80-32fb-11e9-8015-4b9981c6ef15.png">

**Comment by texastoland** [comment]
<img width="1295" alt="screen shot 2019-02-19 at 16 58 00" src="https://user-images.githubusercontent.com/48431/53050746-0b292600-3468-11e9-9c02-2cdca9b327ff.png">

**Comment by iHiD** [comment]
@texastoland I don't see a bug in the OCaml one. For the typescript one, is there a button called "Complete exercise (unapproved)"?

**Comment by texastoland** [comment]
The OCaml one was in independent mode yet pending mentor feedback I hadn't requested. Yes I noticed the button a few days ago and completed all stuck exercises. Was it there before? The contrast makes it rather subtle.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
