### ISSUE TITLE
Calculate mentors' "weekly progress" per track

### ISSUE THREAD

**Issue by katrinleinweber** [exercism/exercism#4438]
https://github.com/exercism/website/pull/380 added a basic progress bar, calculated from [a static guesstimate](https://github.com/exercism/website/blob/4bfb65a58c60509756c98db500c694d8becc2df1/app/views/mentor/dashboard/show.html.haml#L22). In order to provide mentors with more specific data and thus a clearer view of the [situation in their track(s)](https://gist.github.com/iHiD/50f4fc82e63717766ae233f8f3854336), please consider updating the calculation to something more dynamic and track-specific.

For example: when 10 new solutions are posted early in a week, and 8 of them receive mentoring comments during the week, the progress bar should be at 80% at the end of the week.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
