### ISSUE TITLE
Solutions You're Mentoring section: reverse order to find recent submissions

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4439]
Currently the list of exercises showing up in this section are ordered Oldest First. As my number of mentorings is growing, the list doesn't show all the solutions. Even when filtered.

Most of the times when I'm looking for solutions filtered by `completed` or `waiting for them`, I'm looking for some recent solution. Those are not available in the filtered lists, as they are ordered oldest -> newest.

**Comment by iHiD** [comment]
These should be paginated so you can click through to all solutions.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
