### ISSUE TITLE
Update 'Code of Conduct' links across repos?

### ISSUE THREAD

**Issue by houhoulis** [exercism/exercism#4441]
In various exercism GitHub repos, I found several broken Code of Conduct links.  There are at least 13 broken links to "https://github.com/exercism/exercism.io/blob/master/CODE_OF_CONDUCT.md".

There's also one link to the Contributor Covenant, in [trackler](https://github.com/exercism/trackler): _"contributors are expected to adhere to the [Contributor Covenant](http://contributor-covenant.org/) code of conduct"_.  (Perhaps that's the right CoC for that project?)

1. Should I fix these across repos?
1. What is the preferred Code of Conduct link in a GitHub repo?
* https://exercism.io/code-of-conduct ?
* https://github.com/exercism/website-copy/blob/master/pages/code_of_conduct.md ?

**Comment by iHiD** [comment]
@houhoulis Yes please. Thank you! They should all go to https://exercism.io/code-of-conduct

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
