### ISSUE TITLE
Add link to exercise from student solution

### ISSUE THREAD

**Issue by swalladge** [exercism/exercism#4443]
Currently when mentoring student solutions it's difficult to find and download the exercise (eg. for solving it yourself). A link to the `/my/solutions/<hash>` on the `/mentor/solutions/<hash>` page for the corresponding exercise would be nice. 

Related: it would be nice to see the exercise id that is used in the `--exercise=` flag on all exercises to facilitate downloading the exercise without copy/pasting the download command.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
