### ISSUE TITLE
Completed side exercises should display differently

### ISSUE THREAD

**Issue by swalladge** [exercism/exercism#4444]
Referring to the small icons displayed in between the main track exercises like so:

![1540598936](https://user-images.githubusercontent.com/9714796/47597362-abe56880-d9d5-11e8-919c-930b3ef929bb.png)

I've completed the first three, but they won't display as completed unless I mouse hover over them. I know in the dedicated side exercise listing below the core exercises they are visually different, but it would be nice to have a similar visual indication here too.

**Comment by iHiD** [comment]
@nicolechalmers Let's revisit this question when you have some free time.

**Comment by Stigjb** [comment]
In addition to 'Unlocked' and 'Completed', these side exercises can also be in a state of 'In progress'. It would be great to see the states of the exercises without hovering over them or scrolling to the bottom of the track.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
