### ISSUE TITLE
Give contrast to the code background in the Light theme

### ISSUE THREAD

**Issue by Ornataweaver** [exercism/exercism#4447]
There is no contrast in code in the light mode with the dark theme feature disabled:

for seeing the difference I have used the "Dark Reader" extension on browsers.
Dark them and Dark Reader:

<img width="1440" alt="screen shot 2018-10-27 at 12 56 54 pm" src="https://user-images.githubusercontent.com/27126408/47602192-0982b080-d9e8-11e8-9300-1e209579ad5e.png">

Only Dark Reader (like Light theme, there is no contrast.):

<img width="1440" alt="screen shot 2018-10-27 at 1 03 16 pm" src="https://user-images.githubusercontent.com/27126408/47602228-d260cf00-d9e8-11e8-95ab-a94ad4e9edb8.png">

Light theme:

<img width="1440" alt="screen shot 2018-10-27 at 1 03 25 pm" src="https://user-images.githubusercontent.com/27126408/47602230-d5f45600-d9e8-11e8-9003-45b49e6bf185.png">

**Comment by sshine** [comment]
Just to clarify: You are requesting a bigger contrast between foreground/background in dark mode, right? As covered in #4924, we have an objective way to measure if contrasts are big enough using WCAG 2.1. Perhaps a first step would be to conclude how much off target we are in dark mode.

**Comment by Ornataweaver** [comment]
I was requesting a bigger contrast between the code divs and the background.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
