### ISSUE TITLE
Don't Skip Tests on Exercises Downloaded for Mentorship

### ISSUE THREAD

**Issue by bdjnk** [exercism/exercism#4459]
As a mentor, the first action I want to take after downloading an exercise for mentorship is to run the tests to ensure they all pass. None of the tests should be marked to be skipped in this scenario.

**Comment by iHiD** [comment]
So I wrote a little about my thoughts on this in [#856](https://github.com/exercism/exercism/issues/856#issuecomment-427475222).

My preferred solution to all the problems is to have some sort of per-language test-runner that fails fasts when any test fails. So we can eliminate skipping altogether, but still have the constraint that only one test will fail in any run.

**Comment by bdjnk** [comment]
That is fine and potentially worthwhile for students, but it seems like a complex undertaking.

As a mentor I simply want all the tests to run so I can easily provide feedback on the set of failures.

**Comment by rpottsoh** [comment]
Two test suites....  One with skips that the CLI serves to the students.  A second test suite could be served to mentors that would not contain "skips".  Can the CLI determine if a mentor or student is downloading in order to determine which suite to serve?  This idea only has about 60 seconds of thought behind it so I am will not be offended if no one likes it.

**Comment by iHiD** [comment]
Yeah. That would work. Depends if all the maintainers want to maintain two
test suites though. We could try and script it that per track i guess with
a rule to apply to each tests file.

**Comment by rpottsoh** [comment]
Those with test generators I would assume would not care too much.  Those without generators would be free to work out whatever manual means that they might come up with.  

Or perhaps each track could establish a search and replace pattern that the CLI would utilize when serving the test suite to a mentor, the CLI would remove or comment the skip calls based on the pattern....

**Comment by bdjnk** [comment]
Each exercise in each language should have a single test suite. Duplicating it may accomplish what I want, but at a cost I don't.

I like your latest suggestion @rpottsoh, that a pattern could be associated with each language, capable of unskipping all tests, and run by the CLI on mentorship exercise download.

**Comment by NobbZ** [comment]
Maybe I repeat myself, but @kytrinyx said when she first publicly talked about v2, that she wants that the Testsuite gets uploaded exactly as the student has it on disc, including unskipoed tests, personal additions or removals. 

If this would finally happen, this issue among many others were solved in an instant.

**Comment by kytrinyx** [comment]
I changed my mind about wanting to submit the test suite, at least by default.

Overall I think that it's useful to have everyone working against the same requirements (thank you for that phrasing, @bdjnk!). This will help keep mentoring consistent, and will allow for the addition of certain automated tools/steps to help offload simple things from mentors.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
