### ISSUE TITLE
Add a default icon for exercises that do not have a icon

### ISSUE THREAD

**Issue by PatrickHollweck** [exercism/exercism#4460]
The side-exercises in the csharp track are not displayed correctly

https://imgur.com/a/Mss0pm1

**Comment by FetzenRndy** [comment]
Alright. Should I close this then?

**Comment by iHiD** [comment]
No thanks. I've renamed it to solve the problem you've described - which is when we've not got an icon, it all looks rubbish :)

**Comment by F3PiX** [comment]
The latest title suggests that the track icon is missing, but it's about the exercise missing an icon. 
(I can't change the title myself)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
