### ISSUE TITLE
Add 'approved' status on solution in mentor view when someone else mentored

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4462]
I was mentoring a solution, refreshed and someone else had mentored ✨ 

I couldn't immediately tell from the comment whether it was approved or not. (It turns out, yes).
It would be *super* helpful if it said "approved" on that solution in this case.

**Comment by iHiD** [comment]
This is already there:

<img width="570" alt="screen shot 2018-11-15 at 13 04 49" src="https://user-images.githubusercontent.com/286476/48554714-0d16a280-e8d7-11e8-86da-2ac092a5a7e5.png">

**Comment by iHiD** [comment]
This whole page needs some restructuring. Something I want us to do in Jan.

**Comment by kytrinyx** [comment]
Sorry, I should have taken a screenshot. This is what I see:

<img width="536" alt="screen shot 2018-11-15 at 07 49 17" src="https://user-images.githubusercontent.com/276834/48557092-6537af80-e8ab-11e8-824d-1f3e0acfa766.png">

**Comment by luchiago** [comment]
Hi, this issue still need correction?

**Comment by iHiD** [comment]
Hello. It does but I don't think we'll do it as we're about to entirely restructure this page. Thank you for offering to help though!

**Comment by luchiago** [comment]
Ok, no problem.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
