### ISSUE TITLE
lookup www-myproxy.com: no such host

### ISSUE THREAD

**Issue by GregSimpson** [exercism/exercism#4463]
I am on Windows (using cygwin).
exercism worked the other day, but now fails on every attempt with:

$ exercism version --latest
exercism version 3.0.10
Error: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: dial tcp: lookup www-myproxy.com: no such host

$ env|grep HTTP
HTTP_PROXY=http://www-myproxy.com:80

Another thread (from 2014) mentions setting HTTP_PROXY to the exercism proxy host,
but does not say what that is.

Can you help please?

**Comment by rpottsoh** [comment]
Since you are on Windows can you confirm that the CLI is working properly outside of Cygwin?  Please include the output of `exercism troubleshoot` in a comment when executed at a Windows CMD prompt and from within a terminal window in Cygwin.  What version of Windows by the way?

I am not sure how much I can help, but the information I have asked for may be helpful to others monitoring this issue.

**Comment by GregSimpson** [comment]
Thank you for your suggestions.
This was working the other day.  I was able to upload my hello-world intro project.
I also tried it in a Command prompt window - same result:

exercism version --latest
exercism version 3.0.10
Error: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: dial tcp: lookup www-myproxy.com: no such host


I am on Windows 10 Home
Version 1803
64-bit
16G of memory


Here is the troubleshoot output:
exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.10
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: dial tcp: lookup www-myproxy.com: no such host

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\gsimp
Workspace: C:\Users\gsimp\Exercism
Config:    C:\Users\gsimp\AppData\Roaming\exercism
API key:   05a8*****************************58b

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: proxyconnect tcp: dial tcp: lookup www-myproxy.com: no such host]
    * 0s

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: proxyconnect tcp: dial tcp: lookup www-myproxy.com: no such host]
    * 0s


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.

**Comment by NobbZ** [comment]
There is a free and public anonymisation proxy service named "myproxy.com" is that the one you want to use or is there a proxy server in your network known to the local DNS as www-myproxy.com?

If neither of this is true, try `unset` the proxy variable and try again without having a proxy configured.

If though you intended to use the free proxy service, try one of their IP/Port pairs directly instead of using a name.

If though your intention was to use a proxy from your network and you actually need it to connect to the internet, you need to talk back to your networks administrator and double check its configuration.

**Comment by GregSimpson** [comment]
Thank you NobbZ.
unset -ing the HTTP_PROXY variable worked.
I do not know why or how it was set.  I did not deliberately do that.

Thank you for the fast responses, everyone!
