### ISSUE TITLE
Finishing the last exercise in a track has misleading message

### ISSUE THREAD

**Issue by Thiez** [exercism/exercism#4465]
I think an image best illustrates the problem:

![image](https://user-images.githubusercontent.com/204550/48289984-978f7a00-e471-11e8-8ba7-009e7bc06470.png)

The message suggests that another exercise should be unlocked ("You have unlocked the following Core Exercise:"), but no such exercise is displayed! Why? Because there are no more core exercises on the track (Haskell, in the example, but I imagine the text is the same for all tracks).

I had expected a message more along the lines of "Congratulations, you have finished the track. No more Core Exercises remain, but you can still do Side Exercises. You have unlocked the following Side Exercises:".

**Comment by iHiD** [comment]
Thanks. Well done on completing the track! :)

**Comment by Thiez** [comment]
My pleasure, I enjoy Exercism and am happy to see it improve. Too bad nobody spotted this sooner - this could have been a good hacktoberfest issue for someone 😃

**Comment by iHiD** [comment]
Ha - true.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
