### ISSUE TITLE
Sorting and filtering of tracks on personal dashboard

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4477]
As a student who has joined 30 tracks. I'd like to be able to filter/sort the tracks on my dashboard.

## sorting

* progress (absolute/relative)
* progress core
* progress side
* other?

## filtering

* core exercises available? (meaning preconditions are fulfilled to download the next core or having downloaded already but not committed yet)
* waiting for a mentor?
* changes requested by a mentor?
* approved but not completed?
* side exercises available?
* track can submit side exercise to a mentor
* track can submit legacy solution to a mentor
* other?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
