### ISSUE TITLE
Exercise Topics & Difficulty should display on My Solutions page.

### ISSUE THREAD

**Issue by yawpitch** [exercism/exercism#4478]
The _Topics_ and _Difficulty Rating_ of any given exercise are reflected only on the **My Tracks** page, which means that if you want to look these up you have to go back to the **My Tracks** page and do a search; it would be very helpful if these displayed on the **My Solutions** page for each exercise, ideally with a rollover or click through explanation of each.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
