### ISSUE TITLE
[cli walkthrough] mac os instructions using brew sometimes end up with old versions

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4482]
Let me first put a small disclaimer: I'm not using mac OS, and therefore the following is a bit of generic linux knowledge mixed with what I learned by helping students out. Knowing just enough to be dangerous ;)

Over the last couple of weeks, a lot of students asked for help in the gitter because `-token` was not a recognized flag. It always ended up beeing an old version installed.

For mac users this was often solved by running `brew update && brew upgrade`, so I assume, that the old version gets installed because of outdated repository data (recipies in `brew` parlance as I understood it).

My guess is, that there might be pathes in the mac OS instructions that do not use `brew update` before installing `exercism`.

Those pathes needs to get identified and fixed.

After a first glance, I identified at least, that after installing `brew` no `brew update` is done, but I'm unable to identify the correct files in the repository, as the mac instructions are huge…

**Comment by iHiD** [comment]
@nobbz @kytrinyx I've moved this to this repo as it's more likely to get someone pick it up with a PR.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
