### ISSUE TITLE
Suggestion for New Email Subject: Exercism Teams

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4486]
The existing subject (see below) feels like a company update. My suggestion is to change it to something like "You've been invited" or "Accept your invite" or "Invitation to X on Exercism Team".

<img width="693" alt="screen shot 2018-11-19 at 13 29 19" src="https://user-images.githubusercontent.com/5421823/48710096-3b5df000-ebff-11e8-9227-90fad5eecbc2.png">

**Comment by sshine** [comment]
@iHiD: Was this completed?

**Comment by iHiD** [comment]
Nope. Will accept a PR to `[Exercism] You've been invited to a team by Nicole Chalmers` :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
