### ISSUE TITLE
Edit to Teams Landing Page

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4487]
I think we need to be clear here that it's not necessary for existing Exercism users to create a new account in order to use teams. 

<img width="570" alt="screen shot 2018-11-19 at 13 33 52" src="https://user-images.githubusercontent.com/5421823/48710310-c6d78100-ebff-11e8-853d-423d1f48cffd.png">
We could add something like the following underneath the buttons.

> Already use Exercism? Sign in to your existing account and switch between to normal mode and the Teams Edition, from header menu.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
