### ISSUE TITLE
Team Invite Process

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism#4489]
There will be situations where creators of teams invite friends/colleagues to a team with the email address that is different to the email address that the friend/colleague has already signed up to exercism with.

I'm not sure what the best solution is.
Perhaps to have two links in the invite email - "Already have an Exercism account? Click here" and "New to Exercism? Click here"

**Comment by sshine** [comment]
I think an easy solution to this problem is to signify clearly in the email by which email address their friends/colleagues used to invite, so if it's the wrong one, they get a chance to object and have themselves re-added with the right one, and if they click, they consent.

**Comment by iHiD** [comment]
Sounds sensible at first glance. My mind is so far away from teams atm though, that I'll need to give it some proper thought when I'm in that space next :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
