### ISSUE TITLE
A way to provide track feedback or exercise specific feedback

### ISSUE THREAD

**Issue by jonakirke94** [exercism/exercism#4493]

**Comment by iHiD** [comment]
Can you please describe what this issue is about?

**Comment by NobbZ** [comment]
I can only guess.

Yesterday someone asked in the gitter whats the prefered way to give feedback to a certain track, as they considered their feedbeck not worth a github-issue (we told them it is, because they considered the learnig curve to be not balanced well).

Also the github repositories aren't always easily to discover.

Therefore I asked that user to file a bug here, that asks for an easier to discover way of giving feedback or even integrated into the site.

**Comment by jonakirke94** [comment]
Yes @NobbZ is spot on - I should have been more elaborate - apologizes!

**Comment by iHiD** [comment]
You can just open this issue in this repo and I'll triage it appropriately :)
