### ISSUE TITLE
Feature request: Let mentors see anonymised feedback from other mentors

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#4496]
1. Let mentors opt in (by checking a checkbox) that their feedback may show up as example feedback.
2. Give mentors a button for each exercise that provides random, anonymised feedback that has been given five stars. The student's solution is shown, but the student's identity is anonymised and their messages are marked as hidden. The mentor's identity is anonymised, but their messages are shown.

Right now I improve my feedback from (a) discussions on Slack (uncommon), (b) mentor notes (not good enough yet), (c) getting feedback myself (stops after a while), and (d) giving a lot of feedback, eventually learning from your smart students (doesn't work as well for low-volume exercises).

I don't know if there are implications of showing the student's source code anonymised. Perhaps another clause could be to only show examples that have been published by the student to the community, since then the code has been made publicly available, and the student's private messages are still hidden.

**Comment by F3PiX** [comment]
I'm all for ways to help us mentors improve our feedback. 👍 
And I'm not sure that these are the best ways to accomplish that. 
Mainly because I'm not at all convinced that '5 stars rating' and 'great feedback' are the same thing. (Full disclosure: I'm not a fan of rating mentors, I'd prefer that students would rate what they learned.)  

Re: means for feedback improvements
a) discussions on Slack:
Just after launching V2, when mentoring was introduced, there was a lot of discussions on Slack between mentors how to improve mentoring. That was inspiring and interesting and helpful to me. I wonder if we can use Slack better than we're currently doing?

b)  I'm thinking of ways how the Mentor Notes can be improved for the goal. 
In the Ruby Track, I shared a tried and tested standard snippet for one early exercise, for other mentors to use. Is that something you feel should be added to the Mentor Notes?

c) 'getting feedback myself' : what do you mean by 'stops after a while'?

You don't name the Mentoring Guides. You don't use them? Are they not helping to improve mentoring skills?

**Comment by sshine** [comment]
> I'm not sure that these are the best ways to accomplish that.
> I'd prefer that students would rate what they learned.

I agree.

> I wonder if we can use Slack better than we're currently doing?

We can; but I'd like to know how. I'm posting core queue statistics to the Haskell track channel to try and motivate emptying the queue before the end of the week. I'm not really sure that's working out. Slack offers some quite interesting discussions at times, but it's mostly brainstorming, bug-hunting and less a day-to-day learning-to-mentor tool.

> I shared a tried and tested standard snippet [...]
> Is that something you feel should be added to the Mentor Notes?

Good question! I don't know! The (limited) mentor notes for Haskell don't contain snippets. I have a growing snippet collection for the first exercises on the Haskell track. It is so valuable to me that when I leave my computer at work with them on, I don't bother to give feedback when I get home.

We should definitely look into popularizing snippet collections one way or another.

I don't think they should necessarily *be* the mentor notes, since they explain the exercise to a new mentor, while snippets automate the process once you've given feedback a number of times yourself.

Perhaps this is a discussion for Slack.

> You don't name the Mentoring Guides. You don't use them?

I'm not sure what they are. Is it [this page](https://exercism.io/mentoring-guide), or [this page](https://exercism.io/mentoring-faqs)?

**Comment by sshine** [comment]
I don't think snippets should be the format of mentor notes. To popularize snippets in some other way may be very valuable.

I'd like to see the anonymised feedback of other mentors for inspiration, whether it is selected via opt-in and ratings or some other recommender mechanism.

**Comment by sshine** [comment]
This feature was added, so I'm closing this issue.
