### ISSUE TITLE
Markdown code blocks have uneven background colour

### ISSUE THREAD

**Issue by bitfield** [exercism/exercism#4497]
![screen shot 2018-11-19 at 17 09 19 1](https://user-images.githubusercontent.com/142262/48916454-47a1b180-ee7a-11e8-8734-2aac0128bb11.png)

In the attached screenshot the `=` signs have a slightly lighter background colour than the rest of the code. This code is marked up as a code block in an Exercism comment with three backticks and `go`.

**Comment by SleeplessByte** [comment]
![image](https://user-images.githubusercontent.com/1964376/49244285-ba2d0700-f40f-11e8-8b4e-63415da6158d.png)
This is JavaScript, TypeScript, Ruby and Kotlin when it's indented...

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
