### ISSUE TITLE
Leave team

### ISSUE THREAD

**Issue by bkhl** [exercism/exercism#4499]
I don't see any way to leave a team on https://teams.exercism.io/teams/rust-mentors

It would be nice, as I'm in a couple of teams from the old site that are no longer relevant to me.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
