### ISSUE TITLE
Add pointer cursor to details/summary

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4500]
Add a pointer cursor to `.post-html details summary`

**Comment by jitenagarwal19** [comment]
@iHiD is it still up for grab? I would love to contribute if not.
Questions on this - 
1. Do you mean all the `.post-html, .details and .summary` styles?
2. Is there a classname called `summary`? Asking because I was only able to find 2 instances of summary and both are not used as class.(PFA)
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/8362231/49121019-f23a2a00-f2e9-11e8-9a18-1af77572639f.png">

**Comment by iHiD** [comment]
@jitenagarwal19 Thanks. Go for it :) I've update the OP with the correct css class. The details are summary are elements, not classes. Sorry for the confusion.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
