### ISSUE TITLE
Submit comment along with solution

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4501]
Mentors appear to have a much better experience when there is _some_ discussion along with the solution, rather than just code. One thing that may help this is if we allow people to submit a comment with the CLI along with their solution.

**Question 1: do we want to support this behavior from a product perspective?**
**Question 2: if so, what should the API and CLI look like?**

To support this we'd need to update the API to take an additional field ("comment" perhaps), and we would need to define the additional behavior in the CLI as well.

I am thinking something like:

* Flag: `--message`
* Short flag: `-m`

An improvement on top of this might be to ask for a comment interactively if none is provided, with the possibility of providing a flag in order to not be asked (e.g. `--no-message` or `-M`). If you simply press enter in the interactive prompt, we would submit without a comment.

I do worry slightly that it would be easy to accidentally not submit at all if you are unfamiliar with the command-line, so if we do the interactive prompt thing.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
