### ISSUE TITLE
What to do if mentor doesn't show?

### ISSUE THREAD

**Issue by crankysparrow** [exercism/exercism#4510]
I'm working through the Javascript track and got responses within a couple of days for my first few exercises. Currently, I've been waiting on a mentor response for about a week - is that normal? 

It would be great if there was a way to contact the mentor assigned to a solution, or make sure that it gets reassigned to a different mentor after a certain amount of time has passed.

**Comment by NobbZ** [comment]
No mentor gets assigned before they comment on your solution.

Also even if a mentor is assigned and he doesn't report back after you have resubmitted or commented, the solution should go back into the pool after a couple of days, at least I think this has been implemented already… @iHiD?

Because of its age it should be ranked relatively high by then and picked up by another mentor.

**Comment by SleeplessByte** [comment]
I think it's this one: https://exercism.io/mentor/solutions/05d2f49acf4b43db98d9656292f45516 right? 

I'll review it; that said -- the current backlog for JavaScript is _9 days_, yours is 7 days old.

**Comment by crankysparrow** [comment]
@SleeplessByte I can't tell since I'm not a mentor...but no need to review it ahead of the backlog! Helpful to know that wait time is normal - I was worried that something was wrong but it seems that's not the case. Thank you for checking :)

**Comment by SleeplessByte** [comment]
Change mentor in the URL to my :)

**Comment by iHiD** [comment]
For clarity, I hadn't fixed the issue with mentors disappearing once they had initially commented. This will get fixed by https://github.com/exercism/website/pull/491, which I'll run daily for a while before croning, and will eventually be formed into a reminder-framework to nudge mentors who disappear.
