### ISSUE TITLE
Improve complete solution dialogue

### ISSUE THREAD

**Issue by MaksimDanilau** [exercism/exercism#4511]
When you are completing a solution, that hasn't has been mentored, you, however, see the "Rate your mentor" dialog. 
![image](https://user-images.githubusercontent.com/8911660/49211273-3dc70380-f3d0-11e8-97f7-9419698f3463.png)

In my opinion, it's an unneeded step in this case.

**Comment by arhont375** [comment]
Also I don't like then need to click buttons 4 times. Maybe it's better to combine all steps in one form?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
