### ISSUE TITLE
Publishing of completed solution should also raise confirmation dialogue

### ISSUE THREAD

**Issue by arhont375** [exercism/exercism#4512]
1. Complete solution without publishing
2. Open this solution again and `publish solution` button available
3. Click this button

Actual behavior
4. Solution immediately published

Expected behavior
4. Confirmation dialogue `do you really want to publish` is shown

**Comment by iHiD** [comment]
@arhont375 Thanks for this. What's the reason for this?

**Comment by arhont375** [comment]
@iHiD Seems it's not possible to unpublish solution (at least I haven't found such button), so as this action is permanent then it's better to confirm with user if it his intended action and not misclick

**Comment by iHiD** [comment]
You can unpublish solutions at `/my/solutions`

**Comment by arhont375** [comment]
Thank you!  Just expected to see this button on solution page, not somewhere else.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
