### ISSUE TITLE
Allow to rate mentor after completion

### ISSUE THREAD

**Issue by arhont375** [exercism/exercism#4513]
I think it should be possible to rate mentor after submission if it was not done before. \
If during completion dialogue user forgot to rate mentor, but would like to rate him later such ability should be provided.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
