### ISSUE TITLE
Return an error if the CLI submits a file with a leading slash

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4518]
**BLOCKED by https://github.com/exercism/cli/issues/773**

If the CLI submits a filepath with a leading slash, there's something wrong—all filepaths should be relative to the exercise directory.

If such a filepath is submitted, it likely means that the submitter is using an old version of the CLI. We can check this by checking the `User-Agent` header of the request, and comparing it to the `Location` header when calling `https://github.com/exercism/cli/releases/latest`.

If they are on the latest CLI, then there is a bug, and we need as much information as they can give us. In this case they should open an issue in http://github.com/exercism/exercism/issues.

In both cases we should link to an explanation of how to proceed (to upgrade or to give us the CLI information we need).

See https://github.com/exercism/exercism/issues/4503 for background and the details of the investigation into this bug.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
