### ISSUE TITLE
Clean up stored filepaths that have a leading slash

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4519]
All filepaths for solution files in the database should be relative to the exercise directory. We need to run a script (very likely several iterations of a script) in order to clean up any paths that start with a leading slash.

I would recommend starting by cleaning up any paths where we can identify a directory that is `$EXERCISE_SLUG-$NUMERIC_SUFFIX`. Once we have that taken care of we can see how many are left and eyeball them for ideas about what patterns there might be.

The script should be idempotent so that we can run it once https://github.com/exercism/exercism/issues/4518 has been implemented and deployed, so that we catch any stragglers.

See https://github.com/exercism/exercism/issues/4503 for background and the details of the investigation into this bug.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
