### ISSUE TITLE
Accessibility - HTML tags are not semantic

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4522]
When I look at the HTML source code for the website I see div tags being used all over the place, even for wrapping text content. This would make it difficult for people using screen reading software to understand what is going on with the content and use its functionality. With the development of HTML5 we have a greater selection of semantic tags at our disposal than ever and we should be using them in the website to describe the content.

**Comment by iHiD** [comment]
Thanks @PatrickMcSweeny. Got a couple of concrete examples we can discuss?

**Comment by PatrickMcSweeny** [comment]
[The breadcrumb links](https://github.com/exercism/website/blob/master/app/views/my/tracks/show.html.haml#L6) on track and other pages should be in unordered lists.
[These stats](https://github.com/exercism/website/blob/master/app/views/my/tracks/show.html.haml#L26) should be an UL
[Exercise image tags](https://github.com/exercism/website/blob/master/app/views/my/tracks/_unlocked_exercises.html.haml#L3) lack alt attributes
[Progress bars](https://github.com/exercism/website/blob/master/app/views/my/tracks/_track.html.haml#L15) should use progress tags instead of divs
[Exercise title](https://github.com/exercism/website/blob/master/app/views/my/tracks/_core_exercises.html.haml#L17) should be a heading tag

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
