### ISSUE TITLE
Add link to unpublish solution on 'my solution' page

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism#4525]
I was expecting to find a link to unpublish a solution on the 'my solution' page and it took me a while to find the actual place to do it so I think it would be useful to include a link on the solution page itself.

I would be willing to work on this.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
