### ISSUE TITLE
Teams: Structured track

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#4530]
It would be great if Teams could actually select exercises and have it be a track, just like the current tracks. Right now they are random exercises everyone can just pick and work on. 

Use case:

We'd like to use Teams for our interns to get them to be more confident in the languages they are coding. The exercises and way of CLI + feedback via exercism is amazing, but we want our own "track-experts" to give them mentoring.

**Comment by jeff-m-sullivan** [comment]
I'm in the same boat, but for a different reason: I'm using Teams to help my kid learn programming. This enhancement would be a great help to that.

In the meantime, I've asked her to sign up for the regular track and post anything she needs help on into the Teams version of the same exercise. This gives her some structure and allows me to help, but it a little clunky.

**Comment by iHiD** [comment]
@jeff-m-sullivan If you sign up as a mentor you can get her to post solution URLs directly to you to mentor. As long as you get to them before a normal mentor, you'd still be her only interacting person.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
