### ISSUE TITLE
Mentor dashboard: sorting of `solutions you're mentoring`

### ISSUE THREAD

**Issue by tehsphinx** [exercism/exercism#4532]
The sorting of `Solutions you're mentoring' on the mentor dashboard seems to be oldest first.

That is perfect for "Requires action from you". But it is problematic if I am looking for a solution I just mentored or I mentored a few days ago. In "Completed" I never find something.

Maybe that could be inverted to show newest first for all drop-down items except "Requires action from you" -- until there is pagination and/or custom sorting.

Currently the only way to reach just mentored solutions is via browser history.

**Comment by iHiD** [comment]
Todo: 
- Invert to show newest first for all drop-down items except "Requires action from you"
- Add pagination

**Comment by F3PiX** [comment]
Related to #4439

**Comment by bitfield** [comment]
Is _that_ how they're sorted? It always appeared essentially random to me. Perhaps it's ordered by the date of submission of the _first_ iteration?

What would make more sense to me (and be extremely useful into the bargain) would be sorting by _last updated time_. I usually have 10 or 20 exercises in flight at any given time, and when I have a few minutes for mentoring I naturally want to start with the students who have been waiting the longest for my attention. Whether or not this is the default (which I think would make sense), I'd love at least the _ability_ to sort them.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
