### ISSUE TITLE
Begin walk-through link not displaying instructions if Ts&Cs not accepted

### ISSUE THREAD

**Issue by RangerDan** [exercism/exercism#4533]
Having navigated to a solution in Teams mode for the first time, the Begin walk-through button did not show the popover about the OS I'm using, "Welcome to the Exercism installation guide!"  Instead, it was forwarding me with a 302 to the Terms & Conditions page, but the page was not redrawing.  Right-click, Launch in new tab showed the Ts&Cs page just fine.  After accepting Ts&Cs and returning to the solution page, the popover displayed asking for my OS.

It could be that the popover cannot handle to Ts&Cs page redirect.  Once I accepted the Ts&Cs, the popover displayed the walk-through page.

Chrome 70
Windows 10

Steps:
- Sign up using Teams link
- Confirm Email
- In new tab, open exercism.io
- Log In
- Get added to team
- Go to Solutions list for a language (I chose C#, Accumulator)
- Choose a solution
- Click 'Begin walk-through' button, nothing happens
- Right click button, open in new tab
- Accept Ts&Cs
- Reload Solution
- Click button
- Walk-through instructions display

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
