### ISSUE TITLE
Bugs related to Markdown auto-bullets in comment field

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#4534]
## Bug 1
Write a comment to a student containing:

    - Hello <Cursor Here>World

and hit <kbd>Enter</kbd> This will produce:

    - Hello 
    - <Cursor Here>
    orld

so auto-formatting bullets eats the `W`.

## Bug 2
Write a comment to a student containing:

    1. Hello<Cursor Here>

and hit <kbd>Enter</kbd> and <kbd>2</kbd> in quick succession. This will produce:

    1. Hello
    23. <Cursor Here>

so auto-formatting numbered bullets increases the bullet count just slow enough for the counter to base itself on the `2` rather than the `1`, and to allow inserting the `2` before the bullet rather than after it.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
