### ISSUE TITLE
Add visual cue in the UI warning that tests might not match solution (pre-mid-2018 solutions)

### ISSUE THREAD

**Issue by PeterPerhac** [exercism/exercism#4535]
As discussed with @iHiD on Slack, 

> There's a lot of legacy here. We only linked solutions to the tests they were solved against relatively recently. For data before v2 (mid-2018) we have no linkage at all. And about 900,000 solutions that fall into that lack-of-knowledge bucket
> We've also probably made a bad decision in linking old solutions against new tests, which makes it hard now for us to know where the mismatches are too.
> We could/should probably add something to the UI for pre-mid-2018 solutions, warning that the tests might be a mismatch.

A badge/banner/icon could be added to each pre-mid-2018 solution to inform users that the version of tests could be different from the version of submitted solution. Also the solution could be for a different version of the exercise (possibly not a valid solution to the current version of the exercise)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
