### ISSUE TITLE
Topic field overflow

### ISSUE THREAD

**Issue by elyashiv** [exercism/exercism#4536]
![rust_topic_overflow](https://user-images.githubusercontent.com/1577529/49694896-f47a6f00-fb9a-11e8-967f-18aa19b63402.png)

This happened to me in the rust track, but I guess it's not unique for it...

**Comment by iHiD** [comment]
@exercism/rust - Could we reduce the length of that topic please?

**Comment by elyashiv** [comment]
Should there be a test for whether topics are too big?

**Comment by iHiD** [comment]
Probably, yes. But that would fit into individual tacks rather than the website repository. 

@kytrinyx Maybe this could go in configlet?

**Comment by rpottsoh** [comment]
@iHiD I don't disagree but would like to add that the primary basis for the topics is [TOPICS.txt](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt).  Perhaps this file should receive a once over to correct topics that are too long?  What is an acceptable max length?  Should this number be added as documentation to TOPICS.txt?

**Comment by kytrinyx** [comment]
@rpottsoh those are great points. I'm still not certain we've figured out how to manage topics properly, but I think until we do having a few things in place would help.

1. Figure out what the max length is. -- @iHiD ?
1. Open an issue in exercism/problem-specifications to ensure that TOPICS.txt adheres to that, and this is documented in the file.
1. Open an issue in exercism/configlet to add linting for topic lengths

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
