### ISSUE TITLE
language set up pages difficult to find, only linked from hello world?

### ISSUE THREAD

**Issue by absurdist** [exercism/exercism#4537]
I've come back to exercism after the redesign. I remember previously there were very useful pages about how to set up to work in a given language. For example, the cpp hello world says: 'Make sure you have read the C++ page on exercism.io. This covers the basic information on setting up the development environment expected by the exercises.'
Following the link to the cpp page is now just a list of tasks in the track.

Ok found the, link to : https://exercism.io/tracks/cpp/installation

These pages would be great have most prominent on the cpp page,

cheers

Mat

**Comment by NobbZ** [comment]
Those pages are still there and visible on each languages overview page in the right menu.

**Comment by F3PiX** [comment]
As there are more people that seem to not find that information easy, maybe the links should be on a more prominent place.

**Comment by SleeplessByte** [comment]
I've searched for it quite a few times when starting a new language. I expected the "Getting Started" walkthrough to have it, but it did not.

**Comment by iHiD** [comment]
We'll have a think about making them more prominent.

They're on the RHS of the tracks here FYI: 

<img width="895" alt="screenshot 2018-12-13 at 14 32 21" src="https://user-images.githubusercontent.com/286476/49945084-ee122d00-fee3-11e8-8a60-bad274d888b3.png">

**Comment by SleeplessByte** [comment]
Yep! That's where I got to it in the end :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
