### ISSUE TITLE
Feature request: Mark solution as requiring your action

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#4538]
In exercism/website#462 the ability to ignore solutions requiring action was added.

I'd like the opposite: For solutions that don't require my attention, mark them as requiring my action.

The use case:
- I approve a solution but recommend optional improvements.
- The student submits those and I get a notification.
- I check the submission on mobile, but realize I need a PC to give them proper feedback.
- *I mark the solution as requiring my action, even though it's approved.*
- I forget to do this, and the submission ~~disappears into the void~~ pops up on my mentor dashboard.
- I post my feedback and the `requires_action` flag is set to false again.

This button/link could be placed in the same green bar as exercism/website#462 introduced, but on the opposite condition.

**Comment by NobbZ** [comment]
As a workaround I shared those submissions to myself via google inbox and snoozed the link until I'm home/at work depending of direction of travel.

After google removed "snooze until location", I snooze until a time I expect to be near a computer.

Those are not very good workarounds and I'd probably use the proposed feature as well.

**Comment by sshine** [comment]
OK. I'm not using email notifications.

**Comment by NobbZ** [comment]
You do not need to use email notifications, you can just use the website and use the "share link" functionality of your browser. Well, and you need an app to share via that allows to share with self, and that allows "snoozing".

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
