### ISSUE TITLE
Feature request: mark extra exercises as completed

### ISSUE THREAD

**Issue by alex-bender** [exercism/exercism#4539]
I would be great to know which of the extra exercises are completed. So mark them with any symbol would be helpful.
(or at least differentiate it by color/shadow/gray out)
![image](https://user-images.githubusercontent.com/3628862/49795507-d0f22880-fd42-11e8-9b8e-223a692f0c0b.png)
Thanks

**Comment by SleeplessByte** [comment]
I agree. Right now you can see it by hovering. It will say "Completed", which is tedious.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
