### ISSUE TITLE
'No new notifications' when not on first page of notifications

### ISSUE THREAD

**Issue by bitfield** [exercism/exercism#4540]
To reproduce:

1. Go to the notifications page.
2. If you have more than one page of notifications, click to go to the last page.
3. Read all the notifications on this page.
4. Refresh the page.
5. It tells you 'You have no unread notifications at the moment', even though there are N other pages of notifications.

Perhaps if there are no new notifications on page N, you should automatically be taken to page N-1?

**Comment by OPARA-PROSPER** [comment]
@bitfield i tried the reproduction steps and the "You have no unread notification at the moment" did not pop up on the last page:

### last notification page
![exercism_last](https://user-images.githubusercontent.com/30195980/70657419-11d59380-1c5c-11ea-936e-84aafbb390af.png)

### notification page
![exercism_notif](https://user-images.githubusercontent.com/30195980/70657450-1f8b1900-1c5c-11ea-8bf5-8ab61d15fda2.png)

**Comment by bitfield** [comment]
Hey @OPARA-PROSPER! Thanks for looking at this.

In your second screenshot there, you have a notification showing, which is presumably why you don't get the 'you have no unread notifications' message. If you click on that notification, to go and read the comment, and then come back to this page, you should see the message I'm talking about.

If you are on Page 1 of your notifications and there's nothing to show, then it's correct. But if you are on Page 2, or any other page, then you actually have somewhere between zero and a full page of notifications (on Page 1) which you can't see, which is why the message is a bit misleading.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
