### ISSUE TITLE
Allow the comments to float

### ISSUE THREAD

**Issue by elyashiv** [exercism/exercism#4546]
It will be nice if the mentor comments will float while scanning the code. Sometimes I review a large piece of code, and it's a little annoying to scroll back and forth. I guess I can download the solution and split screen, and yet...

I guess this will also help the student following the comments :smile:

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
