### ISSUE TITLE
Christmas banner

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4551]
Note to self: add a banner for festive season warning that mentor response time might be slower than normal.

**Comment by sshine** [comment]
@iHiD: May make sense for the upcoming christmas. :-)

**Comment by iHiD** [comment]
We could do with a GitHub reminder bot that reminded me to do this on Dec 10th... :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
