### ISSUE TITLE
Add an 'updated' badge for updated Mentor Notes

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4553]
When I update Mentor Notes, I post the news to the Slack track channel, but not all mentors read that, or have that top of mind at the time they mentor that exercise. It would be nice to have an indication on the link to the notes that they are updated recently.

**Comment by F3PiX** [comment]
Friendly bump :-) 
With all the changes to the Ruby track, I'm also updating Mentor Notes a lot. It would be cool for mentors if a little badge would notify them that something changed recently. 
IMO it would be okay if it just was an "updated less than a week ago" kind of badge. And dissappearing after that week.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
