### ISSUE TITLE
Feature Request: Analyze Code Submissions in GitHub Repo

### ISSUE THREAD

**Issue by nodeselector** [exercism/exercism#4557]
Hopefully this is the right place for this, but after reading the roadmap I have a suggestion:

> **Online completion of exercises**
> Remove the requirement to install the CLI allow people to complete the exercises and run the tests on the Exercism website. This will also allow us to automatically run tests against submitted code to test that it works and help mentors.

I think that having to develop locally on ones own machine is always better than using an online code editor/IDE. Though automatic code analysis could still be possible by having users push their code to GitHub. Once on GitHub a submission can be analyzed and discussed.

Now you have:

1.  Users writing code in their preferred development environment.
2.  Users pushing their code to GitHub, thus building up their presence there. Not to mention increased familiarity with Git based commands and practices.
3.  Automated analysis of submissions.

**Comment by sshine** [comment]
As I understand it, @jeffmartinxyz is suggesting that people submit solutions to exercises by pushing to GitHub. This would mean that instead of lowering the bar for entry, as an online code tool would, we'd be raising the bar by requiring users to get familiar with git and GitHub before they can submit solutions.

If the purpose is to become CLI-independent (I've read one criticism of Exercism being that the CLI can be hard for users), perhaps allowing file upload via web would lower the bar of entry. As long as all solutions are *one* file it shouldn't be difficult. (Some use cases, e.g. adding extra dependencies to a project file, warrant multi-file upload, but not many students seem to learn this workflow.)

I personally think integrating GitHub is a great way to let people build their portfolios, and we'd have the benefit of GitHub's open APIs for improved distribution of developer workload. But I don't know if it'd be a good strategic choice to make Exercism more accessible. Those students who are already capable of using GitHub seem to be uploading solutions to their own portfolios, creating PRs on language tracks, etc. already. This has happened around a dozen times in my ~3 months here.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
