### ISSUE TITLE
Feature Request: Teams: Better access control (promote to admin)

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#4558]
As a first iteration, as an admin for a team, I would like to be able to give admin status to another user.

As a second iteration, it would be nice if there could be multiple admins.

---

As a third iteration, access control should be more fine-grained: Owner, admin, member.

There can only be one owner. There can be many admins.

Owners can change who is an admin or pass ownership status to one other user who must already be an admin on the team. (So a non-admin user would need to be promoted to an admin first; two steps prevents accidentally giving away a team.)

Admins can remove non-owner, non-admin users and have all the other privileges for which admins were intended.

The only purpose of owners is for distributing the admin privilege.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
