### ISSUE TITLE
Add pending solutions counter

### ISSUE THREAD

**Issue by alex-bender** [exercism/exercism#4561]
It would be nice to know how many solutions are pending.
In total and divided by tasks.
I'd like to know an approximate time what I need to spend on reviewing all existing solutions for the specific task.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
