### ISSUE TITLE
Streamline the cycle of download-submit

### ISSUE THREAD

**Issue by lucianferoiu** [exercism/exercism#4566]
The command line is quite verbose, having to specify the track and the exercise (by an identifier that usually needs to be copied form the website, etc). Also, checking the website for the slugs, clicking various buttons, copy-pasting the command line and so on are breaking one's stride :) -- especially in the solo ninja mode.

Wouldn't it be better if a _current state_ is maintained (perhaps backed by the config file) to remember the track, the current exercise, the path to it, the team, etc. and also the next exercise in the track?
The command line operations would be simplified:
```bash
$ exercism s[ubmit]
```
   submits the file(s) for the current exercise, in the current track etc.
```bash
$ exercism n[ext]
```
  downloads the next (just unlocked) exercise in the current track, without having to consult the website.

The track, team and all the other _current state_ values will be changed by mentioning them in the command line (the current practice).

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
