### ISSUE TITLE
Allow mentor to track ('follow') student progression

### ISSUE THREAD

**Issue by lbsa71** [exercism/exercism#4567]
As a mentor, I want to be able to 'fav', 'track' or 'follow' a student so that I can mark my interest in forming a longer-lasting cooperation.

Background:
As a 'mentor' one of my main incentives and motivations is to form longer-lasting relations (to create 'rapport') with students that I have had interesting interactions with; it would be very motivating for me to be able to 'bookmark' or 'subscribe' to a student so that I could get a notification when a student have submitted a new solution so I can then choose to mentor him again for this new exercise. 

I do not want to go as deep as to set up a 'team', merely to be able to give extra time to the students I have found the most rewarding to work with.

Related:
https://github.com/exercism/exercism/issues/4571

**Comment by lbsa71** [comment]
If you think this is a good idea, I could implement this and provide a pull request.

**Comment by iHiD** [comment]
@lbsa71 This is something we're going to be working on in the next few months, but will need to go through a wad of product-design work first, to work out the best ways to do it. I'll keep you updated on our progress here and let you know if there is an opportunity for you to help out with the coding. Thank you for the idea and the offer of help :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
