### ISSUE TITLE
large number of iterations causes issues with layout

### ISSUE THREAD

**Issue by mikewalker** [exercism/exercism#4575]
If you are on a tablet, or a narrow browser window the message about solution being published is a bit too small to read.  Maybe this should be flowed under the iteration numbers?

![interations](https://user-images.githubusercontent.com/1875177/50581523-51222000-0e0f-11e9-8bdc-77f04961f4a6.png)

**Comment by Smarticles101** [comment]
a flexbox would be perfect to wrap the iteration number boxes!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
