### ISSUE TITLE
Collaboration with Morning Cup of Coding

### ISSUE THREAD

**Issue by pekalicious** [exercism/exercism#4580]
I'm the creator of [Morning Cup of Coding](https://www.humanreadablemag.com/morningcupofcoding). I believe the goals of my newsletter and Exercism are very similar and would like to discuss some ideas I have for a collaboration.

**Comment by sshine** [comment]
Hi @pekalicious!

This is an open source project.

Feel free to discuss. :-)

**Comment by pekalicious** [comment]
Haha, good point 😄 

I'd like to find a way to offer my small community a curated version of Exercism. For example, a track with exercises I've selected based on articles I've shared through my newsletter. I understand that this does not fit the goals of the tracks on the main website, hence why I thought maybe a collaboration of some sort might be better?

I took a look at the teams edition but I'm not sure if that can work for me either. I thought maybe I could create a team with specific mentors that would give feedback to members of my community. However, it doesn't look like that is the goal of the teams edition. For example, it doesn't seem that as an admin of a team I can control much. There's no distinction between students and mentors that I can see, and there's no way to restrict tracks. 

What I imagined team edition would be was that I could bring in mentors and students, select specific tracks that I know my mentors can help with and let students take those tracks. Instead teams seems to be just the equivalent of Friends or Groups in social media, in that, team members use the site regularly with the only difference being that they can see each other's solutions? Please correct me if I'm wrong.

So, having said all this, is my best bet to host my own version of the site? I have no problem with this, I've already setup a local copy on my computer (with some minor issues) and it seems that I can take it from there, but I was hoping there would be a different option.

I'm open to any suggestions.

Thank you.

**Comment by sshine** [comment]
I think you've explored the easily available options: teams and selvf-hosting.

**Comment by pekalicious** [comment]
Gotcha. I'll see what I can do with self-hosting. Thanks.

**Comment by iHiD** [comment]
@pekalicious Thanks for the issue and @sshine thanks for helping.

Firstly, congrats on your project and its success so far :)

The exercism codebase isn't really meant to be deployed separately. You're welcome to try and do so, but it'll be increasingly hard to achieve over 2019 as we add more and more things in a micro-services style architecture, and migrations aren't always guaranteed to apply cleanly.

Your thoughts on Teams are definitely something we've thought about. The idea that admins can "assign" exercises to be completed. We've not taken that step yet, because we don't want to limit functionality on the teams side (and requiring admins to assign exercises would limit things for groups who have different workflows). But this would be an on/off feature we would consider. It's worth stating that our "goal" for Teams at the moment is to offer a private space, rather than to force people into a workflow. We've deliberately left it open until we better understand what the community want us to achieve.

Saying that, my gut instinct is that you could definitely use teams in its current incarnation. You could just create a team for your community and suggest to people that they do Ruby/Bob this week (or whatever). I don't think the UI needs to enforce that constraint for people to socially enforce it.

On a separate note, we're going to be generating a lot of content this year, specifically about exercises and how they can be solved in interesting ways. We're going to be looking for contributors who want to write good articles in exchange for the face/brand and links appearing next to them. There might be a source of collaboration here too. I'll be posting more thoughts/details about this over the next few weeks once the Core Team firm up the details :)

**Comment by pekalicious** [comment]
Hi @iHiD,

Thanks for your response and kind words.

I spent my weekend setting up Exercism locally and figuring out some of its components. Indeed there are already parts of it that feel hard coded, but I'm enjoying learning the architecture and how everything is organized. I'm pretty new in Ruby on Rails, so this is a great opportunity for me to learn.

I didn't realize Teams was so new. I haven't visited the site in a while, but after reading some other comments about them it seems that there is still work to be done to them. I can, as you suggested, use Teams by enforcing the rules socially, but after discussing with my community, the limitations don't stop there.

Specifically, the way we think we will use Exercism is by releasing a new exercise on a specific track every other week so everybody is on the same level and my very (very) limited mentors can follow along. The track is probably gonna be custom made and very likely will be using existing exercises from other tracks. Things are still up in the air as to what exactly our workflow will be.

So what I thought I'd do instead is maybe develop a third edition: Class Edition (I'm horrible at naming things). Basically, rather than modifying the systems that are already there to fit my needs, I'll just add something on top. Ideally this can be merged to upstream at some point after it has been battle tested in my small community.

I'm open to any type of collaboration. This is a fantastic platform that more people should be aware of  😄

**Comment by iHiD** [comment]
OK, great. I'll leave you experiment and have fun and see where you end up! Feel free to post here if you have any questions :)
