### ISSUE TITLE
Feature Request: Allow students to specify a non-exercism mentor/friend that is allowed to comment on their submissions

### ISSUE THREAD

**Issue by grepsedawk** [exercism/exercism#4581]
I'd love to be able to add comments to my friend that I'm mentoring's postings but when I visit his submissions in the comment pane I see the following: 
![image](https://user-images.githubusercontent.com/6721355/50749001-c91e8a80-1201-11e9-8d26-05ae55da6585.png)

**Comment by iHiD** [comment]
Hello :) If you want to mentor someone outside of the main mentoring flow then you need to use Teams. At the moment comments are not enabled on submissions.

Both of these are because we don't want unsolicited mentoring-style comments outside of the mentoring flow. I understand that that's frustrating if you are friends with someone and they want your input, but we're choosing to protect everyone from unsolicited comments for now. 

We'll re-enable comments at some point once we've worked this out :)
