### ISSUE TITLE
Auto-invitations to teams by domain

### ISSUE THREAD

**Issue by bkhl** [exercism/exercism#4586]
It would be helpful for setting up teams for work to have an automatic signup/invitation thing similar to e.g. Slack.

That is, if someone creates an account using a domain you have registered, automatically offer them to join the team(s) related to that domain, or at least make them be able to list the teams they are invited to by domain, and allow them to join them without team owner intervention.

**Comment by iHiD** [comment]
Nice idea.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
