### ISSUE TITLE
Show the whole queue

### ISSUE THREAD

**Issue by bitfield** [exercism/exercism#4608]
At the moment I think Exercism just shows you the top N pending solutions, rather than the whole queue. It would be good to be able to see everything in the queue, maybe paginated if there are more than X solutions waiting. At the moment there's no real sense of how long the queue is. If it's getting particularly long, this might help galvanise mentors into action to deal with it!

**Comment by Smarticles101** [comment]
I agree, it would be great to see some stats on mentoring for each track. Even just some text saying something like "20 / 200 total solutions" would be great

**Comment by F3PiX** [comment]
>this might help galvanise mentors into action to deal with it 

And also adapt their action, like quickly run through solutions that can pass without much mentoring, or save some presumably complex mentorings for later.

**Comment by BethanyG** [comment]
Big agree from me here - and that tags on to something I've been thinking about around _momentum_.    I'd love to be able to very quickly turn around something like `Two-Fer` or `Acronym` (exercises 2 & 3 on the Python track), since that could help build momentum for students.  But right now, I only see the top 20 from oldest to freshest unless I filter.

It's not that I want to neglect students who are further along (I really **don't!**) or cherry-pick -- but I also think that students who've gotten through the first few exercises and have come back for more are little more dedicated to the process, whereas the "newbies" might need a tighter feedback loop.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
