### ISSUE TITLE
Exercism download: not the same as visible in web interface

### ISSUE THREAD

**Issue by tehsphinx** [exercism/exercism#4611]
Have a solution here on the Go track that if downloaded does not match what the web interface shows.

Below what I did in the terminal to reproduce this.

```
 ~/Exercism/users > rm -Rf nmarlow
 ~/Exercism/users > exercism download --uuid=3f9d6a94c8714fc2b7510303b4b78096

Downloaded to
~/Exercism/users/nmarlow/go/hamming
 ~/Exercism/users > ~/Exercism/users/nmarlow/go/hamming
 ~/Exercism/users/nmarlow/go/hamming > ls -la
total 32
drwxr-xr-x  7 gabrielnelle  staff   224 Jan 19 09:13 .
drwxr-xr-x  3 gabrielnelle  staff    96 Jan 19 09:13 ..
drwxr-xr-x  3 gabrielnelle  staff    96 Jan 19 09:13 .exercism
-rw-r--r--  1 gabrielnelle  staff  2658 Jan 19 09:13 README.md
-rw-r--r--  1 gabrielnelle  staff  1210 Jan 19 09:13 cases_test.go
-rw-r--r--  1 gabrielnelle  staff    61 Jan 19 09:13 hamming.go
-rw-r--r--  1 gabrielnelle  staff   796 Jan 19 09:13 hamming_test.go
 ~/Exercism/users/nmarlow/go/hamming > cat hamming.go
package hamming

func Distance(a, b string) (int, error) {
}
 ~/Exercism/users/nmarlow/go/hamming >
```

The web interface shows a proper solution for the hamming exercise: https://exercism.io/mentor/solutions/3f9d6a94c8714fc2b7510303b4b78096

It is the first time I see this. It looks similar to #4503 as the downloaded file seems to be the stub.

**Comment by tehsphinx** [comment]
Found another solution where the solution file is missing completely when downloading:
https://exercism.io/mentor/solutions/2d019381aa074eeb85656c6e2494ef41

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
