### ISSUE TITLE
Different page for deleted exercises from generic 404

### ISSUE THREAD

**Issue by paparomeo** [exercism/exercism#4613]
As discussed in #4595 with @iHiD, this is probably not going to be trivial to implement, but it would be a better user experience if a page with a clear indication was displayed for deleted exercises that were already being mentored instead of the generic 404 which can be confusing.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
