### ISSUE TITLE
Reflect new rating calculations in median mentor rating

### ISSUE THREAD

**Issue by pgaspar** [exercism/exercism#4616]
https://github.com/exercism/website/pull/508 removes the bottom 5% for mentor rating calculations but did not update the median mentor rating calculation. It still displays the same value as before.

<img width="305" alt="screen shot 2019-01-19 at 16 28 47" src="https://user-images.githubusercontent.com/31735/51429550-5f41b000-1c07-11e9-8b50-84fc7dbd3077.png">

**Comment by sshine** [comment]
It still does.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
