### ISSUE TITLE
[Community Consultation] Exercism Mentor organisation

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4631]
Some people have suggested that we have an "Exercism Mentors" organisation on GitHub that mentors can be added to, which then means that others can see they are an Exercism Mentor and sort of act as a badge of honour. I quite like the idea as long as it's scriptable and I don't have to manage it.

Can I garner how much support there is for this please, and if anyone has any general points to raise?

Thanks!

**Comment by yyyc514** [comment]
I'd rather have maybe a cool little badge I could add to my blog, or a sticker for my laptop.

**Comment by iHiD** [comment]
Yeah, for clarity, I'm not saying this is the *one* way that we reward people. I just really want to know if anyone objects to this or has any good ideas about what it is / how it works / whatever :)

**Comment by ErikSchierboom** [comment]
I also don't mind it, but personally I don't really see much use in it.

**Comment by bitfield** [comment]
What problem are we really trying to solve here? I wasn't quite clear on that from your account of the suggestions (maybe they weren't either).

**Comment by QLaille** [comment]
If showing to the world that we are mentors on exercism means more pupils and mentors as well I am 100% okay with it.

**Comment by iHiD** [comment]
> What problem are we really trying to solve here? I wasn't quite clear on that from your account of the suggestions (maybe they weren't either).

It's a suggestion that has come up repeatedly with regards to https://github.com/exercism/exercism/issues/4304 I know from when I've been part of organisations in the past, it's given me a nice fuzzy feeling and it feels like low-hanging fruit to give others that same fuzzy feeling.

So I guess the problem is "what we can we do to help those who help us" and this feels like a *very* easy first step that seems to matter for some people.

**Comment by mikegee** [comment]
> for _whom_ does membership in a Github org appears as a badge of honor?

Great question! I occasionally click on a person's Github profile and check which organizations they are members of to get better feel for who I'm conversing with. I think showing that I'm a member of the Exercism Mentors group is a positive signal for other people working with me via Github.

**Comment by zhengfu23** [comment]
I would love to join the mentor organization!! It would be an honor and might attract more people to become mentors.

**Comment by bitfield** [comment]
> It's a suggestion that has come up repeatedly with regards to #4304 I know from when I've been part of organisations in the past, it's given me a nice fuzzy feeling and it feels like low-hanging fruit to give others that same fuzzy feeling.
> 
> So I guess the problem is "what we can we do to help those who help us" and this feels like a _very_ easy first step that seems to matter for some people.

Sorry to seem like a pedant (heaven forbid!), but that's a question, not a problem. If the problem were, for example, "mentors feel undervalued and unrewarded", that would be something I agree we should try and address. But first I'd want to know what data there is to support that hypothesis. A survey of mentors, for example, showing that a significant proportion of mentors feel that way, or some complaining blog posts and tweets.

To be clear, I'm not against this idea; I just want to enquire a little more closely into what's driving it, so that we can get a better sense of whether this _particular thing_ is a good solution to the problem. Obviously we can't know that until we know what the problem actually is.

> "Forty-two!" yelled Loonquawl. "Is that all you've got to show for seven and a half million years' work?"
> 
> "I checked it very thoroughly," said the computer, "and that quite definitely is the answer. I think the problem, to be quite honest with you, is that you've never actually known what the question is."
> 
> "But it was the Great Question! The Ultimate Question of Life, the Universe and Everything!" howled Loonquawl.
> 
> "Yes," said Deep Thought with the air of one who suffers fools gladly, "but what actually is it?" A slow stupefied silence crept over the men as they stared at the computer and then at each other.
> 
> "Well, you know, it's just Everything ... Everything ..." offered Phouchg weakly. 
> 
> "Exactly!" said Deep Thought. "So once you do know what the question actually is, you'll know what the answer means.”

**Comment by iHiD** [comment]
Pedantic is fine. Details are good :)

The problem is that not enough people mentor. Which is a result of problems such as:
- not enough people sign up
- not enough people go from sign-up to first-solution
- not enough people stick around beyond the first few solutions
- there's no strong extrinsic reward for mentoring

The solutions to these problems are complex and multiheaded. They involve everything from higher awareness, better UI, static analysis, better onboarding, improved notifications, automatic CoC monitoring, and feeling part of a community, etc. We are addressing all of those areas slowly.

This particular solution is a low hanging fruit that:
- Raises awareness ("what's this Exercism Mentors org that xy is part of")
- Increases a sense of belonging/community ("I'm an Exercism mentor. It says it on my GitHub") and therefore also increases a sense of responsibility (I'm an Exercism mentor so I should mentor")
- Gives a external extrinsic reward

I in no way think this is the solution to all our problems, but it *is* something that enough people see as a reward that I'm willing to do it, and it has the side effect of raising awareness. 

I hope we eventually get to a point where we make the intrinsic motivations clear enough that those themselves give enough reward without the need for "gamified" rewards, but in the interim I don't think it harms us to do this and I can see enough advantages to do it.

Does that help explain my thinking more?

**Comment by vladimino** [comment]
I would love to be a member of Exercism Mentors organization. There is no such thing as bad publicity (c)

In order to help with setting things up I've found a full guide for [Setting up and managing organizations and teams](https://help.github.com/categories/setting-up-and-managing-organizations-and-teams/) but with a quick scan wasn't able to find any automation options. Sorry and hope there are guys who did this before and can suggest the way to script members addition/removal.

**Comment by bitfield** [comment]
> not enough people mentor

Great, thanks for drilling down a bit further. Can we quantify this? What does 'enough' mean? If we can define some KPIs that encapsulate our definition of 'enough mentors', then we'll know if our putative solutions are having the right effect, and, indeed, we'll know when we're done! Test-driven product management 😏

**Comment by NobbZ** [comment]
I do not see value in this for myself, but for those that have a more GitHub centric world view, such an organisation might be beneficial.

I've heard there are companies hiring solely based on the GitHub profile...

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
