### ISSUE TITLE
Filtering the Mentor Queue

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4633]
I would love a different setup of the exercise filtering in the `Solutions to mentor` filter:
- first group: the core exercises in the order they appear in the track
- second group: side exercises alphabetically. 

Why?
- I use filter to find a specific core exercise far more often than for finding sides. 
- I can't remember the order of the core exercises.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
