### ISSUE TITLE
[Community consultation] Move track docs into website-copy

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4638]
I'd like to discuss the idea of moving tracks' docs into the website-copy repo (under `/tracks/$lang/docs`).

I have three main motivations for this:
1) I would like to build a website-copy team over time who can edit these. I would like to not give them write-permission to language repos but would to this. (These people might be experts in writing copy, not coding, for example). I also feel that this would remove some of the "burden" of maintainership and leave maintainers to just be thinking about exercises and curriculum (They could of course still contribute to both and I would expect maintainers to have website-copy write permission).
2) I would like them in one repo to make batch changes easier. I want to start being cleverer about how we can use all the content in these and that's much easier to work with if it's in one repo.
3) We can point new contributors to one repository and tell them to go help us here, rather than them needing to look in multiple places.

The two main disadvantages are:
1) The actual job of doing in, and the associated changes in the website (but as I'll be the one doing these I don't mind)
2) A loss of the fine-grained control of committers over docs (a non-Ruby person *could* merge a JavaScript PR). However, if we trust the person to be a committer, we trust them not to do that.

I'd appreciate everyone's thoughts, especially @exercism/track-maintainers, @exercism/website-copy and @kytrinyx :)

**Comment by coriolinus** [comment]
This sounds like a good idea to me.

**Comment by ErikSchierboom** [comment]
> This sounds like a good idea to me.

Agreed!

**Comment by bitfield** [comment]
Which docs are we talking about specifically? The mentor notes? The 'how to run the tests' stuff? Not the individual exercise READMEs, I'm guessing, since those are mostly generated.

**Comment by petertseng** [comment]
> Which docs are we talking about specifically?

I would like to take a guess at the answer, though I am not sure about it.

> under `/tracks/$lang/docs`

That these correspond to exactly the docs under https://github.com/exercism/$LANGUAGE/tree/master/docs

**Comment by petertseng** [comment]
EBWODP

> Answers range from Ceylon at 1.0 (the two are exactly equal) to multiple tracks at 0.0 (no lines in common).

As should be clear, answers were expressed as a ratio. Let's also express the range of values:

Answers range from Haskell at 41 lines in common to multiple tracks at 0.

> result of my net evaluation of the advantages vs disadvantages means I would support this change

I gave insufficient justification that balances the disadvantages because I only discussed the advantage. My justification would be more complete if I were to add the following sentence:

The situations that require a PR to two repos are rare enough that the increased overhead is an acceptable cost in exchange for the reduced scope of maintainership.

**Comment by F3PiX** [comment]
I'd rather have it the other way around: move all the track related stuff to the track repo, so that everything I need to keep an eye on is in one place. The disadvantage of being out of sight is partly covered with [auto-mentions 👍](https://github.com/exercism/exercism/issues/4637#issuecomment-457821224). 

But especially in regard to  the mentor notes, I'd rather have that I have/can search all issues and PR's in the track repo, and that all things related to an exercise in the Ruby track are stored together than in different repo's.   

More like how the `hint.md` file works: the shared part of the Readme is not in the language track, but the language related part is. 

I realize now that my hesitations are mostly because of the Mentor Notes. The thing is that those aren't actually 'copy', but part of the exercises documentation.
So I'd rather have an exchange: mentor notes to the track repo, readme's and more general track stuff to website-copy.  🤝 :-)

**Comment by iHiD** [comment]
Thanks everyone. Some notes on the key points raised below.

> Which docs are we talking about specifically? The mentor notes? The 'how to run the tests' stuff? Not the individual exercise READMEs, I'm guessing, since those are mostly generated.

As @petertseng correctly guessed the docs under https://github.com/exercism/$LANGUAGE/tree/master/docs

> I'd rather have it the other way around: move all the track related stuff to the track repo, so that everything I need to keep an eye on is in one place. The disadvantage of being out of sight is partly covered with auto-mentions 👍.

I feel that the cross-pollination benefit of having a specific copy team (especially moving forward where those people might include less technical people), and also the added burden that this would cause to track maintainers to have dozens of PRs into their track repos, makes this a less attractive option to me. A middle ground would be to have `exercism/ruby-copy`, which solves both our concerns about organisation, but again I'd be worried about the lack of cross-pollination and the added complexity of someone first starting out finding the right thing.

I would like to solve the problems of easy searching/filtering etc, but would rather do this with auto-mentions, auto-labels, etc.

> If we are in the situation where none of exercise_readme.go.tmpl moves to website-copy (case 2 above), the result of my net evaluation of the advantages vs disadvantages means I would support this change. 

Yeah - I think the `exercise_readme.go.tmpl` should probably stay where it stays.

**Comment by kytrinyx** [comment]
I think that moving the track-specific documentation to the website-copy repository would be good. I would like to remove the burden of maintaining this documentation from the track maintainers, and I would absolutely love to see some cross-pollination in these.

I agree that the `exercise_readme.go.tmpl` should remain in the track repository. Any copy that should be included in all exercises should go directly in the readme template rather than be included in the documentation copy.

As @petertseng mentioned above, the cases where we would need to edit in both places are fairly rare.

**Comment by sshine** [comment]
I can imagine the the main reason for deciding is a question of manpower. If enough tracks don't have the maintainer resources to maintain these files, and there is enough track-independent manpower to handle them, I think it's a good idea.

The drawback I see is that handling PRs to mentor notes seems a little overwhelming; I receive emails from the website-copy repo, and I open maybe 10% of them while e.g. @rpottsoh and @SleeplessByte seem to be doing a heroic effort there. So the cost of subscribing to changes to website-copy increases as we add more track-specific resources to it.

**Comment by iHiD** [comment]
@sshine Very good point. My solution to that is to auto-mention language-specific subteams in issues (see https://github.com/exercism/exercism/issues/4637), which means you can just unsubscribe from the repo and you'll only get emails for things your team(s) have been mentioned in. Does that make sense?

**Comment by Stargator** [comment]
I don't see an issue with how the docs are currently stored.

As a maintainer on a relatively new track (Dart launched in 2018, but efforts started in 2017), I think it would add additional complexity to anyone looking to launch a new track.

However, to address that issue. I would recommend we allow the docs to reside in the track-repo until the track is launched. That way the efforts for starting a new track are easily monitored until the track is ready.

**Comment by kytrinyx** [comment]
> However, to address that issue. I would recommend we allow the docs to reside in the track-repo until the track is launched. That way the efforts for starting a new track are easily monitored until the track is ready.

That's a good potential compromise, @Stargator.

**Comment by SleeplessByte** [comment]
@sshine is right. Right now during my OSS allocated time it's not a problem to run through website-copy as it's all bundled together. I'll abuse my polyglotting to respond to everything and mention the appropriate teams when I deem it necessary, but this will become _unfeasible_ if it were over 10 repos. 

The main reason I'm actively reviewing and merging is that there are a few great people right now such as, but not limited to @jeffdparker, @mikegehard and @michael-berger-FR who are submitting mentor notes and solution for exercises that have *none*. It helps the mentors of the track they're writing for so significantly that I'm trying to get it in as fast as possible.

If there were dedicated people for each track on a daily basis, this wouldn't be a problem so perhaps something for the future?

As a **maintainer**, my personal recommendation would be to keep it as is, and I'd concur this as **website-copy** team member.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
