### ISSUE TITLE
Add option to display mentor rating on profile

### ISSUE THREAD

**Issue by nathanchere** [exercism/exercism#4650]
It's one thing to say you 'helped x people', but I think more meaningful to demonstrate a higher standard of mentoring with fewer people than to simply approve a whole bunch of excercises with little or no meaningful feedback. It would also discourage people from 'mentoring' as a power trip or being jerks about it.

**Comment by BethanyG** [comment]
I do think having incentive (and standards and exemplars) to be a _good_ mentor would be nice.  But I don't know that displaying the _**rating**_ is really the way to go here.  That might exacerbate the whole "power trip" dynamic even further. 

There's also a big variance in opinion for what constitutes "good", so we'd really have to zero in on what that means for students and for mentors.  

I have a high rating over 250+ solutions, but it's meaningless  without specifically knowing the things I did well, and the things that I blew/could improve.   And it is even more meaningless to the student, because it gives them no insight as to how I behave as a mentor.  There are also situations where I simply can't give any meaningful feedback for a variety of reasons, and so just say "well done!" - which doesn't deserve any sort of rating at all.

**Comment by nathanchere** [comment]
> That might exacerbate the whole "power trip" dynamic even further.

I would concede it feeding a need for extrinsic validation in some people, but that in and of itself isn't a bad thing if the outcome is still a higher standard of mentoring. If someone is power-tripping off a high rating they will probably already be doing the same based on a high number of `students helped`, and can get away with very low-quality or outright damaging 'mentoring'. When the public quantification of their contribution is influenced by student feedback and how much they actually *help* rather than solely derived from one's turning over as many mentoring tasks as possible, I would expect that to have a significantly positive impact.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
