### ISSUE TITLE
Share My Solution with Team

### ISSUE THREAD

**Issue by zacjones93** [exercism/exercism#4654]
I recently created a Team to share solutions with a few people that I'm working on tracks with.

When I am in a specific solution in `My Solutions` on the `Team` page, I would like to share that work with others. It would be nice to share the URL but as of right now, sharing the url gives others in the team an error page.

As a member in a team, I would like a url to share a solution I've posted to the teams solutions so that I can get feedback from others sooner.

**Comment by sshine** [comment]
This would make Teams more useful. Alternatively, email notifications.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
