### ISSUE TITLE
My Solutions missing submissions

### ISSUE THREAD

**Issue by imminent** [exercism/exercism#4660]
I submit my solutions to team and personal, my personal solution count is 29, while my team solution count is only 21. When I check through a few of the missing solutions on the team Exercism, I go to Start New Solution and select the exercise. I then see that my solution shows on that page, but I don't see that my solution is visible outside of that.

**Comment by sshine** [comment]
Do I understand correctly that you're saying: This is a bug: The solution count on Teams is somehow lower than the actual solutions you can see that you have made.

> but I don't see that my solution is visible outside of that.

I don't understand this last part of your message. Perhaps you can clarify?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
