### ISSUE TITLE
Streamline solution publishing

### ISSUE THREAD

**Issue by rwstauner** [exercism/exercism#4664]
After taking some time off I have returned to find the "new version" of exercism.
Overall it seems just as nice as before.

I find the "publishing" workflow a bit cumbersome, though.

It would be lovely if i could:
- enable an "auto-publish" setting (publish upon submission)
- or a "skip the prompts" setting for pushing the publish button
- or if the cli could publish so that i could submit and publish in one go

Have any of these (or an alternative) been considered?
Would you be open to me pursuing any of these (or an alternative)?

**Comment by iHiD** [comment]
@rwstauner Hi and thanks for the idea. Are you working in mentored mode or independent mode?

**Comment by rwstauner** [comment]
independent mode

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
