### ISSUE TITLE
[Request for comments] Remove mentoring option in independent mode

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4671]
**Note: At this stage, I want use this issue to hear a wide range of opinions, rather than us debating each other's opinions. Therefore, please stick to only one post on this issue (but feel free to edit it freely).**

I am proposing removing the option for requesting mentoring in Independent Mode. I think this a sensible approach for the following reasons:

1) The Track Anatomy Project is defining a specific list of exercises that someone should take to ensure they do not overburden mentors by doing complex exercises when they only have basic knowledge. Independent Mode circumvents this and means often solutions are of a lower quality and need much more effort.

2) Now we have reintroduced community comments, people can publish their solutions and ask friends/world for feedback, without giving mentors the extra work to do. This largely negates the original need for requesting mentoring in Independent Mode

3) With the soon-to-be-announce Automated Mentoring Support Project, we will (over time) start to have automated feedback for users, which means Independent Mode learners aren't totally neglected.

4) Independent Mode was created to serve the needs of those who want to blitz through a track by themselves without being slowed down by mentors. It was not felt to be a core part of the experience, and as our mentors just about keep up with the Mentored Mode learners, I think the added burden that Independent Mode learners cause isn't worth it.

5) It would dramatically simplify the most complex part of the codebase, in which people often get into all sorts of weird situations due to moving in and out of modes. *(This is by far the weakest reason, and irrelevant on its own, but if all other pros/cons were equal, this would tip the favour of the argument for me)*

The counter-argument is that we want to support people who want to use Exercism outside of its more rigid structure and Independent Mode offers a pragmatic solution for that. I agree and support that argument, but I am not convinced that that "support" should extend to mentoring. However, mentors may not mind the extra burden, and Independent Mode users may really value the mentoring support. If that's the case, I want to know.

### Data

Some data which might be informative in making this decision (or may not be).

Since January 1st there have been 14,079 submissions in Independent Mode. Of those 1,897 have requested mentoring, and 460 have received it.

#### Submitted in independent mode
```ruby
[["python", 2838],
 ["rust", 1628],
 ["go", 1570],
 ["javascript", 1415],
 ["java", 1193],
 ["ruby", 958],
 ["csharp", 589],
 ["typescript", 439],
 ["elixir", 376],
 ["kotlin", 334],
 ["haskell", 320],
 ["bash", 277],
 ["scala", 256],
 ["fsharp", 251],
 ["c", 215],
 ["cpp", 213],
 ["swift", 173],
 ["clojure", 152],
 ["dart", 98],
 ["ocaml", 88],
 ["php", 81],
 ["julia", 76],
 ["elm", 68],
 ["elisp", 56],
 ["erlang", 51],
 ["reasonml", 42],
 ["groovy", 38],
 ["racket", 32],
 ["perl5", 31],
 ["prolog", 29],
 ["common-lisp", 27],
 ["crystal", 25],
 ["mips", 24],
 ["r", 24],
 ["nim", 22],
 ["objective-c", 17],
 ["purescript", 14],
 ["perl6", 10],
 ["lua", 9],
 ["scheme", 5],
 ["d", 4],
 ["vimscript", 4],
 ["sml", 3],
 ["delphi", 2],
 ["plsql", 2]]
```

#### Requested mentoring:
```ruby
[["python", 375],
 ["javascript", 249],
 ["go", 248],
 ["ruby", 143],
 ["java", 129],
 ["rust", 92],
 ["csharp", 78],
 ["typescript", 62],
 ["haskell", 59],
 ["elixir", 48],
 ["c", 39],
 ["bash", 36],
 ["swift", 36],
 ["scala", 35],
 ["clojure", 33],
 ["fsharp", 31],
 ["kotlin", 27],
 ["dart", 20],
 ["ocaml", 20],
 ["cpp", 16],
 ["julia", 14],
 ["prolog", 14],
 ["perl5", 13],
 ["elm", 11],
 ["elisp", 10],
 ["erlang", 9],
 ["reasonml", 8],
 ["racket", 7],
 ["nim", 4],
 ["php", 4],
 ["purescript", 4],
 ["scheme", 4],
 ["groovy", 3],
 ["mips", 3],
 ["perl6", 3],
 ["vimscript", 3],
 ["r", 2],
 ["common-lisp", 1],
 ["crystal", 1],
 ["objective-c", 1],
 ["plsql", 1],
 ["sml", 1]]
```

#### Received mentoring:
```ruby
[["go", 93],
 ["ruby", 60],
 ["java", 52],
 ["rust", 37],
 ["haskell", 29],
 ["elixir", 24],
 ["python", 22],
 ["csharp", 20],
 ["scala", 19],
 ["fsharp", 17],
 ["typescript", 15],
 ["swift", 11],
 ["julia", 10],
 ["elisp", 6],
 ["javascript", 6],
 ["c", 5],
 ["dart", 4],
 ["erlang", 3],
 ["kotlin", 3],
 ["ocaml", 3],
 ["perl5", 3],
 ["racket", 3],
 ["clojure", 2],
 ["perl6", 2],
 ["php", 2],
 ["prolog", 2],
 ["common-lisp", 1],
 ["cpp", 1],
 ["plsql", 1],
 ["r", 1],
 ["reasonml", 1],
 ["sml", 1],
 ["vimscript", 1]]
```

If there is other data that people feel would be helpful to make the decision (waves at everyone mentoring R and Python) then please let me know!

**Comment by bitfield** [comment]
I think there's a case for keeping this option, or something like it. Without it, a student's only two options are:

1. Progress one exercise at a time, waiting up to several days for a mentor response each time, depending on the track. (If turnaround time is greater than 24 hours, that means that you can't do Exercism every day, greatly reducing the likelihood of building a habit.)

or

2. No mentoring at all.

Neither of these is great. What's missing, especially for intermediate or advanced students, is the option to work at your own pace, completing as many exercises as you want until you get to one you're not sure about, and would like some advice on. You would then be able to ask for mentor input on that one, but still move on to the next exercise while you wait.

(Looking at community solutions is slightly better than nothing, but nowhere near as good as getting actual _advice_. There are thousands and thousands of solutions, and no way of knowing which ones are any good. Ratings aren't much help here. Some genuinely terrible solutions have quite high star ratings. What we'd be training students to do is to look at lots of indifferent-quality code and then copy and paste bits of it at random, which I suppose is at least some kind of preparation for life as a commercial software developer.)

It's striking that none of the reasons advanced for dropping this feature are about improving Exercism for _students_. Two of them are about the benefit to mentors, one about the benefit to maintainers, and the other two are _mitigations_ of the problems that removing it would cause.

This is a little like saying that one good reason for chopping your leg off is that you can get a prosthetic one instead. While unarguably true, on careful inspection it doesn't actually make a convincing case.

**Comment by yawpitch** [comment]
I would tend to agree with @bitfield here; I don't see from the above that independent mode submissions have been adding anything like an insurmountable burden to the queues, and in fact I see the benefits of people getting to the more meaty problems first if they're sufficiently skilled, and also mentors having a chance to hit the less-common problems more often.

Now _some_ penalty for Independent mode makes sense, because you want to dis-incentivize true noobs from essentially at-will skipping requisite skills only to barrel into something they're not prepared for simply because they did that skipping. The Independent mode really should be aimed at those who are sufficiently advanced or polyglot that at the very least the _core_ exercises can be readily self-managed ... anyone else should feel like they're in over their head. But to me that means maybe eliminating or bottom-of-the-queue-ing their _core_ mentoring requests, not removing those requests entirely.

**Comment by NobbZ** [comment]
I'm with I'm pretty much against disabling mentoring for independant mode for the reasons said already, but I do see the problems that arise with alowing it.

Perhaps put a "mask" over the independant mode, only alloowing to ask for review for exercises that the user would be able to do in mentored mode? So they can freely choose the order of doing the exercises, but only submit them in order of mentored mode, and also after they "progressed" and want submit the next exercise, ask them if they are happy with it after they learned something through the last review, and if they really want to submit it for review without iterating.

**Comment by timotheosh** [comment]
FWIW, I am for removing the option for independent mode. If they want mentoring, they are free to switch modes, and skip mentoring on exercises they do not want mentoring on. I'd even consider the option of just getting rid of independent mode altogether. There are plenty of other websites that offer a similar experience to independent mode. People who get the most from this site, are being mentored. All others can find far more expansive lists of exercises in independent mode elsewhere.

My back queue is polluted with independent mode submissions, and quite frankly, I have to ignore them. I have to give priority to those who are using mentoring mode. Tracks like Clojure and Python are so packed with backlog submissions from people who want mentoring, I don't think I have ever seen the independent mode submissions for either track, except for a couple times. They are full enough to where I am inclined to ignore the independent submissions in the quieter tracks like Common Lisp and Racket.

**Comment by lbsa71** [comment]
Decouple the incentive to 'work through the database for the fun of it' from 'have informed discussions about solving tasks in a certain environment' entirely. Allow anybody to download any exercise, but only allow them to submit to the 'current' mentored exercise. Once you have been approved on one exercise, you can submit the next one. Odds are, that if you had worked through it before on your own, once you revisit it to submit the next one, you will have had time to digest your new knowledge, and I would presume you would want to go over your old code before submitting.

**Comment by F3PiX** [comment]
I used to be not a fan of Independent Mode, but my opinion changed. 
I used to avoid students in Independent Mode, but one mentor (maybe Nobbz? I can't remember) opened my eyes, saying that they are really eager to learn the times they do request mentoring. After that, I changed my mentoring style for Independent mentorings; I refer to other exercises that prepare things, ask them how they solved it and if they see the similarity. In general, this will lead to longer and more in depth reflections. It changed my whole thinking about Independent Mode. 
I also like that Independent Mode really puts the student in charge of their own learning path, which is a key part of informal learning. At the same time, it is harder as a mentor to adjust the mentoring to the student, where in Mentored Mode the position of the exercise in the track helps the mentor to adjust the mentoring to the level of the exercise, and thus indirectly to the level of the student. 

The thing I really don't like is that the position in the mentoring queue is not fair; on the one hand, they always come last, and with the growing queues, they have to wait a really long time (in Ruby it's weeks now). On the other hand, they also come before the side exercises of Mentored Mode, meaning those are fairly chanceless to get up in the queue. Especially with the Track Anatomy Project, it's extra useful for Mentored students to have their side exercises mentored and preferable as early as possible for maximum pay-off.    
Also, because they can't see the difference between side and core exercises, we don't have the 'economy of scale ' that mentoring the core exercises have, because they can find exercises that are hardly ever seen, and those require more research time. That happens far less in mentored mode.    

ATM I'd vote to keep Independent Mode. Even though in general they require more mentoring time per exercise.

**Comment by ErikSchierboom** [comment]
I have a fairly simplistic view of this issue. In my experience, what makes Exercism unique is the guided, mentored learning model. The independent mode to me, is like a compromise, where we try to satisfy those users that don't want to use mentored learning. To then have those users request mentoring seems to go against the very fact that they chose to be independent. I would personally not mind if the whole independent mode would be removed. It is better to do one thing well, than to do two things moderately well IMHO.

It is interesting to consider _why_ people go with Independent Mode. I can think of several reasons:

- Progression is too slow in mentored mode. This is something that the mentor automation project can help alleviate greatly.
- There is not much to do while waiting for a core exercise to be approved. We can remedy this by adding more (simple) exercises and having a better side-exercise unlocking strategy.
- They feel that they already know the language sufficiently well to not need mentoring. IMHO this is rarely the case. Even experienced developers can learn new things about their language. If they really are experts that know the language inside-out, I don't think Exercism is necessarily the platform for them.

So my vote goes to removing Independent Mode, and instead work on the above-mentioned issues.

**Comment by bitfield** [comment]
It's worth noting that some people have said they started out in independent mode, but then having got feedback on one or two exercises, they found it so useful that they switched to mentored mode. If you remove the option to get mentoring in independent mode, you lose the chance to bring those people into the "real" Exercism. (If you removed independent mode altogether, I suspect those people would simply never sign up in the first place, which would be a shame, but as that's not what's being proposed, I mention it merely as a sidebar.)

**Comment by iHiD** [comment]
Really great to hear so many well-considered opinions. Thank you all. I will report back once the product-team has thought this through, but due to the lack of general support for the idea, I'm not going to prioritise that discussion internally (which is super-helpful in itself).

**Comment by johncip** [comment]
I'm not sure if this was meant to be limited to collaborators, but as someone currently using Exercism's Clojure track in independent mode, with a pending mentoring request, I was sad to see it called pollution and wanted to shed some light on why I hit the button.

Basically it's @ErikSchierboom's first case. I'm new to Clojure but not to programming, which means that it didn't make sense to wait (or create the review burden) on the earliest exercises. I did try mentor mode but switched off of it so that I could keep going. And viewing community solutions has mostly sufficed for showing what's idiomatic.

But I had one in particular that seemed like it could be made better, and IIRC the community solutions were a little over my head when I first viewed them. I took the "it might be a few days" to be in the ballpark. (That may have changed in the last week, but I believe I can't view them while the request is pending, and I didn't want to lose what I thought was a place in line.)

Exercism has in general been pretty awesome, and I've paid nothing for it, so I can't complain. I'd be happy with whatever -- including being locked out of requesting mentoring -- but I think that as it stands the wait time blurb understates things, at least for Clojure track, and that was part of why I made the request.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
