### ISSUE TITLE
Suggestion: Show discussion with mentor in Published Solution

### ISSUE THREAD

**Issue by Ding-Fan** [exercism/exercism#4677]
It should be really helpful to show discussions in the published solution. The discussions with the mentor always showing why this published solution goes there.

And I found a bug, my first submitted code was approved, then I can publish my iteration without verified by the mentor.

**Comment by iHiD** [comment]
Hello :) 

Yes. This is something we're considering. However, we would want it to have the approval of both the learner and the mentor, and we would not want it to be on by default, as many conversations are private. 

> And I found a bug, my first submitted code was approved, then I can publish my iteration without verified by the mentor.

That's not actually a bug - the mentor's job is to ensure you've learnt "enough" from the exercise. What you choose to do after that is totally up to you :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
