### ISSUE TITLE
Order mentor notifications oldest to newest

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#4678]
Somewhat related to #3883

As I usually have over 4 pages of notifications, it's much more streamlined to respond to the oldest notifications first. Right now I constantly have to click last page, click a notification (or open in new tab) and repeat.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
