### ISSUE TITLE
[Community consultation] Snippets for mentors

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4687]
I often use the same handful of snippets for all solutions.

- Most of my mentorings start "Hello, well done on getting the tests passing!\nHere are few suggestions to make this a bit more idiomatic:"
- If the solution is approvable immediately I'll say: "Hey! This is great and I've approved it. Well done! :)". I might then go on to make a suggestion.
- On the first exercise of a track I'll say something like "Hey and welcome to the Exercism Ruby Track!"

I'd like to bake a few basic snippets like this into the UI. I'm thinking between 3 and 5 that are pre-populated with some defaults (e.g. the hello one and the approval one) and let them be editable by mentors in settings.

I know many mentors use a separate snippet tool to manage this sort of thing, but I think it would be helpful to mentors who don't want to install extra software, and give new mentors some guidance of good things/tones to set.

Your thoughts would be appreciated (but please keep them specific to this topic rather than other feature ideas 🙂)

**Comment by adeshmukh** [comment]
This would be very useful indeed!

Were you planning on allowing the ability to organize the snippets per-problem? That would be super helpful.

After reviewing a bunch of solutions for the same problem, I can usually bucket a sub-optimal solution into one of a handful of previously encountered "categories". At the moment, I organize my responses by these categories and pick the appropriate response snippet, to then further customize.

**Comment by iHiD** [comment]
> Were you planning on allowing the ability to organize the snippets per-problem? That would be super helpful.

I'd see this as a separate thing (ie https://github.com/exercism/exercism/issues/4083). But they might end up as part of the same UI.

**Comment by yyyc514** [comment]
Indeed, I use a separate tool but if it was built in and worked well that'd be a boon to everyone I think.

**Comment by ErikSchierboom** [comment]
I like this. It feels like a great first step towards #4083 (which I would love!).

> [...] let them be editable by mentors in settings.

So mentors can customize the snippets to give their own, personal touch to them?

Just a thought: would it make sense to have these snippets be defined in the website-copy section, possibly per track? This would allow one to customize the default snippets per track.

**Comment by chriswmercer** [comment]
Sounds like a great idea. I've got a OneNote page with my snippets on, but having it in the UI would be great!

**Comment by lbsa71** [comment]
Same here, I have a notepad file with a basic skeleton per exercise, that I would love to have automatically pasted into my first 'review' comment.

**Comment by kytrinyx** [comment]
> After reviewing a bunch of solutions for the same problem, I can usually bucket a sub-optimal solution into one of a handful of previously encountered "categories". At the moment, I organize my responses by these categories and pick the appropriate response snippet, to then further customize.

@adeshmukh this is exactly how I've been doing it (since 2013!). I used to just put all my notes in a doc that I could copy/paste from, but in the past year I've become an avid user of TextExpander.

@iHiD I think that having the snippets easily available is absolutely key to smoothing out friction. For me keyboard shortcuts are essential. If I have to click I probably won't use the UI. That said... I have textexpander so I don't need to, and I have no idea if others are as curmudgeonly as I am with respect to keyboard shortcuts.

I think it's crucial that the snippets be customizable. I would probably never tell someone "Well done :)" We can talk about why, but it's not actually important. Suffice it to say that it would feel extremely unnatural and awkward to me.

> would it make sense to have these snippets be defined in the website-copy section, possibly per track? This would allow one to customize the default snippets per track.

I think this would be very interesting. It's a step further than the shared mentor notes, and it would allow us to do a couple of key things:

- *identify _actual_ patterns* - in two-fer in Go there are maybe a dozen things that I comment on over and over. Knowing what they are for any given exercise would be hugely valuable, as we can use that to ramp up new mentors, to write interesting blog posts, and to inform the automated mentor support.
- *optimize points* - sometimes we've had really interesting conversations between mentors about how people react really poorly to certain suggestions, and in the discussion we realize that there is an underlying point that we're assuming but not making. By having this discussion we're able to figure out what those points are, and ways of phrasing them that communicate them well. This isn't about finding a single voice or tone or something that everyone uses, but figuring out what raises people's hackles and why, and also why a piece of feedback is important in a certain track or for a given exercise.

**Comment by BethanyG** [comment]
I also have snippets I cut and paste - mine are loosely organized by topic (comprehensions, classes, lists, looping, etc.) as opposed to exercise and include some links to supplemental material.  

I would _**love**_ keyboard shortcuts ... but would also love to be able to maybe bulk-edit pre-made snippets or have a set I've uploaded in addition to the basic ones. (a la, https://github.com/exercism/exercism/issues/4083) 

To tag onto what @kytrinyx  said above, each programming language (while being general-purpose) has a community perspective, core problems it was originally made to solve, and core idioms/perspectives.   So being able to edit/keep snippets by track and by exercise would allow mentors to not only zero in on patterns from the submissions..but also zero in on the way a particular community talks about solving problems in that language.  Again - not "one voice" - more like "these are some of the patterns you'll encounter as you talk to other programmers who work in this language."

**Comment by iHiD** [comment]
> So mentors can customize the snippets to give their own, personal touch to them?

Exactly.

> Just a thought: would it make sense to have these snippets be defined in the website-copy section, possibly per track? This would allow one to customize the default snippets per track.

I see these snippets as being personal to each person (per your first clarification) and needing to be real-time updatable and distributed across servers. I'd therefore expect to store them in the database, rather than in git. I don't massively mind the idea of default snippets being stored in website-copy but it feels like overkill, especially as I'm not sure how they could be track-specific.

There's an extra piece of functionality between the mentor-notes and the personal-notes of #4083, which is just general quick pastable snippets. Maybe that is more what @ErikSchierboom @kytrinyx and @BethanyG are referring to? That's quite different to this issue (3-5 one-sentence one-liners) but it's a valuable idea. I actually suspect that these will come via the Automated Mentoring Support Project, rather than adding a third modal/section/option to the UI, but I'm open to be disagreed with or being told that this is valuable enough to prioritise now?

**Comment by ErikSchierboom** [comment]
> [...] the personal-notes of #4083 [...]. Maybe that is more what @ErikSchierboom 

That is indeed what I am referring to! Personally, I would really benefit form having these, but it is not altogether that bad to copy-paste them from a Google Docs file. It's just less efficient.

**Comment by F3PiX** [comment]
A different line of thinking would be: ask TextExpander to sponsor Exercism Mentors. It has a functionality for Team Snippets, so we could have both Track snippets ("`join(" ")` is default in Ruby") and Exercise snippets ("Use `scan`" in Acronym), and site wide snippets (I have a snippet to get the url of an exercise, where I fill in the exercise name only.)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
