### ISSUE TITLE
[Community consultation] Weekly mentor update

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4688]
Hello mentors.

I want to start putting a weekly mentor email out, automated with some stats both general and personal, as well as some links to anything relevant/interesting to mentors (blog posts, issues etc). This has two aims:
1. A heartbeat of how your track(s) are doing, and being able to keep on top of any news etc without having to check Slack every day.
2. A gentle reminder/nudge to mentors who have forgotten about mentoring.

Mentors will be able to opt-out with a single click.

Before I put together a firmer plan, I wanted to hear anyone's opinions on **what** should go into these emails. Thoughts please? :)

**Comment by sbromberger** [comment]
I think the "opt out" may be a problem. It's easily solved by having something in the mentoring agreement that states, "By becoming a mentor, you agree to receive weekly emails. You may stop receiving these mailings at any time by following the link included at the bottom of every email." – that way it's opt in and you can't be accused of spamming.

**Comment by ErikSchierboom** [comment]
What I as a mentor am most interested in, is how well we as mentors are coping with the workload. So I'd appreciate things like:

- Total number of mentored solutions in total
- Total number of mentored solutions by me
- Total number of mentors that have mentored solutions
- Total number of new submissions per exercise
- Total number of mentored submissions per exercise
- Maybe something like average wait time for mentoring per exercise?
- Maybe average number of iterations before approval per exercise?

Note: all the above are of course in the context of the language I am a mentor of.

**Comment by mikegee** [comment]
> 2\. A gentle reminder/nudge to mentors who have forgotten about mentoring.

I'm doing a pretty good job remembering to visit the site every couple days lately, but my habits might change and I would appreciate receiving this email.

**Comment by Smarticles101** [comment]
To add to the list @ErikSchierboom listed it might be nice to have

* Total number of solutions
* Number of core solutions
* Number of side exercise solutions
* Mentor rate of core solutions vs side solutions

**Comment by BethanyG** [comment]
Agree with all of the above, but also might be nice to have:

1)   Welcome section for the latest mentors added on the track.
2)   General announcements on changes/improvements added since last email.
2)   An exemplar piece of feedback / code from your track(s), and why that feedback / code is good.
3)   Optionally submitted "struggle" from a student / mentor for the track - and ways it got resolved.
4)   Any patterns in users/submissions/mentoring that have shown up for the track(s).
5)   Rotating section that has feedback about exercism (maybe pulled from the "testimonials" channel?), general tips on giving/getting feedback on code, productivity tips from other mentors, small blurbs on the benefits of mentoring with exercism.

**Comment by iHiD** [comment]
All fantastic ideas. Thank you. 

Re the emailing side of things, I'm actually fine with just emailing existing mentors and giving them a clear opt-out button and a specific option in communication preferences, and for new mentors, making it clear that we'll send them emails that they can opt in/out of on the mentor sign-up form bit. I'm comfortable with that from a GDPR point of view, and the data is held and processed by a UK company in the EU, so that feels like the best barometer to me.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
