### ISSUE TITLE
Remove "Review this solution" unless there are no mentors 

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4689]
Part of https://github.com/exercism/exercism/issues/4658

Remove it:
- [ ] if there is a solution lock in place
- [ ] if `num_mentors > 0`

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
