### ISSUE TITLE
Notifications API

### ISSUE THREAD

**Issue by codeholic** [exercism/exercism#4691]
That would be really nice to have in-browser and mobile [push notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API). Especially for mentors, but also for students.

**Comment by iHiD** [comment]
I like this idea. I think we'll be implementing this as another project I manage so we can then copy/paste the functionality here when that's done.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
