### ISSUE TITLE
Please point me to issues that discuss uninstalling CLI

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism#4705]
@onlinematters commented on [Thu Feb 14 2019](https://github.com/exercism/website-copy/issues/788)

I see in one entry about uninstalling cli that there are other issues that describe how to do that, but I can't find them.  Can you point me there or tell me how to uninstall the CLI?  The FAQs do not provide any discussion I can find.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
