### ISSUE TITLE
Rust track - no response since december

### ISSUE THREAD

**Issue by VersBinarii** [exercism/exercism#4706]
Hello,
I had no response to exercise for over 2 months now and just wanted to see if its visible to mentors/back in the queue  as the mentor that had initially looked at my solution was removed from team due to inactivity.

I understand the track is overloaded so dont mind waiting as long as there is nothing wrong with my account.

Regards,
K

**Comment by rpottsoh** [comment]
Please post the url that takes you to your submission for the exercise you are seeking mentoring.  Namely the UUID from the link is what is most important.

**Comment by VersBinarii** [comment]
Hello,
Please see here: 33bce11f696244fcacd4bc14a5e69138
I'm not trying to "jump the queue", just to make sure all is fine with the account.

Thanks!

**Comment by rpottsoh** [comment]
@exercism/rust

**Comment by petertseng** [comment]
one should notify the Rust mentors rather than the Rust track maintainers for this; I have no power to see the mentoring queues

**Comment by petertseng** [comment]
(Therefore, I humbly request you do not mention `@exercism/rust` for matters that are pertinent to Rust mentors)

**Comment by iHiD** [comment]
(We will at some point in the not too distant future add a `@exercism-mentors/rust` team for this sort of purpose)

**Comment by ananthp** [comment]
Same issue here. My solution for _Saddle Points_ in Rust track is awaiting response from a mentor for over a month. UUID: `ed685d4769774f518bed24013290d02c`

Is this a technical issue?

**Comment by coriolinus** [comment]
This is a social issue. There are a lot of people interested in learning Rust. There are not very many people interested in mentoring Rust. Being a mentor is uncompensated volunteer work, and it is work: you have to interact with strangers and help them learn, judge their random code and pronounce which parts are good, which need improvement. There are people for whom this is rewarding, fun. They are few.

I'm one of the Rust track maintainers; this works because it doesn't require a huge time commitment. I technically am a mentor as well, though I went inactive almost immediately. Good code review takes effort, and it takes time, more than I am prepared to offer. I'm not willing to be a bad mentor, so I no longer mentor at all.

**Comment by iHiD** [comment]
Also, Rust is the worst track by far for student/mentor ratio. The main reason is that order of the exercises isn't optimised for ease-of-mentoring. In Ruby, for example, I can mentor any core exercise in 1-5mins. But in Rust the choice of core exercises, mean that that's not the case, which means it's a lot harder for mentors to get started, and a lot harder to continue. We have an ongoing project (now being led by @thedarkula) which aims to fix this.

**Comment by YBogomolov** [comment]
Maybe, it is possible to add some kind of cross-mentoring newbie students by students who, say, at least half-way up the track? My solution `a10779f7cd6f4136af8ac6150b043f74` is only about a week without feedback, but it seems that it may be left without any attention for a lot more, which makes me genuinely sad.

**Comment by VersBinarii** [comment]
@YBogomolov I actually did just that. I'm halfway into the core track and have been helping with the exercises that are below my current core exercise.

I will close this issue for now.
Thanks to all involved
