### ISSUE TITLE
Ensure Hello World exercise is as simple as possible in all tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism#4707]
We're starting to look at how to simplify the hello world landing page on the website, and one of the things that came out of that discussion, is the need to ensure that every single language track has the simplest possible "Hello, World!" exercise.

We should define exactly what that means, but at first glance that would be:

1. There is a stub solution that is missing _only_ the string `"Hello, World!"`
2. There is a test suite with exactly one test in it ("say hi"), that asserts the returned string
3. The README correctly states to return the hard-coded string

In other words, no default values, no conditionals, and also no having to write boilerplate. Just adding the string.

Later we'll probably have something to say about the README as well, but for now I think we should ignore that and just ensure that the test and stub file are present

Here is the full list of all the hello world exercises.
If someone would be willing to comb through and identify which tracks will need to be simplified, that would be a grand first step!

---

Per @NobbZ' investigations in https://github.com/exercism/exercism/issues/4707#issuecomment-463959275 here are the tracks that might need to update their test suite or readme:

- [ ] ballerina
- [x] bash
- [x] coffeescript 
- [x] d 
- [x] haxe 
- [ ] objective-c 
- [ ] plsql 
- [ ] powershell 
- [x] prolog 
- [ ] purescript 
- [ ] swift 
- [ ] typescript
- [ ] vimscript 

---

- https://github.com/exercism/ballerina/tree/master/exercises/hello-world
- https://github.com/exercism/bash/tree/master/exercises/hello-world
- https://github.com/exercism/c/tree/master/exercises/hello-world
- https://github.com/exercism/cfml/tree/master/exercises/hello-world
- https://github.com/exercism/clojure/tree/master/exercises/hello-world
- https://github.com/exercism/coffeescript/tree/master/exercises/hello-world
- https://github.com/exercism/common-lisp/tree/master/exercises/hello-world
- https://github.com/exercism/coq/tree/master/exercises/hello-world
- https://github.com/exercism/cpp/tree/master/exercises/hello-world
- https://github.com/exercism/crystal/tree/master/exercises/hello-world
- https://github.com/exercism/csharp/tree/master/exercises/hello-world
- https://github.com/exercism/d/tree/master/exercises/hello-world
- https://github.com/exercism/dart/tree/master/exercises/hello-world
- https://github.com/exercism/delphi/tree/master/exercises/hello-world
- https://github.com/exercism/elisp/tree/master/exercises/hello-world
- https://github.com/exercism/elixir/tree/master/exercises/hello-world
- https://github.com/exercism/elm/tree/master/exercises/hello-world
- https://github.com/exercism/erlang/tree/master/exercises/hello-world
- https://github.com/exercism/factor/tree/master/exercises/hello-world
- https://github.com/exercism/fortran/tree/master/exercises/hello-world
- https://github.com/exercism/fsharp/tree/master/exercises/hello-world
- https://github.com/exercism/gnu-apl/tree/master/exercises/hello-world
- https://github.com/exercism/go/tree/master/exercises/hello-world
- https://github.com/exercism/groovy/tree/master/exercises/hello-world
- https://github.com/exercism/haskell/tree/master/exercises/hello-world
- https://github.com/exercism/haxe/tree/master/exercises/hello-world
- https://github.com/exercism/idris/tree/master/exercises/hello-world
- https://github.com/exercism/java/tree/master/exercises/hello-world
- https://github.com/exercism/javascript/tree/master/exercises/hello-world
- https://github.com/exercism/julia/tree/master/exercises/hello-world
- https://github.com/exercism/kotlin/tree/master/exercises/hello-world
- https://github.com/exercism/lfe/tree/master/exercises/hello-world
- https://github.com/exercism/lua/tree/master/exercises/hello-world
- https://github.com/exercism/nim/tree/master/exercises/hello-world
- https://github.com/exercism/objective-c/tree/master/exercises/hello-world
- https://github.com/exercism/ocaml/tree/master/exercises/hello-world
- https://github.com/exercism/perl5/tree/master/exercises/hello-world
- https://github.com/exercism/perl6/tree/master/exercises/hello-world
- https://github.com/exercism/pharo/tree/master/exercises/hello-world
- https://github.com/exercism/php/tree/master/exercises/hello-world
- https://github.com/exercism/plsql/tree/master/exercises/hello-world
- https://github.com/exercism/pony/tree/master/exercises/hello-world
- https://github.com/exercism/powershell/tree/master/exercises/hello-world
- https://github.com/exercism/prolog/tree/master/exercises/hello-world
- https://github.com/exercism/purescript/tree/master/exercises/hello-world
- https://github.com/exercism/python/tree/master/exercises/hello-world
- https://github.com/exercism/r/tree/master/exercises/hello-world
- https://github.com/exercism/racket/tree/master/exercises/hello-world
- https://github.com/exercism/reasonml/tree/master/exercises/hello-world
- https://github.com/exercism/ruby/tree/master/exercises/hello-world
- https://github.com/exercism/rust/tree/master/exercises/hello-world
- https://github.com/exercism/scala/tree/master/exercises/hello-world
- https://github.com/exercism/scheme/tree/master/exercises/hello-world
- https://github.com/exercism/sml/tree/master/exercises/hello-world
- https://github.com/exercism/swift/tree/master/exercises/hello-world
- https://github.com/exercism/typescript/tree/master/exercises/hello-world
- https://github.com/exercism/vimscript/tree/master/exercises/hello-world

**Comment by NobbZ** [comment]
In the following section I will look very briefly at the current test implementation and the exercises description in the README.

This does explicitely not look for or evaluate the onboarding description in the README. I hope to be able to do that early in the next week. But not all at once then.

At the end I mention the tracks teams that in my opinion require immediate action on the tests because they use the old `two-fer` style tests and therefore require implementing logic which might overcomplicate things for a pure onboarding test. 

* ballerina: I'm not proficient in ballerina, but on a first glance it seems as if it is actually testing if `Hello, World!` is printed to stdout. It also has a stub that seems to be fully implemented and should pass the tests as is. A problem that I see, though, the README says "write a function that **returns** the string 'Hello, World!'" (emph mine), while testing if it is printed. This could possibly confuse students.
* bash: Pretty much the same as balerina. But in bash you only return a string if you print it.
* c: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* cfml: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* clojure: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* coffeescript: Tests with different names, similar to the new two-fer exercise, it seems they missed the update. README talks about returning a static string.
* common-lisp: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* coq: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* cpp: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* crystal: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* csharp: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* d: I'm not pretty sure if I've identified the correct files, but for me it seems as if tests are inline to the implementation file. Anyway, `two-fer` style tests are used. README talks about returning a static string.
* dart: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* delphi: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* elisp: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* elixir: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* elm: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* erlang: Based on spec v1.1.0 (generated). Tests for the static string "Hello, World!" beeing returned.
* factor: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* fortran: tests for the string "Hello world" (no punctuation) beeing returned, while the README asks to return with punctuation.
* fsharp: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* gnu-apl: This really is a rough guess, as not even all characters used in the sources are displayed properly on my system, but: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* go: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* groovy: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* haskell: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* haxe: `two-fer` style tests 
* idris: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data. Also has a version test.
* java: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* javascript: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* julia: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* kotlin: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* lfe: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* lua: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* nim: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* objective-c: `two-fer` style tests, but provides stub files with full implementation. README is up to date and only talks about returning static "Hello, World!".
* ocaml: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* perl5: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* perl6: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* pharo: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* php: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* plsql: Seems to be `two-fer` style. README only talks about static "Hello, World!".
* pony: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* powershell: `two-fer` style tests, static "Hello, World!" in README.
* prolog: `two-fer` style tests, static return value in README.
* purescript: `two-fer` style tests, static return in README.
* python: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* r: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* racket: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* reason: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* ruby: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* rust: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* scala: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* scheme: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* sml: tests for the static string `Hello, World!` beeing returned, seems to match current canonical data.
* swift: `two-fer` style tests, matches description in README.
* typescript: `two-fer` style tests, static return in README.
* vimscript: `two-fer` style tests, not even using well known Alice and Bob, but names I've not seen before in any version of the spec. Static return in README.

---

According to my observations above, the following tracks should update their testsuite:

* @exercism/coffeescript 
* @exercism/d 
* @exercism/haxe 
* @exercism/objective-c 
* @exercism/plsql 
* @exercism/powershell 
* @exercism/prolog 
* @exercism/purescript 
* @exercism/swift 
* @exercism/vimscript

**Comment by NobbZ** [comment]
PS: I've missed to look at the stubs in many places. I hope I'll be able to do so this afternoon/evening.

**Comment by kytrinyx** [comment]
@NobbZ This is fantastic.

As a note, if anyone who isn't on the above teams wants to tackle the updates to the test suite, that would be most welcome! If you do submit a pull request, please add a note in this issue so that I can follow up and ensure that the pull request gets reviewed (by me or someone else). ✨

**Comment by son1112** [comment]
@kytrinyx I can start to tackle some of these. I just wanted to check first if there is any unique set up for PR into these repos. Anything I should know or just a straight-forward fork and PR to the individual track repo? Or is `configlet` / `trackler` a parent project for managing changes in these repos?

**Comment by kytrinyx** [comment]
@son1112 Sweet, thanks so much, and welcome 🎉 

It should be a straight-up fork and PR. Once you've forked it can be worth downloading the latest release of `configlet` so that you can run `configlet fmt .` after making any changes.

You don't need to worry about trackler, as it's deprecated (note to self: rename and archive the trackler repo).

**Comment by son1112** [comment]
@kytrinyx Perfect. I will make use of `configlet` as I proceed. Thanks!

**Comment by kytrinyx** [comment]
@son1112 if you want to pair on any of these, let me know. I have someone who offered.

**Comment by son1112** [comment]
@kytrinyx thanks! I've got fairly busy between work, buying a house and prepping for a baby in the coming months, so have neglected this recently.

**Comment by sareg0** [comment]
Heya @kytrinyx I'm going through the TypeScript track at the moment. I noticed that the 'Hello World' test file has been simplified (to have only one test, instead of three). However, the instructions under the 'Tutorial' section still mention two other (missing) tests. 

Would you like me to submit some suggested changes to the tutorial instructions so it matches the current test suite?

**Comment by iHiD** [comment]
@sareg0 I'm not exactly sure where you are seeing the issue, but an emphatic yes please to fixing it 🙂

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
