### ISSUE TITLE
Show stats to help mentors unblock students

### ISSUE THREAD

**Issue by lukejpreston** [exercism/exercism#4714]
I raised this in #track-javascript in slack and it has piqued some interest.

I noticed that students in the js track were getting blocked for more than 7 days on solution 3 but there was a significant number of submissions for solutions 1 so it was being overlooked. In order to help mentors to not create blockages I propose 2 graphs to be shown on the mentor dashboard.

1. Number of issues vs an ideal level, this would be a warning that blockages might start soon
2. Number of issues which have been waiting for a mentor

I don't have any data for the second graph, but for the first one I created the following graph at a snapshot in time on the js track

![newplot](https://user-images.githubusercontent.com/4129128/53002413-8cf76000-3424-11e9-94fb-b19cf5a0fb47.png)

It uses plotly for the graph, but there are plenty of libraries which do a similar job. Whilst perhaps not perfect, it shows that students are getting blocked at the RNA solution and it is 20 solutions above ideal as well as Cipher solution with about 10 above ideal

Here is my algorithm for generating the data for pltoly. The ideal line is relative to the number of submissions.

```js
const data = [
  170,
  21,
  72,
  36,
  7,
  5,
  15,
  12,
  9,
  11,
  6,
  10,
  19,
  1,
  0
]

const generateData = (data) => {
    let actual = {x: [], y: []}
    let warn = {x: [], y: []}
    const total = data.reduce((prev, curr) => prev + curr, 0)

    data.forEach((value, index) => {
      actual.x.push(index + 1)
      warn.x.push(index + 1)

      actual.y.push(value)
      warn.y.push(Math.ceil((total / (2 * (index + 1))) - (data.length - 1)))
    })

    return {linearData, warn}
}
```

For my example I used react plotly and that code looks like this

```js
const text = [
'Leap',
'Gigasecond',
'RNA Transcription',
'Space Age',
'Pangram',
'Matrix',
'Bob',
'Pascal\'s Triangle',
'Linked List',
'Grade School',
'List Ops',
'Robot Name',
'Simple Cipher',
'Wordy',
'Secret Handshake'
]

<Plot
      style={{ width: '100%', height: '100%' }}
      layout={{
        autosize: true,
        title: 'JavaScript Track',
      }}
      data={[{
          type: 'scatter',
          ...actual,
          mode: 'lines',
          name: 'ACTUAL'
        }, {
        type: 'scatter',
        ...warn,
        mode: 'lines',
        name: 'IDEAL',
        line: {'shape': 'spline', 'smoothing': 1.3},
        text
    }]}
/>
```

I feel it would benefit the students that mentors swarm to help avoid blockages and the current view doesn't quite give enough info without mentors clicking several buttons. All thoughts welcome, I am sure the algorithm isn't perfect and I would like to get more data to test it out

**Comment by iHiD** [comment]
This is very cool.

I'm thinking a lot at the moment about how to give students an estimate of wait times both on tracks and on individual exercises. It would be interesting to think how we could integrate timings rather than purely number of exercises into this ^^

**Comment by sshine** [comment]
To update the state of this request: Since it was made, the mentor dashboard has been improved and waiting time estimates are visible to students. What this feature request still contains is a statistical overview for mentors to understand drop-off points on a track.

@lukejpreston: Am I correct to assume that the data in your graph is based data fetched from the same API that the dashboard uses? It would be possible to develop a prototype of what you're describing this way without interfering with website development.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
