### ISSUE TITLE
Proposal: An additional UI section for the learning resources/tips

### ISSUE THREAD

**Issue by ZapAnton** [exercism/exercism#4715]
Quite often the mentors include an additional paragraph about the learning resources, links or useful tools/utilities in their reviews.

These additional  paragraphs do not change between review. So this issue proposes to add an additional exercise UI section, where mentors can store useful tips for the students to see.

The tips could be tied to the topics of the exercise that the student is currently solving.

**Comment by Smarticles101** [comment]
Isn't this what the mentor notes are for?

**Comment by ZapAnton** [comment]
Mentor notes are visible only by the mentors and are static. In order for students to see them, the mentors have to copy-paste the notes in their reviews, which takes some time and clutters the review a bit.
 
This issue proposes a UI section visible by student, which potentially may change every time a student visits a page.

**Comment by F3PiX** [comment]
I think there are two kinds of resources: 
- resources that help and/or prepare before the student starts, i.e. relevant for all students
- resources that are helpful to explain a sub-subject that comes up in the code. 

The first category should be available in the Instructions for the exercise. In the optional `hint.md` a track can add track specific information with these kind of resources. It seems to me we're not using that option enough yet. 

The second category are related to things that are not relevant for all students, but related to a specific implementation. I'd vote not to publish them to all students. Full disclosure: I think we tend to give students too much information, rather than not enough.

**Comment by sshine** [comment]
@ZapAnton: Besides the "Guides" section that is hiding in the right menu below the first screen on a track page, and besides the exercise-specific hints that @F3PiX recommends, do you think there is an additional need for a help section aimed at students?

Isn't that what the "Guides" section is for? Perhaps it doesn't get highlighted enough.

Maybe it should be moved to the top of the right menu bar? It is, after all, much smaller than the "Side Exercises completed" box that is above it, and that box wouldn't disappear from the first screen if "Guides" was above it.

**Comment by sshine** [comment]
Closing due to lack of clarification.
