### ISSUE TITLE
Mentornotes are rendering HTML comments

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4720]
When I am looking at the mentor notes for erlang, I do see this in the Web UI at the end of the notes:

> \ \ \

If though, I look at the rendered markdown through the GitHub UI, I do **not** see that line, since GitHub correctly treats them as inline HTML.

**Comment by sshine** [comment]
@NobbZ: I'm not sure I understand the implications.

**Comment by NobbZ** [comment]
Those comments are not meant for mentors consumption but editor hints.

Also according to common mark spec, `<!--`/`-->` pairs should be rendered unquoted and treated as whitespace, such that the HTML renderer can "see" them, but discards them as HTML comments.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
