### ISSUE TITLE
Add Alert for Mentor on 'Leave conversation'

### ISSUE THREAD

**Issue by emcoding** [exercism/exercism#4722]
Mentors sometimes push the 'Leave conversation' button accidentally, instead of one of the other buttons. 
Can we add an 'Are you sure?' alert on click?

**Comment by andrewh-itison** [comment]
I second this idea, if a client-side prompt is not considered appropriate (some users might have JS turned off?) then CSS styling on `:hover` could be changed. Currently it turns green, which is not a helpful visual cue.

![image](https://user-images.githubusercontent.com/45427072/55285224-ad99ca80-537f-11e9-9a53-894920ff7c05.png)

**Comment by kotp** [comment]
There should be a confirmation of some sort, or a choice to rejoin conversation.  Found out that 19 days had passed and no notification was received for a student.

I had accidentally clicked on the leave conversation, and very shortly said so in a comment.  Student expected that I would be able to respond after that, and I got 0 notifications of communication afterward (which I can understand why).

2.5 ways to solve this that I see:

1. Second action required to actually leave conversation.
2. Additional comment in that conversation should ask if one would like to rejoin the conversation.
3. When leaving the conversation, ask if notifications should continue.

re: #4700, I used to rely on this "bug", which I thought was a feature (however if the conversation/relationship is sour, I can understand why notifications would not want to be had).

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
