### ISSUE TITLE
Links to existing solutions should be shown to students after first submission

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/exercism#4732]
A student of mine could not find the existing solutions link. It should be made visible after the first attempted solution.

**Comment by sshine** [comment]
@chriseyre2000: Do you mean the link to community solutions? In mentored mode they are deliberately hidden until the point where your solution is approved by a mentor. Are you suggesting that this should be different?

**Comment by chriseyre2000** [comment]
I was suggesting that they be unlocked on first mentor interaction.

**Comment by sshine** [comment]
OK, thanks for clarifying. For now I'm just labelling issues. They will be addressed later.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
