### ISSUE TITLE
Mentor weekly update to include number of mentors

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/exercism#4733]
It would be useful to know how many mentors were active in a given week.

**Comment by NobbZ** [comment]
There is already this line:

> In total, 159 mentors gave feedback on 2,077 solutions.

But I'm interested in "there were x other mentors active on the y track".

Even though I can see already that of x mentored exercises y have been mentored by me, I have no clue if z - x exercises have been mentored by a single person or many.

And since I am mentoring 2 tracks, I might change my priorities based on the per mentor quota of those tracks.

**Comment by chriseyre2000** [comment]
Yes it's how many mentors were active on the tracks that you mentor for.

**Comment by iHiD** [comment]
Cool. I'll add this to a future one :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
