### ISSUE TITLE
Provide URL of pre-launched track or join via CLI

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism#4734]
I'd like to play with a track that is not launched yet. 
```
exercism download --exercise=hello-world --track=powershell
```
I get
`Error: You have not joined this track`

I go to the site but I do not see it. 
https://exercism.io/my/tracks

it would be nice if the CLI told me where I could join.
```
Error: You have not joined this track
Please join at: https://exercism.io/my/tracks/powershell
```
Even better, just join me from the CLI

**Comment by kytrinyx** [comment]
Yeah, that would be a smoother user experience. I've moved this to the exercism/exercism repository, since this is a product question rather than a technical one. @iHiD I'd love your thoughts on what the right move here is.

**Comment by iHiD** [comment]
For pre-launched tracks, you can go to http://exercism.io/tracks/powershell and join. As this is a maintainers-only problem, I'm not a huge fan of adding it into the CLI. 

In the general case, I think it's a good idea to change the recommended URL like you suggested. Again, I wouldn't expect someone to hand-craft this sort of exercism command though, so it's not something that I'd rate as a huge priority.

**Comment by quintrino** [comment]
Out of curiosity what's the reasoning behind preventing people from downloading a track they haven't joined? 

Could downloading a track you haven't joined cause you to join that track automatically?

**Comment by iHiD** [comment]
@quintrino Thanks :) The logic is that we want the website to be the primary experience for a user interacting with Exercism's product (whereas the CLI is the primary experience for solving problems). Joining a track involves making a decision (Mentored or Independent) and soon it will involve answering a couple of questions too, in order to help triage you to mentors more easily. 

While we could add those things to the CLI as part of the experience but then we'd have to maintain two interfaces for the same thing, and we'd also have to consider different CLI versions that people have installed when iterating, which limits the speed at which we can move.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
