### ISSUE TITLE
Mentor mode is missing borders and scroll bars on student submissions

### ISSUE THREAD

**Issue by macta** [exercism/exercism#4736]
While you could consider a larger fix to make the mentor screen have a better layout (#4735) a quick fix is to put a border around the code and enable scroll bars so you can easily scroll around it.

For a photo refer to #4735 to see what the issue is and a bigger fix.

_Originally posted by @macta in https://github.com/exercism/exercism/issues/4735#issuecomment-469232501_

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
