### ISSUE TITLE
Feature request: show submission timestamps

### ISSUE THREAD

**Issue by sbromberger** [exercism/exercism#4737]
Right now, code submissions do not have a timestamp when displayed in the portal. It would be nice to have those timestamps displayed as a way to tell how long it's been in queue for review, and for general interest.

**Comment by iHiD** [comment]
Can you send me a screenshot of where you mean pls?

**Comment by sbromberger** [comment]
unfortunately not easily. But consider when a student has submitted a first attempt at an exercise (no comments in the "Mentor discussion"). There are three tabs: "Instructions", "Test suite", and "Solution", and under the "Solution" tab, the submitted code is displayed. Nowhere on this page is an indication of the time/date the code was submitted, unless I'm missing something.

**Comment by iHiD** [comment]
Gotcha. It's on the mentor dashboard, but not on the solutions themselves.

**Comment by sbromberger** [comment]
it'd be helpful to have it visible to the students so they know when they submitted their last iteration.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
