### ISSUE TITLE
Make login button more prominent on home page

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism#4744]
When I go the home page, and I am not logged-in, I get presented with the following page:

![image](https://user-images.githubusercontent.com/135246/53942629-8707ad00-40bb-11e9-891c-6ab5489b1c98.png)

The most prominent buttons, are those for registering and exploring the languages. This is great for people new to the website, but not so useful for existing users. As an existing users, I then have to click on the relatively small login button on the top right. Wouldn't it make sense to have the login button be more prominently displayed, as I think 99% of visitors will likely be returning users.

**Comment by Smarticles101** [comment]
I'm not so sure we need to make the login button more prominent. The home page is designed in such a way to target existing users, which makes sense, because signed-in users are always redirected to their tracks page. Registered users shouldn't need to sign in again unless they are logging in from another computer, or intentionally signed out. The location of the sign in button on the homepage also seems to be a popular ux choice on many websites, so returning users shouldn't have too much of a hard time finding it I think.

**Comment by ErikSchierboom** [comment]
> Registered users shouldn't need to sign in again unless they are logging in from another computer, or intentionally signed out. 

I do believe there is a maximum login time, after which one is logged-out (at least for the GitHub option).

>  The location of the sign in button on the homepage also seems to be a popular ux choice on many websites, so returning users shouldn't have too much of a hard time finding it I think.

I disagree :) I have some examples:

Outlook:

![image](https://user-images.githubusercontent.com/135246/54017704-1af27b00-4187-11e9-8ee9-1cf6d840e32c.png)

Twitter:

![image](https://user-images.githubusercontent.com/135246/54017715-26de3d00-4187-11e9-85bd-5bdbf220e5a2.png)

Instagram:

![image](https://user-images.githubusercontent.com/135246/54017737-3a89a380-4187-11e9-9275-88e3dda137f1.png)

All three websites make the login option very prominent. Note that I'm not advocating that the login and register button's position should be swapped, just that the login button should be more prominent and more conveniently placed.

**Comment by NobbZ** [comment]
I'm with Eric here, it's simple as "already have an account, then *log in*" with login beeing a link to the login page.

Though I have never been locked out of my session ever since the release of V2 across several computers. Only one that always kicks me is my mobile, but that is set up to not persist coolies across restarts.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
