### ISSUE TITLE
"exercism submit" should not require filenames to be specified

### ISSUE THREAD

**Issue by nikclayton** [exercism/exercism#4747]
[As requested, forking this from https://github.com/exercism/cli/issues/419]

I'm the teaching lead for Powercodes, a coding school for refugees in Switzerland. I've just completed a course with my students, where, for part of the course, I had the students run through exercises from, amongst other places, Exercism.

Doing this, I discovered that a source of confusion for the students was that when downloading an exercise they didn't need to specify any files -- the track and the exercise name is sufficient.

However, to upload the solution you need to specify the name of the file(s) you want to upload.

If you go to the page for an exercise, on the right hand side you get instructions for downloading the exercise, with a handy "copy" link that copies the text so you can paste it in to the shell.

This text works unmodified. For example, on the Gigasecond exercise the command to copy/paste is:

```
exercism download --exercise=gigasecond --track=javascript
```

Just below this is the instructions for submitting. The submit instructions are presented in the same way, with text that can be copied and a "copy" button. Right now, if I click that button the following text is copied.

```
exercism submit /path/to/file [/path/to/file2 ...]
```

This text can not be pasted in to the shell and executed unmodified.

Not only does the student have to change it, the example command carries with it the implication that multiple files might need to be submitted (the `[/path/to/file2 ...]` bit).

So there are two parts of the page that look almost identical, but require the student to do different things. This leads to the confusion.

I think the submission process can be simplified, and propose two variations of the `submit` command.

In the first, `exercism submit`, when run in an exercise directory (i.e., one that contains a `.exercism` subdirectory) should do the right thing, by just submitting the necessary files from that directory.

In https://github.com/exercism/cli/issues/419 the objection was raised that the client doesn't know which files to submit. I think that could be addressed in at least one of two ways.

1. Modify the metadata that is stored about the exercise to record the name of the files that need to be submitted for each exercise. Then just submit those files.

2. When `exercism download` is run, record a checksum of the downloaded files in the metadata file. Then re-checksum the files at submit time, and only submit the modified files (this is slightly more fragile, e.g., if the user had inadvertently modified the README.md file).

In the second, the user should be able to run `exercism submit--exercise=gigasecond --track=javascript` from anywhere, then the directory with the exercise can be figured out in the normal way, and the same heuristics as the first variation can be used to figure out which files to upload.

I'm happy to work on a PR for this, but so far I've been unable to find the "Here's how to run a local copy of Exercism for development purposes" document.. If you can point me at that I'll see what I can do.

PS: If you're interested in exercises from other sources, check out https://github.com/nikclayton/edabit-javascript-challenges

**Comment by guygastineau** [comment]
A little opposite opinion.

I like telling it which files to submit.
I often make backups before I try different approaches or reworking a section.

I don't want to put them in another directory, because I want it to be fast (but also safe) for me to try out different algorithms in my solutions.

When I'm finished I just tell exercism which files to submit.  This is a lot less typing than adding the exercise and track names with flags most of the time. 

This way it doesn't submit any backup I have in the directory which might be preserving a different way I did it that I don't want to forget. Your second option would do this.

I believe if you simply use `exercism submit` from the exercise directory it will use the metadata to submit the main solution file based on name, but you need to specify the files if you are submitting multiple files.

I don't want to stand in the way of progress and development, but I do want the `submit` command for the exercism CLI to have simplicity, expectability, and flexibility.

As I see it the `submit` command has all three of these attributes currently.

**Comment by rdlf0** [comment]
I totally agree with @nikclayton and think that the second option would be very convenient. At least they can both exist side by side and the user can choose which one to use.

**Comment by pranasas** [comment]
Test suites imply which files contain the solution. In other words, such information is "known" without ambiguities, should possibly be part of the metadata.

Cheers to @nikclayton for having patience and staying with his (totally reasonable) suggestion for so long!

**Comment by iHiD** [comment]
@nikclayton Thanks for the idea, and it's great to hear you're using Exercism in this way. Have you been using the teams functionality?

It strikes me that there are two approaches to this. Good-file-list where known files get submitted automatically. Or Bad-file-list where we just don't submit some known "bad" files.

I like the idea that we can have a default "expected file" that gets submitted via the method you suggest, and we're in the process of laying the groundwork for this by asking all tracks to contain stubs, which would make this reliable.

The reality is that this won't be foolproof because people often want to submit test files that they've updated, or different named solution files, so the current method is the only reliable way of getting students to do things. That doesn't mean we can't have a nice default for the situation you suggest though.

@ghost I don't think anyone has suggested @nikclayton's suggestion isn't reasonable. We've just not round to replying to it.

**Comment by sshine** [comment]
Since most submissions include a single file that was named by the track and didn't change name after being submitted, it should be possible, as @iHiD says, once tracks have stub files, to have the CLI know through metadata which file(s) to submit when only doing:

    exercism submit

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
