### ISSUE TITLE
automatic (email) notifications of new exercises in your language track 

### ISSUE THREAD

**Issue by grwkremilek** [exercism/exercism#4754]
Would it be possible to set up an automatic notification  (via email or on the website) in case there is a new exercise in your language track for completists like me? Esp. after you have finalised all exercises, it is rather difficult to keep track of new additions,

**Comment by F3PiX** [comment]
I like that! 

Ideally there is some delay between the introduction of the new exercise itself, and sending the notification to 'completists'.  So that active students can be mentored before the completists fill  the Mentor Queue.

**Comment by iHiD** [comment]
I like this too. There is definitely complexity about who should receive the emails. For example, not only are "new exercises for completists" useful, but also "new exercises are avaliable for you" because the track config has changed. We would need some sort of state for either scenario, which we don't have atm.

**Comment by F3PiX** [comment]
I wouldn't mind if we started with the 'new exercises for completists'-email first. Those people are least likely to visit the site without such a reminder.

**Comment by iHiD** [comment]
Yeah - we have to define what a "completist" is and store that state though. So if a new core exercise is added then should everyone who's completed core be notified. And same with new side about people who have completed everything. And what about if an exercise is moved from side to new core. Lots of small details that would need working out, and states that would need persisting in the db to be able to send anything.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
