### ISSUE TITLE
inadequate tests for python darts 

### ISSUE THREAD

**Issue by grwkremilek** [exercism/exercism#4756]
I came up with this solution which passed all the tests:

```
def score(x, y):

    if abs(x) + abs(y) <= 1:

        return 10

    elif 1 < abs(x) + abs(y) <= 5:

        return 5

    elif 5 < abs(x) + abs(y) <= 10:

       return 1

    return 0
```

nevertheless as someone commented, it does not work for x=0.8, y=0.5

"0.8 + 0.5 = 1.3, which is greater than 1 (so you return 5). But sqrt(0.8^2 + 0.5^2) = 0.94, a radius within the innermost circle (so you should return 10)."

**Comment by sshine** [comment]
Hi, and thanks for your contribution. Since time has passed since you posted this issue, I don't know what the state of this exercise on the Python track is. You should probably go to the Python track repo and open an issue / PR there: https://github.com/exercism/python/issues

I'm closing this issue, but I'm also pinging @exercism/python to ask them if such an improvement is valuable to them. (This may save some round-trip time on the issue creation.) Feel free to continue discussing after this issue has been closed.

**Comment by yawpitch** [comment]
If that solution passes the current tests then this isn’t an oversight in any way specific to Python, but an oversight in the canonical-data.json. Adding at least one test there that implicates trigonometry would be a good idea, though a mentor should catch any such false positive solution on the first review.
