### ISSUE TITLE
saying exercism is installed but cannot check version

### ISSUE THREAD

**Issue by rikasun** [exercism/exercism#4761]
<img width="1054" alt="Screen Shot 2019-03-18 at 17 00 16" src="https://user-images.githubusercontent.com/40652126/54636909-a3550380-4a44-11e9-8511-6555e4602cdb.png">

**Comment by sshine** [comment]
Hi @rikasun. This response is a bit late. Did you eventually resolve the problem? If not, have you tried to upgrade Go? When I google "mspanlist_insert error", I get reports that are related to Go code not working on too new versions of MacOS.

For example: https://github.com/golang/go/issues/17335

I'm closing this issue because time has passed, but feel free to respond if this is still relevant to you.
