### ISSUE TITLE
Making mentor-mentor and mentor-learner interactions a priority

### ISSUE THREAD

**Issue by mikedamay** [exercism/exercism#4764]
Today I reviewed my 1000th exercise (C# track) and was prompted to reflect on what might keep me going for another thousand or two and how my experience relates to the broader question of how the Exercism service can be sustained and scaled.

The recruitment and retention of active mentors is key to scalability.  This can be achieved by developing a rich mentor experience – nurturing the mentors.  Major components are mentor-learner and mentor-mentor interactions.  These should be front and centre in the site roadmap, https://exercism.io/roadmap.  They should be prioritised over mentor productivity, metrics/ratings, snippets and track quality.

I doubt many exercists would disagree that increased mentor activity and richer mentor-mentor and mentor-learner interactions are a good thing but this piece may be at odds with the consensus in putting them centre stage.

The impression I have from the Slack content, Github issues and the roadmap is that priority is being given to mentor productivity over other development directions.  I understand that part of this reflects the earmarking of Mozilla’s funds for the auto-mentoring project.  Whilst auto-mentoring is a significant project both as a boon for mentors and, in its own right, as an interesting development (and one to which I hope I can contribute) I do not think that it does much to achieve the scalability goal.

 In the blog post introducing auto-mentoring, https://exercism.io/blog/automated-mentoring-support-project, Jeremy asks, “Why automated mentor support?” and suggests: ‘Exercism's most significant barrier is being able to deal with scale.’ but ‘we need a better strategy than "add more mentors.”’.

I agree that scale is the goal but I respectfully (and I hope, constructively) disagree that auto-mentoring is the way to achieve it.  Rather, richer interactions.

The two concrete proposals that are in the pipeline, taking a step in this direction are mentor comments, https://github.com/exercism/exercism/issues/3988 ,  and the mentor/learner relationship project,  https://github.com/exercism/exercism/issues/4658

The interactions between mentors could be enriched beyond the disclosure of mentor comments (covered by 3988) by allowing mentor-on-mentor comments, shadow mentoring, joint mentoring, etc.

The best way to enhance mentor learner relationships is to allow for sticky relationships.  Perhaps the learner could make a request to “keep with this mentor” with an appropriate timeout between exercises.

The thing that made me think that I had a point that needed to be made was this comment on the mentor/learner relationship project, https://github.com/exercism/exercism/issues/4658#issuecomment-460751086 where Jeremy pushes back on the suggestion of “sticky” mentor relationships.  If my enthusiasm for this feature were shared I am sure something could be tried in short order.  This is such an important issue that a bit of trial and error might be necessary.

Most satisfying would be an informed discussion around this topic – prioritisation of mentor-mentor and mentor-learner interactions. It would be good to hear counter arguments especially from those with an overview of analytical data (.e.g active mentor retention, queue length) from the site or those with experience of the Go track and the effect of its “auto-mentoring” mechanism or the Team Edition, none of which I have experience of.

*Edit (by @sshine): See also the continued discussion in exercism/discussions#237 by @mikedamay.*

**Comment by iHiD** [comment]
@mikedamay Firstly, thank you for mentoring your 1000th solution - that's a huge contribution to Exercism and more importantly to the hundreds of people you have helped. It also most definitely gives you the right to expound your thoughts on the direction and priorities of Exercism, and I also want to say thank you for doing this in such a constructive way.

Secondly, I fundamentally agree with your points. There are a few subtitles that I disagree with and I'll discuss those below, but more importantly, I agree with the core premise of your argument, which is that both mentor-mentor and mentor-learner improvement is key. So I will explain why other things seem to take priority. Before I start, I just want to emphasise, as it is often difficult to read tone in written text that I am speaking purely in a tone of discussion and with the aim of adding information to the conversation - please do not read any form of "defense" or "rebuttal" into it.

<details><summary>Click to read my small essay on why things are as they are. I have collapsed it because I feel leaving it exposed will put people off reading any more of the thread (due to its length), and the original post does not deserve that.</summary>

Like any project, Exercism is one governed by "resource management" - a crude description of people's time. There are two groups of people who contribute to exercise - the "core" team (I dislike the name but it is what it is for now) and the wider community. The main difference between those two groups (at least in my head) is that community tend to work on small units of work, whereas the core team are working on longer projects. 

For example, mentors mentor individual solutions. If you had stopped at mentoring 999 solutions and not done the 1000th, the value would have still been there for 999 people. Similarly, if a maintainer makes 50 exercises, but doesn't have time to do the 51st, the track is 1/51th worse off, but it's not huge. We believe that it is important that the community can dip in and out of things as their lives allow, and try not to ask for "regular" commitments (although of course many people **are** just as active as the "core" team. In contrast, the units of work that the core team work on are larger and need multiple consecutive days of solely-focused work. In building v2, @nicolechalmers and I spend ~6 months relatively full-time rethinking and building the new experience. @kytrinyx committed hundreds of hours during that period to working on things with us, and @ccare and @kntsoriano also put in a hundred hours or so each doing their parts. So, in order to do these bigger projects, we need to have significant buy-in of time and commitment from the core team over a substained period. Like you, we are volunteers. None of us are paid for working on Exercism and so we need to sacrifice working and earning salaries to be able to do this. As a reference point, during the creation of v2, Thalamus (our company) made almost no revenue for 6 months, while still spending over £100,000 on our salaries doing exercism. We were able to do this because we had worked for the 12 months before saving up enough money to enable us to do that.

With that in mind, the automated mentoring project has been prioritised for two reasons:
1) Mozilla have paid us $30k, which means Thalamus can not do $30k of consulting work and instead work on Exercism. This means that Charles can focus on infrastructure, Nicole on product, and me on direction, wiring, and the Ruby analyzer itself.
2) The project is a huge enabler of the community's time. Once we have laid the groundwork and foundations of static analysis, maintainers will be able to chip away adding extra automation to every exercise. The reason Exercism has grown the way it has is largely because of the phenomenal foundational work that Katrina did initially setting up infrastructure around the community to allow different people to build out tracks and collaborate together. I believe we are doing the same thing here and that empowering people to work on their own analyzers will pay huge dividends.

It's also worth pointing out that both #3988 and #4658 are not really technical time-sinks (although there is a few dozen hours of technical work in the them) - primarily the time will be spent on product design. During the development of v2, we spent months carefully working out the learner side of things, but deliberately kept the mentoring interface as simple as possible because we had no information on how people would choose to use it. We planned to see how people used it for ~6months, and then invest proper time into getting it right once we had that information. #4658 is sort of an outline of the start of that journey based on our learning from 6 months of it existing. It contains the "low hanging fruit" ideas of what we can do to improve things. But it still needs careful thought. As an example, last year in one afternoon I added mentor ratings. It caused chaos. Some people hated it, some people loved it, everyone wanted to tweak it somehow. This was a very bad way to do product-development because it had no product design. It is important in doing #4658 it is important not to repeat those mistakes, rather than just adding features to a website, we continue to develop a product. And in order to do that, we need time. As one final tangible example of this, take [the comment that I made that you refer to](https://github.com/exercism/exercism/issues/4658#issuecomment-460751086). You suggested in your post above that I was "pushing back". I wasn't really - I just don't know how to do it. I agree entirely with the idea - I think it would be a huge step forward, but there are dozens of ways to implement it and I don't know which is right. And getting it wrong would be hugely damaging. So this is exactly the sort of place that needs Nicole, Katrina and I to spend time thinking, and then to discuss with the community before we act.

And time is hard to get. Thalamus co-own and run two startups, both of which are growing fast with their own teams to manage and problems to fix, and which (as startups tend to be) often have unpredictable bumps. Katrina has an intense full time job working at GitHub. When I wrote #4658 in February I'd hoped to have time to have worked on it in earnest by now. Instead I've being dragged into issue after issue in my "day jobs" and haven't had time. Each week I do 20-30 hours of community management on Exercism in my spare time, which leaves me no time to improve the product. So development itself mainly happens when I can actively **not** do my day job because either Thalamus has enough money to pay me to work on Exercism, or because someone like Mozilla helps us out. Also, if I have spent my day at work coding, I often just don't have enough brain-space left in my evenings to write more code. And similarly with product-design. Generally what I do in the evening is the inverse of what I've done during the day. My aim is to be in a position where I can spend the majority of my time in the second half of 2019 working close-to-full time on Exercism, which will mean things can move forward an order of magnitude quicker than they do at the moment, but until things happen in direct correlation to the busyness of my life. And for big product things, we also need Nicole's time and Katrina's time, and they are both super-busy too.

As one final note on this, it's also important to know that things **are** happening with this work. I have an (awful) [WIP PR](https://github.com/exercism/website/pull/573) for some of this, and I spend a lot of time thinking about this and trying to work things out, and also time chatting to Katrina and Nicole about it. I have recently come to some conclusions about how privacy can work in line with mentors reading mentors' notes, and exposing that, and I have a plan starting to form around mentors mentoring other mentors. A lot of this is unseen because it's product work, not development work, so it doesn't get exposed through features quickly.

</details>

With that small essay out of the way, I will debate the two points I disagree with.

Firstly, I believe the value of the automated mentoring project is huge, and will have a massive impact on mentors. Initial estimates suggest that we'll be able to automatically mentor 90% of two-fers (the first exercise in nearly all tracks). That number will reduce as we move through more complex exercises, but I suspect that we'll be able to automatically give first-step mentoring for a reasonable proportion of exercises. This means that mentors are only spending their time where its useful (and they couldn't be automated) and that learners are not frustrated by waiting for feedback on good solutions. Also, In reducing the amount of solutions that mentors have, the wait for learners will be shorter, and so they will be less impatient when they reach mentors.

Secondly, I think the Track Anatomy work is the most crucial work happening on Exercism right now. Tracks that have good structure/progression retain new mentors that sign up (e.g. Ruby). Tracks that don't have good structure/progression lose mentors like water through a sieve (e.g. Rust). Trying to mentor a beginning on Rust on Pythag Triplets or Bob is not fun for the mentor or the student. In contrast, mentoring a beginner on Acronym is fun, and mentoring someone who's 10 exercises in on Bob is really fun. And queue-lengths do directly correspond to the where Track Anatomy has been applied. (e.g. Ruby has an average wait for mentoring of about 2hrs now, down from about 6days before it had it).

Finally (and forgive me for repeating what I said in the collapsed part above), I agree about the importance of a mentor-learning "connection" but [the comment that you refer to](https://github.com/exercism/exercism/issues/4658#issuecomment-460751086) is a genuine question that I don't know the answer to. Maybe you would like to open an issue to discuss this point specifically as I think it would be good to hear people's thoughts on it? 

I'll leave the door open for others to give their thoughts and bow out until some more discussion has been had. Thanks again for your thoughts :)

**Comment by jeffdparker** [comment]
I have some opinions on sticky relationships, but I would think that the students point of view would be much more important than mine.  

My major concern is that students wind up hearing only one point of view, or one opinion about some items we might differ on.

**Comment by F3PiX** [comment]
I also agree that mentor-mentor and mentor-learner improvement is key. 

I wouldn't say that those are more important than the 'big projects'. But I do feel that the mentor-mentor improvement should be the first _next_ priority. And I would love for it to be the nr 1 priority over all the other features, like ratings, commenting and such from now on. 

From the launch of V2, mentors have been expressing interest in opportunities to improve their mentoring skills. 
- I'm convinced that the fastest way to engage mentors and keep them involved is to explicitly facilitate improving mentoring skills. Just as the students learn faster by the 'professional feedback' they receive on their language skills, mentors too will learn faster with peer feedback on the mentoring skills.
- I'm also convinced that new mentors will profit hugely if they can lean from other mentors' experiences.   

The things Mike mentioned - allowing mentor-on-mentor comments, shadow mentoring, joint mentoring - sound wonderful and it makes me happy thinking about it. 

There's one thing that I do not agree with, and actually feel quite strong against: the 'sticky relationships' between student and mentor. It's much more interesting to work towards an exercism where every student gets exceptional mentoring, whoever the mentor is. No better way to mentor-learner improvement.

**Comment by mikedamay** [comment]
@jeffdparker

> I have some opinions on sticky relationships

Is it possible for you to provide more details on your views here or in the [Mentoring Continuation Request](https://github.com/exercism/exercism/issues/4816#issue-433605209) proposal.  

> but I would think that the students point of view would be much more important than mine.

I could not agree more that the students’ point of view is central to this.  There is zero point in implementing this kind of thing if the students aren’t interested or do not find the experience supportive.

We are slightly hamstrung in that (I’m guessing) many students only visit the site for a short period of time so even conducting some sort of survey is difficult.  This is slightly mitigated by the fact that many mentors are/were also students.  For the moment we may have to press on with anecdotal evidence, the developers’ curse – incomplete information, and the old, often unreliable standby, intuition.

> My major concern is that students wind up hearing only one point of view, or one opinion about some items we might differ on.

I totally agree.  I am keen that there should be some standardisation (whilst obviously continuing to encourage a personal touch).  I think that improved mentor-mentor interaction would address this but that is some way off.  For the moment please have a look at the [Mentoring Continuation Request](https://github.com/exercism/exercism/issues/4816#issue-433605209) proposal which requires both mentor and learner to opt in to each exercise individually.  It would be great if you could come up with some proposals that reconcile your concerns with the idea of deeper and lengthier interactions between mentors and learners such as, for example, a cap on the number of exercises subject to sticky mentoring.

Please note that I have made my arguments in favour of Sticky Mentoring in my [response](xxx) to the [comment](https://github.com/exercism/exercism/issues/4764#issuecomment-475857056) by @F3PiX.

**Comment by mikedamay** [comment]
@F3PiX

Thank you for taking the time to respond to my piece.  It took Jeremy’s @iHiD [small essay](https://github.com/exercism/exercism/issues/4764#issuecomment-475804635), above to bring home just what a commitment, work on the service, is for you and other members of the core team.

Perhaps it’s worth bearing in mind that opinions may be shaped by our varying experience on the site.  It was encouraging to hear about the outstanding beneficial effect of the Track Anatomy Project on the language tracks.  As a mentor on the C# track and with great respect to the work done by @ErikSchierboom I feel the main benefit for us, of that project, will be as a foundation for the Auto-Mentor project.  For me the change that caused the biggest difference (in my case increase in personal productivity) was classifying the New Solutions Queue by exercise type – who’d have thought!  All of which is just a warning (mostly to me) not to be too dogmatic.

Thank you for your arguments in support of improved mentor-mentor interactions.  I agree with you that this should take priority after the ‘big projects’ which I take to be Track Anatomy and Auto-Mentoring.

It seems we are at odds on the subject of sticky mentoring, the idea that the interaction between a learner and a specific mentor should be extended for more than one exercise.  I hope you can find time to look at the [Mentoring Continuation Request](https://github.com/exercism/exercism/issues/4816#issue-433605209) proposal which embodies my thoughts on sticky mentoring.  If it would be useful for you to see more detail on UI, behaviour and workflow on this proposal then please let me know.  I did considerably more work which I have not made public as at this stage it is vital to hear a range of views on the outline proposal which will doubtless be considerably modified.  I did not want the work I did (for the purposes of validating the idea and examining complexity) to be seen as any sort of fait accompli.  The implementation does look surprisingly complex.

Although the main rationale for sticky mentoring was to engage mentors like myself to a greater degree in order to sustain and scale the service, it had not occurred to me that it would cause any diminution in service quality.  I think benefits will arise from sticky mentoring as well as some problems.

If I interpret your position correctly, the aspiration of the service is that, as a body of mentors, we should provide a consistently exceptional quality of mentoring to our learners.  I honour this and hope this will largely come from track improvement and productivity-enhancing projects such as Track Anatomy and Auto-Mentoring and, of course, enhanced mentor-mentor interactions with the possibility of mentor-mentoring, group comments and discussions, retrospectives etc.  I think that the question is – is this objective undermined by my proposal?

I think there are three areas where a longer lasting interaction between mentor and learner can pay dividends in terms of mentoring quality:

•	Responsiveness: My intuition is that if there is mutual commitment then speed and thoroughness of response will be improved.
•	Effective Communication: By spending a longer time with a learner, a mentor can internalise much about them that will inform reviews: primary natural language, primary development language and frameworks, is the learner familiar with general software engineering principles and best practice.
•	Concentration of Effort: as I have a certain amount of effort to provide, it is better that it is focused on the exact needs of the learner. If a learner is not using a particular construct (say LINQ in C#) I would like to be aware of whether they have not learned LINQ or don’t how it can be applied to this exercise before I comment.

Taking a combination of improved responsiveness,  more effective communication and concentrated effort I believe that a better informed mentor will provide a superior review.

I have used the term “internalise” above to indicate that getting in sync with a learner’s requirements goes beyond looking at a profile.  I know that as part of the existing [Mentor-Learner Project]( https://github.com/exercism/exercism/issues/4658) the intention is to provide detailed profiles of mentors and learners.  While this can be seen as a prerequisite for what I have in mind I think sustained interaction between the parties is required for this to be effective.

On the other hand @jeffdparker has pointed out a key [disadvantage](https://github.com/exercism/exercism/issues/4764#issuecomment-475836972) his “major concern is that students wind up hearing only one point of view”.  I hope this can be mitigated (possibly by the single exercise limitation, as described in the proposal) otherwise it will give us the difficult question of balancing the pros and cons. 

I hope you can find time to continue to record your reservations with the idea of sticky mentoring either them here or on the [proposal](https://github.com/exercism/exercism/issues/4816#issue-433605209), itself.

Part of what we offer (albeit by no means the larger part) is a more traditional mentoring role.  Conventionally this is guidance on how to negotiate an organisation, deal with peers and others, deal with ethical issues and conflict and get promotion.  For us this translates into how peers in a particular language and technical ecosystem will expect a learner to code, help them assess their level of competence and technical maturity, whose opinions should they look to.  In a traditional environment the mentee may get assigned their mentor on a fairly arbitrary basis.  The experience will be different, the quality almost unmeasurable but you will doubtless be better off for the experience of a close relationship.

**Comment by iHiD** [comment]
Sticky mentoring will be part of v3. This issue will be closed when that's been implemented :+1:

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
