### ISSUE TITLE
Easily identify unlocked exercises

### ISSUE THREAD

**Issue by OpalJellyfish** [exercism/exercism#4765]
I find it hard to tell the difference between which exercises are locked and unlocked because the colors for both are very similar. Making the contrast more noticeable would really improve user experience.

![image](https://user-images.githubusercontent.com/37519939/54793332-25892780-4bff-11e9-9a14-2a2c02c76541.png)

**Comment by PatrickMcSweeny** [comment]
I think it would be good to have locked and unlocked exercises in separate sections.

**Comment by xianrusso** [comment]
The "Status" filter can display exercises that are unlocked.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
