### ISSUE TITLE
Fenced codeblocks with for backticks have some weird dimensions

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism#4772]
In a conversation with a student, I wanted to give an code example containing the markdown of a code block, basically like this:

`````md
````md
```py
"""Your code here"""
```
````
`````

This creates an ugly lower margin in the block as shown in the Screenshot:

![ugly-margin](https://user-images.githubusercontent.com/58951/55063782-0a903a80-5079-11e9-8750-98f9c8fe52d0.png)

It was expected to render similar to it would here on github:

````md
```py
"""Your code here"""
```
````

PS: Using the tilde fence (`~`) does also add the same margin to the top. I'm not sure if this is because of nesting or related to something else.

**Comment by sshine** [comment]
I didn't know you could do that. We should really have a page that describes all the markdown options you have as a mentor.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
