### ISSUE TITLE
Rust `Luhn From` exercise description is misleading/confusing

### ISSUE THREAD

**Issue by jeremyh** [exercism/exercism#4779]
Thank you for all your wonderful work, I’m very much enjoying the exercises so far.

I’ve justed unlocked the `Luhn from` exercise (id `7b7fe77122ef4dba9b3796ed3909670a`), which is one of the first exercises unlocked on the Rust track. The description says to finish the `Luhn` exercise first:

> Before doing this exercise you should probably do the original Luhn exercise. If you have not completed Luhn, you can get it by running the command:

But there’s no `Luhn` visible anywhere, and the given command says it’s locked. After Googling and finding this repository, I’ve found out that it’s one of the last exercises on the Rust track. It looks like the two were moved far apart as part of #804.

#804 says that `Luhn From` is the easier of the two, so it’s now earlier in the track.

I assume:
- The description of the problem/algorithm should be moved to `Luhn From`. (I can’t view Luhn, but I assume it has more of a description that `Luhn From` currently has)
- The above “do Luhn first” recommendation should be removed from `Luhn From`.

**Comment by NobbZ** [comment]
\cc @exercism/rust

**Comment by TheDarkula** [comment]
Thanks so much for bringing this to our attention! I'm currently in the process of restructuring the Rust track as part of the [Track Anatomy Project](https://exercism.io/blog/track-anatomy-project) and this is a side effect of that. For more on the background there, please see [issue #809](https://github.com/exercism/rust/issues/809) opened by @kytrinyx :)

This issue is now resolved by [pull request #812](https://github.com/exercism/rust/pull/812).

Also, in the future, it's best to open these issues in the language specific repository, for instance [Rust](https://github.com/exercism/rust) :)
