### ISSUE TITLE
Make wait time to get mentor attention visible / manage expectations

### ISSUE THREAD

**Issue by jangroth** [exercism/exercism#4787]
I signed up last week, did the first 2 exercises, had a mentor within 24h. Then did exercise 3, waiting for a mentor for 3 days now. Came here because I'm really keen to progress - only to find out that others are waiting for weeks. 

So 3 days isn't long at all. In hindsight, this makes sense - 81 Python mentors vs 32,000 students. Sounds like wait time is currently measured in weeks rather than hours.

I'm new here, but from reading in this forum I understand the exercism is experiencing scaling issues. Way more students than mentors.

**I want to suggest to make wait time information publically available and to manage expectations from the beginning (read: sign up).** 

How about having at least an FAQ article covering the current situation? And maybe publishing an 'average wait time' metric per stream? 

Just so that people know what to expect if they sign up...

**Comment by tvogt** [comment]
Same experience here. I'm already wondering if something broke. I'm on the Rust track and my first excercises received mentor feedback quickly. Then excercises were shuffled around and the one I had in progress became a side excersise and since then, maybe a week ago, I have heard **nothing** from any mentors. I understand everyone is a volunteer, but at least knowing if my current exercise is in queue at all, has been seen by someone, or how many are waiting in line with me, what's my place in the line - anything would help.

**Comment by ydrecords** [comment]
Similar experience.  My current Python core exercise has been waiting 32 days for mentor review.  I don't begrudge this because I appreciate the (free!) value I am receiving from volunteers.  However, if there were a simple status field (e.g. "mentor queue position is #1000"), I could watch that change over time and understand that progress is being made.  As it stands, I don't know if something has broken with my submission, whether it would help to resubmit a new iteration, or to complete more side exercises, etc.

**Comment by Moeser** [comment]
* "Average wait time for this exercise" (because the wait time can be longer for later exercises)
* "Mentor queue position" (from the above suggestion)

If the average of "3 to 4 weeks" continues to hold for the python track, by the time the track is complete we'll have waited for mentor feedback for 13 to 18 months total.  Getting some visibility into a wait queue that long would definitely improve the quality of life for all of the people waiting.

**Comment by iHiD** [comment]
We've added the "position in queue" and will be adding a median mentoring time in the near future, so I'm closing this. Thanks for the ideas/discussion.
