### ISSUE TITLE
Donating to Exercism

### ISSUE THREAD

**Issue by alannallama** [exercism/exercism#4792]
I sent an email and was directed to raise an issue here.

Someone has [pledged a $100 donation to Exercism](https://opencollective.com/exercism) on [Open Collective](https://opencollective.com), a funding platform for open source. If you are interested, you can claim your Collective, so people can back the project or companies can sponsor it?

Most of our Collectives are open source code projects, but we also serve a lot of tech education and outreach programs like Exercism. Setting up a Collective is free (we take a small % of donations to cover platform expenses).

To everyone in the Exercism community, do you think it could be easier to donate, or that budget transparency would be a good thing? Budgets are fully transparent on Open Collective, so you can see where money comes from and where it goes. It also makes it easy for community members to get paid for time on the project or reimbursed for expenses the Collective agrees to cover.

Interested in what people think about this idea!

**Comment by iHiD** [comment]
Hello. Thanks for letting us know about this! I've created an account so that we can claim that money.

That said, while we're very grateful for people who want to contribute money, we've actively decided that we don't want to take donations from individuals at the moment. This is primarily because Exercism has such a large amount of contributors (1000s) that there is no sensible way to distribute it to the community team, and for the bigger projects which we want to hire people for, we need to raise x0,000s to be able to use the money for the level of change. This decision isn't by any means set in stone, but it's where we're at at the moment, so we won't currently be promoting requests to ask for money from individuals.

Thanks again :)

**Comment by alannallama** [comment]
Cool! Thanks very much for the reply @iHiD :)

We do have Collectives on the platform that raise in the hundreds of thousands, mainly from large sponsors, with individual backers able to donate as a way to engage the community and encourage transparency. For example, [Webpack](https://opencollective.com/webpack) and [Babel](https://opencollective.com/babel). We're specifically set up to work with companies giving large amounts (interfacing with their vendor/PO systems, etc). If you ever want to talk more about it, let me know.

**Comment by iHiD** [comment]
OK, thanks. That's good to know. We're exploring various options for funding atm and have a couple of grants either in the pipework or active (for example https://exercism.io/blog/mozilla-supports-exercism-static-analysis). 

Maybe you could drop me an email at jeremy@exercism.io and we can discuss further there?

**Comment by iHiD** [comment]
(cc @kytrinyx to this just for visibility)

**Comment by dzmitry-lahoda** [comment]
not found to donate in crypto. how the button would be added at some point.
