### ISSUE TITLE
Feature Request: Indicate tracks waiting for mentor on home page

### ISSUE THREAD

**Issue by sbonds** [exercism/exercism#4811]
The goal for this feature request is to make it easy to see on the home page which tracks are waiting on a mentor and which tracks I have not yet completed a submission.

One simple way would be to add a note to each track where a submission has been made. For example:

![image](https://user-images.githubusercontent.com/5200082/56096733-dc945e00-5ea0-11e9-9980-0f0584660e55.png)

Another way might be to make a new div class for a joined track where a submission has been made and adjust an appropriate CSS property to make that track summary appear different.

For example using a "greying out" approach:

![image](https://user-images.githubusercontent.com/5200082/56096869-4eb97280-5ea2-11e9-8d75-bb1c9de0063d.png)

Whatever method is used, the idea would be to indicate which tracks' progress is waiting on me, and which ones have me waiting on someone else.

**Comment by sshine** [comment]
Similar feature requests have been made to improve the track overview page. I've tagged this so that it may be grouped together with those feature requests when it is time to make a pass over all of them.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
