### ISSUE TITLE
Display Exercise Concepts When Reviewing

### ISSUE THREAD

**Issue by ronnieoverby** [exercism/exercism#4813]
The track exercise index includes concepts that are relevant for each exercise.

![image](https://user-images.githubusercontent.com/101028/56150835-be506000-5f7d-11e9-8ab0-4c2cf43d4be2.png)

As a mentor, it would be great to see these concepts listed when reviewing a solution, so that we can judge if approval criteria has been met.

This is especially helpful for the many exercises that do not have `Community Mentoring Notes`.

**Comment by F3PiX** [comment]
From a Track Anatomy Project point of view, the topics are not trustfully related to the concepts that matter most with regard to the track's anatomy. That will definitively be updated in the future, but for now, I'm afraid it would add more confusion than insight. 🤷‍♂️

**Comment by sshine** [comment]
This improvement seems easy enough, but I also don't think it adds considerable value to mentors.

**Comment by iHiD** [comment]
@ronnieoverby We had quite a big discussion about this issue on Slack at the time, but I forgot to reply. My conclusion was very much what @F3PiX said - that topics are super important for mentoring, but that the topics right now aren't great (or even correct) so it could cause more harm than good. This is something that we'll be actively fixing as part of the [Chicago project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation).

@sshine Thanks for labelling :+1:

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
