### ISSUE TITLE
BUG: can find solutions before solving myself

### ISSUE THREAD

**Issue by YonatanMyers** [exercism/exercism#4818]
It seems that you put some effort into hiding the solutions for the main exes until a students ex is approved by a mentor. I this is a policy I agree with.
However, I stumbled across a way to see some approved solutions before I ever submitted mine. 
All one need do is:
1. Go into one of his own approved solutions (I did not try with bonus exes but suspect it would work also with one of these).
2. Scroll through to find an ex with a comment.
3. Click to see the profile of the person writing the comment.
4. Under this person's profile, you can find ALL the solutions s/he has submitted on any track...

**Comment by knyzorg** [comment]
You can also just google to find the solutions. Solutions are hidden for your own sake, to not interfere with your thinking.

People who wish to "cheat" the system do so at their own peril, with absolutely no upside.

**Comment by YonatanMyers** [comment]
The solution is hidden not only until you submit but, until a mentor approves it. This leads me to think that they don't want you to find it until it is approved. Yes you can find solutions off the site but finding it through the site seems to me like a bug.

**Comment by iHiD** [comment]
Hello. 

So, as @knyzorg says, if someone wants to cheat they can. It doesn't effect anything really. 

We want to discourage people looking at others' solutions before they solve it themselves, so we make it more difficult to find to remove the temptation. But we don't actively care if someone goes out of their way to find it.

It's a design decision rather than a bug. Thanks for posting though :)
