### ISSUE TITLE
Mentor notes usability improvement proposal

### ISSUE THREAD

**Issue by alex-bender** [exercism/exercism#4832]
> X-posting it from #questions chat.

What about changing the way the Mentor notes are displayed?
Right now If I'd like to compare student's submission with mentor notes I have to click on and off this mentor notes.
![image](https://user-images.githubusercontent.com/3628862/56948951-60557800-6b3a-11e9-8c65-c5763ce3ee22.png)
Wouldn't it be better to be able to see solution and notes simultaneously?
Because system should not limit us from producing a valuable work, it should facilitate it instead.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
