### ISSUE TITLE
Home Page Has Three Extra Hexagons

### ISSUE THREAD

**Issue by evancaplan** [exercism/exercism#4833]
If you navigate your mouse over the first row and the first hexagon with a language displayed, move your mouse to the left and you will notice that there are two empty hexagons that aren't visible unless you mouse over them, in which case they turn blue.
![exercism_bug](https://user-images.githubusercontent.com/17623653/56968970-27b1a080-6b32-11e9-8d5b-35d98bcdb322.png)

**Comment by evancaplan** [comment]
In this example as well, if I were to navigate to the C# icon and hover left, another hexagon appears.

**Comment by iHiD** [comment]
@jackhughesweb Any ideas on this? :)

**Comment by evancaplan** [comment]
@iHiD @jackhughesweb
It looks like there are two divs with the style class `track` that are placed before the icons start. I'm assuming in this style class the :active to make the hexagon blue is in this style class. This is the same at the bottom except there is only one div before the <a></a> start.  It could also have to do with the style classes long row and row short.

**Comment by iHiD** [comment]
Thanks @evancaplan.

**Comment by jackhughesweb** [comment]
@iHiD Both the visible and hidden placeholder `.track` elements will have a hover background due to the following lines:

https://github.com/exercism/website/blob/f25935c482dd74c257b8ddd22d8cf5f9ab54d4d3/app/assets/stylesheets/pages/landing-page.scss#L171-L172

Limiting the `.track` hover selector to only `<a>` tags should fix the issue
