### ISSUE TITLE
Issue with deleting account: ActiveRecord::StatementInvalid in my/settings#delete_account

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#4847]
**Updated**

ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`exercism`.`solutions`, CONSTRAINT `fk_rails_4cc89d0b11` FOREIGN KEY (`approved_by_id`) REFERENCES `users` (`id`)): DELETE FROM `users` WHERE `users`.`id` = 170532

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::StatementInvalid** in **my/settings#delete_account**](https://app.bugsnag.com/exercism/exercism-v2/errors/5c4de88587ed6900193413f4?event_id=5cdfb2a40039f0825e4d0000&i=gh&m=ra)

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ActiveRecord::StatementInvalid** in **my/settings#delete_account**](https://app.bugsnag.com/exercism/exercism/errors/5c4de88587ed6900193413f4?event_id=5d0438910042169caaa40000&i=gh&m=fx)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ActiveRecord::StatementInvalid** in **my/settings#delete_account**](https://app.bugsnag.com/exercism/exercism/errors/5c4de88587ed6900193413f4?event_id=5d19ece600467e60dcbd0000&i=gh&m=ra)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
