### ISSUE TITLE
When go back to profile from solution list is inconsistent with language filter

### ISSUE THREAD

**Issue by DenisVerkhoturov** [exercism/exercism#4856]
Hello, `exercism` team, first of all, thank you for your app it is really great! =D

Here is a little bug I ran into.

**Given:**
Authenticated user visits the profile page and sets filter by language after that goes to a particular solution.

**When:**
A user goes back to the profile page.

**Then:**
Filter by language keep the chosen value (not `Any`) but the list contains all the solutions as if `Any` was selected.

I would expect that either filter is reset to `Any` or list is filtered with a selected filter.

**Comment by iHiD** [comment]
Thanks for the nice and detailed bug report. We're currently swamped with things, but I'll get back to this when I have time and get it fixed :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
