### ISSUE TITLE
Could the exercises be accessible without having to create an account?

### ISSUE THREAD

**Issue by little-dude** [exercism/exercism#4862]
Currently, to access exercises and have a taste of the platform you have to create an account. Being forced to create an account is [discouraging potential contributors](https://www.reddit.com/r/emacs/comments/brq09y/exercismio_a_call_for_a_few_more_mentors_for_the/eofriyu/?st=jvzfp6f2&sh=2a988b3c).

Would you consider making the exercises visible by visitors without an account?

**Comment by iHiD** [comment]
Hello. Thanks for the issue here, and for sharing the word on Reddit. I've replied there too. I'll cross post here.

Hello. Exercism is open-source. The exercises are all freely available on GitHub (e.g. elisp at http://github.com/exercism/elisp). All public content is available without a log in on Exercism's website, and indexed by Google (it has indexed about 300k pages last time I checked). If you want to use Exercism's website and receive mentoring from other users, then you need to sign up and agree to our Code of Conduct. But choosing not to use Exercism's website doesn't stop you from accessing the content that we have, just from interacting through the website with it.

**Comment by iHiD** [comment]
As a follow on, if people aren't interested/curious in seeing what is inside Exercism or how things work, then I doubt they're really interested enough to actually consider taking part in mentoring. We have hundreds of new users a day, and something like a 50% conversation rate from new users hitting our landing page, so I don't feel like this is something that's a general issue. But as I said in my previous post, I do appreciate the thought and suggestion.

**Comment by little-dude** [comment]
Thank you @iHiD !

**Comment by iHiD** [comment]
My pleasure. Thanks for handling it all awesomely! I'm always happy to weigh into discussions if needed so please ping me if appropriate. I don't actively check Reddit (because it can be a shitstorm) but if people link me to things I'm happy to jump in :)

**Comment by vermiculus** [comment]
Hi folks!

Big fan of the platform – and I'm excited about this new(-to-me) 'mentorship' role – both as a learner and a teacher.

One point Chris made on reddit that I think *is* important to talk about (while only tangentially related to this thread) is third-party content archival. Is it in fact true that archive.org cannot access exercise content? IMHO it would be beneficial to allow reviews and such to be publicly available. If this is not already possible today, I recognize some implementations would represent a big community shift – I'd like to suggest some future (or existing?) enhancements that could fill this gap meaningfully for Exercism as an open learning platform and resource. (Probably something similar to Project Euler's 'overview' documents.)
