### ISSUE TITLE
Shortcut to "Most stars" and/or "Most comments" community solutions

### ISSUE THREAD

**Issue by katrinleinweber** [exercism/exercism#4865]
As a mentor, I often do want to rely solely on the mentoring notes and/or my own knowledge of the exercise, but would also like to review community contributions. Thus, it would be neat to 1-click-access the two above-mentioned pages via 1 or 2 buttons in the mentoring interface that open the page in a new tab.

E.g. on https://exercism.io/mentor/solutions/e50a852f8b084e1a9c1e575ca959f798?iteration_idx=1 besides the `View community mentoring notes` (https://exercism.io/mentor/exercise_notes?exercise_id=sum-of-multiples&track_id=r) a button to https://exercism.io/tracks/r/exercises/sum-of-multiples/solutions?utf8=%E2%9C%93&order=num_comments.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
