### ISSUE TITLE
A mentor tool for consolidated review of all past conversation with a student

### ISSUE THREAD

**Issue by vermiculus** [exercism/exercism#4868]
Somewhat related to #4313.

[This idea *sorta* came up on Slack.](https://exercism-team.slack.com/archives/CAQP7JL3T/p1559010273036100) It would be really nice to be able to review your past conversations with a student grouped by exercise/iteration all in one 'story' view. There are many times when I give stylistic or library recommendations to a student but they may validly wish to take an alternate path. I'd like an easy way for me to see that I've already made this suggestion as to avoid sounding like a broken record.

I'm considering keeping my own persistent notes in the meantime. Even something as low-fi as a `git-log`-like interface with the CLI would be helpful (and personally I'd probably use that more), but it would be most accessible / make the most sense as a tool on the website.

**Comment by vermiculus** [comment]
Part of #4658.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
