### ISSUE TITLE
My suggestion for newcomers on submission

### ISSUE THREAD

**Issue by kapple19** [exercism/exercism#4871]
Hi,

The explanations for exercise submission found in multiple issues and the exercism website are very, very unclear.

The following

    exercism submit path/to/file1 [path/to/file2 ...]

implies that you have to type the directory twice, which does not work.

Please simplify the explanation to (Windows example):

1. SHIFT + RIGHT-CLICK in the folder of the exercise you wish to submit.
2. Click on "Open Powershell window here"
3. Type and hit ENTER for

    exercism submit exercisename.jl

4. The command window should hopefully say

    Your solution has been submitted successfully.
    View it at: https://exercism.io/my/solutions/\<...\>

And that's it. That simple. How do you think we are going to interpret

    path/to/file1 [path/to/file2 ...]

which is both incorrect, doesn't work, and is confusing? Why two files (i.e. file2)?

Forgive my bluntness but it took me, a programming novice, two hours to figure out.

**Comment by iHiD** [comment]
> How do you think we are going to interpret ... which is both incorrect, doesn't work, and is confusing? 

Hi there. So that's the normal way to explain optional paramaters on the command line. If you check Wikipedia for usage messages you'll see this as the [canonical example](https://en.wikipedia.org/wiki/Usage_message#Examples). 

> Why two files (i.e. file2)?

Because some languages require multiple files to be committed (e.g. language that has header files and source code files)

> Forgive my bluntness but it took me, a programming novice, two hours to figure out.

Being a programming novice means there are lots of things to learn and many of them take time to figure out. However, now you've learnt this you'll be able to understand guidance on how to use the command line for the thousands of other occasions you need it in your career. It's not a waste of time - it's just the cost of learning.

Could we make it more verbose? Yes. Should we? Probably not. Should we add a link that says "I'm new to the command line. Help?" which then lines to a blog post or video on how to read Usage Messages and how to open the command line. Probably.

**Comment by kapple19** [comment]
Thank you iHiD.

I believe in time as the cost of learning. I'm also an advocate of clear communication. But I'm guessing from your reply that the syntax provided is indeed clear to the initiated.

Specifically, the square brackets provide an optional second file for submission? Thanks for that.

**Comment by iHiD** [comment]
Yeah, square brackets mean optional params. If you look at the example from the wikipedia page above you'll see that square brackets signify things such as flags (anything starting with a `-`) are optional, and specifically at the end you'll see that params are optional. In this case the filename is param to the command `submit` from the application `exercism`

Compare the example:
```bash
program [-aDde] [-f | -g] [-n number] [-b b_arg | -c c_arg] req1 req2 [opt1 [opt2]]

# specifically with the flags stripped
program req1 req2 [opt1 [opt2]]
```

to Exercism:
```bash
exercism submit path/to/file1 [path/to/file2 ...]
```

**Comment by kapple19** [comment]
Thanks for that!

My general take away from this thread is to take time to really read things. And a simplified explanation (in this case, for multiple languages) is just that – a simplification of an explanation that will miss out on elaborating several principles and features.

Thanks.
