### ISSUE TITLE
Lack of mentor response

### ISSUE THREAD

**Issue by BillyBadBoy** [exercism/exercism#4902]
I joined exercism a few weeks ago and began the python track in mentored mode. I've managed to reach the 4th exercise but have been forced to switch to independent mode because I received no response and therefore could not unlock the next exercise. I did this reluctantly - after waiting 14 days for a response. There was no other option open to me.

Perhaps you could consider changing the rules so that the next exercise automatically unlocks after, say, 10 days following the submission of the previous exercise if no feedback is received. This would at least put a cap on how long a student is kept locked out.

**Comment by lazarillo** [comment]
Yes, agreed!  I am actually still on the non-independent mode, simply because I cannot unlock the same number of exercises if I switch to independent.  I have been waiting over a month for a response both on the Python and on the Rust tracks.

I think exercism is great, the exercises are very well designed, and it is great to have mentor feedback.  However, mentor feedback should *not* be required, and we should be able to *opt in*.  This will prevent the platform from creating antagonism / frustration between the students and the mentors.  As is, I have nearly given up on using exercism as a way to learn, despite an otherwise great platform.

**Comment by lazarillo** [comment]
FWIW, while I share @BillyBadBoy 's concern, I disagree that there should be some sort of auto-unlock.  We're all adults -- or at least we're all folks who are actively trying to learn.  We should simply be able to opt in or opt out of mentorship.  Or, perhaps there could be three levels:

- Yes, I want feedback (and want to halt my progress until I receive some).
- I would like feedback, but want to continue further on the track
- I do not feel that I need feedback

Finally, it should be possible to switch between these.  E.g., if I chose to halt my progress until I get feedback, and too much time has passed, I should be able to opt to move onwards.  These "severities" can also be used as a mechanism for the mentors to decide which issues are most critical, as well.  E.g., I know Python fairly well, but want to get to some of the trickier Python problems.  I would like to be able to skip  feedback on maybe the first 8 or 10 exercises.

**Comment by iHiD** [comment]
Thanks for the comments @BillyBadBoy and @lazarillo. This is an area we're currently thinking hard about. 

Two specific things I've pulled out:

> I am actually still on the non-independent mode, simply because I cannot unlock the same number of exercises if I switch to independent. 

@lazarillo Could you explain what you mean by this please?

> Or, perhaps there could be three levels:
> 1) Yes, I want feedback (and want to halt my progress until I receive some).
> 2) I would like feedback, but want to continue further on the track
> 3) I do not feel that I need feedback

(1) is mentor mode. (2) and (3) are independent mode.

**Comment by lazarillo** [comment]
@iHiD In response to your questions:

Regarding being in "non-independent mode", I mean that I still haven't given up hope that a mentor will come and help me.  This isn't, unfortunately, because I expect a timely response from a mentor.  But rather because *I would like to be able to unlock all of the exercises*, and it seems this is only possible if I remain in the mentored tracked.

Regarding the three levels that I propose:  The purpose of my comment was to help address the obvious scaling issue.  Exercism is actually really amazing, and I do not mean to sound begrudging or unappreciative.  Rather, I'm simply pointing out that *some* of the product can scale easily (that which requires no mentor) and some is *very hard* to scale (finding enough mentors to help everyone).  As the product is currently structured, it encourages and even forces us to ask for mentor help, even if we do not feel it is necessary.  As such, those of us who feel confident with our submissions are "wasting" mentors' time.  My suggestion with the 3 levels was to help alleviate the part of Exercism which is so hard to scale.

**Comment by iHiD** [comment]
Hello. I've been off tech for a couple of weeks so sorry for the slow response!

Everything you're saying seems to me to be covered by independent mode. There you have access to all the exercises and can request mentoring just on the ones you want. I'm still unclear on what is missing from Independent Mode with regards to your suggestions.
