### ISSUE TITLE
Default download location for solutions

### ISSUE THREAD

**Issue by itmeson** [exercism/exercism#4915]
Why does the mentor code download script put files in the path: `~/exercism/users/username/trackname/problemname` ?

My preference is for: 
 `~/exercism/mentoring/trackname/problemname/username` 

as I'm unlikely to be looking at all the solutions by a given user, but I do want to be able to download a set of solutions for the same problem, run their tests, and quickly generate common comments/feedback.

In discussion on slack (https://exercism-team.slack.com/archives/CAQP7JL3T/p1557777207269800) it was suggested to use "shell-fu" as a personal solution, and that some mentors do look at all solutions by a given user at once so they can give higher level feedback knowing more about the entirety of the student's work.

I'm open to either approach, and am interested to hear if there are strong reasons for preferring one or the other.

**Comment by NobbZ** [comment]
As I always use `cd $(exercism download …)` I'll always end up in the correct folder…

Also I have mounted `~/exercism/users` to a `tmpfs` which gets wiped regularly. Students code downloaded by UUID is throwaway, nothing I want to keep or look at side by side with something else…

If I want to keep students code for long term mentoring, I store it manually somewhere else.

Therefore I do not care for the exact location and have no strict opinion on this, just wanted to draft out a possible solution.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
