### ISSUE TITLE
Making new exercises.

### ISSUE THREAD

**Issue by thrashdin** [exercism/exercism#4918]
So, I was looking at common lisp track, and I noticed there are not that many exercises there. Thus the question (in general) arises (actually, a few):
1) why? Isn't translating exercises from another languages quite a primitive task in..most cases
2) if I would want to contribute one, should I rather translate an already existing one from different track, or should I make my own?

**Comment by NobbZ** [comment]
1. Different languages do not only have different syntax, but also different idioms, thats why you can't simply "translate" one language into the other.
2. Start by implementing one of the exercises that has canonical data and submit a PR to the tracks repository, for common lisp that is https://github.com/exercism/common-lisp

**Comment by sshine** [comment]
@thrashdin: Have you considered porting exercises to the Common Lisp track?

I'm closing this issue as the question was answered.

But feel free to continue discussing the current state of the Common Lisp track.

Ping @exercism/common-lisp.

**Comment by verdammelt** [comment]
Hello! Yes please submit PR's for further Common Lisp exercises. I currently favor exercises from the canonical set. (See https://github.com/exercism/common-lisp#creating-a-new-exercise)

I wrote a little tool to help with this, it can generate the usual 'boilerplate' of the exercises and do some mechanical translation of canonical exercises into Lisp. From there one should exercise some creativity to make it more idiomatic. (ref. https://github.com/exercism/common-lisp#experimental-exercise-generation).

**Comment by thrashdin** [comment]
I, uhh, wrote several non canonical ones, but after hearing that people here strongly prefer canonical ones I felt very discouraged (and a bit disappointed) and simply chose to become a mentor and just help students.

**Comment by sshine** [comment]
@thrashdin: That's a pity.

The reason why I prefer canonical exercises is to maximize sharing between tracks and avoid nearly identical exercises with different names. Since the problem-specifications repo where canonical exercises live is currently in lockdown, it is only possible to add track-specific exercises at this point.

So if @exercism/common-lisp's maintainers (@verdammelt and others?) favor canonical exercises to the extent where they reject non-canonical exercises (this is a little unclear to me), what you would do now is create them as track-specific exercises and then propose to propagate them back once the lockdown resides.

That is, the distinction between canonical and track-specific exercises is smaller than the uncertainty of how canonical data will be used after the lockdown.

**Comment by verdammelt** [comment]
I'm sorry to hear that you were discouraged. I did not mean to imply that I don't want to see any non-canonical exercises - just that is my preference at the moment to build up the size of the track and keep a consistent experience for people coming from other tracks.

I would like to see your proposed exercises.

We can take this discussion over to the common lisp track slack / github if you'd like.

**Comment by thrashdin** [comment]
Oh, those were just the ones I showed you back then -- I didn't make anything new, and did not upgrade these. Lemme see.

https://github.com/thrashdin/exercism-problem-generator

They are in folders here -- some are just sketches with description, others have some tests.

**Comment by verdammelt** [comment]
Oh i remember those. Please feel free to create PRs to add exercises to the track, I think that might be the best way to discuss the ideas and move them forward.

**Comment by sshine** [comment]
If I were submitting a PR in which I spent effort, I'd probably want to know that the basic idea was something that could get accepted. So maybe if one of those ideas were initially picked, and the problem description was refined and accepted (via the issue tracker), then the nitpicking is restricted to the example solution rather than the scope of the exercise.

I'm not saying PR-driven development isn't the most clear way to communicate, but it's also a way to waste time if it uncovers a disagreement, since it's much cheaper to say "I don't think the track will benefit from this work" than it is to perform the draft of the work.

**Comment by verdammelt** [comment]
I think I see your point. Lacking a mailing list for the track where a discussion could take place I think that bringing this discussion back to the track's slack channel or to the track's github repository (via PR or Issues) is a way to move forward.

**Comment by sshine** [comment]
I think the issue tracker is ideal for this.

People who prefer emails can reply to issues via the reply button.

But I mean, if there's a high degree of agreement in the communication, or the PR is low-effort (e.g. if @thrashdin already made the exercises), submitting a PR directly can fast-forward the whole process.

I think Exercism is a good opportunity to experiment with cooperating in decentralized workflows. :-)

**Comment by sshine** [comment]
As for PR code reviews, it seems that some advanced GitHub interfaces will let you do this in-editor.

E.g. in Emacs: https://blog.laurentcharignon.com/post/code-review-in-emacs/
E.g. in VSCode: https://code.visualstudio.com/blogs/2018/09/10/introducing-github-pullrequests#_review-and-manage-pull-requests
