### ISSUE TITLE
No one watching inactive tracks?

### ISSUE THREAD

**Issue by Bubbler-4** [exercism/exercism#4920]
I recently submitted [an issue](https://github.com/exercism/coq/issues/37) on the Coq track. I want to get some feedback before actually working on it, but I haven't got any so far.

**Comment by kytrinyx** [comment]
@Bubbler-4 Yes, unfortunately at the moment we have not got anything in place to discover when track maintainers are no longer around. I started writing a GitHub App to help with this, but I have been swamped and have not completed it. The issue you have submitted is thoughtful and thorough, and honestly since nobody has responded, I would be happy to give you maintainership on the coq track repository, and let you have your way with it, if you are interested.

**Comment by Bubbler-4** [comment]
Thanks for the suggestion, I'd be more than happy to participate as a maintainer. :)

**Comment by kytrinyx** [comment]
That is fantastic news, @Bubbler-4. Thank you so much! I've invited you to the exercism/coq team. Are you in the Exercism team Slack by any chance? That's usually a pretty good place to discuss things with other maintainers as well as active mentors.

I'm going to close this, but feel free to reach out with more questions if you have them.
