### ISSUE TITLE
Two core exercises "in progress" - is it normal?

### ISSUE THREAD

**Issue by ghost** [exercism/exercism#4921]
I have two core exercises in Python track "in progress" and waiting for mentoring simultaneously. Unsure if that should even be possible. 

UUIDs are:
`c3a8f97e29ae429d9ae8d187177f139e`
`f7d1eda558a348c89ff0cf7657d6abfb`

They've been in a queue for around two weeks but were originally solved months ago. Maybe the weren't part of the core set at that time.

Could somebody comment whether it's all good?

**Comment by tejasbubane** [comment]
My guess is one of those exercises was changed from non-core to core (or vice versa) during track restructuring.

**Comment by sangvo1991** [comment]
I thought I was the only one.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
