### ISSUE TITLE
CLI token warning/hint

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#4926]
("Moved" from https://github.com/exercism/website-copy/issues/930)

A lot of students ask for help with setting up the CLI on Gitter. Many of them also post their token as part of the command they're stuck at. NobbZ is usually pretty fast at telling them to reset it and to not share it again, but it happens so often that perhaps there should be a hint on the website itself that the token is like a password and should not be shared.

Relevant comments:

> I'd also suggest to have a big red warning on https://exercism.io/my/settings, which clearly states that one should never tell anyone the token and that it is like a password.
>
> _Originally posted by @NobbZ in https://github.com/exercism/website-copy/issues/930#issuecomment-482089478_

---

The warning on the settings page is still missing, the walkthrough has one now.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
