### ISSUE TITLE
Is the kotlin thread still being monitored?

### ISSUE THREAD

**Issue by norricorp** [exercism/exercism#4928]
I submitted a solution several weeks ago and there has been no action since then. Up to that point I was getting a turnaround of a few days which was great.

**Comment by sshine** [comment]
Hi @norricorp, and sorry to keep you waiting here also!

Unfortunately there's no clear way to measure the activity of a track besides the expected waiting times which may fluctuate. So a track that is super active mentor-wise one week may be dormant the next. There's not a terrible lot we can do about that. I hope you've gotten back on the track since then!

**Comment by dector** [comment]
@norricorp track is slowly getting on the rails. :)
