### ISSUE TITLE
Prevent development of foregone exercises

### ISSUE THREAD

**Issue by jmrunkle** [exercism/exercism#4932]
This proposal / question goes out to maintainers of the various language tracks.

I assume that Java is not the only language to have certain exercises that cannot be implemented in that language and have been marked as "foregone" in the config.json file (I have been assured this is true by others).

We have been discussing how to make it clear which exercises cannot be implemented in Java (see https://github.com/exercism/java/issues/1589), and have made several proposals:

1. Make it clear in the contributing guide by listing the foregone exercises explicitly there.
2. Use a pull request template
3. Pin an issue in the repo with exercises that cannot be implemented

All of these proposals are deficient in that the prospective contributor has to look at the right document otherwise they find out too late (when they create the PR) that their contribution was wasted effort. The end result is frustrated contributors who may not contribute again in the future. Furthermore, the list of exercises that cannot be implemented is not necessarily fixed. We might later have to designate more exercises as foregone and contributors who had formerly read these documents may not realize that the list has changed (I certainly would not be likely to read such a list more than once or twice).

Recently, I have proposed the following which should resolve that problem: we can use a special markdown file called DO_NOT_IMPLEMENT.md inside the exercise's directory which contains an explanation as to why it should not be implemented. Here is an example adding the DO_NOT_IMPLEMENT.md file: https://github.com/exercism/java/pull/1711

This has the advantage that right when some would-be contributor goes to add the foregone exercise, they would see that there is already something in that directory and it unequivocally tells them not to implement the exercise (even if they do not read the contents of the file). Reading the contents would explain the reasons behind the decision if they were curious.

This solution would require at least one modification to the configlet tool (which I have already prepared in https://github.com/exercism/configlet/pull/163), but it may allow configurations that some tools would have problems with (though there are no tools that I know of currently that would have a problem). If any such tools are discovered, I would propose that they should ignore directories that are foregone in the config.json file.

So onto my questions for other maintainers:

1. Do you accept my proposal (to use a DO_NOT_IMPLEMENT.md for foregone exercises)? If not, why?
2. Are there any other systems out there that have been used to deal with this issue?
3. Are there any more known issues or workarounds for the other proposals here?

**Comment by NobbZ** [comment]
Shouldn't `configlet lint` already error on foregone exercises in the `exercises` folder?

And I checked…

I created an empty folder `exercises/linked-list` (`linked-list` is already foregone in erlang), and I ran `bin/configlet lint .`:

```plain
bin/configlet lint .
-> An implementation for 'linked-list' was found, but config.json specifies that it should be foregone (not implemented).
```

In the contribution guide I have also the following paragraph section ["before pushing"](https://github.com/exercism/erlang#before-pushing):

> Please make sure, that all tests pass by running _test/check-exercises.escript. On windows you might need to call escript _test/check-exercises.escript. Also a run of bin/configlet lint should pass without error message.
>
> Both programs will be run on Travis and a merge is unlikely when tests fail.

This comes very late, yes, but I think its totally fine.

If someone would implement (or try to) an exercise that is not yet a foregone, but we decide during the PR, because its hard/impossible/unidiomatic, then that PR would be closed and the contributor can add the exercise to the foregone key.

And even though I'm not happy with the current way how foregone exercises are communicated in erlang, I also have to say, creating folders just with the `DO_NOT_IMPLEMENT.md` feels wrong as well. Not only that I can't decide from an `ls` whether an exercise is implemented or not, but also I have to adjust a lot of tooling that currently assumes, that each folder below `exercises` is a valid exercise with a rebar project.

**Comment by yawpitch** [comment]
I have a feeling this is is a solution in want of a problem. If an exercise is _impossible_ to implement in a given language then would you ever receive a PR implementing it? If you a _do_ receive such a PR, is your reasoning about it being impossible not suspect?

The reasoning in Java for the three verboten exercises being verboten is not that they are technically impossible, un-idiomatic, or that they recreate an extant language feature (like Linked List would often do with functional languages), but that they were inspired by some other website. That is a reasonably questionable basis for banning an exercise, especially for `grains` (which goes back to at least the Ancient Greeks, if not _much_ further), and `leap` (which I’d think Julius Caesar holds the lapsed copyright for), and so perhaps Java gets more PRs for these exercises than is ideal? That reasoning might be sufficient and valid for the track maintainers, but the excess PRs are a track-specific consequence of having adopted it and simply may not warrant a general solution. Especially one implemented via dirtying up the directory tree with dead end branches.

Wouldn’t it be sufficient and also cleaner to maintain the list of implemented / not implemented / never implemented exercises in the track’s README.md (or CONTRIBUTING.md) file? Both should head off those PRs, at least the vast majority of them.

**Comment by NobbZ** [comment]
In erlang there are currently 3 items in the list:

* `binary-search`: technically possible to implement, but nonsensical on linked lists. Unidiomatic on tuples.
* `linked-list`: technically impossible, as the BEAM (erlangs VM) is purely immutable, and this exercise, as its described as doubly-linked list, needs mutability.
* `lens-person`: This is one I put on the list, because I do not really understand lenses. But this is one I'd maybe overthink.

But I'd never put `grains` or `leap` on the list, because I think its not properly attributing the author.

**Comment by jmrunkle** [comment]
> This comes very late, yes, but I think its totally fine.

This is precisely the problem that my solution seeks to avoid - the fact that it comes too late to be useful for the contributor to find out that they are wasting time.

> Not only that I can't decide from an ls whether an exercise is implemented or not

How much does it really muddy the waters to know that an exercise should not be implemented vs the fact that it is actually implemented? I can only think of using ls to identify exercises that you are planning to implement or modify. In what situation does that distinction matter (and could not be better answered by looking at the config.json file)?

> I have to adjust a lot of tooling that currently assumes, that each folder below exercises is a valid exercise with a rebar project.

@NobbZ - could you clarify what tooling? That was part of the point of this issue is to find any tooling that may have a problem with this structure. Is this tooling specific to erlang?

NOTE: I am not suggesting that we get rid of the system, nor do we even need to have all tracks use this DO_NOT_IMPLEMENT.md file. Only tracks that are interested in doing so would have to do this. There is nothing that I am proposing which would obliged all tracks to do this for their foregone exercises, but it would mean that all tracks would be *allowed* to do this. I suppose I could even modify the PR for configlet so that you have to enable allowing this for your track in the config.json file.

> I have a feeling this is is a solution in want of a problem. If an exercise is impossible to implement in a given language then would you ever receive a PR implementing it? If you a do receive such a PR, is your reasoning about it being impossible not suspect?

I am not concerned about cases where the solution is impossible or extremely difficult to implement in a given language. My concern is about ones that we are (for one reason or another) not accepting PRs implementing them. Why they are not allowed to be implemented is a different issue that could be discussed for each case individually.

> Wouldn’t it be sufficient and also cleaner to maintain the list of implemented / not implemented / never implement exercises in the track’s README.md (or CONTRIBUTING.md) file?

As mentioned in the original issue description, these solutions require that everyone reads the full README / contributing guide before every pull request. There are no guarantees that the list of foregone exercises is stable and unchanging. Nothing about having them listed there makes them any more obvious than the checks in the configlet that come too late to prevent the contributor from already having implemented them (or looking at the config.json file itself which should be listing them anyway). How often would anyone re-read the full README / contributing guide?

**Comment by yawpitch** [comment]
> I am not concerned about cases where the solution is impossible or extremely difficult to implement in a given language. My concern is about ones that we are (for one reason or another) not accepting PRs implementing them. Why they are not allowed to be implemented is a different issue that could be discussed for each case individually.

Fair enough, but if the foregone exercise is both possible to implement and people keep erroneously issue PRs implementing it, isn't the reason for foregoing _doubly_ suspect?

I'm arguing the point here because I'd hate to think that students are losing out on an exercise there's obviously a demand for -- if there are PRs -- because of a worry about licensing on an algorithm that's been in the public domain for _centuries_ (`leap`),  _millennia_ (`grains`), or _since the invention of numbers and written language_ (`say`). I'd be more concerned that someone can effectively DMCA an exercise based on so flimsy a claim.

That said my concern with the specific initiating event doesn't directly address the solution you're proposing.

> As mentioned in the original issue description, these solutions require that everyone reads the full README / contributing guide before every pull request. 

I'm sorry, but to be precise no, it doesn't; it requires them to scan a particular checklist or, if there's a good, clean commit history, to just scan through `git log`. A pinned Issue with a direct link to that checklist _should_ be sufficient to head off all but the keenest of contributors.

Personally I do not -- yet -- see the benefit of moving the goalposts on the configlet script and introducing an ad-hoc "standard" mechanism for dealing with a problem that, at first glance, _appears_ to be, for lack of a better term, a self-inflicted wound. I'd prefer to see some rough consensus from other tracks that they're either experiencing some level of struggle with the same issue, or foresee struggling with it.

So far the only tracks I can see that are forgoing _any_ exercises are **common-lisp**, **cpp**, **erlang**, **elixir**, **fsharp**, **java**, **python**, **rust**, and **csharp**, and only **java** seems to have foregone any for reasons other than impossibility (most are mutation-requiring in immutable functional languages or immutability-requiring in mutable imperative languages) or redundancy (ie `binary`, `octal` in **rust**).

Now of course someone has to be the test case, but without a more obviously established need, preferably across tracks, it still _feels_ premature to address this by adding a file rather than exhausting the other avenues.

Addressing what specific reasoning went into those three exercises and whether or not there's a legitimate licensing concern would go a long way towards establishing that the need exists for at least one track.

**Comment by NobbZ** [comment]
> could you clarify what tooling?

The most important are the testrunner (for devs), which is a simple erlang script which has no access to a JSON parser and therefore has to rely on the folder structure to do its job.

Also I have provided test runners for travis on some tracks that did also iterate over folders in `exercises` rather than using `jq` to read the config, because I didn't know about that nice tool back then.

The most explicit thing you can do is to begin the contribution guide with something like this:

> Before implementing anything, please make sure the exercise you want to implement is not in the list of `foregone` exercises. You can find the caconical list in the `config.json`, here is not necissarily complete excerpt:
>
> * `grains`: Copyright doubt
> * `leap`: ditto

But as your biggest concern seem to be legal issues, I think, we had already big troubles if your concerns were valid.

@kytrinyx can you please clarify if and how maintainers of a track were sueable in the case of someone trying?

**Comment by kytrinyx** [comment]
As far as I know, nobody is suable, as long as we provide attribution, and we write our own descriptions. That should be the case even if an exercise is inspired by an exercise seen elsewhere (as is the case for the Java track's `grains` and `leap` and `say` exercises. I think we are fine to implement them if we want to, I was just being extra careful early on).

**Comment by sshine** [comment]
To summarize this discussion, as there are currently several open issues/PRs related to this that have not seen attention in a while:

- Neither @yawpitch or @NobbZ are in favor of breaking with the invariant of having only exercise directories for implemented exercises. This is to say that the Java track maintainers have autonomy to do so, preferrably in a way where `configlet` does not fail, but exercism/java#1589 seems to suggest that there are mixed opinions and that an effort to break the invariant has stalled.

- The PR exercism/configlet#163 seeks to make it possible for individual tracks to do this. It hasn't received approval or denial, but @kytrinyx wrote the message above at a later point in time than the last comment in the PR. This makes me think that the implicit opinion is that: If the exercises don't strictly need to be foregone, then perhaps adding this `configlet` support is entirely unnecessary.

- @exercism/java should feel free to revise their stance on not implementing the exercises for copyright reasons. They can also continue to not want the exercises for other reasons, but the mechanism should probably be track-local until a point in time where either different circumstances apply or more tracks request something more general.

I would suggest abandoning exercism/configlet#163, closing this present issue until it becomes actual again, and dealing with foregone exercises on the Java track in exercism/java#1589. How is that for you, @jmrunkle? (I think your effort to convince of how easy this fix would be wrt. the `configlet` PR is very noble. Typically "doing the work" is a very effective way to show that something is possible, but it carries the risk of being done in vain.)

**Comment by yawpitch** [comment]
Due to exercism/java#1712 having been merged in mid July the driver for this issue has been entirely eliminated. The exercises involved are either implemented (`leap`, `grains`) or in the process of being implemented (`say`) on the Java track, and none of them remain `foregone`.

Since the obvious need for a general mechanism has ceased to exist we should close:

1. exercism/exercism#4932 -- the present Issue
1. exercism/java#1589 -- which motivated the DO_NOT_IMPLEMENT.md mechanism
1. exercism/configlet#163 -- which would implement it generally
1. exercism/java/#1711 -- which adds a DO_NOT_IMPLEMENT.md to the (since implemented) `leap` exercise

@sshine the last one wasn't addressed in your list.

And yes, thanks to @jmrunkle for the effort ... the discussion was certainly useful.

**Comment by sshine** [comment]
I'm closing this issue by reasoning of the latest comments by myself and @yawpitch.

If it is the case that @jmrunkle does not feel that his questions to other maintainers have been properly addressed and thoroughly discussed, feel free to address these again, and the issue can be reopened.
