### ISSUE TITLE
When median mentorship time is high, allow side exercises when self-completing 

### ISSUE THREAD

**Issue by Leland** [exercism/exercism#4947]
Hi there!

I've been waiting for a few days now on mentorship on the JS track. The median waiting time is listed as _13 days_. It seems oddly harsh, given these giant wait times, to have self-completion not unlock side exercises... and to prevent reactivation of the exercise in the future.

I'd really like to move on, and perhaps double back when the mentorship queue isn't so high.

Perhaps removing these egregious penalties when the median mentorship is high is a way forward?

![image](https://user-images.githubusercontent.com/714017/61750596-cd605e80-ad73-11e9-9265-fd0fe21d2c88.png)

**Comment by iHiD** [comment]
Thanks for the ideas.

> Perhaps removing these egregious penalties when the median mentorship is high is a way forward?

There are two problems with that approach:
1) We just get more exercises in the queues as people move onto the next exercise
2) The standard of submissions goes down because people haven't learnt the prerequisite thing through mentoring on the previous exercise.

The problem is that the wait time is 13 days, which is something we're working on. In the meantime I suggest switching to Independent Mode where you can complete things without waiting for mentors :)
