### ISSUE TITLE
Main exercises in mentored mode - allow to put at least 2 into waiting queue

### ISSUE THREAD

**Issue by KillyMXI** [exercism/exercism#4953]
I've seen the issue #4947.
I understand what you aiming for.
And yet I think some compromises have to be made.

My understanding:
Mentors are batching their activities.
Let's say the average time between when a mentor look into priority queue is 13 days.
17 exercises will take 221 days (2/3 of a year) if we have to wait each and every time for a mentor to clean up priority queue.
Will anyone really stick around for basic stuff for that long?

> We just get more exercises in the queues...

Do you really want people to complete exercises? Currently, you just spreading it over time beyond reason and turning people away. In it's current state, the system doesn't seem to be able to meet it's goals.

My suggestion is to allow at least two main exercises to wait for mentor response.
This will be a reasonable compromise between control over student's progression, queue size and the time required to complete the track.

My further thoughts:
You will never have enough mentors. And it is boring to look into the same basic stuff over and over again.
The only way to have human eyes on students submissions - is to identify when students are good enough to perform peer reviews on certain exercises (progressed deep enough into associated topics), then allow and encourage them to do so, before they done with their own track and gone.

**Comment by iHiD** [comment]
> My suggestion is to allow at least two main exercises to wait for mentor response.
This will be a reasonable compromise between control over student's progression, queue size and the time required to complete the track.

I don't understand how this helps at all. If the wait time is 3 months for a response, then you'll just be waiting for 3 months for two reviews instead of 1. Surely the next GitHub issue will be someone suggesting that we allow 3 reviews, then 4 reviews in the queue etc.

> In it's current state, the system doesn't seem to be able to meet it's goals.
> You will never have enough mentors. And it is boring to look into the same basic stuff over and over again.

Neither of these things are true though :) For tracks that have gone through the Track Anatomy Project and have some Automated Mentoring, we're absolutely fine. See Ruby, Go, C# etc on [this list](https://gist.github.com/iHiD/f04914b28db975f9ecf3349f024ba186).

[Our strategy document](https://exercism.io/strategy) shows what we're doing to improve things. If that fails then we'll consider other things. But we're confident that it won't.

As I said in the other thread, if you don't want to wait for feedback, switch to Independent Mode, where everything is unlocked so you don't have any of the frustration you're currently experiencing.

**Comment by KillyMXI** [comment]
> I don't understand how this helps at all. If the wait time is 3 months for a response, then you'll just be waiting for 3 months for two reviews instead of 1

I'm talking about total time to complete the track, if that was not obvious. That will be halved.

**Comment by iHiD** [comment]
>I'm talking about total time to complete the track, if that was not obvious. That will be halved.

So for Ruby, with 15 core exercises, and an initial <1day response time, you can expect to complete the track within 3-4 weeks if you are focused.

With tracks that aren't currently working well, the Track Anatomy, Automated Mentoring, and the other points in the Strategy document I linked to, will bring these up to speed.
