### ISSUE TITLE
Any distinction between mentored and independent modes from the end result point of view?

### ISSUE THREAD

**Issue by KillyMXI** [exercism/exercism#4958]
Extreme delays in mentors response are really frustrating.
On the other hand, switching to Independent mode feels like have a lesser value.

Does exercism make a difference in which mode a student completed a track?
It better be clarified somewhere.

(Even if not - it will still have lesser value in self-estimation.)

**Comment by iHiD** [comment]
Independent mode solutions appear below normal solutions in the queues. 

Basically, if you want mentor feedback, then you can use Mentored Mode and you have to be patient. If you want to just practice and not rely on mentor feedback then you can use Independent Mode. As I said in the previous issue you raised, our [strategy](https://exercism.io/strategy) shows how we're improving response time.

**Comment by KillyMXI** [comment]
I mean, does exercism provide any sort of recognition for people completed a track?
A badge, certificate, or anything of that nature?
I've seen some mentors have "alumni" badge? Is it something they got for track completion?

Do I do exercises purely for myself in either mode, or there is any difference after completion?

**Comment by iHiD** [comment]
> I mean, does exercism provide any sort of recognition for people completed a track? A badge, certificate, or anything of that nature?

Nope. Not currently.

> I've seen some mentors have "alumni" badge. Is it something they got for track completion? In certain mode?

Maintainers have that for being maintainers who have since stepped down. This is nothing to do with mentoring.

> Do I do exercises purely for myself in either mode, or there is any difference after completion?
If not then what's the point to keep the separation?

We keep the seperation so that people who want to practice exercises without waiting for mentors can do so in Independent Mode, and those who want to take their time and go deeper with a mentor can do so in Mentored Mode.

**Comment by KillyMXI** [comment]
> ... people who want to practice exercises without waiting for mentors can do so in Independent Mode, and those who want to take their time and go deeper with a mentor can do so in Mentored Mode.

The wording is still not great.
"If you're well familiar with the topic - you don't need Mentored Mode, it will provide no extra benefits for you in the end. You will be able to request mentors feedback in Independent Mode when you actually need it.
If you're still learning and want to be corrected, want to know if you're using right language features in idiomatic way - Mentored Mode is for you."

Long term strategy is good to have, but proper messaging right now is equally important.

**Comment by iHiD** [comment]
Yes messaging is important. But your wording is rong. It's actively different to what I said, and what I said is correct. I know this because I'm part of the team that invented and defined the concepts of Mentored Mode and Independent Mode.

Mentor mode is for people who want to work with mentor, on mentor's timeframes, learning one thing at a time, and exploring a concept deeply. Independent Mode is for people who want to practice exercises without having to wait for mentor's feedback. That's the distinction. It's a person's personal choice which they do. It's nothing to do with skill or ability. I've been programming professionally in Ruby for a decade and I learn new stuff by being mentored on Ruby in Exercism.

**Comment by KillyMXI** [comment]
Because expectations established by existing MOOCs are different - it requires to be VERY clear to break them and deliver the actual concept of your service - what it is and what it isn't.
