### ISSUE TITLE
Java bytecode track

### ISSUE THREAD

**Issue by MartinRixham** [exercism/exercism#4961]
I don't know if you've considered making a Java bytecode track but I think it would be a fun one.

**Comment by sshine** [comment]
@MartinRixham: Hi, and sorry for the delay.

You're right, that does sound fun. We do have at least x86-64-assembly and mips tracks, but this would be a first VM. My intuition tells me that the request is borderline; for example, we don't have framework tracks (jQuery, Rails, for example).

Are you asking because you might be interested in making this track?

**Comment by MartinRixham** [comment]
hi

I don't really see the comparison with jQuery or Rails. Bytecode is a language in its own right and a fairly high level one once you get past the binary encoding.

If I find some time I'd happily contribute to a bytecode track.

**Comment by sshine** [comment]
Yes, I understand that that's why Java can so easily be decompiled. To request the creation of a new track, jump over to the [Request a new Exercism language track](https://github.com/exercism/request-new-language-track#readme) repo.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
