### ISSUE TITLE
I can't request mentor feedback after clicking `Complete exercise (Unapproved)`

### ISSUE THREAD

**Issue by dvik1950** [exercism/exercism#4977]
I thought I got stuck in the queue for waiting for too long (might've been just curious to see what happens if I click the button but not willing to admit) so I clicked the `Complete exercise (Unapproved)` and it asked me to confirm clearly stating: 
> you will be able to reactivate the exercise in the future

Yet, I am unable to reactivate the exercise. Is this how it's meant to be, is this not the future yet? Do I have to wait to reactive the exercise or is this a bug?
Thank you

**Comment by iHiD** [comment]
> is this not the future yet?

It's probably somewhere between this and a bug - ie I forgot to do it / didn't get round to it yet :)

If you send me the id of the solution (in the URL) I'll put it back into the queue for you :)

**Comment by dvik1950** [comment]
Cool, thanks a lot. Here's the ID: 630a8128d9cb48179331982dff2b1057 . Meanwhile I managed to ruin the next exercise too (wanted t if it's broken for every exercise or just that one) : 7135fcf96b0e4fbaa8e03a27be34e4e5 but I haven't completed it yet. Can you just wipe the second one somehow or if that's too much work, just put it back in queue as well I'll explain it to the mentor. Thank you for your time

**Comment by iHiD** [comment]
Both are back in the queue now. Maybe post a comment on them to explain to the mentor before they get there :)

**Comment by iHiD** [comment]
I'll leave this open as a bug/backlog thing.

**Comment by davidfrogley** [comment]
Would you mind doing the same for mine?
95a860c692874b6eb4e25992305e71f0

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
