### ISSUE TITLE
Add link to mentor tracks settings

### ISSUE THREAD

**Issue by arueckauer** [exercism/exercism#4979]
The settings page, where a mentor can [choose the tracks to mentor](https://exercism.io/mentor/configure), is only referenced from the [Mentoring Guide](https://exercism.io/mentoring-guide). At least I could not find it anywhere else. It is hard to remember.

It would be a neat thing to have a link added to the settings bar (and even somewhere in the mentor dashboard?).

![Mentor Settings](https://user-images.githubusercontent.com/1815979/63010762-47719800-be87-11e9-8087-cd39d24e6242.png)

**Comment by sshine** [comment]
I can *never* find that link.

I've probably asked on Slack three times.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
