### ISSUE TITLE
Translation to TR-TR

### ISSUE THREAD

**Issue by LeaveNhA** [exercism/exercism#4982]
As #4207 said, It would be lovely to see Exercism in other languages. Like, Turkish, or any other languages.
If it's ok for the community, I can start an initiative for Exercise in Turkish. At least, Exercises.

Sincerely, Seçkin.

**Comment by sshine** [comment]
Hi Seçkin!

Thanks a lot for your offer. As #4207 has been renamed into a general issue on translations, and because implementing multi-language support has been deferred for now, I am closing this issue. A link to this issue will pop up in #4207 so we can find this offer if/when the site is translated.
