### ISSUE TITLE
Team edition request: easy URI to your solutions for others

### ISSUE THREAD

**Issue by Trevoke** [exercism/exercism#4992]
If there is an easy way to create a link to one's own solutions that others can consume, I have not found it. Right now I go to the URI bar in the browser and copy-paste, but that leaves me with `my_solutions`, which needs to be changed to `solutions` so others can consume it. 

I'd like to be able to get the link with `solutions` in the URI easily.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
