### ISSUE TITLE
Testimonials should be sorted most recent first

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5003]
Nothing much to say.  Having to go to the end each time to see new ones makes no snese.

**Comment by TeaDrivenDev** [comment]
Well, it's the same system as in the solutions lists (both the queue and mentored solutions). I would find that acceptable (though certainly not ideal), **but** they're not ordered strictly chronologically either, so the newest one isn't always the last one in the list; that means I have to *remember* who I recently mentored on what exercise and try to find a testimonial that I think I haven't seen before. That is very unhelpful.

**Comment by yyyc514** [comment]
Yes, sadly this new feature goes COMPLETELY unused by me because of this deficiency. 😢 

Assuming this is just adding an index and `order()`...

**Comment by iHiD** [comment]
> sadly this new feature goes COMPLETELY unused by me 

I mean, I get that this isn't a massively hard fix, but you could also just click to the last page on the pagination to see new ones?

**Comment by TeaDrivenDev** [comment]
@iHiD As mentioned, that's not the whole story, because the newest one is not necessarily displayed last. It is *additional work* to actually find that latest addition.

**Comment by yyyc514** [comment]
> I mean, I get that this isn't a massively hard fix, but you could also just click to the last page on the pagination to see new ones?

You mean the 2nd to last page? or the 3rd to last? Depending on when I looked at it last, right?  See the problem?

**Comment by yyyc514** [comment]
PR: https://github.com/exercism/website/pull/726

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
