### ISSUE TITLE
Feature request: Slack integration for teams

### ISSUE THREAD

**Issue by Trevoke** [exercism/exercism#5016]
I see that #3682 actually un-suggested the Slack plugin itself. but we're two years later and the landscape has changed: it would be great to get notifications of exercism activity in Slack.

I suppose this may be related to #4508 as well.

**Comment by iHiD** [comment]
In principle I love this idea, but we're intending to deprecate Slack in the next six months ([see point 5 on Strategy document](https://exercism.io/strategy)), so I doubt it's something that we will actually get done.

**Comment by Trevoke** [comment]
@iHiD Is this something that makes sense for *TEAMS* ?

**Comment by iHiD** [comment]
Ah, I see. Yes, maybe. I'll have a think.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
