### ISSUE TITLE
Need sample inputs in the exercise description

### ISSUE THREAD

**Issue by bratah** [exercism/exercism#5033]
Could you please provide at least one example input so that the question becomes clear as sometimes the question is too generic.

**Comment by iHiD** [comment]
You're going to need to provide some context :)

**Comment by rpottsoh** [comment]
Which exercise?  Which language track?

**Comment by bratah** [comment]
I was solving python track and the exercise that made me think that way was high-scores. Also, it would be nice to have constraints mentioned in the description if any along with the input details. The hackerrank exercises are what I have in mind.

**Comment by iHiD** [comment]
Does the tests file not provide that for you? If not, could you explain what it's not giving you please?

**Comment by sshine** [comment]
@bratah wrote:
> it would be nice to have constraints mentioned in the description if any along with the input details

If I understand you correctly, I think so, too: For all exercises, consider revising the descriptions so that they continue to be language-agnostic, but so they also provide a more technical description, for example using equations, illustrations, tables or similar.

Hackerrank does a lot of other things different from Exercism; they inline the text editor, and they don't give you a test suite, but rather they keep it as a secret which you can verify against once you submit. Another difference is that they have decided that exercises all print strings to standard output, and that all exercises must conform to this format. Many Exercism exercises would not work in this format, for example if they are about manipulating and returning certain data structures.

I think a comparison with Hackerrank must go a little deeper before one can easily extract single things that could be adapted without much modification. I do think their typography and styling of the description area of the page is very beautiful. Maybe I'm just a sucker for TeX rendering. ;-)

@bratah: If you would like to continue this discussion, we should keep the issue open. Otherwise we should probably close it.

---

![hackerrank](https://user-images.githubusercontent.com/50879/65265115-775c2d00-db10-11e9-88ce-8800e152d844.png)

**Comment by bratah** [comment]
@sshine Thanks Simon for the elaboration! I really appreciate it. Exercism's way is a lot cooler than Hackerrank, it is just that I had been going to that site quite often before discovering this.

Before we close this topic, I'd like to ask if it would be possible to have CLI commands to list and download the next exercise without knowing the name of it beforehand. That way, one can use only CLI to follow any track without having to go the website to find the next exercise. Of course, the website provides a great deal of other features such as community interaction etc but this CLI only feature for a particular track would make users like it a bit more I guess :)

**Comment by iHiD** [comment]
> I'd like to ask if it would be possible to have CLI commands to list and download the next exercise without knowing the name of it beforehand.

Hi @bratah. It's not possible right now. Enriching the CLI is something we want to do, and this idea is something we might consider in the future with a `exercism download --track=ruby --current-core` style command, but it's not high on the priority list atm. Thank you for the suggestion though! :)

**Comment by sshine** [comment]
> CLI commands to list and download the next exercise without knowing the name of it beforehand

This would also depend on a public API as requested in #4087.

It is also high on the wishlist among mentors.

I'm closing this issue as its first point (improving the exercise overview) is something that will be addressed in the roadmap; as part of that, I'm sure looking at Hackerrank and other similar sites would be beneficial to learn from.

As for the second point (API-backed CLI download commands), this feature request has open issues already. (Mainly: #4711. Related: #4333, #4138, #4162, #4161, #4087)
