### ISSUE TITLE
Flagging more challenging reviews

### ISSUE THREAD

**Issue by andrewwhitehouse** [exercism/exercism#5037]
Having reviewed a number of Clojure submissions I've noticed that some are more challenging to review than others. 

Perhaps the submitter wanted to experiment with a particular approach, which may lead to increased complexity and so it is difficult to pick out specific points on which to be constructive without spending too long on the review. Also for beginners it may be difficult to know how far to go with feedback to get to a "good enough" solution.

In these cases, in the same way that mentors can choose to skip a review, could we have a way to flag submissions as "difficult" so that they can receive the right kind of scrutiny.

**Comment by sshine** [comment]
This feature request is comparable to another feature request I've heard but cannot find an issue for:

Mentors giving students a rating or a review.

Your request, however, addresses slightly different use-cases and is a lot less controversial since it would only indicate that a submission may be hard or time-consuming, but not why. Do you mind if we retitle this feature request as "Ability to flag submission as challenging to review"?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
