### ISSUE TITLE
Keystrokes for bold, italic, etc do not work in editor

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5039]
Problem seems to be we do not use the `jquery-hotkeys` plugin  which is required for this to "just work" out of the box.  Can this be added?

Should we just pull in the https://rubygems.org/gems/jquery-hotkeys-rails GEM or would we rather just vendor the file ourselves into `javascripts/lib` or another location?

I think with a little guidance I could submit a PR for this.

**Comment by iHiD** [comment]
It can go in `app/javascripts/libs` for now. I'll happily accept a PR from your for this, thanks.

**Comment by yyyc514** [comment]
For my reference: https://github.com/jeresig/jquery.hotkeys

**Comment by yyyc514** [comment]
Removing myself.  I needed the app to "just work" when I fired it up, but that's not the case. Don't have time to fiddle with it and jump thru hoops when someone who already has this working might be able to fix this in 5 minutes.

**Comment by yyyc514** [comment]
https://www.bountysource.com/issues/80724435-keystrokes-for-bold-italic-etc-do-not-work-in-editor

**Comment by karuppiah7890** [comment]
Idk much, but I'll see if I can learn asap and make it work ;)

**Comment by yyyc514** [comment]
Your PR does not close this issue if CMD key does not work in Mac.  See how the GitHub editor works and almost any other modern web editor I've used on the Mac.  The CMD key "just works" in my experience.

I've filed an issue upstream: 
https://github.com/toopay/bootstrap-markdown/issues/329

This seems like the kind of thing someone should have already solved and you just flip a switch and get it working.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
