### ISSUE TITLE
my/tracks: Distinguish paused tracks from unstarted tracks

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism#5045]
If I pause a track, it leaves the "Tracks you've joined" section of https://exercism.io/my/tracks and goes back to the "Available tracks" section. I was thinking it may be nice to visually distinguish it so that I can tell at a glance it is paused, as opposed to a track that I've never had a relationship with at all.

I have not decided whether to suggest:

* Having a "Paused tracks" section separate from "Available tracks"
* Leaving them in the "Available tracks" section but showing "PAUSED" somewhere in its box.
* Your idea here

**Comment by sshine** [comment]
This relates to #5042 in that it is another suggestion for improvement to the "Tracks" page.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
