### ISSUE TITLE
Submit solution - The exercise directory does not match exercise slug in metadata

### ISSUE THREAD

**Issue by llRandom** [exercism/exercism#5051]
Can't submit a solution for a Rust - Hello World task. Steps:
1. `exercism.exe download --exercise=hello_world --track=rust`
```
Downloaded to
C:\Users\Random\Exercism\users
```
2. `exercism.exe submit .\users\main.rs`
```
Error:

    The exercise directory does not match exercise slug in metadata:

        expected 'users' but got ''

    Please rename the directory 'users' to '' and try again.
```

It's probably related to the content of `C:\Users\Random\Exercism\users\.exercism`. In my case it's this:
```
{"track":"","exercise":"","id":"","url":"","handle":"","is_requester":false,"auto_approve":false}
```

**Comment by sshine** [comment]
I think that should be `--exercise=hello-world` with a dash and not an underscore?

I'm not on Windows, but if I run the similar command on Linux, I get something quite different:

```
$ exercism download --exercise=hello-world --track=c

Downloaded to
/home/simon/exercism/c/hello-world
```

I would very much think that it's an error that `exercism.exe` reports that the exercise itself has been downloaded to the users directory. Are you sure that the exercise is not located in a directory like `C:\Users\Random\Exercism\rust\hello_world`? If that is the case, what happens if you go to that directory and type `exercism submit src\lib.rs`?

**Comment by sshine** [comment]
If this is caused by `--exercise=hello_world` rather than `--exercise=hello-world`, and it works with the latter, I think this should be reported as a bug, since the outcome of running the wrong command does not indicate what went wrong (that the exercise doesn't exist under that name).

**Comment by NobbZ** [comment]
I have created an issue at the CLI repository: exercism/cli#885

@llRandom please make sure to copy/paste the command from the web-page as is when downloading.

**Comment by llRandom** [comment]
Yes, worked fine after fixing the exercise name. Thanks!

**Comment by sshine** [comment]
@llRandom: Thanks for discovering this bug!
@NobbZ: Thanks for reporting it!
