### ISSUE TITLE
Queue placement estimator sometimes moves students back

### ISSUE THREAD

**Issue by Jamie95187** [exercism/exercism#5061]
I've been really enjoying doing the exercism problems on the Ruby track but I can't progress until a mentor has checked my code. I was wondering if there was anyone still mentoring that track, its been three weeks since the last time a mentor has commented on my last activity. When I check where I am placed in the queue the placement varies,sometimes I move forward but sometimes I move back.

**Comment by sshine** [comment]
@JamieWong92: I think there is unfortunately not much to do but wait, or switch to independent mode.

@iHiD: Were you aware that queue placement could go back? This doesn't seem ideal.

**Comment by sshine** [comment]
Sorry, I'm tired. Could it be that it does this because it constantly recalculates expected waiting time based on mentoring activity that may vary widely? Perhaps having a queue number that is only monotonically decreasing will provide better intuition about the fact that you never lose your place in line, but you also never know when it's your turn.

**Comment by iHiD** [comment]
There was a bug for a while that meant your queue position might not be accurate, but this should be fixed now. The only time it should go backwards now is if a mentor times out (or leaves) and their solutions are placed back in the queue, in which case they get priority over newer solutions. This happened recently as a key mentor timed out (as she was on holiday) and a whole loads of solutions were put back in the queue. So I suspect that's what's causing your pain.

**Comment by sshine** [comment]
Some UX may go into that eventually; going back in a queue without explanation evokes certain negative feelings in at least most of western culture. :-D (In Denmark we describe having a "queue culture".) I'll leave this issue here as the changed title reflects what you just described.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
