### ISSUE TITLE
way back after filtering course by 'topic' in track page does not work as expected

### ISSUE THREAD

**Issue by fcnoronha** [exercism/exercism#5065]
The following procedure make the filter on tracking page not work correctly:

- At the track page of some course and apply the 'topic' filter
- Select a problem
- Go back to the tracking page

Now, the list is does not have the filter applied anymore, but the selection is still made is the 'topic' list and now you have to select another topic and re-select the preview one.

**Comment by remoteforrest** [comment]
I was able to reproduce this bug in Chrome on macOS, but the problem doesn't occur in Firefox or Safari.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
