### ISSUE TITLE
error Command "tsc" not found

### ISSUE THREAD

**Issue by soundcrawlers** [exercism/exercism#5074]
Hello, 

I´ve started today in Exercism with the TypeScript track. I have installed everything but I get an error when typing $ yarn test: error Command "tsc" not found.

yarn test
yarn run v1.19.1
$ yarn lint:types && jest --no-cache
$ yarn tsc --noEmit -p .
error Command "tsc" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
hello-world $

Has anyone encountered the same issue?

Thanks

**Comment by sshine** [comment]
Ping @exercism/typescript.

**Comment by soundcrawlers** [comment]
I solved the issue by installing npm in the same folder as the exercise. I have installed npm globally now.

**Comment by SleeplessByte** [comment]
`yarn` is a _replacement_ of `npm`. Installing the binary `npm` in the exercise folder is not what you want, but I also don't think that's what you did. As per [the official instructions for the typescript track](https://exercism.io/tracks/typescript/installation), 

> **Each assignment** needs some tools to run the tests:
>
> They can be installed running this command within each assignment directory:
> ```bash
> $ yarn install
> ```
> **You must run install before you are able to run the tests**.

So each time you download an exercise using the `exercism` cli, you need to go _into that folder_ and run:

```bash
yarn install
```

The equivalent method using `npm` would be:

```bash
npm install
```

...but that is not recommended, because the track is set-up for `yarn` (using `yarn.lock`) and _not_ for `npm` (which would use `package-lock.json`).

**Comment by sshine** [comment]
Excellent, I'm closing this issue, then.
