### ISSUE TITLE
Need more feedback

### ISSUE THREAD

**Issue by OneFabric** [exercism/exercism#5086]
Greetings!

I was wondering if I could get more feedback on my current exercise in the java track? My assigned mentor was very prompt, but for some hasn't responded in the past week...Is this to be expected?

I hope this was the best place to open the issue.

**Comment by sshine** [comment]
@OneFabric: We have a tag to address this type of request here, so opening the issue here is fine!

If your mentor for that exercise has left you with a task and you've responded to it, and the ball is in their court, they get one week to respond before your submission is put back into the queue for another mentor to pick up. This is to avoid leaving students in limbo when mentors drop the ball.

So I think your best bet is to either wait for the mentor in question to get back to you, or for another mentor to pick it up and possibly provide more insight in the particular exercise and your current iteration of a solution for it.

I'm closing this issue as there's not much we can do about it in the short run, except hope that mentors on the Java track have time to eventually look at it. I will say that one week is not so bad compared to some other tracks, even though it is annoying to wait. :-)
