### ISSUE TITLE
Proposal: Rename Perl 6 track to Raku

### ISSUE THREAD

**Issue by frncscsrcc** [exercism/exercism#5099]
Hello!

Not really an issue, but due to the fact that recently Perl 6 was renamed in Raku (http://blogs.perl.org/users/ovid/2019/10/larry-has-approved-renaming-perl-6-to-raku.html), the track Perl 6 should be renamed accordingly.

Thank you very much.

**Comment by sshine** [comment]
@frncscsrcc: Thanks for pointing that out.

I've changed the title so it reflects your proposal rather than the information that the language was renamed.

The most recent website change that addresses the Perl 6 / Raku track is exercism/website#793.

Ping @exercism/perl6: I suppose you agree that this rename should eventually take place?

Since @iHiD probably must perform some routine only available to him, this may take some time.

**Comment by kotp** [comment]
I think leaving i`Perl 5` as is should be fine, as we don't need to change it, as it is clear that it is not a prior version.

**Comment by mienaikage** [comment]
I currently have a PR open on the track itself for renaming, but I've been quite busy lately so haven't followed up on it: https://github.com/exercism/perl6/pull/353

I think having Perl 5 as Perl would be a nice adjustment, but not a necessity.

**Comment by mienaikage** [comment]
I've created a couple of PRs to address this:
https://github.com/exercism/perl6/pull/353
https://github.com/exercism/tracks-maintenance-dashboard/pull/40

**Comment by iHiD** [comment]
I've done this on the website now. Please could you check I've not totally broken everything and then close this if you're happy :)

Thanks for sorting it all!

**Comment by kotp** [comment]
Looking good to me @iHiD

**Comment by iHiD** [comment]
Thanks @kotp!

**Comment by rfilipo** [comment]
It looks good for me also. Thanks, @mienaikage, @iHiD, and @kotp.
