### ISSUE TITLE
Hyperlinking Concept Lables

### ISSUE THREAD

**Issue by adhamfarrag** [exercism/exercism#5109]
Thanks for creating exercism, I'm very grateful. It's not an issue, more of a feature request.

<img width="600" alt="Screen Shot 2019-11-05 at 3 08 17 pm" src="https://user-images.githubusercontent.com/23562275/68186089-2a86c580-ff9b-11e9-89bc-f2bba5b9d0c6.png">
Every challenge tackle certain concepts, what if we can use labels to refer to documentations,Like MDN for for Javascript.

Personally I tend to read about every concept before solving it, and I learn more which helps me in future challenges.

**Comment by iHiD** [comment]
@adamhundley Thanks! :)

So, we're currently working on [redeveloping Exercism tracks](https://github.com/exercism/exercism/issues/5088) and will be focussing a lot more on topics ("concepts") as part of that. The current topics aren't trustworthy, and we have no good way of storing data about them across repos that would allow us to hyperlink them, so I'm going to say that we probably won't do this in this way. But not because I disagree, but because we're reworking this stuff to be much more deeply ingrained and will do things similar to what you suggest as part of that.

> Personally I tend to read about every concept before solving it, and I learn more which helps me in future challenges.

100% this.

**Comment by sshine** [comment]
As far as I understand this feature request, it is that an exercise's labels should be hyperlinks to some learning material? If this is the case, then this feature request may be viewed as compatible with the efforts of redeveloping Exercism tracks?
