### ISSUE TITLE
Cannot delete teams

### ISSUE THREAD

**Issue by 8itbangr** [exercism/exercism#5116]
I have the team name, but once I created my profile, I see nowhere to associate myself with an existing team.  Do they have to send me an invitation?

In the process of fumbling around, I also ended up creating my own team with the same name, but don't see a way to delete it.

**Comment by sshine** [comment]
Hi @8bitangr, and sorry for the delayed response.

Yes, they have to invite you. I assume this was resolved in the meantime?

And yes, I don't think there is a way to delete teams right now.

I will label this issue as "Cannot delete team" and mark it as a feature request so that we can eventually support this.

**Comment by 8itbangr** [comment]
Thanks @sshine !

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
