### ISSUE TITLE
Allow commenting student solution at certain line.

### ISSUE THREAD

**Issue by dector** [exercism/exercism#5122]
Code (solution) review comments attached to appropriate lines might be very handy.

**Comment by sshine** [comment]
Perhaps if there is a pluggable Javascript code viewer of comparable appearance and quality with what we've got now, it is more likely to be prioritized.

**Comment by docljn** [comment]
CodeTriage Volunteer here.

@dector do you have any suggestions for how to implement your feature request? The issue has been unchanged for almost 18 months, without apparent discussion, perhaps because it isn't specific enough.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
