### ISSUE TITLE
haskell/resistor-color-trio: Renders without README on website

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5123]
This is how the resistor-color-trio side exercise looks like:

![resistor-color-trio](https://user-images.githubusercontent.com/50879/69058491-110e6080-0a14-11ea-89ee-5166e2ed5418.png)

It was added in exercism/haskell#869 with a README.md and `"core": false`.

I don't know if it looks like this when logged in as someone who isn't also mentor.

But either way, this seems wrong.

I don't think anything is missing in Haskell track's config.json, and the track's CI passed `configlet`'s check to see that the exercise's README.md and .meta/hints.md were properly merged.

**Comment by iHiD** [comment]
So, the git sha of your `solution` is locked to `baf9d5a5d837c99ae3ea6e0cc68e521bf06b7a0b`, which is before this exercise was added.

This is because I ran my `sync tracks` script in a tmux that was started before I went away.

I've updated all of these exercises to have the right slug. If other exercises were added last week they might suffer from the same issue and I'll need to go through manually and fix them, so please let me know if you see similar issues. I'll message on #maintainers on Slack too.

**Comment by sshine** [comment]
Thanks!
