### ISSUE TITLE
[ Exercise: Resistor Color Duo ] Default exported function is named `value`

### ISSUE THREAD

**Issue by clockelliptic** [exercism/exercism#5131]
I am currently mentoring the JavaScript track.

On the Exercise 'Resistance Color Duo', the default name of the exported function is `value`, which ironically makes it difficult to discuss the problem.

While it is almost trivial for a student to alter the default test suite and change the name of the exported function, I feel students should not have to do this. Unless fixing badly named functions is part of an exercise, all exercises should be setup with default function names that are sensible and easy to discuss.

Most importantly, default values and function names should reflect good practices.

**Suggested Solution:** Change the default function name to `resistanceValue`

**Comment by iHiD** [comment]
@clockelliptic Thanks.

cc @exercism/javascript before opening up the love on problem-specs.

**Comment by tejasbubane** [comment]
Agreed. `resistanceValue` is better 👍

**Comment by SleeplessByte** [comment]
In ES6, but in module based languages in general, the filename should also be considered when determining what the name is of a function. Whilst I agree that the name prefixed with resistance or resistanceDuo is better, it obscures the fact that the generated value is NOT a "resistance" value. 

A generically named function that is exported from a file that is named "resistor-color-duo" is not "bad naming".

In this particular case, I opt for a much verboser resistanceColorDuoValue for the reasons above.

**Comment by sshine** [comment]
> `resistanceValue` is better

Yes. In [`resistor-color-trio`](https://github.com/exercism/haskell/blob/master/exercises/resistor-color-trio/src/ResistorColors.hs) I named this `ohms`. But `resistance` is just as good.

Having "value" in the name because it's a value is kind of... redundant.

> `resistanceColorDuoValue`

For the sake of the old gods and the new, no.

If we're entertaining this thought, why not `resistorResistanceColorDuoValueFunction`?

To summarize my criticism of this kind of name: We're trying to embed a namespace into a single variable's name. Anything with "ColorDuo" in the name should already be covered by the module / package. "Value" should already be covered by the fact that it's a value. The only part of this name that provides meaningful context is "resistance". Since there aren't multiple things that can have a resistance in the scope of the exercise, "resistor" is also superfluous here.

So `resistance` is a good name.

**Comment by SleeplessByte** [comment]
Except that it's not a resistance, nor a resistance's value. It's a computation of the significant digits of an incomplete encoding.

But with that I'll remove myself from this conversation. I do not support a rename of any kind, so do whatever you like.

**Comment by sshine** [comment]
> Except that it's not a resistance, nor a resistance's value. It's a
computation of the significant digits of an incomplete encoding.

Yes, I'm not sure what a best practice is here. Either you name it after
what it will eventually do, or you give it a noticeable and verbose name,
or you just don't care and call it "value" or "function". :-P

I'd be tempted to continue to go with the third one, but this exercise
isn't core on a track I mentor, so I haven't been bugged by this.

**Comment by clockelliptic** [comment]
@SleeplessByte 
Well I think the important thing here is removing any obstacles between students and their learning.

So, we can stick with an ambiguous name that makes it difficult for students and mentors to converse about, or the name can be changed in order to make user-experience, mentoring, and learning a better experience.

When I went through this exercise my mentor said "This is a terrible function name that should be changed."

Now that I am mentoring the problem, I agree. I see students agreeing as well.

**Comment by SleeplessByte** [comment]
> So, we can stick with an ambiguous name that makes it difficult for students and mentors to converse about, or the name can be changed in order to make user-experience, mentoring, and learning a better experience.

Yes, I am 100% for a better experience. If a name change helps there, then I support a name change. Like I said: I don't support any of the names laid out above, because they are incorrect (as in, they convey factually incorrect information). I absolutely can understand that `value` is just meh to talk about. 

> When I went through this exercise my mentor said "This is a terrible function name that should be changed."

This by itself is pretty bad mentoring, but like I said, pick whatever different name (even one suggested above which I don't agree with) and I am _happy_ to merge it in `exercism/javascript`.

**Comment by clockelliptic** [comment]
> This by itself is pretty bad mentoring
Agreed. I've actually cleaned up some dropped solutions from this particular mentor.

> pick whatever different name (even one suggested above which I don't agree with) and I am happy to merge it in `exercism/javascript`

Okay, I see your point of view. I believe most people who do this problem perceive that they are in fact returning a resistance value, though it is never explicitly stated that this is not the case. 

The problem statement says "Each band has a position and a numeric value." Maybe one of these names is sensible? It doesn't matter to me, honestly.

`significantDigits`
`decodedVals`
`resistanceValue`
`doubleColorCode`

**Comment by SleeplessByte** [comment]
I love the first one, but I believe Katrina and Jeremy feel that the word significant makes it too compSci, which I get.

`decodedValue` could work
`resistanceDuoValue` could work

What do you think of that?

**Comment by iHiD** [comment]
I like `decodedValue`

**Comment by clockelliptic** [comment]
+1 for `decodedValue`

**Comment by SleeplessByte** [comment]
Alright then. Do you have the time to PR this in our repo? If not let me know and I'll do it.

**Comment by clockelliptic** [comment]
done! 

[https://github.com/exercism/javascript/pull/792](https://github.com/exercism/javascript/pull/792)

**Comment by SleeplessByte** [comment]
https://github.com/exercism/automated-analysis/issues/90
