### ISSUE TITLE
Triangle exercise in java on the triangle inequality

### ISSUE THREAD

**Issue by xinri** [exercism/exercism#5133]
Hello,

I have opened an issue in website-copy but I want to have a talk here about the potential issue.

So this is the copy/paste from the [issue](https://github.com/exercism/website-copy/issues/1403#issue-533613533): 

On the triangle part, I saw double manipulation for adding values. 
As we know, double is not precise and we need to use the BigDecimal in order to have an exact calculation.

Is it necessary in this exercise? Is it a good way to introduce the double vs BigDecimal ? As it is a medium exercise, it is perhaps good to add a unit test that will emphasize this problem?

I test with this unit test :
```
        Triangle triangle = new Triangle(0.18, 0.16, 0.33999999999999999);
        assertTrue(triangle.isScalene());
```
0.18 + 0.16 = 0.34 which is > 0.339999... so the two sides are greater than the third side.

This test throw an exception with the current implementation in the code in .meta.

**Comment by sshine** [comment]
It seems that my comment to this issue was lost before posting it 21 days ago.

The canonical tests contain floating-point values, but it is up to individual tracks whether they want to support that. The Haskell exercise, for example, does not assume a particular kind of number, and so allows for a lossless type as well.

Since the Java track does not have a "core track" of exercises, the Triangle is listed somewhat arbitrarily as a "medium" exercise, so I don't think the use of doubles is purposeful, e.g. to keep the exercise simple. So the use of BigDecimal may make sense here.

Ping @exercism/java. If there is no response after a while, you can try to submit a pull request to the Java track on GitHub: http://github.com/exercism/java in which you make the necessary change.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
