### ISSUE TITLE
Not able to submit solution

### ISSUE THREAD

**Issue by Pensu** [exercism/exercism#5136]
Hi all,

I am trying to setup exercism on my mac. After installing the CLI, here is the version:

```
$ exercism --version
exercism version 2.4.1
```

I am able to configure the CLI as well:

```
$ exercism configure --key=<token>

Configuration written to /Users/peeyush/.exercism.json

  --key=<token>
  --dir=/Users/peeyush/exercism
  --host=http://exercism.io
  --api=http://x.exercism.io
```

And I see, there is already a gigasecond directory inside the `/Users/peeyush/exercism` directory. But when I try to submit the solution, I always get this error:

```
$ exercism submit gigasecond.go
2019/12/18 11:46:49 unable to submit (HTTP: 401) -
```

I also get the error if I try to download another problem:

```
$ exercism dl <solution_ID>
2019/12/18 11:56:58 unable to fetch Submission (HTTP: 401) -
```

Not sure what is causing the issue. Any help is appreciated. Thanks.

**Comment by NobbZ** [comment]
> ```plain
> $ exercism --version
> exercism version 2.4.1
> ```

This version is **very** old and does not work anymore since the middle of the year 2018 due to a massive serverside overhaul.

We had some problems in the past with versions of that era distributed by linux distributions standard package sources, please file a bug with your distributions maintainer. If their distribution is still under support they should either update the package to have a version of 3.0 or newer or completely remove the package from the index.

Then you need to follow the manual or `snap` installation instructions from [the CLI installation guide](https://exercism.io/cli-walkthrough)

If though you are on a mac (looks like that from your users home folder), you need to update update the `brew` package database and then upgrade installed packages.

**Comment by Pensu** [comment]
@NobbZ Yeah, that was the issue. Upgrading exercism worked. Thanks.

Closing the issue.
