### ISSUE TITLE
Suggestion: add brew as an installation option for Linux

### ISSUE THREAD

**Issue by stchris** [exercism/exercism#5148]
I was following the installation steps for the `exercism` CLI and noticed that there is a up-to-date bottle which can be installed via linuxbrew: https://formulae.brew.sh/formula-linux/exercism. I would think that is also a perfectly fine installation option you could link to.

**Comment by NobbZ** [comment]
I do not know nothing about how Linux brew works, but if the Linux package is derived automatically from the Mac version, then yes, I think advertising it as an official means of installation.

But if it's a third party package, even if just copied, we should treat it like any other third party package and treat it as non existent.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
