### ISSUE TITLE
Feature request: Let tracks disable feedback ability for certain exercises

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5153]
While the Haskell track is still in v2, I would like to disable the ability to request feedback for non-core exercises. It seems that we will not reach these last exercises, and that they will inevitably be very time-consuming since mentoring them efficiently requires both having solved them and having mentored quite a few of them, which are both unlikely.

When the Haskell track becomes v3 and core/non-core exercises become *practice exercises*, some similar distinction would continue convenient, but the exact details should probably be weighed.

Alternatively, we can continue to pretend that students may receive feedback on exercises, but it never happens, and the students wait indefinitely and possibly quit the site.

**Comment by iHiD** [comment]
I like this idea. I'll have a think about how we could implement it. Nudge me at the end of the week if I've not replied pls.

**Comment by sshine** [comment]
*nudge* @ihid :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
