### ISSUE TITLE
Feature request: Better exercise navigation in practice mode

### ISSUE THREAD

**Issue by kimvais** [exercism/exercism#5155]
This would be extra helpful for us doing things in practice mode to choose the "core exercises" over side exercises.

For example: Allow filtering of exercises by (preferably check-box) core / side.

*Edit by @sshine: Changed title into example in body.*

**Comment by iHiD** [comment]
What is the reason you want to choose between core and side in practice mode?

**Comment by sshine** [comment]
I recently took the Elm course in practice mode because I was in a hurry and didn't want to wait for mentors. (I would have enjoyed mentoring, but I had a couple of hours and wanted to fast-forward through it.) Doing a track in practice mode comes not only without guidance of mentors, but also without any hints at a good order in which to complete exercises.

We use Teams at work to train new people in Perl, and it similarly doesn't have any hints at a good order. In the case of the Perl track, the listed order is actually not that good, so we have a curated list of exercises we like people to do. But doing practice mode alone, you have nobody to tell you what order might be good.

If I understand @kimvais's request correctly, being able to complete the core exercises in that order, but in practice mode, would deliver one such suggested order. So rather than insist on making checkboxes on the page, perhaps this could be seen as an attempt to order / list exercises in a better way in practice mode.

**Comment by iHiD** [comment]
I think we probably wont change this to v3 as I'm doing no active work on v2 from now on. But for v3, things are changing enough that you'll be able to do deep-dives into learning mode without being blocked by mentors so the issue will go away.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
