### ISSUE TITLE
can not submit Hello world 

### ISSUE THREAD

**Issue by calvinalee2006** [exercism/exercism#5169]
Hello! i have tried to submit my hello world code for about 3 hours and I don't know what is going on, I have tried different times with different paths and I cannot get it to work. I have tried lowercase uppercase, and shortening my path. my git bash is up to date and I have downloaded the proper CLI. Would you have any idea what could be causing my issue?

**Comment by NobbZ** [comment]
Can you perhaps provide some more details about your system, the commands you tried, the error messages you have seen, the track and exercise you are trying to submit, the version of `exercism` CLI you use?

**Comment by calvinalee2006** [comment]
I will actually screen shot them to you. I have had these issues. 
![Screenshot (27)](https://user-images.githubusercontent.com/34635521/72748631-f9b73500-3b74-11ea-8d00-cf3b887b362d.png)

![Screenshot (28)](https://user-images.githubusercontent.com/34635521/72748664-16ec0380-3b75-11ea-9537-95c8f6644038.png)


I have tried looking on the internet for some answers (in which i tried and and they still didn't work). and i thought when i downloaded CLI I was fine but apparently not. I am just trying the hello world exercise.

**Comment by NobbZ** [comment]
That doesn't look like submitting, but like downloading.

Have you installed the `exercism` CLI? When you did it, did you use the manual installation method or the windows installer?

Does it work from within a powershell or `cmd.exe` terminal?

**Comment by precious-adeyinka** [comment]
Okayyyy..yy @calvinalee2006 you are going to far, you don't have to go through all this stress. All you need to do is, work with cmd instead of bash that's one, not for any major reason though, but it will make life easier for you if you know your way around CLI. Then if you are using windows and your windows version is not windows 10, use the 'exercismCLIInstaller.exe' option and run it when downloaded, which will configure things quite well for you. Then you actually need to configure your CLI to make your environment prepared for further usage and you can get that info here https://exercism.io/cli-walkthrough and here https://exercism.io/cli. Also after that in each exercise to the right-hand side there are CLI commands that you can just copy and run, one is to download the exercise and the other is to submit. It is that easy.

**Comment by sshine** [comment]
I'm closing this issue due to lack of response.

@calvinalee2006: Feel free to get back to this thread if anything is still broken.
