### ISSUE TITLE
Adding a "related search terms" section in the instructions tab

### ISSUE THREAD

**Issue by ondono** [exercism/exercism#5170]
As a student in the Rust track, I've found myself **knowing there's a better way** to build an exercise but **unable to find the specific syntax** required. I was constantly searching for variations on "trait parameter", when in retrospect it was obvious that I should've searched for "trait constant". This adds unnecessary workload to the mentors that need to hint the appropriate search terms. 

I know that some of the exercises are tagged, but once on the actual exercise there's no way to see the tags, and in some tracks like the C track, there's no way to see them at all because they don't fit in the track grid.

![image](https://user-images.githubusercontent.com/1643836/72721747-0b9cd600-3b7d-11ea-99ca-be53018e6d05.png)

**Comment by sshine** [comment]
I've labelled this as a website bug because it seems like if tags rendered correctly, the exercise could simply have been tagged with "trait constant", is that right? If not, this issue appears to address two things, and I've gone with the tag rendering as being the main one, since the other one may be better addressed by the @exercism/rust group of maintainers.

**Comment by ondono** [comment]
Yes, it's mostly a UI bug.

Some of the tags are visible on the Rust track, but on tracks like the C one only one is visible per exercise (if at all). Those tags are also not visible on the exercise page, were I'm guessing they'd be more useful.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
