### ISSUE TITLE
UI bug on leaving the track modal

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [exercism/exercism#5173]
## There is UI bug on leaving the track modal.

![image](https://user-images.githubusercontent.com/6451384/73133587-4798d500-406e-11ea-9773-28b41ff6a7d9.png)

### related stylesheet

![image](https://user-images.githubusercontent.com/6451384/73133597-6bf4b180-406e-11ea-8f99-0270e5ee02ac.png)

### suggestion

- fix the width to 48%
(i got this style from one of the normal modals)
![image](https://user-images.githubusercontent.com/6451384/73133600-7616b000-406e-11ea-9d9d-56d19278e679.png)

**Comment by omer-mohamed** [comment]
Hey, is this up for grabs?

**Comment by iHiD** [comment]
Hello both. 

@Violet-Bora-Lee Sorry I missed this when you posted it!
@omer-mohamed No sorry - we don't accept PRs on this repo. But thank you for asking. If you'd like to contribute to Exercism, we're currently looking for help with building out the v3 language tracks at https://github.com/exercism/v3 :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
