### ISSUE TITLE
excercise content is empty

### ISSUE THREAD

**Issue by gcobc12677** [exercism/exercism#5182]
https://exercism.io/tracks/kotlin/exercises/forth-9ec3351c-0383-4965-8de2-c93ecc70c718

**Comment by dector** [comment]
Thanks, we will check it and fix

**Comment by NobbZ** [comment]
Your URL looks suspicious.

It seems as if https://exercism.io/tracks/kotlin/exercises/forth/solutions/632208aff8104c5995c8446cdf40d0ea would correctly point to your submission.

**Comment by iHiD** [comment]
@dector Can you confirm that Nobbz is pointing to the right solution please. Yours seems wrong. But then also, I get content when I check the one Nobbz is referring too.

Thanks.

**Comment by gcobc12677** [comment]
In my tracks of Kotlin, there are two exercise with the same name "Forth".
One is hard level and the other is medium.
Content of hard level is fine. On the other hand, the content of the medium one is empty
(Url above leads to the latter in incognito mode)

**Comment by NobbZ** [comment]
Kotlin removed the `forth` exercise in March '19 in commit exercism/kotlin@a8783b763fe95556bd300ddd4e6bc8a4f4e0350c because it caused very long builds on CI.

It was re-introduced in commit exercism/kotlin@bbdf6d310f5e6e8aace79e35402584b67e524ee8, because simply removing it without notice caused issues with students that solved the exercise previously.

Both versions of the exercise use different UUIDs, which makes them basically different exercises.

Please see also:

* exercism/kotlin#360
* exercism/kotlin#302
* exercism/kotlin#312

@iHiD and @exercism/kotlin. I think we need to "join" both exercises in the database to make them the same. Though I fear this will cause problems with students copies that already contain a `.solution.json` or its successor (which I'm currently not remember the name of).

**Comment by dector** [comment]
Indeed. This one looks strange: https://exercism.io/my/solutions/a3f9d54786df485da3574c012b7cc5f7:
 - empty exercise description;
 - offers strange cli arguments: `exercism download --exercise=forth-9ec3351c-0383-4965-8de2-c93ecc70c718 --track=kotlin`.

**Comment by iHiD** [comment]
Yeah. So that exercise basically doesn't exist any more. It's not in Git, so there's no files to retrieve and show you. But I can't delete it because I don't want to delete people's submitted work.

I've just set it to deprecated in the database, so it shouldn't show up for people who haven't previously downloaded it.

**Comment by iHiD** [comment]
I'm going to manually delete this exercise now so that it doesn't show up for you anymore. No-one has submitted anything for it, so it's safe.

**Comment by iHiD** [comment]
Done. I'm going to close this. Please reopen it if stuff still looks wrong.
