### ISSUE TITLE
No feedbacks on solution for long time

### ISSUE THREAD

**Issue by hacaonguyen** [exercism/exercism#5184]
I submitted my solution for month. However, there’s no feedback until now. Please help to check if my submission has any issues.

Here is the link to my submission: https://exercism.io/my/solutions/2ba41334e04240c9a8ac908f895f8ab4

**Comment by sshine** [comment]
@hacaonguyen: It appears there's a shortage of F# mentors then.

I'm afraid there is not much we can do about that.

**Comment by AndrewHuntington** [comment]
Hi, I'm not sure if I should tag along on this, or start a new issue. I guess, I'll start here and see how it goes.

It's been about 2 weeks since I submitted my solution for High Scores in the Ruby track. Compared to the 14 mentors available in the F# track, Exercism lists over 100 for Ruby. I was wondering if my submission has somehow been over looked, if I just need to be more patient due to whatever circumstances, or something else. Any help would be appreciated! Thank you in advance, and keep up the great work!

[My submission](https://exercism.io/my/solutions/bff9457eb1e24d7aa852690ca32913d3)

**Comment by sshine** [comment]
I'm going to close this issue because mentoring happens on a voluntary basis and should happen at the pace of those who sign up. But I also hope that you get a response in a reasonable time. :-)

Remember that if you run out of patience, it is possible to switch to Practice Mode and progress at your own speed, but at the cost of feedback. (You can technically get feedback on individual exercises by requesting it, but they're sorted last, so if you don't get a response in Mentored Mode, chances are you'll wait longer in Practice Mode.)
