### ISSUE TITLE
Objective C mentor.

### ISSUE THREAD

**Issue by AdamSanderz** [exercism/exercism#5185]
the Objective C track has just 3 mentors, and it seems they don't check the solution like in the other tracks. could you please find more mentors with real knowledge of the language.

Thanks you :)

**Comment by iHiD** [comment]
How would you suggest we do that?

**Comment by AdamSanderz** [comment]
> How would you suggest we do that?

I don't know, man. I just don't like the way that it has just 3 mentors and they don't check anything. :(

**Comment by iHiD** [comment]
I imagine they probably gave up :)

As we move towards Exercism v3, this problem will decrease to a large extent. But getting new people to help is never easy. I'm going to close this because there's not much we can do more than all the things we're already doing, but I share your pain, and thanks for reaching out :)

Just remember when you've got the expertise to mentor, to come help out!
