### ISSUE TITLE
can't configure in Win10

### ISSUE THREAD

**Issue by AshLingua** [exercism/exercism#5186]
I'm new to exercism so this is a pretty basic issue, but didn't find it in faq. I've tried both command line and powershell cl; the exercism 
cli installs okay and creates the shell dir. When I try to download the first exercise, I get :
mv : Cannot find path 'D:\ais\shell\exercism_completion.bash' because it does not exist.
At line:2 char:1
+ mv ../shell/exercism_completion.bash ~/.config/exercism/exercism_comp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\ais\shell\exercism_completion.bash:String) [Move-Item], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand

=============================
running troubleshoot, i get: 

GitHub:
    * https://api.github.com
    * [connected]
    * 435.4705ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 223.4811ms
email: abbygfxx@gmail.com
Thanks for any help!

**Comment by NobbZ** [comment]
Can you please tell us what exact command caused that error message?

`exercism download` should not be able to cause that error.

Also, please always provide the full output of `exercism troubleshoot`.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
