### ISSUE TITLE
Feature request: Require at least one character in feedback when given one star

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5187]
Alternative: *... when given one or two stars.*

This is @NobbZ'es idea from Slack that I'm repeating here because it seems easy and useful:

> Sometimes I think we should force students to enter a text when only giving a single star…

Some care ~may~ *must* be taken in phrasing *why* this is necessary rather than a red "Field missing" to clarify that it's *because* of the low rating given, and phrased in a way that does not the accuse the student.

For example:

> Please help this mentor on how they can improve their style of mentoring so that their feedback would be more valuable to you.

**Comment by kotp** [comment]
Please also with a way to indicate if it is OK for the mentor to get this feedback, or if the student doesn't feel comfortable with giving honest feedback to the mentor for whatever reason.

**Comment by kotp** [comment]
Also, I would revise: "Some care may be taken" -> "Some care must be taken"

**Comment by sshine** [comment]
> a way to indicate if it is OK for the mentor to get this feedback

@kotp: Good point: If we require feedback for 1-star or 2-star reviews, those students who would not give the mentor direct feedback are discouraged. In one regard, this is kind of the point because it's not constructive and potentially a little hurtful, but in another regard, we prevent students from being honest.

But who should then be the recipient of the feedback? We don't have a committee above the individual mentor except for exceptional code of conduct breaching cases. We don't have any meta-moderation mechanism. We certainly could have, but I don't see a trivial way to employ this option (1-star or 2-star review giving no feedback to the mentor, but giving feedback elsewhere).

**Comment by kotp** [comment]
There must be some reason for a 1, right?  Either the student wants to give feedback somewhere to help "unload a hurt" or they realize that it might be helpful to let the mentor know (if they had instantly recognized that fact, they would have written it in a comment, perhaps, but there is another aspect of comments there being "semi-public".) at that point... but not think to come back to make a comment in the exercise itself.  Then the other problem is critical communication in a public forum invites backlash from those that we may not be talking to... which puts a pause on that kind of thing in various places.  If I could take someone to the side and ask if I could be frank and honest with them, then I would maybe feel a little more comfortable stating whatever it is I feel (as I would be vulnerable at that point, knowing as well that I am perhaps making them feel vulnerable to, no need to do this in "public".)

Having an indicator or check box that says "Yeah, I need someone besides me and the mentor alerted to this" means that the "organization leaders" probably need to at least hear about it, even if it is just a review and a mention.

Would giving a 1 star rating with a student indicating some "higher level involvement" happen very often?  I hope not, so this should be a sustainable trigger.  Of course, I don't see things at that level of the organization.

Give the student the option to alert, and this should act as a natural filter to have it go to "founders" level feedback... or perhaps to indicate to the student to phrase the feedback so the conversation could happen.  (I do come back to students that give a 5 star review, and make a comment to thank them.  If I had a 1 star with feedback that I could reason with, I would also thank them... even if I could reason and not agree, at least I have an opportunity to improve things based on their viewpoint.

We do have a meta-moderation mechanism though, in a way.  And it has happened, where a student contacts me off platform, and asks me to review an exercise that I haven't reviewed, and I have talked to them about it, so the meta moderation mechanism is currently organic.  I am sure this has likely happened with other mentors that students have come to respect over time.

**Comment by iHiD** [comment]
I won't for now comment on my thoughts on the pros/cons of this (because it's late and I'm tired and it's complex), but I will say two things:
1) To clarify the current mechanism - students are only **able** to give feedback on 5 star reviews, and they are specifically asked to leave a testimonial for the user. We do not capture comments on other ratings. 
2) We're rethinking a lot of this as part of changes to mentoring in v3. We'll be introducing a credit-based system (where you get credits for things such as mentoring, and spend them on things such as requesting mentoring). Ratings will factor into this somehow so we're going to be rethinking this more deeply as part of that process. I have on my todo list to write up all my notes about this as a basis for discussion, but we've not yet formally considered how ratings will factor into things, so this discussion is useful for starting my brain ticking.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
