### ISSUE TITLE
Feature request: Don't show inactive mentors

### ISSUE THREAD

**Issue by sshine** [exercism/exercism#5191]
When there are 100 mentors, but it takes 14 days to get feedback (#5184), it is either the case that the track is very busy or that there aren't 100 *active* mentors. How about we find a way to quantify if a mentor is inactive and only list those mentors? This will be more truthful and work better with people's expectations.

When is a mentor active?

- **"If a mentor gave feedback in the last N days, the mentor is active."** Won't work because low-traffic tracks will have 0 mentors when there are N days between submissions.

- **If the difference between 'when a mentor last gave feedback' and 'a new solution was most recently submitted' is less than N days, the mentor is active.** Problematic if highly responsive mentors will render less responsive mentors invisible against their interest. But easy to calculate.

Other definitions could be made and evaluated.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
