### ISSUE TITLE
Update FAQ with how to deal with stalled mentoring queues

### ISSUE THREAD

**Issue by ThomasOh92** [exercism/exercism#5192]
Hi there! I recently submitted a solution for the Resistor Color Duo exercise in the javascript track.

Is it normal that for two days, the queue position numbers don't change? This has been displaying for sometime now. 

> There are currently 147 solutions ahead of this in the JavaScript queue, and 38 ahead in the Resistor Color Duo queue

Thanks!

**Comment by ThomasOh92** [comment]
I'm just slightly concerned that there is something wrong and my solution will never get reviewed

**Comment by sshine** [comment]
I don't have intimate knowledge with the Javascript queue, but the queue is usually affected by mentors who take on a bulk of solutions at once. So you can expect some days waiting, and then a sudden yank in the queue.

I suggested [here](https://github.com/exercism/exercism/issues/5112#issuecomment-551999016) (Nov 8, 2019) that we should probably link to an FAQ that explains what to expect here. @iHiD appeared open to it then, so this consideration may still apply.

Since #5112 in which this proposal was made was closed due to the scope of the issue, I would like to ask you if you would either (a) tag this issue `type/mentoring-support` and have it issue closed on the same premise, or (b) tag this issue `type/improvement`, rephrase the title and append the suggestion to have an FAQ? Then we can repurpose this issue into a request to improve usability.

We'll still need to find out what to put in such an FAQ.

**Comment by iHiD** [comment]
> I suggested here (Nov 8, 2019) that we should probably link to an FAQ that explains what to expect here. @iHiD appeared open to it then, so this consideration may still apply.

Yep - if someone PR's an FAQ update to website-copy, I'll happily link to it in the website code :)

**Comment by ThomasOh92** [comment]
Ah okay, thanks for the response guys. Yea i think it would be a good FAQ! To let people know theres nothing wrong even if their queue position doesn't change.

I'm happy to tag is as type/improvement - how should I go about doing this?

**Comment by sshine** [comment]
@ThomasOh92: Good question. So since I don't know the answer to this question, here is how I went about exploring how to do it: I first went to the [exercism/website-copy](https://github.com/exercism/website-copy) GitHub repository and [searched for "faq"](https://github.com/exercism/website-copy/search?q=faq). I [explored "Commits"](https://github.com/exercism/website-copy/search?q=faq&type=Commits), as I hoped this would lead me to files that contain an FAQ. I then [clicked "add Exercism prefix to FAQ sections"](https://github.com/exercism/website-copy/commit/764a2e5d9cd36dd7f8df64a1270b2ee633bfe7c4) because that resembled a change made to something related to an FAQ.

This tells me there's [multiple FAQ pages](https://github.com/exercism/website-copy/tree/master/pages), including [pages/faqs.md](https://github.com/exercism/website-copy/blob/master/pages/faqs.md) and [pages/mentoring_faqs.md](https://github.com/exercism/website-copy/blob/master/pages/mentoring_faqs.md).

I believe a section in **pages/faqs.md** is warranted.

Let me know if you need instructions wrt. git, GitHub or Markdown to continue.

**Comment by rahulkeerthi** [comment]
Happy to update and reorganise (i.e. group questions by category) the mentoring FAQ with this and other changes, including #5203.

**Comment by rahulkeerthi** [comment]
Addressed in this [PR for faqs.md in website-copy](https://github.com/exercism/website-copy/pull/1622), along with lots of other additions. 

As a confirmation, this question belongs in the general FAQ as per @sshine comment:

> I believe a section in **pages/faqs.md** is warranted.

#5203 with be resolved with a separate PR.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
