### ISSUE TITLE
Remove Danger Zone?

### ISSUE THREAD

**Issue by JimLynchCodes** [exercism/exercism#5197]
After you enter mentored mode for a track there is a like box in the sidebar labeled "danger zone":

![Screen Shot 2020-02-17 at 8 54 48 PM](https://user-images.githubusercontent.com/5354163/74784602-46765480-5276-11ea-8ecd-527802fd30ae.png)

Woah! In my opinion this causes some anxiety and thought like, "oh man, danger. I better be careful not to press that!". 

Personally, I think that students should be able to move freely between mentored mode and practice mode. If you have completed all the questions in mentored mode and are waiting for a mentor to respond then you should be able to switch over to practice mode and try some problems if you'd like to without it being such a "dangerous" situation! hehe

Anyway, I'm sure this is likely addressed in the new site design, but I just wanted to throw the idea out there! Thanks! ❤️

**Comment by iHiD** [comment]
Hey :) Thanks.

So originally it started as "leave track" which deletes everything, which is bad. So it was appropriate then. But the others are not really that dangerous - you're right. I'll keep this in mind for v3. Thanks! :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
