### ISSUE TITLE
The file you are trying to submit cannot be found.

### ISSUE THREAD

**Issue by ChoaticVerge** [exercism/exercism#5202]
Trying to submit hello-world exercise which i used java for however i get this error : 
The file you are trying to submit cannot be found.

Entering this C:\Users> exercism submit C:\Users\username\Exercism\java\hello-world\src\main\java\Greeter.java

Error : The file you are trying to submit cannot be found.

        C:\Users\Username

No files have been  moved around neither
My Username does contain spaces in not sure if that would cause an issue as in the error message it does not state the full name?

**Comment by NobbZ** [comment]
For those that get here by a search machine, the problem was probably that the space which is part of the path was not escaped properly.

Always remember to escape special characters according to the rules of the shell you use.

Especially `cmd.exe`s escaping rules are somewhat weird at times.

In most cases its enough to just wrap the path in doublequotes (`"`).
