### ISSUE TITLE
Update mentoring FAQs with instructions for removing oneself

### ISSUE THREAD

**Issue by lloyddewit** [exercism/exercism#5203]
I wish to stop mentoring the Go track. The FAQs state:
'If you'd like to stop mentoring a track please email us at mentors@exercism.io and let us know.'
I wrote the email below to mentors@exercism.io and received an auto reply asking me to raise an issue instead. So here is the issue :)

Dear Sir/Madam

I am a mentor on the Go track. My user name is lloyddewit.

Unfortunately due to a new role, I don’t feel I can continuing mentoring. Please could you remove me from your list of mentors. My photograph is also on the Go mentors page.

I find Exercism a fantastic and worthwhile platform. I hope to return to mentoring again in the future when my circumstances change.

Thanks for your help

Stephen Lloyd

**Comment by iHiD** [comment]
@lloyddewit Congratulations on your new role. You can remove yourself by undoing the PR you did when you signed up here: https://github.com/exercism/website-copy/blob/0f6f87e4b116942d52a7b884f2b2d3534531e4da/mentors/go/l.json

**Comment by lloyddewit** [comment]
Done. Please see pull request ‘Remove user lloyddewit from Go mentor list #1485’ (https://github.com/exercism/website-copy/pull/1485). Please let me know if I need to do anything else.

 

Thanks

 

Stephen

**Comment by sshine** [comment]
Perhaps the FAQ should be changed to avoid this detour. :-D

**Comment by sshine** [comment]
Since #5192 addresses updating pages/faqs.md with how to deal with stalled mentoring queues, let us clarify a similar improvement to [**pages/mentoring_faqs.md**](https://github.com/exercism/website-copy/blob/master/pages/mentoring_faqs.md#how-can-i-stop-mentoring-a-track) which was mentioned in this thread's original post. It would be better if this FAQ section also elaborated on removing oneself as @ihid did [a few comments above](https://github.com/exercism/exercism/issues/5203#issuecomment-592547028).

**Comment by rahulkeerthi** [comment]
Happy to pick this up (see proposal below). A couple of things to check:

1. I'm unsure of how a PR revert flows through. Would it remove that track from your mentor list so you can no longer see the queue for it? Would it also stop email notifications associated with previous mentoring activity in that track? In [user preferences](https://exercism.io/my/settings/preferences/edit), there are only global options for mentor notifications (rather than track-based ones).
2. Not everyone will have created a PR? It appears that this step is optional when you sign up as a mentor. If so I will suggest that nothing be done, but they can optionally also turn off mentor notifications if that is the only track they are mentoring.

Just want to understand so I can provide the correct guidance, no issues with any of this functionality! For now, I'm going to propose we replace the existing text:

> If you'd like to stop mentoring a track please email us at mentors@exercism.io and let us know.

with this: 

> If you would like to stop mentoring a track, please revert the pull request (PR) you (may have) made to add yourself to the list of mentors on the website for that track. You can find all website copy PRs [here](https://github.com/exercism/website-copy/pulls). Filter with the Author dropdown to find yours and select the PR for the right track (if you made more than one). Near the bottom of the PR, click Revert.

**Comment by rahulkeerthi** [comment]
[PR created](https://github.com/exercism/website-copy/pull/1623) in website-copy repo to address this, plus update mentoring FAQ more generally.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
