### ISSUE TITLE
JavaScript track set up problem (hellow-world)

### ISSUE THREAD

**Issue by TCE-1** [exercism/exercism#5211]
Hello,
Was able to complete most of the setup steps successfully on Ubuntu.  When I get to`npm install` I run into problems.  Below is the output from:

`npm install`
`npm test`
`exercism troubleshoot`

 

`$npm install` which returns:

> $npm install
> npm WARN saveError ENOENT: no such file or directory, open '/home/../../package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/home/../../package.json'
> npm WARN dev No description
> npm WARN dev No repository field.
> npm WARN dev No README data
> npm WARN dev No license field.
> 
> audited 611 packages in 1.001s
> 
> 3 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities

 and `$npm test` returns:

> $npm test
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path /home/../../package.json
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, open '/home/../../package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/../.npm/_logs/2020-03-06T17_36_31_742Z-debug.log

`$exercism troubleshoot` returns:

> $exercism troubleshoot
> 2020/03/06 12:36:43.002693 cmd_run.go:884: WARNING: cannot create user data directory: failed to verify SELinux context of /home/../snap: exec: "matchpathcon": executable file not found in $PATH
> 
> Troubleshooting Information
> ===========================
> 
> Version
> ----------------
> Current: 3.0.13
> Latest:  3.0.13
> 
> 
> Operating System
> ----------------
> OS:           linux
> Architecture: amd64
> 
> 
> Configuration
> ----------------
> Home:      /home/../snap/exercism/5
> Workspace: /home/../snap/exercism/5/exercism
> Config:    /home/../snap/exercism/5/.config/exercism
> API key:   4a82*****************************47d
> 
> API Reachability
> ----------------
> 
> GitHub:
>     * https://api.github.com
>     * [connected]
>     * 69.501891ms
> 
> Exercism:
>     * https://api.exercism.io/v1/ping
>     * [connected]
>     * 537.018972ms
> 
> 
> If you are having trouble please file a GitHub issue at
> https://github.com/exercism/exercism.io/issues and include
> this information.

**Comment by iHiD** [comment]
This isn't anything to do with the exercism CLI, it's just an issue with the use of npm. 

cc @exercism/javascript for help.

**Comment by TCE-1** [comment]
Running `npm init` seemed to solve the problem.
No where in the instructions does it tell you to do this.  Is it a necessary step to get things set up or did I make a mistake while following the instructions?

**Comment by SleeplessByte** [comment]
Hi there!

[`npm init`](https://docs.npmjs.com/cli/init.html) is used to _create_ a `package.json`. If that "solved" the issue, the issue has actually **not** been solved. Let me elaborate:

[`npm install`](https://docs.npmjs.com/cli/install.html) is used to install the exercise's dependencies. It knows which dependencies there are, by locating a `package.json` in the working directory, and following the folder path to the parent directory, until it hits the root. 

The current (today) output of hello-world should be (on windows):

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 693 packages from 476 contributors and audited 894058 packages in 12.829s

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

In _your case_ it's trying to use ` '/home/../../package.json'`, instead of the actual exercise `package.json`. When you did `npm init`, the warning went away because it created this file (empty) in the current directory.

Please first make sure your current working directory (`cd path`) is the exercise directory. If you were in this directory, try the resolutions/suggestions from [these search](https://duckduckgo.com/?q=npm+WARN+saveError+ENOENT%3A+no+such+file+or+directory%2C+open&atb=v184-1&ia=web) results.

Post here again if you can't make it work.

**Comment by TCE-1** [comment]
@SleeplessByte 
Thank you for breaking that down for me.  What I had not done was download the exercise.  

I'd like to recommend that the be integrated into the introduction section.  I'll create another ticket for that.

**Comment by SleeplessByte** [comment]
@TCE-1 Yes. I just realised that the section about **using** the CLI to download the exercise is missing.

If you open an issue (and have not done so already), can you open it on `exercism/javascript`? We'll also accept a PR. The `CONTRIBUTING.md` guide of that repo is very extensive.

**Comment by TCE-1** [comment]
Done!  I hope it's useful.

Thanks for the help.  I would have done a PR but I'm not sure how.
