### ISSUE TITLE
A way to disable my public profile

### ISSUE THREAD

**Issue by dralley** [exercism/exercism#5213]
I just came back to exercism after a long hiatus and I was asked about setting up a public profile for my track submissions, and said yes.

I've now changed my mind and don't want my submissions to be visible on one public "profile", although I don't mind people seeing or commenting on them in the typical submission stream.

I've looked throughout the web UI and I can't find a single button which would disable my centralized public profile page.  https://exercism.io/my/solutions will, of course, allow individual submissions to be yanked, but most users would have dozens of indvidual submissions and also, I can't find a way to change the default such that new submissons wouldn't end up on the profile again.

I could be missing something, maybe this already exists -- but if not, it should.

**Comment by lacedelli** [comment]
On the settings menu you can find a tab that reads "Track Settings," you can set up an alias there to add an extra level of anonymity.
It's not precisely hiding your public profile, like I assume you want to, but it might do while a feature of "going private" exists.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
