### ISSUE TITLE
Stop mentoring a track

### ISSUE THREAD

**Issue by Dinesh210291** [exercism/exercism#5219]
Hi,

I took a tour of mentoring a track @exercism and it was awesome but as of now I don't want to mentor anything.

So, please stop mentoring a track for me...

Thanks.

**Comment by rpottsoh** [comment]
@cybagians to be removed as mentor you will need to open a pull request and remove yourself from the `c.json` file for the track you were mentoring.

**Comment by kotp** [comment]
You can also uncheck the mentored track [here](https://exercism.io/mentor/configure).

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
