### ISSUE TITLE
Give users the ability to see if a track is oversubscribed without having first to join it.

### ISSUE THREAD

**Issue by alexanderhlee** [exercism/exercism#5220]
Right now, the only way to know if a track is oversubscribed is to join it first. You see the "oversubscribed" warning, but there's no way to cancel out. You have to join the track first. If you decide later that you'd rather wait for the track not to be oversubscribed, you have no other recourse but to visit the danger zone and leave the track.

It would be nice if there was an indicator right on the learning tracks page showing which tracks are oversubscribed or not. Or, at least have the chance to cancel out when seeing the "oversubscribed" warning. 

![swift_over](https://user-images.githubusercontent.com/26277473/76710785-9d8a1080-66e0-11ea-8b7a-0b301e6cb6a7.jpg)

**Comment by iHiD** [comment]
Yep. Nice idea. Thanks for opening the issue. 

As all this is changing for v3 when this will cease to be a thing, I'm not sure I'll get round to it before then. But I'll leave this open for if I'm looking for some low-hanging v2 fruit to improve.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
