### ISSUE TITLE
Set workspace on mounted partition disallows installation

### ISSUE THREAD

**Issue by LukaszGrela** [exercism/exercism#5227]
I've tried to change the workspace to the folder on mounted partition

```
{
  "apibaseurl": "https://api.exercism.io/v1",
  "token": "4**********f",
  "workspace": "/mnt/E*******8/Development/exercism"
}
```
but when I try to install exercise I receive permission denied
```CLI
$ exercism download --exercise=resistor-color --track=javascript
Error: mkdir /mnt/E...8/Development/exercism/javascript: permission denied
```

but my user have read/write to that folder. What is the problem then?

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/me/snap/exercism/5
Workspace: /mnt/E8**********8/Development/exercism
Config:    /home/me/snap/exercism/5/.config/exercism
API key:   4cfb*****************************cff

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 47.915264ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 159.387715ms

```

**Comment by iHiD** [comment]
What does `ls -lah /mnt/E...8/Development/exercism/javascript` give you?

**Comment by LukaszGrela** [comment]
There is no `javascript` folder as the download couldnt create it. The `excercism` folder on that partition has following result of the `ls -lah` command:
`drwxrwxrwx 1 me root    0 Mar 28 15:14 exercism`

This is result of calling this command on the folder I've created on my main partition where all is good:
`drwxrwxr-x   5 me me 4.0K Mar 29 12:34 exercism`

**Comment by iHiD** [comment]
There's something weird going on there as the size of the first folder is 0, not 4K. Sure exercism is a directory and not a file?

What's the full output of `ls -lah /mnt/E...8/Development/exercism/`?

**Comment by LukaszGrela** [comment]
Empty folder, yes. I've created this folder then with `exercism configure --workspace /mnt/E...8/Development/exercism` set the workspace then called the `download` and it failed. I did the same (mkdir then exercism configure, exercism download) on the main partition in my home directory and it worked

**Comment by iHiD** [comment]
Yeah. It don't think this is an exercism issue. There's something strange with that folder, as it's 0kb.

Can you paste the output of `ls -lah /mnt/E...8/Development/exercism/` please? :)

**Comment by LukaszGrela** [comment]
```
me@Toshiba:~/Development/golang$ ls -lah /mnt/E...8/Development/exercism/
total 4.0K
drwxrwxrwx 1 me root    0 Mar 28 15:14 .
drwxrwxrwx 1 me root 4.0K Mar 28 15:14 ..
```

**Comment by SleeplessByte** [comment]
I believe this is a _snap_ issue. I saw @NobbZ mention that sometimes snap causes issues like this.

**Comment by LukaszGrela** [comment]
Did he mentioned how to solve it? :)

**Comment by iHiD** [comment]
Reading through these might help :) https://github.com/exercism/exercism/search?q=snap&type=Issues

**Comment by NobbZ** [comment]
I'm not sure this issue is related to `snap`.

Please check all folders in the chain for permissions:

* `/mnt`
* `/mnt/E…8`
* `/mnt/E…8/Development`
* `/mnt/E…8/Development/exercism`

My assumption is, that at least one of these is not owned by the user `me` and has some permissions missing.

If this is indeed true, please either use `chmod`/`chown` to fix the permissions, or if that does not work as well, please tell us how you mounted the drive and what FS it uses.

**Comment by LukaszGrela** [comment]
```
drwxrwxrwx 1 me root    0 Mar 28 15:14 exercism
drwxrwxrwx 1 me root 4.0K Mar 28 15:14  Development
drwxrwxrwx  1 me root 4.0K Mar 25 07:24 E...8
drwxr-xr-x   4 root root 4.0K Mar 17 17:38 mnt
```
I havent created the `/mnt` folder (at least can't recall, I'm linux user since Feb this year:) ), I'm auto mounting this drive with the following entry in the `fstab`:

```
/dev/disk/by-uuid/E...8 /mnt/E...8 ntfs defaults,uid=me,x-gvfs-show,permissions 0 0
```

**Comment by NobbZ** [comment]
Could you please show the output of `mount | grep /mnt; echo $USER`?

Please do me a favor and do not obfuscate anything in that output (except of the UUID). Perhaps usernames, but then make sure they really are the same before obfuscating!

Also please verify if you create files or folders on that NTFS partition by hand.

> I havent created the `/mnt` folder

Yeah, thats normal. It is a standard location for temporary or short term mounts. Though it lost its relevance since mounting the userspace through `udisks` or similar tools became more common.

**Comment by LukaszGrela** [comment]
```
me@Toshiba:/mnt/E...8/Development$ mount | grep /mnt; echo $USER
/dev/sda4 on /mnt/E...8 type fuseblk (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,x-gvfs-show)
me
```

> Also please verify if you create files or folders on that NTFS partition by hand.

Do you mean if I actually can create files or folders?

```
$ touch test.txt
$ ls -lah
-rwxrwxrwx 1 me root    0 Apr  3 22:46 test.txt
```

```
$ mkdir test
$ ls -lah
drwxrwxrwx 1 me root    0 Apr  3 22:46 test
```
I also use it to develop applications, VSCode doesnt have a problems, npm also, just exercism can't use it:)

**Comment by NobbZ** [comment]
Okay, I'm really out of ideas, except for one...

In the meantime indeed I became the feeling, that indeed snap, or the containerisation, could be a problem here.

Do you have the same problem if you use a manually installed exercism?

Also why are you using a userspace driver to mount NTFS in the fstab? Might cause trouble for encapsulated/isolated/containerised processes. Especially if you also have AppArmor or SElinux enabled.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
