### ISSUE TITLE
Error: not in workspace (Python submission) 

### ISSUE THREAD

**Issue by owalaG** [exercism/exercism#5228]
I get the message above when I submit high_scores.py file. I can't figure out what the issue is? Here's my troubleshooting info:

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           darwin
Architecture: amd64

Configuration
----------------
Home:      /Users/Phibe
Workspace: /Users/Phibe/Exercism
Config:    /Users/Phibe/.config/exercism
API key:   1314*****************************acc

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 49.277905ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 489.914967ms

If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.

**Comment by glennj** [comment]
Do you notice the Workspace in the troubleshooting output above? Your current directory should be `/Users/Phibe/Exercism/python/high-scores`
 
Did you `exercism download --exercise=high-scores --track=python` initially?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
