### ISSUE TITLE
Improve mentor discussion comment h2 headers styling

### ISSUE THREAD

**Issue by 64kramsystem** [exercism/exercism#5230]
Hello!

At least on my browser/OS combination (Chromium/Ubuntu MATE), the h2 headers styling of the mentor discussion comments, are indistinguishable from regular text.

For example, in the screenshot below:

![image](https://user-images.githubusercontent.com/1595356/77845004-78e76b80-71ab-11ea-804b-f97a5a30611b.png)

- the first line is regular text
- the second is an h2 header
- the third is an h3 header

the h3 header is fine, as it has a separator below, but the h2 is essentially regular text.

This makes it hard to separate the comment sections, at least, for long comments.

**Comment by HarrisonMc555** [comment]
If I'm not mistaken, using markdown headers used to behave pretty much how you'd expect (bigger, bolder fonts for h1, gradually decreasing for h2, h3, etc.).

Do we know why this changed? Did we update whatever package we use to do markdown(ish) formatting in comments?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
