### ISSUE TITLE
Submissions that are shorter should be sticky when scrolling long discussions

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5234]
When the left side content fits inside the browser window it should be sticky when scrolling so that the code is still visible even if the discussion thread is quite long.

Mockup (see the scrollbar):

<img width="795" alt="Screen Shot 2020-04-02 at 1 13 50 PM" src="https://user-images.githubusercontent.com/6473/78278593-452a7f80-74e4-11ea-8293-bc15b169afc3.png">

I was able to do this in about 20 lines of Javascript in my extension.

**Comment by iHiD** [comment]
This is how v2 started. And people hated it for various reasons, so we undid it. But yes, I agree :)

**Comment by yyyc514** [comment]
Oh, is there a discussion of that anywhere?  I'm finding it hard to imagine why it would be hated if it was done properly... but perhaps I'm missing something.

Switching tabs is slightly annoying if they are longer, but not sure how to fix that...

**Comment by glennj** [comment]
Have you tested with with the full width code panes enabled?

**Comment by yyyc514** [comment]
I did just now, seems to work just fine with no changes (as it it just does nothing).  As soon as flex is removed from the parent container the sticky just stops working.  I've never 100% understood sticky (not had occasion to need it much).

If this wasn't sufficient it'd be trivial to sniff for when wide mode was on and change the behavior manually.

Or are you actually WANTING it to sticky?  I never considered that (I don't use wide mode)... if it was sticky we'd need different rules than otherwise because if the code took up 99% of the page you wouldn't want it sticky at all because you couldn't do any work in the remaining 1%.

So can you clarify the desired behavior?

**Comment by yyyc514** [comment]
> While playing with it, I quickly noticed that when an element with a position: sticky style is wrapped, and it is the only element inside the wrapper element, this element, which was defined position: sticky will not stick.

<https://medium.com/@elad/css-position-sticky-how-it-really-works-54cd01dc2d46>

There is nothing to stick to in wide mode because the tab area content is only as tall as the LHS content... I fixed this quickly by removing `rhs` and putting ALL the content into LHS... and then you get sticky in wide mode back...

So fixable if it was desired.

**Comment by yyyc514** [comment]
I think a better solution for a lot of people though would be just to remove the max-width coding and use the full browser width in a 60/40 split:

<img width="563" alt="Screen Shot 2020-04-03 at 9 45 06 AM" src="https://user-images.githubusercontent.com/6473/78378258-baf32180-759e-11ea-8f46-770fc7b10b4a.png">

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
