### ISSUE TITLE
Add some form of description to community solutions

### ISSUE THREAD

**Issue by 64kramsystem** [exercism/exercism#5236]
Community solutions are generally in large number.

While stars/comments are a form of description of starred/commented solutions, the vast majority of them is virtually a black box.

Adding some form of description would make browsing them effective. For example, if there is a novel solution to a common exercise, it may go unnoticed.

With "form of description", I'm very generic:

- it could be just a small description of the approach ("performance-oriented solution", "novel approach", "CS algorithm")
- it could be tag ("good_practices", "performance", "algorithmic")
- it could also be the count of the total stars of the student - it would be valuable to optionally find skilled students at the top

**Comment by iHiD** [comment]
Thanks :) This will happen in v3 via approaches. See https://github.com/exercism/v3/issues/690 for details.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
