### ISSUE TITLE
Docker Exercism CLI

### ISSUE THREAD

**Issue by JuanVqz** [exercism/exercism#5238]
Hi! I'm an exercism ruby user and I'd like to return something to you.

I created a [docker exercism CLI version](https://github.com/JuanVqz/docker_exercism_cli)

If it is useful for us I'd like to give you the repository owner.

I'm not a docker expert and it would be better but I'd like to contribute

Thank you!

**Comment by iHiD** [comment]
Thank you for making this. We don't officially maintain Docker builds as too much overhead for us. But I'll leave this open in case any other contributors want to help out :)

**Comment by JuanVqz** [comment]
I hope this would be helpfully for someone

**Comment by pernambucano** [comment]
I'm in the ruby track, and am learning docker too. Your docker-compose helped me a lot!

**Comment by kotp** [comment]
Definitely good to have an "Unofficial Docker Environment" that can be used.  Community driven solutions I find are informative, helpful, instructional, and morale boosting.

There are other things that the community brings, such as css styles via Stylish plugin that someone has put together and made available, and a mentor focused plugin that is available as wel --l [Exercism Plus](https://chrome.google.com/webstore/detail/exercism-plus/mpbkfakldcnnihdkfkhkpfijjaoglcah).

**Comment by JuanVqz** [comment]
@kotp Thank you for your comment that is the goal of this contribution, regards.
BTW if you know someplace for share it, I'd like to know, please

**Comment by kotp** [comment]
I think to know where to share it, it would be helpful to document the idea of how or why to use it.  This would then help inform the decision.  Is it useful for mentors, or more useful for students?  Does it help alleviate installation problems on Windows?  Does it solve some other problem?

Why does this exist, and what problem does it solve?

**Comment by JuanVqz** [comment]
For my experience, this is helpful for students but I don't know if the mentors have been using the **exercism** command because I haven't experience as a mentor.

Yes, this helps with all operative systems because you don't need to deal with the PATH, in fact it's more helpful on the windows system for the same reason.

It's the easy way to install [exercism CLI](https://github.com/exercism/cli) and go ahead to solve exercism problems

**Comment by kotp** [comment]
You might announce it in the gitter support room for Exercism, maybe.  I am not sure if someone is unfamiliar with howto manipulate their path on Windows would be expected to know how to manage docker though.

**Comment by alhuelamo** [comment]
Hi all! I was about to open a new thread when I came across with this issue! Just wanted to introduce to the community that I just uploaded [a set of Docker images](https://github.com/alhuelamo/exercism-docker-images) with the exercism CLI plus the minimum build tools for some of the tracks. I created them because I want to keep my host machine clean, so just wanted to share it in case somebody finds it useful too.

I'm glad to see I'm not the only one Dockerizing stuff :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by JuanVqz** [comment]
Congrats! I'll have a look
