### ISSUE TITLE
Extending exercism to other field like music practicing or spoken language

### ISSUE THREAD

**Issue by MartinDelille** [exercism/exercism#5239]
If https://exercism.io/ is historicaly a programming language learning place, I wondered if the mechanichs behind it could serve other purpose like music or spoken language practicing.

Instead of posting code, the users would share a video of them practicing there instrument (a track would be associated to an instrument). The mentor could then critique the student playing, asking more detailed view on how he put it's hand on the instrument.

I start trumpet class with a personal teacher in 2020. Since we are all confined here in France, I ask him if it was ok to continue remotely and it works! Of course it is not as good as a real class where the teacher is here but it is better to have a good teacher in another country than a bad teacher in your district no?

**Comment by iHiD** [comment]
Yep. I've often thought that Exercism might end up in that direction (different variants to help learn different things). For the foreseeable future we'll be working on making it work perfectly for programming, but once we've perfected that formula, there's no reason we could spread it out (like StackOverview as part of StackExchange).

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
