### ISSUE TITLE
Robot-mentor at least for for first exercises in the track

### ISSUE THREAD

**Issue by izikeros** [exercism/exercism#5241]
I think that you can offload mentors a bit if new solutions matching solutions submitted by a past students will receive the same comments. There are techniques for smart diff for the code (that is not sensitive e.g. to variable names). There is more submissions for the initial exercises than for the final ones. If the student reply to the comment then the reply could be routed to the real mentor.

In the beginning core of the solution might fit into one line (e.g. "Two Fer" in the Nim track) - it should be easy to cluster solutions and provide quick comments.

When student progress on its track and submit solutions to many exercises, then overview comment from the mentor would be difficult to be replaced by robot-comment.

From the student perspective, having immediate, robot-mentor feedback will positively affect perception of exercim and make motivation stronger.

**Comment by kotp** [comment]
The [Roadmap](https://github.com/exercism/docs/blob/master/about/roadmap.md) documentation may be of interest to you.

**Comment by iHiD** [comment]
Hi, we already do that on a good number of tracks. If you'd like to help contribute to a track to do this, please let us know and we can get you set up.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
