### ISSUE TITLE
Feature request: cluster solutions shared by community

### ISSUE THREAD

**Issue by izikeros** [exercism/exercism#5242]
I found I can learn a lot from browsing community solutions. However, opening them one by one is sub-optimal. I would appreciate if the solutions would be displayed as groups having almost the same solution withing the cluster but meaningful difference between clusters.

Such feature could dramatically improve how we can learn from others.

Number of stars and comments could suggest solutions to inspect in first order but it does not work if "starring" is not a common practice.

**Comment by iHiD** [comment]
It's probably marginally harder than you think to reasonably do. "Almost the same solution" is an extremely difficult metric to measure. To solutions can be identical but one missing a semicolon and so one is perfect and the other doesn't even compile. In other situations solutions can seem wildy different due to (for example) using ternaries instead of if statements instead, and inline functions instead of standalone functions, etc, but semantically be very very similar.

That said we have lots of work going on to solve this in partnership with The University of Chicago and our own team of maintainers per language. If you'd like to get involved in helping, you'd be very welcome.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
