### ISSUE TITLE
Feature request: Ignore but do not skip. (for incomplete submissions, etc)

### ISSUE THREAD

**Issue by joshgoebel** [exercism/exercism#5243]
Exercism is missing an “ignore but tell me if the student posts a new iteration”. I can only permanently skip. If something is both incomplete AND super old I don’t always necessarily want to engage - ie, bug the student.  But I’d be happy to if the student submitted a new iteration for review. I can’t be the only mentor to skip incomplete sometimes. Enough of us skip them suddenly student comes back but no one is left to review.

Allowing a mentor to ignore/skip one iteration without skipping/ignoring all others would solve this.  IE, "skip forever" and "ignore for now" are two different concepts.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
