### ISSUE TITLE
Simplify Status filter while in Practice Mode

### ISSUE THREAD

**Issue by alevincenzi** [exercism/exercism#5244]
Hello.

At the top of the page of a track in practice mode, there is a "Status" filter that allows to select among 

- All
- In progress
- Unlocked
- Completed
- Locked

The filter partitions correctly the exercises into the four categories but despite it, all exercises are rendered as "unlocked" (green border and open lock).

Differently from a mentored track, you can select "locked" in the filter and click on an exercise to see its details.

If in practice mode the access for free download and submit of an exercise is (willingly) granted, then there is no sense in having the categories "Locked" and "Unlocked" in the filter above.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
