### ISSUE TITLE
Opening exercises on /my/tracks/slug in a new tab opens a different view than opening them in a current tab

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5251]
If I click on an exercise panel on https://exercism.io/my/tracks/julia, it opens `https://exercism.io/my/solutions/<id>`. However, if I open it in a new tab by middle-clicking it, it opens the "Your completed solutions" screen with the url `https://exercism.io/my/solutions?exercise_id=leap&track_id=julia` showing all solutions I submitted to any exercise/track.

Using the latest Firefox on Windows 10 Pro

**Comment by iHiD** [comment]
The technical reason for this is that when you click on it it's interpreted as a POST but when you open it in a new tab it's a GET.

It's rubbish though, and we won't do it in v3.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
