### ISSUE TITLE
"Tell the maintainers" button

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5254]
I'd really like an equivalent to the "Edit on Github" button many doc pages have. A button that easily lets you report issues/feedback with the exercises to the maintainers from exercism.io itself. Currently I feel like the friction is so high that issues often go unreported.

**Comment by sgedye** [comment]
Do you mean to make this link easier to find/access? i.e. Making a button that is available on every screen and links to the same location as the link circled.

If so, an easy way to do that would be to add a report button to the navbar (maybe just the github logo) next to the notifications icon (bell). If that sounds acceptable, I would be happy to implement it. Please advise :)
 
![exercism-btn](https://user-images.githubusercontent.com/14964449/82044017-291f1e00-96df-11ea-8ae3-294f0683860e.jpg)

**Comment by iHiD** [comment]
@sgedye Thanks for offering to help! :) However, we don't accept PRs to the website itself. If you'd like to help with Exercism, please check out https://github.com/exercism/v3#exercism---v3 - thanks! :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
