### ISSUE TITLE
Cannot complete my solution

### ISSUE THREAD

**Issue by smrtsmrf** [exercism/exercism#5257]
I just finished the Acronym exercise on the ruby track. Submitting it worked just fine. But when I click to complete my solution, it takes me to an error page that says 

```
Oh dear, we can't find that page. Sorry about that.
Continue by heading back to the homepage.
```

Looking in the Chrome dev tools, there are multiple errors on the page. Also, the tabs for `Instructions` and `Test Suite` are not functional.

**Comment by iHiD** [comment]
Could you try this in a different browser please? Maybe some extension you have is disabling JavaScript on the page. 

We have thousands of solutions completed a day without issue so my guess is that it's something your end rather than a system problem, and a browser-extension would be my best guess.

Let me know how you get on and we can try and debug further.

**Comment by smrtsmrf** [comment]
Opening it in Safari worked out.

This is odd though because I was able to complete 3 exercises in Chrome on Saturday just fine. But the one I tried to submit Sunday didn't work. I didn't install/enable any new extensions during that time.

Later today I'll get to the next exercise and I will see what happens. If it doesn't work in Chrome, I will try disabling extensions one by one to see if I can confirm that it is an extension that's causing the issues.

**Comment by iHiD** [comment]
Great. Thank you for checking :) Please do report back if you find it to be a weird extension so others can find this thread in the future.

**Comment by smrtsmrf** [comment]
I went to the website to begin a new exercise. I opened up the Chrome dev tools before I clicked on anything, and there's a bunch of errors in there. (i.e. `unexpected end of input`, `$ is not defined`, also a 404 error on the prism-autoloader CDN). I closed the tab and disabled all of my extensions and returned to the website and the result is the same. 

Chrome **did** recently release an update, and I believe it may have been Sunday when my browser updated. Not sure what was contained in the update, but it seems like maybe the update broke some things on the site.

**Comment by iHiD** [comment]
> unexpected end of input, $ is not defined,

**Comment by iHiD** [comment]
Thanks for the detailed feedback :)

> unexpected end of input, $ is not defined,

For this bit, do you get a stack trace of any line numbers. Could you possibly send a screenshot pls?

I think the prism-autoloader is probably a red-herring.

**Comment by smrtsmrf** [comment]
Fortunately, or unfortunately, Chrome seems to be working just fine now... Hmm. That was weird.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
