### ISSUE TITLE
ACCESS DENIED, BUILD FAILED in GOLANG

### ISSUE THREAD

**Issue by Sagr859** [exercism/exercism#5258]
I'm posting this the third time to get a response as fast as I can. I need a solution to this problem.
You can find my issue HERE: https://github.com/exercism/go/issues/1338

Exercism is an excellent platform for which I searched for long, and I even started recommending it to my friends. Instead of just giving meaningless computational questions they took the effort to mix real-world questions into it. It is even supported by experienced mentors who help us to improve it in every way possible. 

But NOW I NEED A SOLUTION FOR MY ISSUE. PLEASE HELP !!!

**Comment by iHiD** [comment]
Hi. I've pinged the Go mentors to see if anyone has any ideas. As @tehsphinx said in his original response it won't be a problem with Exercism though, it'll be a problem with something that's changed on your system. You have some sort of permission denied error that looks like it's to do with some directory not having access permissions, so that would be my starting point. I'll close this as the other issue is already open :)
