### ISSUE TITLE
horrible time in submitting hello-world excercise

### ISSUE THREAD

**Issue by ra481** [exercism/exercism#5261]
Trying to learn r, i copied the path of exercise file found on download tried to submit it error no such file

**Comment by iHiD** [comment]
Sorry you're having a hard time. Maybe you would like to paste a screenshot of what you're trying to do and the error you're getting. Also it's helpful to know if you're new to programming and/or working on the command line?

**Comment by michaelpaulcuccia** [comment]
Absolutely ridiculous. I've been learning/writing JavaScript for 9 months. A simple console.log('Hello, World!') doesn't need to be this complicated to submit.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
