### ISSUE TITLE
Need a mentor to keep going

### ISSUE THREAD

**Issue by littlejr** [exercism/exercism#5263]
I'm stuck 'cause apparently there's no mentors to check my solution and confirm my submit.
Please I wanna learn! haHA

**Comment by rpottsoh** [comment]
In order to help you we need to know which language track you are working in.  Then we can see about getting the appropriate help.

**Comment by littlejr** [comment]
Python

**Comment by littlejr** [comment]
> In order to help you we need to know which language track you are working in. Then we can see about getting the appropriate help.

Python

**Comment by rpottsoh** [comment]
I am not sure how long you have been waiting for a mentor to review your submission.  There appear to be 120 mentors signed up for the Python track.  It is one of the most popular tracks.  At this point I can only recommend patience.

cc: @iHiD @exercism/python

**Comment by yawpitch** [comment]
@littlejr we are sorry for the delay, but there is a backlog due to the work going on for the next version of Exercism (a video should have been presented to you in a recent login to the site explaining this). I was able to find your most recent submission and it's been waiting a day, but I'm afraid there's a substantial queue ahead of you and we have to clear those first. Again I'm sorry for the delay, but please be patient.

**Comment by littlejr** [comment]
@rpottsoh @yawpitch thank you guys for the answers and I totally understand. Can you guys recommend another site for me to keep practicing while I wait.

**Comment by rpottsoh** [comment]
If there are side exercises available to you in Python while you wait on a mentor I suggest working on those.  If any other languages might be of interest check those out as well, there are many other languages available at exercism.io.

**Comment by littlejr** [comment]
alright, I did all the sides already, but I'm going to follow your advice. Thank you brother!

**Comment by iHiD** [comment]
You can also switch to Practice Mode if you want to practice without a mentor.
