### ISSUE TITLE
Unable to submit Python exercise

### ISSUE THREAD

**Issue by rangavid** [exercism/exercism#5267]
Unable to submit python hello world exercise

Get error
![image](https://user-images.githubusercontent.com/53163031/80334764-828ced80-8895-11ea-8fb4-ed94f65a44de.png)

**Comment by glennj** [comment]
How did you download the exercise?
Did you perhaps set up the PATH for exercism in a different terminal?

**Comment by nash981** [comment]
i believe you have to specify the file path of the file as follows :
"exercism submit C:\Users\kuttipattu\Exercism\python\helllo-world\hello_world.py"
the above would be the entire command need to submit the exercise ig.
Hope this helps

**Comment by kotp** [comment]
The error is about the `exercism` executable file not being found rather than the file to submit being found.

I hope @nash981 does not have to use that style of command for each time a solution is submitted.

Instead, find the executable file, and move it to somewhere in your path.  For Windows, I am not sure where that is.  But letting us know what directions you have used to do the installation, might help someone familiar with Windows to help you out.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
