### ISSUE TITLE
Looking for  Mentor assistance 

### ISSUE THREAD

**Issue by YashashreeGujar** [exercism/exercism#5270]
Hi 
This request is regarding getting assistance from mentorship program . 
I would like to know how to get support from our Mentor program?
I am new to java script and this if first time I am trying exercism  exercises and facing difficulties in understading js concepts .
if anyone can help me in this path will be grateful

**Comment by SleeplessByte** [comment]
Hi there! 

You can [read about Exercism here](https://exercism.io/about), as well as [our values](https://exercism.io/values). The gist is that we're a platform for _current_ developers to learn a _new language_. If you currently don't have 'sufficient' programming knowledge, I suggest the great resource [freecodecamp.org](https://freecodecamp.org). 

As for getting help: we expect students to do self-study to come to a solution. If all fails, you can always submit an incomplete solution. If you're in Mentored Mode, you will automatically be assigned a mentor for that exercise and they will help you further. [Read about the different modes here](https://exercism.io/mentored-mode-vs-independent-mode).

- If you're new to programming: good luck on your journey. We're happy to have you back once you know at least one language.
- If you're only new to JavaScript: follow the instructions on `exercism.io` and try to complete the exercise you're working on. Submit your solution if you can't figure something out and have spend the time trying to figure it out.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
