### ISSUE TITLE
Can't Download Exercises - No such Host Error

### ISSUE THREAD

**Issue by OKELLOMARVIN** [exercism/exercism#5271]
Its my first time using exercism, i followed all the instructions to set up. When i paste the link to download my first exercise, i get an error:

We were not able to upgrade the cli because we encountered an error:
**Get https://api.github.com/repos/exercism/cli/releases/latest: dial tcp: lookup api.github.com: no such host**

when i troubleshoot, this is what i get:
API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 365.0141ms

Exercism:
    * https://api.exercism.io/v1/ping
    * **[Get https://api.exercism.io/v1/ping: dial tcp: lookup api.exercism.io: no such host]**
    * 11.5863878s

Any Help extended to me is fully appreciated.

**Comment by iHiD** [comment]
Hi. Where are you geographically?

**Comment by NobbZ** [comment]
The error suggests that the name can be resolved, though no connection can be established to its IP.

This is usually due to missconfigured proxies or firewalls.

Please check that there are no firewalls blocking your traffic, and please also ensure that `HTTPS_PROXY` and/or `HTTPS_PROXY` environment variables are properly set if there is a proxy.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
