### ISSUE TITLE
Mentor dashboard: filtered results disappear

### ISSUE THREAD

**Issue by Eiermann** [exercism/exercism#5278]
On the `Solutions you're mentoring` tab on the Mentor Dashboard page there seems to be a filtering bug:

1. In the `Status` drop down, choose a status that you know you have solutions for. `Completed` is typical.
2. In the `Track` and `Exercise` drop downs choose a track and an exercise you know you have solutions for.
3. When the list of solutions corresponding to that `Status`, `Track`, and `Exercise `are displayed, click on one of them.
4. When that solution is displayed click the "Back" button in your browser (or go back by your favorite means of going back).

The previous results will be gone and you have to choose a different exercise in the drop down, then re-select the initial exercise to get the results back. This is particularly an issue when searching this way for a comment you know you wrote for somebody but you don't remember exactly which solution it was.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
