### ISSUE TITLE
Privacy Policy doesn't cover CLI app

### ISSUE THREAD

**Issue by toastedmilk** [exercism/exercism#5279]
I'd really like to know how the privacy policy applies to the CLI as it is expressly NOT covered in the Privacy Policy verbiage at https://exercism.io/privacy apart from being defined as part of the platform.  Thanks!

**Comment by iHiD** [comment]
> as it is expressly NOT covered in the Privacy Policy verbiage

I don't understand this, sorry. It is defined as part of the platform, which is what the privacy policy is about. Where do we express that it's not covered?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
