### ISSUE TITLE
Consider misgendering/use of pronouns in testimonials

### ISSUE THREAD

**Issue by cmcaine** [exercism/exercism#5280]
Some mentors are misgendered by students (and I'm sure the other way around, too). Accidental misgendering can be a bit upsetting or even very upsetting, so it would be nice if we could avoid that.

Discussion on slack seems to show a consensus for showing pronouns in the interface and allowing users to select them, perhaps even encouraging the use by setting them to something silly first.

On Mozilla, I think the standard is to link to this site: http://pronoun.is/ (e.g. http://pronoun.is/they) for example sentences, but whatever works.

**Comment by yyyc514** [comment]
> even encouraging the use by setting them to something silly first.

This seems a bit silly to me persaonlly, but showing pronouns can only help.  Will there also be a "I do not wish to disclose" option?

**Comment by cmcaine** [comment]
I think an option like "use my name" would make more sense than "I don't want to disclose", because it's an instruction to others?

**Comment by ScottPJones** [comment]
I like the "use my name" as a default, and letting people then select (if they wish) whatever pronouns they prefer people to use.

**Comment by iHiD** [comment]
Thank you for this. I'm going to lock this and we will have a product-team discussion about it and consult the community further at the right time.

As a note, it would be easy to check if people misgender by searching for words, so a programmatic solution might work.

**Comment by iHiD** [comment]
Also see https://github.com/exercism/website/pull/942

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
