### ISSUE TITLE
Add a white / light grey glow or backgroun on favicon

### ISSUE THREAD

**Issue by FabienTregan** [exercism/exercism#5283]
Hi,

  In situation where you have a dark theme on your navigator, the black on dark favicon is not easy to see. Since rust and the rust documentation also have this particularity, it's hard to find the tab among  the rust other ones.

  Not really important, but if it is cheap to fix that would help :)

  My tabs right now:
![image](https://user-images.githubusercontent.com/2663407/81685954-91a89980-9458-11ea-9f75-1f173ca34c46.png)

**Comment by iHiD** [comment]
Thanks :)

**Comment by SleeplessByte** [comment]
@iHiD consider https://blog.tomayac.com/2019/09/21/prefers-color-scheme-in-svg-favicons-for-dark-mode-icons/ and adding a glow, or mask background (https://derk-jan.com).

**Comment by FabienTregan** [comment]
I didn't do deep tests with `prefers-color-scheme`, but for me it seems to only detect OS setting (which matches the description on MDN)

I don't think many people (at least under windows) use it and most will just install a dark theme on firefox. I guess glow / mask background is a safer option (but don't have any numbers to back this).

**Comment by SleeplessByte** [comment]
I think the future is that those themes will come with a "this is a dark theme" flag, or even better, browsers will do a luminescence check (e.g. `0.299*R + 0.587*G + 0.114*B` or similar).

Good that at least dark mode windows solves it for GH tabs :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
