### ISSUE TITLE
Issue on web page while generating token for python exercises

### ISSUE THREAD

**Issue by saurabh896** [exercism/exercism#5285]
I got the following error when I tried to generate a token.
PFB image for the same.
![Capture_execr](https://user-images.githubusercontent.com/8954341/81838341-9efe7a80-9563-11ea-8f95-f23ef005fa29.PNG)

**Comment by iHiD** [comment]
@saurabh896 What do you mean by generating a token?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
