### ISSUE TITLE
Show concepts on the track details page

### ISSUE THREAD

**Issue by andreferrazz** [exercism/exercism#5287]
I think it would be great if i could see all the concepts involved in the exercise alongside the title of the track.

It would be like the card on the track list page, but on the details page there is more space, so I thought someone could put the whole list of concepts there too.

It is not an essential feature, but it would be nice!

**Comment by SleeplessByte** [comment]
This is coming in the next version!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
