### ISSUE TITLE
The "Still Stuck" resource links vary in location depending on context.

### ISSUE THREAD

**Issue by Makebuildmodify** [exercism/exercism#5292]
The resource links move and are omitted depending on the context of the user.

Example: 
"Still stuck
- These guides should help you.
- Installing Perl 5
- Running the Tests
- Learning Perl 5
- Useful Perl 5 Resources
- Remind me how to set up the CLII'm not sure where or who to give feedback"

Interesting thing, while in practice mode and after asking for mentor help for a specific exercise, the "still stuck" section is not available for that particular exercise (gets replaced by mentor discussion). I had to go to another exercise that I had not worked on to find it.

When in practice mode the main exercise selection is tiled without the "still stuck" information. But when in mentored mode the tiles move to a linear orientation and the "still stuck" is on the right-hand side.

It would be great if the "still stuck" links where inside the "instructions" tab or maybe they could have their own tab alongside the "instructions", "test suite", and "solution". Maybe a tab that's called "resources" or something like that?

Thanks!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
