### ISSUE TITLE
Configure Mentor tracks button

### ISSUE THREAD

**Issue by rajkumarGosavi** [exercism/exercism#5303]
If a mentor wants to configure their tracks then there is not a button available in the mentor dashboard for it.
The way I configured was 
1. Open the mentor guideline
2. click on configure the tracks

Is it possible to add a link in the mentor dashboard to do it directly?

**Comment by kotp** [comment]
I am making some assumptions here, as I am not sure what is being referred to… but [Configure your mentor settings](https://exercism.io/mentor/configure) (which has the unfortunate browser title of Mentor Dashboard) is what I think you are referring to?

Can you show or describe where you would want that button to be?  And what it looks like currently?

**Comment by rajkumarGosavi** [comment]
1. Click on the user image you will get a dropdown
2. Click on Mentor Dashboard link
3. You will now be on `https://exercism.io/mentor/dashboard/your_solutions` this route. Which is not same as `https://exercism.io/mentor/configure`
4. As far as I can see there is no link or button available that will take you to `https://exercism.io/mentor/configure` this route

**Comment by kotp** [comment]
If one click on "Mentoring Faqs" in the footer, it takes you to that page, and from that page, is the link to get to https://exercism.io/mentor/configure.

I am not sure that will change any time soon, due to the V3 work being done, and this will change.

So there is no direct link, and since it is something that you won't change that frequently, having it linked from the first page and referenced in the "second" level is probably OK.

It is also in the directions from Start Here on how to get that those settings.

**Comment by iHiD** [comment]
@rajkumarGosavi Thanks for pointing it out. As @kotp says I'm not currently adding things to v3. However, as it's so simple I've just done this via f84be707d0f2fc5085f4112082dd19fe53e57942

**Comment by rajkumarGosavi** [comment]
Thank you @iHiD  and @kotp . Although it was so simple my aim was to let the team know about it.
