### ISSUE TITLE
Worried submission fell through the cracks again

### ISSUE THREAD

**Issue by vmarchitect** [exercism/exercism#5305]
In the Kotlin track I have a submission that has been waiting for 186 days now. I know it has been quite some time since it dropped to 0 ahead in the queue but I still haven't received any feedback on my submission. I'm not quite sure what I'm doing wrong as this appears to happen fairly frequently to my submissions. Would love to get this resolved so that I can stay mentored through the course.

Here's my solution for the Flatten Array problem: https://exercism.io/my/solutions/fcddbc66d0294ee38596529491cc840f

**Comment by iHiD** [comment]
I've pinged the Kotlin mentors. It seems we're lacking anyone that's actually submitted that exercise themselves for Kotlin, who's actively mentoring right now.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
