### ISSUE TITLE
Keep getting unhandled exception when I try to run my projects

### ISSUE THREAD

**Issue by JAW1** [exercism/exercism#5314]
Hi, I keep getting an unhandled exception error when I try to run my projects, I'm not sure what to do. 
Here's what it says:
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f.......' or one of its dependencies. The system cannot find the file specified.

-->

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\Jakew
Workspace: C:\Users\Jakew\Exercism
Config:    C:\Users\Jakew\AppData\Roaming\exercism
API key:   0968*****************************5c1

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 90.2928ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 882.8979ms

If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
