### ISSUE TITLE
Push my code to Github

### ISSUE THREAD

**Issue by ekemi** [exercism/exercism#5326]
I am new to programming so I was wondering how to push my code once passed to Github.

Thank you!

**Comment by NobbZ** [comment]
Your `exercism` solutions you mean?

Create a repository at GitHub.com, initialise your local folder as a git repo (either in the workspace or per language, thats your choice), `git remote add origin …` as described on the GitHub empty repo page, `git add` changed files, `git commit` them, and finaly do `git push origin master` to get the stored commits to GitHub.

The workflow is not different from any other GitHub project.

**Comment by iHiD** [comment]
And for added clarity, you don't push your code to GitHub to get it to Exercism, you push it to Exercism using `exercism submit ...` (Just in case you're confused)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
