### ISSUE TITLE
Workspace not being created

### ISSUE THREAD

**Issue by francescoZ93** [exercism/exercism#5327]
Version of exercism: 3.0.13
OS: Windows 10

configuration --> home:          C:\Users\f***
                             workspace:  C:\Users\f***\Exercism
                             config:         C:\Users\f***\AppData\Roaming\exercism

the folder Exercism, in that path, doesn't exist. Why?

**Comment by NobbZ** [comment]
It should be created once you `exercism download` for the first time.

**Comment by francescoZ93** [comment]
If i download one exercise with the command exercism download --exercise_name, it create a folder with only that exercise for the specific language. On the other pc, when i had installed Exercism for the first time, it created a folder called Exercism in the workspace's path. This time i haven't a folder called Exercism in the workspace's path.

**Comment by NobbZ** [comment]
There is no `--exercise_name` flag for the `download` subcommand.

To download an exercise, you have to either use `--uuid` or `--track` + `--exercise`.

Either should download to `$(exercism workspace)/$track/$exercise` and create folders along the way.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
