### ISSUE TITLE
Enhancement to /my/tracks

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5335]
Enhancement suggestion. On https://exercism.io/my/tracks include in each track's box an icon to indicate stage and progress. 

Currently I have 16 tracks that I'm working in (daft I know.) I have to click on each track and scroll down to see where I'm up to. 

It'd be nice instead to be able to look at the tracks page and see, for example, 
 - that I've finished 5 challenges in Crystal but the sixth is still in progress (and hasn't been touched for 10 months); 
 - that I'm in progress on the 7th C challenge; 
 - that I've submitted the 6th challenge on PHP but am waiting for the mentor.

**Comment by iHiD** [comment]
Thanks. We'll be making changes among these lines for V3 :)

Keep an eye out for the beta and we'd love your feedback on progress then :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
