### ISSUE TITLE
Could the solution page be more readable?

### ISSUE THREAD

**Issue by BrianMcKeever** [exercism/exercism#5336]
![image](https://user-images.githubusercontent.com/1056904/87855059-0d98e500-c8d3-11ea-8dfc-47a96a7a209c.png)

I'm trying to learn from this solution. The code is cut off despite 2/3rds of my screen being white space. There is no obvious way to scroll the code horizontally. The horizontal scroll bar is 3 pages down.

I would make the two column layout a one column layout with the "What can you learn from this?" blurb stacked on top.

**Comment by endlesslycurious** [comment]
I have a similar issue on a 4k monitor (on a Mac in Safari or FireFox) the code solutions are ~540 px wide, the rest is white space and the 'What can you learn from this solution?' box!

![image](https://user-images.githubusercontent.com/61634041/90417177-4231c500-e068-11ea-8ed1-e410fa924b9b.png)

This seems quite unfriendly if the intent is for the user to learn anything from non-trivial code with comments.

**Comment by NobbZ** [comment]
In your [preferences](https://exercism.io/my/settings/preferences/edit) you have "Code viewing options" at the bottom of the page. There you can enable "full with code panes", this will still leave the space on the right to have an editbox for comments as far as I remember, but allow the pane to grow to the left. That way reading experience is usually a lot better.

**Comment by BrianMcKeever** [comment]
Well, that solves my issue, but I never would have thought to look there.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
