### ISSUE TITLE
Submit code incorrect on leap.js

### ISSUE THREAD

**Issue by EmilyBonar** [exercism/exercism#5340]
The copy-able console command reads "exercism submit /path/to/file [/path/to/file2 ...]" instead of "exercism submit leap.js".

![Screenshot_2020-07-21 JavaScript Leap Exercism](https://user-images.githubusercontent.com/15078396/88101213-4cdd6500-cb63-11ea-90f2-2280d4833157.png)

**Comment by NobbZ** [comment]
That is just an example that you have to modify to suit the actual names of the files. It is not meant to be used as is.

**Comment by EmilyBonar** [comment]
I thought that for a previous exercise it included the actual name, but now I can't see it. Regardless, I believe it would be an improvement if it was able to be used as is. The "copy" button implies as such, since the download text is usable as is.

**Comment by kotp** [comment]
Yeah, this is definitely broken.  @iHiD

**Comment by kotp** [comment]
It effects all tracks that I have checked, not just JS.

**Comment by iHiD** [comment]
@EmilyBonar Thanks for the suggestion :)

@kotp I mean, it's not broken. It does exactly what it's been coded to do :)

Everyone: We currently have nothing in the system that tells us what the filename that people should submit is, so this isn't something we can currently do. That said, in v3 all exercises are required to have stubs, and the file names specified in the exercises config.json file so we **can** do this for v3.

**Comment by kotp** [comment]
Ah, so used to mentoring that it does populate the exercise.  Looking at it in the wrong context.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
