### ISSUE TITLE
Deplyment script for tracks

### ISSUE THREAD

**Issue by elyashiv** [exercism/exercism#5342]
Is there a way to run a script on deployment for a language track?

Some tracks will benefit from organizing the code in github differently from the way the website wants exercises to look. Examples:
1. c/cpp track come with files for the testing framework, that should be the same for all the exercises. If one wants to upgrade the version, he needs to change it for all exercises, and make sure they are all upgraded.
2. Some tests can be auto generated from the specification, allowing for a easier upgrade of the problem set.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
