### ISSUE TITLE
Enhancement to /my/tracks/{track}

### ISSUE THREAD

**Issue by Rustery** [exercism/exercism#5343]
Enhancement suggestion. 
Every time on https://exercism.io/my/tracks/{track} I'm scrolling down just to visit my last changed core exercise. 

It'd be nice just have somewhere on site header something like a link "Current exercise of the track" and to be able to click on it for moving to exercise solution page.

**Comment by iHiD** [comment]
We'll be making this easier with the new dashboard in V3 :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
