### ISSUE TITLE
Enhancement suggestion

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5346]
An extension to the command line tool which removes everything except that which the programmer has written. So it deletes all the cruft added by dotnet, npm, yarn, and the other testing frameworks. This saves a lot of hard disk space but keeps the sources available should the programmer wish to refer back to them.

**Comment by iHiD** [comment]
I like this idea. It would almost certainly need things maintained by the individual tracks. They could run through the CLI maybe, but as a first step it might also be easier to have them written as track-scripts for each language.

**Comment by workingjubilee** [comment]
Someone mentioned that the JS track could help a lot with this by pushing `pnpm` as the preferred package manager. I agree with this, though I say that as a not-a-maintainer of JS, merely an at-times-webdev, so my opinion should be considered marginal.

I would speculate that for many tracks it's going to be more about generating useless intermediate binaries and cleaning those up. Those langs always have an equivalent to `make clean` but having it run over the entire `~/exercism/${track}` subfolder could be something the CLI (or a script) does. For Rust, at least, the Cargo.toml is important since it provides dependency versions on the handful of exercises which involve those. The Cargo.lock could be discarded, but it would have to preserve the source and the Cargo.toml.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
