### ISSUE TITLE
Studio for EXERCISM suggestion

### ISSUE THREAD

**Issue by hgvanpariya** [exercism/exercism#5348]
Hi All,

If there is a EXERCISM studio will be created with eclipse RCP, then it will be really helpful to the users. They can just download the studio, select the problem statement and studio can provide the environment to run and test the code.

**Comment by iHiD** [comment]
Sure! Want to make one? :)

**Comment by hgvanpariya** [comment]
yes, Shall I start creating one ?

**Comment by hgvanpariya** [comment]
I can start with Java first and then scale for other languages...

**Comment by iHiD** [comment]
Sounds good! I know nothing about eclipse. If you email me at jeremy@exercism.io I can add you to our slack where you can ask the community for help :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
