### ISSUE TITLE
Not Able to execute.

### ISSUE THREAD

**Issue by codeofsid** [exercism/exercism#5349]
I have installed CLI and Nodejs. Now i need to run "Hello World" Program. Im not able to run the program. Please guide the STEPS or PROCEDURE to run the Hello world program and Execute it.

**Comment by kotp** [comment]
There should be no need to execute the `hello_world.js` program.  The `README.md` states to run `npm test` instead.

The readme is delivered with the exercise locally, but you should also be able to read the "Instructions" tab on the website, which should show the same information.

Let us know what you have tried, what you expect to happen, and then what happened.  We should be able to help you out.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
