### ISSUE TITLE
Update 'new notification' icon in real-time

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5350]
When I open the notification menu in a new tab and read all the notifications, the red icon is not updated until I refresh the page that I originally opened the menu from. It would be nicer if this was updated in real time (real-time? realtime? 😬), like on GitHub for example.

**Comment by SaschaMann** [comment]
I can't try it out but I suspect the reverse (you receive a notification while viewing a page and the icon is not updated) may also be true.

**Comment by cmcaine** [comment]
> I can't try it out but I suspect the reverse (you receive a notification while viewing a page and the icon is not updated) may also be true.

This is true.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
