### ISSUE TITLE
Mark notifications as unread

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5352]
When I click on a notification on exercism.io, it will mark it as read and remove the red dot from the icon. I'd like to have an option to undo this, in case I read a comment, that I, for whatever reason, can't respond to immediately upon reading it.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
