### ISSUE TITLE
Editor lacks a preview when editing a mentor comment

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5356]
see above. Would be useful for fixing formatting issues.

**Comment by iHiD** [comment]
(keep firing these here and I'll keep labelling them)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by bobahop** [comment]
I'm in favor of this issue being reopened.

**Comment by SaschaMann** [comment]
Test
