### ISSUE TITLE
Add some guidelines about how to solve exercises

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5357]
https://github.com/exercism/problem-specifications/pull/1665#issuecomment-669161707

As the others have said, this sounds like something worth doing on a track-specific level, or actually probably a wider problem with Exercism not making clear the "rules" around submitting things (as @cmccandless alludes to). I think my take on this is that it's worth us having a "guidelines" doc for people using Exercism which explains these sorts of things, which we point people to, rather than adding the line in every exercise. Thoughts on that?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
