### ISSUE TITLE
Allow students to view locked exercises

### ISSUE THREAD

**Issue by p-ku** [exercism/exercism#5358]
i find it kinda frustrating that I can't view future exercises on the Mentored track. Locked could still prevent submission, but why not get started on the next exercise while I wait on feedback?

**Comment by iHiD** [comment]
> but why not get started on the next exercise while I wait on feedback?

Because generally that leads to students carrying their misunderstandings over into new exercise they're working on.

But I totally hear your pain, and all this is changing in v3 of Exercism.

**Comment by p-ku** [comment]
Understandable. It would assume some discipline. I know for me the feedback has can fundamentally alter my approach. Frustration is certainly possible, but lessons learned could still be edited in before submitting the next. Thanks for the response!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
