### ISSUE TITLE
Mentor slack email

### ISSUE THREAD

**Issue by elireiner** [exercism/exercism#5364]
How can I access the mentor slack channel? When I click on [this link](https://exercism-team.slack.com/messages/CARRG4MNC) and enter my email I get an error message 'incorrect email'.

**Comment by iHiD** [comment]
If you have signed up to be a mentor on the website, you'll have recieved an invite at whatever email address is registered on Exercism. If you email me directly (jeremy@exercism.io) from the email you want to use I'll invite you.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
