### ISSUE TITLE
Is the Python Track still active?

### ISSUE THREAD

**Issue by drbazpython** [exercism/exercism#5373]
It's been 2 weeks since my submission and no feedback. Indeed it seems that there's very little going on right across Exercism

**Comment by glennj** [comment]
It's a very busy track, current queue size is 600. Which exercise did you submit?

In general, the work on exercism v3 is pulling some people away from mentoring.

**Comment by drbazpython** [comment]
The Hamming Exercise

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
