### ISSUE TITLE
Allowing a student to cancel mentoring request, whenever.

### ISSUE THREAD

**Issue by bid0uille** [exercism/exercism#5376]
I'm not sure about that, because I can't really test from student point of view. For what I know:
- a student can cancel a request by clicking the suitable button, as long as no mentor began to review it;
- a student can complete a core exercise without mentor approval, as soon as a mentor began to review it.

It seems to me a student can't cancel a request if a mentor began to review it, and that he can't complete a side or pm exercise. I'm not sure about that but OK, let's see precisely my concern here. To  change my mind from core, while cleaning a bit the queue, I began to mentor very old solutions (1+ year) from side. Most of people don't answer (that populate my "stale" queue and that's OK). Some answer their still interested, and that's satisfy my first goal. But some answer they don't need to be mentor anymore. From there, we can't go out. They don't see any button to cancel nor complete. I obviously can't approve if it doesn't deserve it, and if I leave discussion their solution go back on the queue, then it looks like they still can't cancel the mentoring request, defeating the second goal.

PS: I feel concerned about that for some week, but I'm pretty sure the v3 will better handle that case, so I delayed about this "issue". Now, I'm wondering if that's an easy change, and also to me it's related to another "issue" I'll raise previously.

**Comment by iHiD** [comment]
Thanks 🙂  We'll fix this in v3. I'll label this appropriately.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
