### ISSUE TITLE
Feature Request: Filter Old Solutions 

### ISSUE THREAD

**Issue by jmahmood** [exercism/exercism#5379]
I have been using and enjoying Exercism for the past few weeks while learning about Rust.

The community solution page, in particular, is interesting and provides us with a rich historical context of how solutions may have been done in the past.

However, for a rapidly evolving language like Rust, the top responses (star-wise) are usually not very relevant to the language anymore.  That is nothing against the student who implemented them; the solutions are usually creative and involve overcoming limitations of the language at the time they were created.

I would love for a date-based filter function, so I could more easily determine which solutions had been updated after the release of a new version of the Rust compiler.

**Comment by iHiD** [comment]
Hey 🙂  Thanks for your thoughts. This is currently something we're working on for #v3 of exercism. We're taking a first stab at improving the page to show things like how fresh the exercises are (and whether they currently pass the tests), as well as showing which different ideas and concepts different solutions use. Hopefully this will take some big steps forward in making the right content more discoverable, but I imagine this will be a very active area during 2021 in general.

(cc @taiyab)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
