### ISSUE TITLE
Command prompt| Syntax Error|Js

### ISSUE THREAD

**Issue by tirado646** [exercism/exercism#5382]
Hello, 

I'm running in to an issue uploading to the command line when using template literals but when I use string concatenation & remove "export" everything works accordingly. any suggestions? 
 
![image](https://user-images.githubusercontent.com/68622928/94600854-8e277a80-0260-11eb-8038-ff09b004f83e.png)

**Comment by glennj** [comment]
Did you read https://exercism.io/tracks/javascript/tests ?

**Comment by tirado646** [comment]
Hey Glenn, so I ran a npm test and got a whole bunch of errors. Did I do something wrong while setting up? 
![image](https://user-images.githubusercontent.com/68622928/94634719-c8177180-029e-11eb-8be0-dd28a10ebec9.png)

**Comment by NobbZ** [comment]
You need to run the `npm run test` from within the exercises folder.

`C:\Users\nicho\Exercism\javascript\two-fer` should be the correct folder. You might also need to run `npm install` once per exercise.

Also please copy and paste code and terminal outputs. They are easier to read even on mobile. You can use markdown code-fences within GitHub comments to mark them as code:

````md
```plain
In such a block goes your terminal output
```

```js
// and in such a block with a "js" caption, the javascript code
```
````

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
