### ISSUE TITLE
Finding learning paths on Exercism.io Python track

### ISSUE THREAD

**Issue by sgcoding2016** [exercism/exercism#5391]
Hi Exercism, how can I find learning paths on Exercism.io Python track? I'm trying to find OOP challenges.

**Comment by glennj** [comment]
On the [python track](https://exercism.io/my/tracks/python) page, jump down to the [side exercises](https://exercism.io/my/tracks/python#side-exercises) -- there you can filter by Topic: "classes" seems to be the OO topic

If you're in Practice mode, the Topic filter should be right at the top.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
