### ISSUE TITLE
Proposal: Drop "5" from Perl track

### ISSUE THREAD

**Issue by m-dango** [exercism/exercism#5392]
We had a previous discussion regarding the renaming of the language formerly known as Perl 6 (https://github.com/exercism/exercism/issues/5099) and the subject of renaming Perl 5 came up.

Keeping the 5 made sense at the time, but things have since changed and now Perl is headed for some more exciting changes: https://www.perl.com/article/announcing-perl-7/

Perl 7 is described as being mostly Perl 5.32 with saner defaults, and I don't think such a similarity would warrant a separate track, so perhaps the time has come to consider what to do with the track name?

Any thoughts from others in @exercism/perl5 ?

**Comment by iHiD** [comment]
Naively makes sense to me 🙂

**Comment by mienaikage** [comment]
Waiting until a release candidate is available is most certainly the best idea for now before making the decision, but I wanted to get a head start on the discussion so that others can give input on the possible future of perl track(s).

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
