### ISSUE TITLE
Error: Failed api

### ISSUE THREAD

**Issue by Muhammad-Muazzam** [exercism/exercism#5395]
Hi there how are you i am here to need your help i am downloading an exercise for exercism but it cannot download it and cannot run it and generating error the error is following
" Error: failed to parse API error response: invalid character '<' looking for beginning of value
exit status 255 "
kindly inform me about this if any of you have any idea about this.
THanks

**Comment by glennj** [comment]
Have a look at the Troubleshooting section of https://exercism.io/cli

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
