### ISSUE TITLE
Feature request: search past conversations

### ISSUE THREAD

**Issue by tomerarnon** [exercism/exercism#5397]
I'd love a way to search through my own past replies. Sometimes I will write a very detailed response to a question, only to have something very similar show up a week or so later. The community mentor notes are great way to store some of these things (and I use them extensively!) but some questions about the language are not exercise specific and can show up anywhere, but I find myself mentioning them often enough that I wish I could copy-paste a past reply.

Maybe my mentor workflow isn't dialed in yet, but what I've started doing is creating local .md files with some pre-canned, in depth, replies to avoid "burnout" (i.e. to prevent one student getting excellent feedback when I'm feeling fresh, and others getting progressively poorer and poorer feedback as I get bored of repeating myself).

**Comment by iHiD** [comment]
Hi @tomerarnon. Thanks for the ideas!

In v3, we'll be providing a "notes" section inbuilt to replace your local .md files, so that should solve that.

We've not put a "search old replies" in yet, but it's in my mental roadmap of a feature to launch in like v3.1 etc.

Thanks for mentoring! 💙

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
