### ISSUE TITLE
bug: Clicking "Review this solution" then immediately leaving conversation artificially inflates weekly progress

### ISSUE THREAD

**Issue by DjangoFett** [exercism/exercism#5402]
Urgency: Minor
In the mentor dashboard when you drill down into a students solution, you can click to review there solution and immediately leave the conversation to inflate stats. To be considered a mentored solution the metric should check that any comments were posted.

**Comment by kotp** [comment]
> hat any comments were posted.

Maybe, even by a mentor.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
