### ISSUE TITLE
ReAdd Powershell track

### ISSUE THREAD

**Issue by jrdnr** [exercism/exercism#5406]
I use Powershell all the time and would love to be able to point people who want to learn powershell to something like an Exercism style way to learn powershell. Poking around a little bit I see there used to be a powershell track.

What would it take to get the powershell track back up and running?

**Comment by iHiD** [comment]
Hello 🙂 

Adding another 10 or so exercises I think. If you're serious about helping, I can add you to our Slack and you can discuss with other maintainers?

**Comment by jrdnr** [comment]
Yes, that would be great. I'd be glad to look at the possibility of
building out more exercises.

**Comment by iHiD** [comment]
Great. If you could email me at jeremy@exercism.io I'll get you added :)

**Comment by endowdly** [comment]
I'm also willing to help write exercises if necessary!

**Comment by iHiD** [comment]
Great. Email erik@exercism.io and he can get you set up :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
