### ISSUE TITLE
Waiting for mentor on Kotlin track for 2 weeks with 0 ahead of me

### ISSUE THREAD

**Issue by AmitaiMyers** [exercism/exercism#5410]
Ex: Two Fer
User: 2438

Thanks

**Comment by glennj** [comment]
I'll look at it.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
