### ISSUE TITLE
Mentor needed on Python track. I've been waiting for 29 Days

### ISSUE THREAD

**Issue by YonatanMyers** [exercism/exercism#5413]
user: yonim
Ex: Lunh
I handed the ex in on Oct/10 and I was ~9-th in line on the Ex. It has been 29 days I've been 0-th in line for a number of days.
I've done all the side ex-s that look interesting to me. PLEASE have a look at my Ex and let me continue.

**Comment by kotp** [comment]
To make it easy to look at, feel free to provide the link to the exercise.  I have notified the mentors of this issue.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
