### ISSUE TITLE
Cannot download student solution for someone I'm mentoring

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#5418]
```bash
$ exercism download --uuid=30524e870eb24ed7906567f1c433cdbb
Error: You do not have permission to view this solution
```
This is in my mentor dashboard as "Requires action from you".

I see no visual indication on  https://exercism.io/mentor/solutions/30524e870eb24ed7906567f1c433cdbb that there's any difficulty, except that if I try to enter a comment, clicking the Comment button has no effect (looking at the console, it returns with 403 Forbidden).

What's going on?

**Comment by iHiD** [comment]
Can you check you still have bash as a selected track on https://exercism.io/mentor/configure pls?

**Comment by glennj** [comment]
Right, that's it. I hop on and off that track.

**Comment by glennj** [comment]
I'm not a rails developer, but I see where it's returning 403 in https://github.com/exercism/website/blob/master/app/controllers/mentor/discussion_posts_controller.rb

It would be nice UI to have a little label show up explaining why "nothing happened", like "You can't comment because you're no longer mentoring this track"

**Comment by iHiD** [comment]
Yeah, good point. I'll add it to the TOODs for v3.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
