### ISSUE TITLE
Please include 1 sample input/output

### ISSUE THREAD

**Issue by SoulNinja-dev** [exercism/exercism#5420]
I am doing the java track, and the ones I've done till now, do not have sample input-output. 
It would be amazing if there was one sample input-output

PS: I am willing to include those for the track 🖐🏻

**Comment by kotp** [comment]
That's great to hear.  If you are going to develop these, you may want to create the issues in [exercism/website-copy](https://github.com/exercism/website-copy) as that is where the mentor notes reside for each track.

**Comment by kotp** [comment]
Sorry, I mistook the sample input-output as mentor notes.  Doesn't the tests serve the purpose of the required input/output for the exercises?  The README.md file that is delivered should give some as well.

**Comment by SoulNinja-dev** [comment]
Nah, in the ones ive done till now, the questions dont seem well put up. The questions are nice, but i wish there were more sample input/outputs.

**Comment by glennj** [comment]
I have to agree with kotp here: this is exactly what the tests are. Which exercises have you done, and how do the tests fail to provide sample input&output?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
