### ISSUE TITLE
Analyzers: CI for comments

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5421]
I would like each analyzer to have a CI check that compares the comments used in the analyzer repo to the comments on master in website-copy. It should fail if any of the comments used in the analyzer are not in website-copy (ie, website-copy changes have to go down first). 

If we agreed config for the analyzers, I think we could write one CI "bot" that would work for all the analyzers. I'm thinking maybe we have a file at the root of the repo called "comments", which lists one comment slug per line. This could then be compared to the files in the website-copy repo.

Tracks could then implement bespoke CI checks that that file is correctly populated based on the values that their analyzers actually use.

I have no experience in how to do this, but I think it could be done along the same sort of lines as the [CI tests for website-copy](https://github.com/exercism/website-copy/blob/master/Rakefile). 

So two things:
1) People's thoughts/ideas/improvements please.
2) Would anyone like to take the lead on creating a Rakefile that we could use generically?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
