### ISSUE TITLE
Analyzers: Standardize Analyzer Tests

### ISSUE THREAD

**Issue by tehsphinx** [exercism/exercism#5422]
When it comes to analyzers producing comments I consider this a very good case for TDD. Tests for exalysis do this by taking real life solutions and defining which comment to add or not to add.

Should we generalize that accross analyzers or leave that up to the implementers?

I would vote for generalizing that so that contributors outside the specific analyzer team can easily add a new case to be covered by the analyzer.

Here my suggestion:
- Have a folder per exercise with one subfolder for each sample solution
- have a `cases` file in each exercise folder with a list of which solution folder should provide/not provide which comment. The format could be language specific (like the tests are) or language agnostic (e.g. JSON, YAML).
- location of actual test is left up to the analyzer team.

Folder structure:
```
- tests
   | - twofer
        | - solution1
        | - solution2
        | - solution3
        | cases.json
   | - hamming
        | - solution1
        | - solution2
        | cases.json
```

Here a sample of how exalysis does it currently: https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer_test.go

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
