### ISSUE TITLE
Command Prompt.

### ISSUE THREAD

**Issue by charlierdm** [exercism/exercism#5423]
Hi there,

I have followed the tutorial video to get started but I am confused as to a few things. 

In command prompt (running win10), I do not see the same information that is displayed when running, or looking into the files, which are crucial for being able to complete the challenges.

For example, when looking inside the first test file, I only see the file size, whereas in the video the files inside are displayed which says it requires a certain file, how am I supposed to know to make that file if I can't see it?

Also it says that in that first example, more information is displayed within the terminal when running the initial file, but I do not see that either.

Please could you help get this up and running. Am I missing something in Command Prompt (new to me), or is there an alternative piece of software I can use?

I am following this for Makers course and they are emailing me every few days to do certain tasks so I'd like to get going with this asap.

Many thanks in advance

**Comment by kotp** [comment]
Makers course has your e-mail and I am not sure how they are incorporating this site with your course. It isn't that I won't help, but they may be set up to more directly help you in terms that you are using this site with.

But, if you would like assistance with this here, can you show what you have tried, so we might help you out?  I am not understanding what you see when you say that you see a file size rather than content.

I am not sure what video tutorial you have watched, so a link there might be helpful as well.

Stop in to the [gitter support channel](https://gitter.im/exercism/support) and ping us there, we may be able to help you out a bit more "synchronously".  Please supply details as requested above as well, so that when we do see it we are ready to understand what the situation is and we can help you out right away.

**Comment by kotp** [comment]
And also, thanks or creating an issue here, as well.  You did right doing so, just to be clear I am not trying to pass you off to the makers folks.  I am just not clear as to how that fits in here.

**Comment by kotp** [comment]
Closing issue, as per request from poster via e-mail.

Unable to delete issues.
