### ISSUE TITLE
Clarify where to open website issues

### ISSUE THREAD

**Issue by corneliusroemer** [exercism/exercism#5433]
I'm confused as to where to open issues related to the current website. In particular, I don't understand the difference between this repository and the exercise/website-copy one.

This description in the Readme.md is not self-explanatory to me. Please make it understandable to people who are not acquainted with your dec cycle.

![Screenshot_20201211-174056~2.jpg](https://user-images.githubusercontent.com/25161793/101930536-91cc6b80-3bd8-11eb-8202-1ed8fdb03cbb.jpg)

Also, under the v3 heading I don't understand the meaning of the sentence "We are not accepting contributions to the website at this time."

I think this should all be cleaned up and made clearer to first-time visitors.

**Comment by iHiD** [comment]
Hello. I'm not sure how to make it clearer as it all feels clear to me. I'll explain what it means and then you can maybe submit a Pull Request wording it better?

1. All of the copy for the website is stored in the `website-copy` repo. So if you find typos or copy that could be improved, then it should be fixed there.
2. All other things relating to the current website (e.g. bugs) should be reported here.
3. We're not accepting contributions to version 3 of the website - it has a specific team working on it

Which of 1/2/3 doesn't make sense?

**Comment by corneliusroemer** [comment]
@iHiD Thanks for your clarifying comments. That's really helpful for me.

Let me explain where I think the current wording isn't clear (to me):

1. I didn't get that `website-copy` *contains* the *copy*, i.e. text/content, of the website in contrast to the *code*. My first thought was that it *is* somehow a *copy* of the website repository, like a release version or something. It may be an ESL issue, but I lived/studied in the UK/US for 4+ years, so if the wording isn't immediately clear to me, I can imagine it isn't to a lot of others.

2. Got it, so it's typos/content issues in `website-copy` and `layout/logic/code` in `exercism`.

3. V3: The main distinction here seems to be website code vs website content. For the code you don't need help, but for the content you do.

Recap:
With your explanations, and reading the main repo Readme, things are pretty clear now. What could be improved is the Readme of `website-copy` pointing people to the main repo for most issues. I don't know why, but I somehow hit the website-copy repo first and opened two issues there that actually belong on the main repo. So what's really missing I think is a pointer from website-copy Readme/Issue-template -> main-repo. 

Plus, it'd be good if content was used in addition/instead of copy as content seems to be less ambiguous a word, especially for non-native speakers.

I'll see how I can operationalise these suggestions in PRs.

Lastly, I don't know how common it is that people open issues in the wrong repo, but do you periodically scan Issues for wrong classifications and move them from one to the other? For example these two issues of mine should be moved. Issue-movement should be cleaner and easier to do than closing-reopening. I'm thinking of these two of mine for example: https://github.com/exercism/website-copy/issues/1840 and https://github.com/exercism/website-copy/issues/1841

Just glancing through other website-copy issues, I noticed that most issues are mis-classified and actually belong in this repo. Maybe someone could clean up.

**Comment by iHiD** [comment]
@corneliusroemer Thanks for the update and for triaging those issues. PRs to make things clearer in both repos would be appreicated :)

**Comment by corneliusroemer** [comment]
@iHiD Happy if I can be of some help.

Before I set out to improve documentation, may I ask what the reason is for having two issue trackers, one for the /exercism repo (which doesn't seem to contain any code) and one for /website-copy (which contains at least some code)?

I think the root cause of all confusion is that the main repo is code-empty and some devs may have the urge to put issues where the code is, and thus in the "wrong" place.

Seeing how little relevant issues /website-copy gets, would it not make sense to completely close it to issues, and route all issues straight to /exercism from which they can be triaged? It may be best to apply labels there. Then all is in one place and still somewhat ordered.

If you have good reasons to use the current system, sure, a rewording PR would go some way, but it may be worth looking at the root cause, too.

**Comment by iHiD** [comment]
There are ~250 repositories that make up Exercism, each with their own "Issues" that respond to things relevant to them. There are literally thousands of issues across those, each with a different team subscribing to them. (The exception for that is `website`, which we actively don't want to have Issues on, because experience shows that it becomes a total mess if we do). Putting everything in one place means that the relevant teams don't get the relevant notifications, or get spammed with loads of stuff that's not relevant to them. I don't mind people opening issues here and them getting moved to website-copy (or anywhere else), but I can't guarantee I find the time to do that, which makes it much more likely those issues will just get missed by the active website-copy (or other) team that manage that stuff. It's worth noting that there are only a handful of misplaced issues on website-copy. The vast majority end up in the right place.

I suspect the real solution is to have issue templates in `website-copy` with a generic one that has some placeholder text saying "Not related to the copy used within the website? Please open at exercism/exercism".

It's worth also saying that much of this might change as we launch v3 (in the next 2-3 months), so it's probably worth not putting too much effort in until that's finalised.

So for now, I'd suggest adding a note to the README, and maybe added/amending a CONTRIBUTING.md too. Thanks for trying to make this better 💙

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
