### ISSUE TITLE
Cannot complete Bash Lesson 1

### ISSUE THREAD

**Issue by JKracken** [exercism/exercism#5434]
I have not been able to get through the first lesson of bash scripting. I have created a "Hello World" file, installed bats, and am now trying to submit said work, but the system is saying the file cannot be found! This is incredibly frustrating, as any tutorial on lesson 1 is just to set up your command line. 

I'm using Git Bash. 

![exercism help](https://user-images.githubusercontent.com/33261988/102000616-4937af80-3cb7-11eb-9d05-fb3f3248db15.PNG)

**Comment by NobbZ** [comment]
The folder you are in is not the folder that I would expect to contain the exercise.

The exercises should have been downloaded to `$(exercism workspace)/bash/hello-world`, and from within that the `exercism submit hello_world.sh` would suceed, assuming you also solved the exercise within that folder.

The error though suggests, that your configured workspace is `C:\Users\Jon\Exercism` (which is the default for windows), but it does not exist yet, which again would mean that you haven't downloaded the exercise using `exercism download`.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
