### ISSUE TITLE
Dragging exercises from one track to another

### ISSUE THREAD

**Issue by RNA-Messenger** [exercism/exercism#5437]
I started in the practice track to browse a little and discover how this works. I passed to the mentored track and it dragged the medium level exercise that I was trying to view to the mentored track. Now, I don't really intended to go directly into doing a medium level exercise and I can't see any cancellation action that could get this exercise out of the track and it's listed as a second exercise in the track. So, now if I don't do it I can move forward but at the same time this exercise doesn't match the difficulty of the others. I jumped from a very simple "Hello World" to Pascal's Triangle.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
