### ISSUE TITLE
Feature request: show diff between iterations

### ISSUE THREAD

**Issue by NieDzejkob** [exercism/exercism#5438]
On some exercises further down a track (for example, Poker or Forth in the Rust track), the code starts becoming somewhat large (300 lines or so). At that point, mentoring on new iterations starts becoming somewhat tedious, since we have to either try to notice the changes made, or do some juggling in the command-line to "checkout" both iterations at once and diff them.

I'd like to suggest adding a button for showing the diff between iterations.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
