### ISSUE TITLE
[Feature Request] Add checkbox for "current version only" in community solution viewer

### ISSUE THREAD

**Issue by corneliusroemer** [exercism/exercism#5440]
After I solve and submit an exercise, I like to browse through community solutions to get inspiration for other approaches.

Often, those solutions that have been starred and/or commented on a lot are most interesting, which is why I often filter using the provided dropdown.

Unfortunately, due to exercise changes over the past few years, the most starred/commented solutions are rarely for the current version of the exercise. Sometimes changes are just cosmetic, but often they are significant enough to make the solutions non-applicable, e.g. using different types or methods.

I would like to be able to filter solutions down to solutions of the current exercise version at a click of a checkbox. This shouldn't be too hard to change and would improve UX a lot. Right now, my best workaround is to manually scan newest solutions for starred/commented solutions, but this is tedious.

Here are two screenshots to visually portray what I'm talking about:
![image](https://user-images.githubusercontent.com/25161793/100543483-c4797a00-3250-11eb-94e2-0ae3bccff347.png)
![image](https://user-images.githubusercontent.com/25161793/100543519-e70b9300-3250-11eb-9bd1-d27a98bf4e5a.png)

**Comment by anadayloft** [comment]
It could just be the track I'm in (rust), but it seems to me like *all* the solutions with stars are for old versions—something I see as a direct result of this feature's absence.

While there might only be a small number of solutions available when a new version comes along, this very lack provides an opportunity for newer users to be a part of the discussion. Without a need for people to participate, they won't! If this feature were implemented *and made default* (changing the proposed checkbox to "show older versions"), I think people would be significantly more likely to look through newer solutions and star or comment them then they are now, and we'd see a healthy influx of activity whenever a new version came along, which would enhance the learning process.

**Comment by iHiD** [comment]
@anadayloft Did you read my last comment?

**Comment by anadayloft** [comment]
I did! This is why my comment references the "small amount of solutions" issue (but from a perspective where it's a benefit), and proposes a change to the initial feature request (defaulting, "show older versions") that would take advantage of that benefit (without requiring rerunning old solutions to avoid the "small amount of solutions" issue/benefit).

**Comment by iHiD** [comment]
@anadayloft Thanks. So I'm unclear if you're suggesting defaulting to only showing new versions or showing all versions. I think the OP is defaulting to showing all versions (ie an unticked checkbox) and your suggesting having a ticked checkbox for "show all versions". So the effect would be the same, but you're inverting the checkbox and it's default. Am I understanding correctly?

The problem remains in my eyes though that, say for v3, every exercise will have changed on Exercism. So out of the millions of existing solutions, zero will be up to date. So toggling that checkbox takes you from millions to zero. And then there's no guarantee that any of the next 1,000 or so that appear in the subsequent days are any good. I think that makes the feature pretty suboptimal

---

All this said, we're adding the checkbox along with the option to only show solutions that have ever passed the tests, when we launch v3. By default we'll show all solutions that ever passed the tests, and users can toggle to only see the most up to date and/or ones that fail the tests too 🙂

**Comment by anadayloft** [comment]
Yeah, you're understanding. I do see how it would be a bit strange with all the exercises being updated at once, leaving quite the void—I hadn't considered that.

From a learner's perspective, having millions of solutions can feel the same as having none, unless meaningful solutions are brought to the front easily. This is especially true regarding the discussion features, where—I think—a smaller number of solutions which are not guaranteed to be best is an optimal environment for learning, as it encourages students to engage in continued discussion over each other's ideas.

It's good to know the versioning option will be implemented, either way. Thank you!

**Comment by iHiD** [comment]
> From a learner's perspective, having millions of solutions can feel the same as having none, unless meaningful solutions are brought to the front easily. 

Yeah - I entirely recognise the intention here and agree with it.

My concern is that these checkboxes are more of a "sticking plaster" for problem, rather than an actual solution. Our medium-term aim is to actually bring interesting solutions to the forefront using more intelligent metrics - such as static analysis as we're doing with analyzers and representers to find things that are unusual (or common). We're also taking a more manual approach and introducing "Approaches" - curated articles for each exercise that explore the different approaches people take and pull out interesting and cool varieties.

Learning from each other is a core part of Exercism's future and I probably feel a little defensive that we find proper solutions to the challenges of learning from millions of your peers, rather than skin-deep ones. But that said, that intention shouldn't get in the way of these shorter-term fixes making the site better today :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
