### ISSUE TITLE
Increase width of the code section of community solutions.

### ISSUE THREAD

**Issue by brianwyu1** [exercism/exercism#5441]
The most important content is the code itself and making it easily visible will greatly help.
The "What can you learn from this solution?" can just be put on top or below the code.

Just change the width from 50% to 100% will help a lot. Thanks.

@media screen and (min-width: 48em)
.pure-u-md-1-2, .pure-u-md-12-24 {
    width: 100%;
}

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
