### ISSUE TITLE
[Visual] Solution code box only 65 char wide instead of 80+, even on wide screens

### ISSUE THREAD

**Issue by corneliusroemer** [exercism/exercism#5442]
Reproduction steps:
- Use large screen with e.g. 2560px width
- Navigate to any solution website, e.g. a community solution: https://exercism.io/tracks/csharp/exercises/robot-name/solutions/72547020fea7444682692c902a9ee251
- Observe width of solution code box

Expected:
- Website takes advantage of large screen and shows at least 80 characters width of code (the standard width recommended by e.g. Python)

Observed:
- Only 65 characters are shown even on wide screens, making code less readable by forcing user to scroll

See screenshot 1: 
![image](https://user-images.githubusercontent.com/25161793/100542735-2edbeb80-324c-11eb-82b0-37154609059f.png)

Possible root-cause: `max-width` of `lo-container` is set at 1200px, making use of less than 50% of available screen width in wide screen case. Should probably be changed to a combination of max-width 80% and 1800px if 80% not hit on wide screens.

Here's how it looks like if I change the values myself through dev tools, needs some cleaning of higher up containers but shouldn't take more than a few minutes to fix.

![image](https://user-images.githubusercontent.com/25161793/100542831-d9540e80-324c-11eb-897c-6df3e67c2ac2.png)

Here are browser details:
```
Operating System Windows 10 (64-bit)
Web Browser Chrome 87.0.4280.67
Screen Resolution 2560 x 1440
Browser Size 2559 x 1342
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
```

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
