### ISSUE TITLE
Dart exercise Reverse String is skipping tests

### ISSUE THREAD

**Issue by Macaa23** [exercism/exercism#5446]
Hi,

I noticed that by default Dart's exercise ReverseString has all tests skipped but the first one, so some of the answers from Exercism members do not work when this problem is fixed.

**Comment by glennj** [comment]
This is discussed in the TESTS document: https://github.com/exercism/dart/blob/master/docs/TESTS.md

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
