### ISSUE TITLE
Rather quiet in crystal country

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5456]
```
There are currently 0 solutions ahead of this in the Crystal queue, and 0 ahead in the Raindrops queue. Learn more about how mentor queues work. 
```
It's been like that for quite a while

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
