### ISSUE TITLE
Challenge won't unlock in Javascript track

### ISSUE THREAD

**Issue by jschack94** [exercism/exercism#5461]
Hello--

I just completed the resistant color lesson and submitted, however the next track (resistor color duo) will not unlock. Can someone look into this for me?

**Comment by iago-lito** [comment]
@jschack94 Are you aware that you need to wait for a mentor to mark your solution as accepted for the next lesson to unlock on the main track?

Regarding side exercises, they progressively unlock as you progress on the main track.

Alternately you can choose the option without mentorship so you don't have to wait, but if this is what you did, then maybe there is a problem indeed.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
