### ISSUE TITLE
[Roadmap] Proposing a system design track

### ISSUE THREAD

**Issue by giorgiozoppi** [exercism/exercism#5463]
This is feedback on the v3 roadmap (#690).

The idea and what is really missing is a design track, a system design track. It is very important as well
with doing in code trial, this will enable trial code. With webassebly should be not so difficult support many languages directly in browser. See https://www.youtube.com/watch?v=5N4b-rU-OAA
I would volunteer such project if needed or we could ask to Matt Goldbot to integrate its compiler explorer.

**Comment by iHiD** [comment]
Moving to exercism/exercism as it's not a specific v3 thing :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
