### ISSUE TITLE
[Haxe] Bootstrap Haxe track

### ISSUE THREAD

**Issue by mfoda** [exercism/exercism#5464]
Hi @ErikSchierboom,

Please bootstrap the Haxe track! I'd love to see Haxe on exercism v3 :-)

**Comment by iHiD** [comment]
@mfoda! Hey! I've just seen all the amazing work you've done on the haxe track. Totally missed that :)

You'll be getting a load of issues opened automatically in the next hour to help you prepare for the v3 launch. 

@ErikSchierboom will also review a couple of your PRs to check they're all good, then we can give you lighter merge permissions. If you'd like to chat to us about this, please say hello on Slack!

**Comment by mfoda** [comment]
@iHiD Sounds great! I'll pick up from the haxe track then and read a bit more about how to get started.

Would definitely be great to join Slack to get help with the transition to v3. Is this the right [workspace](https://exercism-team.slack.com/)?  (it seems I'm not able to join directly)

**Comment by iHiD** [comment]
Drop erik@exercism.io an email and he'll send you an invite now :)

**Comment by mfoda** [comment]
Will do. Thanks!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
