### ISSUE TITLE
Am I able to add a Z3 track?

### ISSUE THREAD

**Issue by Newby555** [exercism/exercism#5472]
Hello, I am looking to add a Z3 language track to exercism. 

-Would this be possible/helpful? 

-How do I go about creating a new repository (exercism/Z3) for it? Do I need permissions from exercism?

**Comment by iHiD** [comment]
Hello. Thanks - we'd love you to add a Z3 track :)

You'll need to read the README and then open an issue at: https://github.com/exercism/request-new-language-track/#request-a-new-exercism-language-track

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
