### ISSUE TITLE
Elm in research website does not show debug output

### ISSUE THREAD

**Issue by vfsoraki** [exercism/exercism#5477]
I'm almost sure that my solution is correct. I've checked with Elm examples website (that kind of acts like a playground for Elm) and it show different result than what is shown on research website.

But the thing is that debug output is not shown when a test fails. I've seen other languages and they mention that output is shown, but for Elm there is no mention of how to get debug output.

Also, website does not mention the version of Elm that is being used, so that maybe another thing.

I can provide my code here, or check with someone somewhere else if possible.

**Comment by iHiD** [comment]
cc @exercism/elm to lend a hand :)

**Comment by mpizenberg** [comment]
Yeah sorry about the debug output not showing. There was an issue when using elm-test in conjunction with the `--report junit` which basically made it impossible to report calls to `Debug.log`. I've spent a loot of time on this (one year basically) now come out with a new tests runner (elm-test-rs) which solves the debug logging issue. It is the thing we use now in the tests runner but I don't think that the tests runner used for the research project got updated (@iHiD ?). I don't even remember if they are compatible.

**Comment by iHiD** [comment]
Thanks Matthieu! :) The v2 website is now locked down so we can't deploy test-runners for that now. They should work on the v3 staging site.

@vfsoraki As you suggest, maybe post your code here and @mpizenberg can point you in the right direction.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
