### ISSUE TITLE
Variable Length Quantity, I have no idea what is required.

### ISSUE THREAD

**Issue by janlimpens** [exercism/exercism#5479]
I am on the rust track.
I am not that fluent at reading Hex or binary notation and where I have to look to get good hints.
What I was able to grasp was (just to illustrate):
  - I get an array of u32. I don't know if this constitutes the digits of a number or if those are individual numbers. Looking at the tests does not help me, because everything is written in Hex.
  - I assume, I need to chop the binary representation of these numbers into blocks of 8 bits. As they are all positive, the leftmost bit should always be 0. 8 bits form a byte, an u8.
  - All but the last byte, before binary conversion, I need to multiply by -1 to set the eight bit. Setting a bit probably means putting a 1 there. Or not.
  - I am lost. And there is nowhere to turn to.

Please make the tests communicate more clearly what is required. Take some care in wording the requirements, it's just a formless mess to me.
Otherwise, this task is only for people that had this in their courses already and translate it to whatever language they are currently tracking. And as such not a real eye-opener.

It's not that it is unsolvable, but paths to the solution divide early on, and it is more than likely, that given my current information, I will spend days on this to pass the tests because I have no way to decide, whether something is going into the right direction or not. It is extremely frustration prone.

**Comment by iHiD** [comment]
(cc @exercism/rust)

**Comment by coriolinus** [comment]
Thanks for mentioning this. Ideally you can try to hack something together, even if it doesn't pass all the tests, and then submit and ask a mentor for help. Still, you're here, so I'll try to get something together for you.

## Fundamentals

I might cover something you already know. Bear with me. These concepts are the basics of how a computer represents numbers, and are required knowledge for this exercise.

A byte is the fundamental unit of storage and memory in a computer. It is comprised of 8 bits. Each bit is a single binary digit, which can be 0 or 1.

All numbers are stored in a computer as some pattern of bytes. Integer primitives in Rust all have a fixed width: a `u8` has 8 bits, which is one byte. A `u32` has 32 bits, which is 4 bytes. Etc.

For example, let's take the number 123. When stored in a `u8`, it has the bit pattern 0111 1011. When stored in a `u16`, it has the bit pattern 0000 0000 0111 1011. The pattern continues: higher bit widths just prepend zeroes.

It's kind of inconvenient to write out binary all the time. Just takes a lot of space. It's not easy to convert the decimal representation of a digit to and from the binary representation in your head, for most people. It turns out to be easier to use hexadecimal. In hexadecimal, each digit corresponds to four bits. You just kind of memorize the bit patterns. The hex representation of the number 123 in a `u8` is `7b`. In a `u16`, it's `007b`. Etc.

## Concept

Say you have an array of 10,000 `u32` values. A `u32` takes 4 bytes to store, so you're looking at 40,000 bytes to store that array. 

However, you've looked at your data: low values are predominant, and high values are rare. A value less than 128 can be efficiently represented in only 7 bits: less than 1 byte. If you can encode your array with VLQ, you only have to store 10,000 bytes. Effectively, you've compressed your data by 75%. That can make a big difference.

Example: you have an `array: [u32; 2] = [123, 210];`. Stored naively, it comes out to the bytes (hex representation) `[00 00 00 7b 00 00 00 d2]`. That's a lot of wasted zeroes. What you want is to leave those out. The goal, for this example, is to reduce it to `[7b 81 52]`.

How did we get there? Let's look at the binary again. 123, in binary, is 0111 1011. It takes a single byte, and the leftmost bit is 0, so it can be encoded in a single byte. Just copy that low byte into the output buffer. 

Now, we have 210. That also takes a single byte: 1101 0010. Because the leftmost bit is 1, we can't encode it as a single byte; we have to use two bytes. The first encoded byte has a leading 1 because it is not the last byte in the sequence. It has a trailing 1 because that bit was carried over from the input number: 1000 0001. Paste that byte into the output buffer. Then, let's encode the second byte. That has the same bits as the input number, except the leftmost bit is set to 0, because this is the final byte in the sequence. 0101 0010. Paste that byte into the output buffer. 

No more bytes. You're done, and the buffer is correct.

## Implementation

What you really want is a good tutorial on bitwise operators. There are plenty out there; just google the phrase. Here's a brief overview.

- `<<` is left shift: shift the digits of a number left.
- `&` is bitwise and: produces an output number with 1 bits in the positions where both inputs had 1 bits.
- `|` is bitwise or: produces an output number with 1 bits in the positions where either input had 1 bits.
- `!` is bitwise not: flips all bits of the input number.

Let's use those in some recipes:

- set the `n`th bit of `input` to 1: `input | (1 << n)`
- set the `n`th bit of `input` to 0: `input & !(1 << n)`
- test whether the `n`th bit of `input` is 1: `input & (1 << n) != 0`
- test whether the `n`th bit of `input` is 0: `!input & (1 << n) != 0`

That should be all you need to solve the exercise. Good luck!

**Comment by janlimpens** [comment]
That is a great answer, thank you! It definitely should make i

**Comment by iHiD** [comment]
In v3, we add a new hints file for exercises. This might be a great piece of content for that :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
