### ISSUE TITLE
F# track doesn't support .NET 5.0?

### ISSUE THREAD

**Issue by MarkuBu** [exercism/exercism#5480]
Hi,
I want to start with the F# track, but I get an error when I run the test. (sorry for the German parts)

```
Der TestHost-Prozess wurde mit folgendem Fehler beendet: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      5.0.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.0.0&arch=x64&rid=ubuntu.20.04-x64
. Weitere Informationen finden Sie in den Diagnoseprotokollen.
```
But .NET 3 is outdated 

I'm running Ubuntu 20.04. How can I solve this?

**Comment by ErikSchierboom** [comment]
We will be updating the F# track to .NET 5.0 once v3 launches!

**Comment by ryepesg** [comment]
`net5.0` also works:
```xml
<TargetFramework>net5.0</TargetFramework>
```

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
