### ISSUE TITLE
Waiting on mentor for nearly 2 weeks

### ISSUE THREAD

**Issue by clinzy25** [exercism/exercism#5481]
How can I solve this issue without completing exercise (unapproved)?

**Comment by glennj** [comment]
Which track? Which exercise?

**Comment by clinzy25** [comment]
Javascript gigasecond

**Comment by kotp** [comment]
You can change mode from mentored mode to practice mode.  But if you give a link, it would make it a simple "click" to check out your submission from here.

**Comment by hakhundov** [comment]
Would be nice to be in a mentored mode, but still have the ability to continue with the exercises...(maybe at least a couple) 🤓

**Comment by kotp** [comment]
Still no link provided so we can easily review, though.  Help us help you out.  (Unsure if you are the also @clinzy25).  But yes, practice mode does allow requesting a mentor.  Just lowered position in the queue.

**Comment by clinzy25** [comment]
@kotp https://exercism.io/my/solutions/0b51d58467c9454887caef2e563e4d61

**Comment by hakhundov** [comment]
If possible please https://exercism.io/my/solutions/ed086047afa145e280943e8b760e6880

**Comment by kotp** [comment]
@hakhundov it looks like someone may have naturally picked up your two_fer, as there is activity as of yesterday from a mentor perhaps 20+ hours before the time post of your link being posted.  Check again.

Thank you @clinnzy25, now I can see some information about the situation.  There are at least 3 students ahead of you on the queue, for this exercise alone.  But I will mention using a function rather than a constant (really use both!) to give some hints there.  I hope that helps inspire a new iteration  while you are patiently awaiting a mentor.

**Comment by kotp** [comment]
I have picked up the exercise for @clinzy25 .
