### ISSUE TITLE
The base API URL 'https://api.exercism.io/v1' cannot be reached.

### ISSUE THREAD

**Issue by jalalvandi** [exercism/exercism#5492]
Hi guys
when trying to enter the following command :
`exercism configure --token=<Token>`

i get this error:
`Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.
Get https://api.exercism.io/v1/ping: net/http: TLS handshake timeout`

 Troubleshooting Information
===========================

```
Version
----------------
Current: 3.0.13
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: net/http: TLS handshake timeout

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.


Operating System
----------------
OS:           windows
Architecture: amd64


Configuration
----------------
Home:      C:\Users\sina
Workspace: C:\Users\sina\Exercism
Config:    C:\Users\sina\AppData\Roaming\exercism
API key:   2ee2*****************************29b

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: net/http: TLS handshake timeout]
    * 11.2159924s

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: net/http: TLS handshake timeout]
    * 10.4059931s

```

**Comment by iHiD** [comment]
It couldn't reach GitHub either so either your internet was down when you tried to do it, or there's something broken in your terminal that won't allow internet access. Could you try again and see if the same thing happens pls?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
