### ISSUE TITLE
Accidentally had mentor slack invite sent to wrong email

### ISSUE THREAD

**Issue by kelsonpw** [exercism/exercism#5493]
I wasn't aware that my email was set to the email from my previous company, so I never received the slack invite email and cant figure out how to have the invite resent to my updated email.

Username: kelsonpw
Prev email: kelson dot warner at fundingcircle dot com
Email: kelsonpw35 at gmail dot com

How can I get the slack invite sent to my updated email?

**Comment by iHiD** [comment]
Sent :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
