### ISSUE TITLE
make it possible to browse specifically solutions that have been mentor-reviewed

### ISSUE THREAD

**Issue by jerabaul29** [exercism/exercism#5494]
I love to browse for solutions to exercises. One thing I think would make this even better is if one could filter to show only solutions that have been reviewed by mentors, because these are usually of higher quality. Could such a filter be added (for example to the ```sort by``` selector available when browsing solutions)?

If this is not the right place to ask just let me know :) .

**Comment by iHiD** [comment]
Hey. Thanks for the suggestion :) 

There's some privacy issues I have with leaking whether someone chose to have mentoring or not, so I'd have to think on this. 

However, we are adding some other metrics to try and bring better solutions to the top, and have long term plans to invest a lot in doing this cleverly and well, so it's definitely something that's on the radar :)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
