### ISSUE TITLE
v3.n+1 suggestion: Button to download exercise as (Jupyter) notebook

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5495]
In v2, the Julia track ships all exercises in a Jupyter notebook in addition to the normal files.

A lot of people learning Julia in a formal context are used to working with notebooks, and this accommodates those workflows, so that people can focus on learning the language rather than learning yet another editor/IDE.

It also makes it easier to use a browser-based environment that doesn't require a local installation.

It would be nice to have a proper way to download an exercise as a notebook file straight from the website. This may also be useful for other tracks about data science languages, e.g. Python.

Example v2 notebook: https://github.com/exercism/julia/blob/v2-final-version/exercises/bob/bob.ipynb

While we don't have a way to actually measure usage, every so often people submit a notebook or ask about it, so there's at least some demand for it.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by SaschaMann** [comment]
AFAICT this is still relevant and should be reopened.
