### ISSUE TITLE
[PHP][v2] Class `X_test` could not be found in `../X_test.php` when I run `phpunit.phar`

### ISSUE THREAD

**Issue by neenjaw** [exercism/exercism#5503]
There is a known issue in the current version [v2] of Exercism's PHP track.  As it is, the PHP track is set up to work with **only** PHPUnit 8.x.  There is a fix for this in place ready to deploy when the new version [v3] of Exercism is released.

For the interim time, see this [discuss answer here](https://github.com/exercism/exercism/discussions/5502#discussioncomment-540840), but in short the solution is to specifically download PHPUnit 8 for local testing.

```shell
# Linux/Mac
> cd ~/exercism/php

> curl -L https://phar.phpunit.de/phpunit-8.phar -o phpunit-8.phar

> chmod +x phpunit-8.phar

> ./phpunit-8.phar hello-world/hello-world_test.php
```

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
