### ISSUE TITLE
Haskell Stack fails to download build plan

### ISSUE THREAD

**Issue by phma** [exercism/exercism#5504]
I just joined the Haskell track, installed Stack from the Ubuntu Focal repo (I already had GHC and Cabal installed), downloaded hello-world, and ran `stack test`. I got this:
```
RedownloadInvalidResponse Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/fpco/lts-haskell/master//lts-16.21.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 "/home/phma/.stack/build-plan/lts-16.21.yaml" (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"},
responseVersion = HTTP/1.1, responseHeaders = [("Connection","keep-alive"),("Content-Length","14"),("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'; sandbox"),
("Strict-Transport-Security","max-age=31536000"),("X-Content-Type-Options","nosniff"),
("X-Frame-Options","deny"),("X-XSS-Protection","1; mode=block"),
("Content-Type","text/plain; charset=utf-8"),("X-GitHub-Request-Id","97D6:76FC:75C468:97958A:606167DF"),
("Accept-Ranges","bytes"),("Date","Mon, 29 Mar 2021 05:39:14 GMT"),
("Via","1.1 varnish"),("X-Served-By","cache-den8254-DEN"),("X-Cache","HIT"),
("X-Cache-Hits","1"),("X-Timer","S1616996354.246391,VS0,VE0"),
("Vary","Authorization,Accept-Encoding"),("Access-Control-Allow-Origin","*"),
("X-Fastly-Request-ID","9151b106e05204f300d87e3d9723d6489a824284"),
("Expires","Mon, 29 Mar 2021 05:44:14 GMT"),("Source-Age","35")], responseBody = (),
 responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose})
```
How do I fix it?

**Comment by iHiD** [comment]
(cc @exercism/haskell)

**Comment by sohang3112** [comment]
I am having the same issue while doing ```stack ghci``` or ```stack setup``` on Ubuntu 20.04 LTS. If you find a solution for this, please let me know.

**Comment by M-Miller-42** [comment]
@sohang3112 Had the same problem on Ubuntu 20.04 today, try running `stack upgrade`.

**Comment by sohang3112** [comment]
@M-Miller-42 Thanks! I did ```stack upgrade``` and now ```stack ghci``` is working as expected.

**Comment by petertseng** [comment]
I will see about updating the Exercism Haskell track docs to include this solution.

**Comment by petertseng** [comment]
I find that I am no longer sure what file I have to edit to update the instructions that show up on the website.

**Comment by petertseng** [comment]
I find that I am no longer sure what file I have to edit to update the instructions that show up on the website.

I intend to amend the instructions that show up in the "Instructions" tab. There is a portion of those instructions that is common to all exercises. For example for Haskell it contains the text "To run the test suite, execute the following command:", among others. The only place I can find the text that shows up there is config/exercise_readme.go.tpl. but I am not sure that file is actually being used to show those instructions.

**Comment by iHiD** [comment]
@petertseng That "to run the test suite..." now lives in the shared docs files here: https://github.com/exercism/haskell/blob/main/exercises/shared/.docs/cli.md

---

The rest of this post outlines the way exercise READMEs are generated now, purely as an FYI for you.

The exercise readme is generated **at runtime** now, based on context (whether the user is using the CLI or the online editor).

If follows this format:
- exercise_title
- -
- welcome_text
- help_text
- hints_text
- -
- introduction,
- instructions,
- source

The title and various `_text`'s in that list are all generated by the website. 

The introduction (optional) and instructions live in the per-exercise `.docs` directory. The main `instructions.md` and `introduction.md` are copies from problem-specs, and there are also optional "append" files which are haskell specific (see https://github.com/exercism/haskell/tree/main/exercises/practice/acronym/.docs for an example)

Then along with the exercise we provide the user with info on running the tests and submitting via the cli; or if the user is using the online editor how to debug. These files are:
- `exercises/shared/.docs/cli.md`
- `exercises/shared/.docs/debug.md`

---

Having just checked the docs (https://exercism.lol/docs/building/tracks/shared-files) I note that the docs references `tests.md` rather than `cli.md` although some tracks contain `cli.md`. @ErikSchierboom Can you please confirm which is correct here.

**Comment by ErikSchierboom** [comment]
@petertseng Our documentation was lacking in this regard. I've just opened a PR to help clarify these files: https://github.com/exercism/docs/pull/164

In short: a track can have three track-wide documentation files:

- `exercises/shared/.docs/debug.md`: explains how a student that is coding in the browser can still do "debugging" (optional)
- `exercises/shared/.docs/help.md`: contains track-specific-wide instructions on how to get help (required)
- `exercises/shared/.docs/tests.md`: contains track-specific instructions on how to run the tests (required)

The above-mentioned PR aims to also show how these files are used to present content to the student.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
