### ISSUE TITLE
Exercism should consider a paid version

### ISSUE THREAD

**Issue by clinzy25** [exercism/exercism#5505]
I'm not sure if this is the right place for this, but I no longer can wait on mentors to approve my solutions, and thus the main reason I use the site is now null.

> There are currently 147 solutions ahead of this in the JavaScript queue, and 15 ahead in the Space Age queue. The median waiting time for mentoring on this exercise is 29 days.

I'm guessing there is a shortage of mentors because there's not enough motive for them to sign on and do the mentoring. This is an issue that could be solved with a subscription based service where mentors are paid to review exercises. I know no one wants to hear this, but the system is currently broken.

I would gladly pay for a service like this. It has immense value to me as a student, I'm sure others will agree. It's popular because it's valuable.

**Comment by iHiD** [comment]
Thanks for your thoughts.

The problem with that logic is that to pay a mentor to help you, you'd need to pay a market rate for their time. For most of our mentors, that would be in the region of $50-$200/hour. I don't think many people are really going to want to pay that.

Also, people mentor because they want to help others - they don't mentor because they're trying to earn money doing so. Most actively don't want Exercism to be another job. 

Also, more importantly, the moment we start charging for Exercism, the moment we become another site where the rich can learn and the poor can't afford it, which goes against the whole ethos of Exercism. So that's not going to happen.

At some point you'll have been [shown this video](https://www.youtube.com/watch?v=XiV_vYn1Ea8&t=1s&ab_channel=Exercism) in a modal on the site. It explains what we're doing to fix this.

**Comment by iHiD** [comment]
You might also want to watch https://www.youtube.com/watch?v=5Cj1Dr9m3GM&ab_channel=Exercism

**Comment by clinzy25** [comment]
Thanks for pointing me toward the videos. I understand your approach here and you have my full support. I will try to be more patient.

I do like the idea of the learning and practice experiences. Best of luck with v3.

**Comment by iHiD** [comment]
Thanks :)
