### ISSUE TITLE
Not all concepts are 100% in the completed Rust track

### ISSUE THREAD

**Issue by sergree** [exercism/exercism#5511]
Hello! I have just completed Rust track: all the core and side exercises.
But I noticed that the Strings and Match concepts are not 100%, but 96% and 75%, respectively.
Maybe there is some bug or hidden task? 😮

![img](https://i.ibb.co/1zTmqG0/c.png)

Best regards from Moscow! 🤗

**Comment by iHiD** [comment]
Congrats on completing the track! It might be that this list takes into consideration deprecated exercises which you can no longer access. As dev on v2 is frozen pending the launch of v3, I can't fix this now, sorry. But if the issue remains in v3 please let me know and I'll take a look for you!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
