### ISSUE TITLE
How can I see ... (omitted tags) in tag list?

### ISSUE THREAD

**Issue by davyzhu** [exercism/exercism#5513]
![image](https://user-images.githubusercontent.com/149704/113960436-13ff3080-9857-11eb-8591-6655fda5a6e5.png)

**Comment by iHiD** [comment]
No, but you will be able to in v3, coming soon.

**Comment by davyzhu** [comment]
> No, but you will be able to in v3, coming soon.

Thanks! Looking forward to v3!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
