### ISSUE TITLE
v3.n+1 suggestion: Allow maintainers to define always-linked terms

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5516]
[Internal links will be decorated with tooltips in v3](https://github.com/exercism/docs/blob/main/building/markdown/internal-linking.md). For some concepts, it may be useful to let the maintainers define track-wide terms that are automatically annotated with such a tooltip. For example so that all mentions of `REPL` always link to the REPL concept tooltip, even if the Markdown file doesn't contain a link.

Alternatively, it may be useful to add this as a configlet check to ensure certain terms are always linked.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by SaschaMann** [comment]
AFAICT this is still relevant and should be reopened.
