### ISSUE TITLE
c prog excercise

### ISSUE THREAD

**Issue by dogscoin** [exercism/exercism#5518]
how i can  run my first test for hello world using excersim then check the solution i know it easy to write this code but i m new in this platform so i don t know how it s work thank you

**Comment by glennj** [comment]
Assuming you downloaded the exercise with `exercism download --exercise=hello-world --track=c`, you will use the `make` command to run the tests.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
