### ISSUE TITLE
Running on Windows 10 with a mounted hard drive gets EvalSymlinks "too many links" error on submit

### ISSUE THREAD

**Issue by tbrown92030** [exercism/exercism#5521]
My Windows 10 environment has a large hard drive mounted at a specific folder on C: in which I have my Exercism workspace. Unfortunately, when trying to submit from this location I get:

**Error: EvalSymlinks: too many links**

Here is the troubleshooting output:
> 
> Troubleshooting Information
> ===========================
> 
> Version
> ----------------
> Current: 3.0.13
> Latest:  3.0.13
> 
> 
> Operating System
> ----------------
> OS:           windows
> Architecture: amd64
> 
> 
> Configuration
> ----------------
> Home:      C:\Users\tbrow
> Workspace: c:\SEAGATE-1-4TB\Documents\Exercism (<== SEAGATE-1-4TB is the mount point)
> Config:    C:\Users\tbrow\AppData\Roaming\exercism
> API key:   20ee*****************************dda
> 
> API Reachability
> ----------------
> 
> GitHub:
>     * https://api.github.com
>     * [connected]
>     * 37.9875ms
> 
> Exercism:
>     * https://api.exercism.io/v1/ping
>     * [connected]
>     * 686.7816ms

I'm sure I can re-jigger everything so that the separate drive is accessible just through a drive letter, but it's so nice to be able to keep everything under C: and not worry about which drive is which.

**Comment by iHiD** [comment]
cc @exercism/cli

**Comment by iHiD** [comment]
(Also @ekingery as you weren't in the right team)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
