### ISSUE TITLE
v3: Add IPA field to profile

### ISSUE THREAD

**Issue by SaschaMann** [exercism/exercism#5528]
It would be really nice to be able to add the pronunciation of one's name to one's profile.

This should be particularly helpful for people with non-English names whose names are often butchered.

This is primarily helpful for the people who join the calls or hackathons, but also for properly reading a name in one's head.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by SaschaMann** [comment]
AFAICT this is still relevant and should be reopened.
