### ISSUE TITLE
search community solutions by keywords

### ISSUE THREAD

**Issue by namin** [exercism/exercism#5533]
It would be great if one could search community solutions for a problem by keywords. For example, whether they're using a particular API (e.g., `RefCell` vs `Mutex` in Rust).

**Comment by iHiD** [comment]
Hey :)

Thanks. It's out intention to add this and other similar functionality to community solutions in the next dev cycle once v3 is launched :)

**Comment by namin** [comment]
That's great to hear. Thank you!

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
