### ISSUE TITLE
UI Bug: Line numbers not aligning with lines of code on mobile view

### ISSUE THREAD

**Issue by YohannesKifle** [exercism/exercism#5539]
Line numbers do not align with lines of code on mobile version. Tested on Android 11, Chrome 90

![Screenshot_20210521-101737_Chrome](https://user-images.githubusercontent.com/19463889/119098429-80587c80-ba1e-11eb-8f2f-32079275a45e.jpg)

**Comment by kotp** [comment]
This tends to happen even for non-mobile browsers when the zoom is not set at 100%.  Can you confirm that?

**Comment by NobbZ** [comment]
@kotp it even happens on 100%, but the effect is less significant depending on your Browser.

V3 will probably not have this issue, though it will also not get fixed in v2 anymore, as development is frozen.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
