### ISSUE TITLE
What happens if I don't agree with review comments from mentor, steps explaining that is missing

### ISSUE THREAD

**Issue by vikramvi** [exercism/exercism#5546]
Dear Team,

Please check the review comments from mentor and my reply to it 

[https://exercism.io/my/solutions/fd5f0200a44c43748d58c6fdcb119d3a](https://exercism.io/my/solutions/fd5f0200a44c43748d58c6fdcb119d3a
)

In this particular case, I don't fully agree with mentor's review comments as he is totally wrong in one point and in another it's just other way of achieving same result without any significant gain

Kindly let me know what are the next steps 

1. When will I hear back from mentor again on my comments ? It's not clear from this page 

2. What happens if me and mentor don't come to common conclusion on solution ?

<img width="1440" alt="Screen Shot 2021-06-01 at 3 37 53 PM" src="https://user-images.githubusercontent.com/308490/120306499-8b998b00-c2ef-11eb-895e-46eaea35e8ae.png">

**Comment by SleeplessByte** [comment]
> In this particular case, I don't fully agree with mentor's review comments as he is totally wrong in one point and in another it's just other way of achieving same result without any significant gain

To answer the question you've asked the mentor:

Your mentor was neither totally wrong, nor just another way of achieving the same result without any significant gain. The goal of Exericsm is to learn an new language, the idiomatic way. Converting (in some other languages this would be type casting) a string to a number can be done in several ways. The `parseXXX` family is _great_ if you're not certain if the input actually represents a number, but you want to try to convert it, as loosely as possible. 

```javascript
parseFloat('99 problems')
// => 99
```

Ok, so what gives?

`parseInt('08')` will not give the same results on all JavaScript engines. On those not supporting ECMAScript 5+ (very little at the moment, but they do exist), this might return `0` and not `8`, because the leading 0 makes it being intepreted as _octal_. [There are various other examples](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#description).

`Number(value)` however, is much stricter, and doesn't allow for unexpected interpretation. If what you want is _conversion_ and not _parsing_, it's always recommended and more idiomatic to use `Number`. 

```javascript
Number('99 problems')
// => NaN
```

For the second point the mentor made, I think they didn't convey enough information for you to pick up what they meant to say. The code as you've displayed it in your screenshot is convoluted where it's type-juggling. It's converting `code1` and `code2` (the numbers) to a string (`${code1}`) and concatenating the result of that conversion (`${code1}${code2}`) and then turning it back into a number (`parseInt(...)`). The mentor's suggestion was to use "math" instead:

```javascript
// Instead of this:

return parseInt(`${code1}${code2}`)
// => parseInt(`42`)
// => parseInt('42')
// => 42

// You could do something like this:
const tens = code1 * 10 // 4 becomes 40
const ones = code2      // 2 becomes  2
return tens + ones      //   results 42
```

The point here isn't speed, or amount of lines of code, but intention and cognitive complexity. There's just not a good reason to convert the colours' values into a digit-string, and then back into a number.

> When will I hear back from mentor again on my comments ? It's not clear from this page

You would normally hear back from the mentor whenever they have time again. Often it's fast, sometimes it takes a while. All mentors are donating their time for free for your benefit. The barrage of comments you've left *demanding* a response are not encouraging to actually get you a response. That said:

- If a mentor fails to respond within 7 days, they are removed instantly and automatically
- You join the queue, but at the appropriate _higher_ place, so it can be picked up by a different mentor. 

Waiting that long is not great, and since we require mentoring to continue, it can be very discouraging. The founder of exercism has a great video on [4 ways Exercism sucks and how we're going to fix them](https://www.youtube.com/watch?v=5Cj1Dr9m3GM), which might interest you. TL;DW, v3 is launching in 60 days and has a different approach on how to learn and how mentorship works.

> What happens if me and mentor don't come to common conclusion on solution ?

This sometimes happens. You can always request the mentor to stop mentoring you, in which case they will be replaced with someone else. You can also disagree and voice that, and sometimes they will feel that the discussion itself was valuable and approve your solution without agreeing.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
