### ISSUE TITLE
Change associated github username for account

### ISSUE THREAD

**Issue by rustycat17** [exercism/exercism#5555]
Hello, 

I am using Github to login to exercism, however now I am using a different github username. Is it possible to change the github username to login for the same account? 

Thank you for exercism btw. :-)

Cheers and thank you

**Comment by iHiD** [comment]
Hello. If you send me emails at jeremy@exercism.io from **both** email addresses (registered with GitHub) and explain the change, I can action it 🙂

**Comment by iHiD** [comment]
Thanks for the nice comments btw 🙂

**Comment by rustycat17** [comment]
Thank you for your reply. I sent the two emails as requested. Thank you for your help.

**Comment by rustycat17** [comment]
Hello @iHiD, 
did you receive my emails from June 7?

**Comment by iHiD** [comment]
Sorry! I missed this. I'll do it post v3-launch for you. The whole current website is frozen atm. Please remind me again after launch (Sept 1st) and I'll get it fixed for you.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂

**Comment by rustycat17** [comment]
@iHiD Hello :-) I wanted to ask if you could change my username after the v3 release. Thank you very much!
