### ISSUE TITLE
Practice mode doesn't have links to how to install language

### ISSUE THREAD

**Issue by axtens** [exercism/exercism#5557]
Only mentored mode has instructions on how to install the language. Scheme is oversubscribed and can't be done in mentored mode, so where does one find instruction on how to install Scheme?

**Comment by iHiD** [comment]
That's an annoying bug. Thanks. Instructions are here: https://exercism.io/tracks/scheme/installation

(The URLs should map from other tracks that you can see)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
