### ISSUE TITLE
Very Important Issue 

### ISSUE THREAD

**Issue by ERRA-Augment** [exercism/exercism#5565]
Your website hurts my eyes it causes me physical pain to look at, it would amazing if you could implement some form of darkened theme, thank you

**Comment by taiyab** [comment]
I've been saying this all along. Sheesh.

**Comment by CyanCoding** [comment]
I use the Dark Reader extension, which is supported in almost every browser and forces websites to display a dark theme. Not a perfect solution but helps with eye strain.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
