### ISSUE TITLE
Haskell submission issue

### ISSUE THREAD

**Issue by Siyanda-mkhize** [exercism/exercism#5569]
Hi, guys, I am new to Exercism and I am working with Haskell. I am confused on how to submit an exercise I keep getting the following error: 
C:\Users\Sisan>exercism submit /haskell/hello-world
Error:

    The file you are trying to submit cannot be found.

        C:\haskell\hello-world 

Can anyone in a simplistic manner please explain what is the correct way to submit?

**Comment by NobbZ** [comment]
Try again with using a relative path (neither a leading `/`, nor a leading drive letter) and also adding the actual name of the solution file.

Alternatively `cd` into the solutions folder first and just use the solutions file name.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
