### ISSUE TITLE
Issue with submission.

### ISSUE THREAD

**Issue by WRsraina** [exercism/exercism#5571]
Hi! 
When I trying to submit the solution using
 `exercism submit /path/to/file [/path/to/file2]exercism submit /path/to/file2 [/path/to/file2 ...]`

I get following error, It is blocking me to move to next excercise.

` $mac: two-fer sraina$ exercism submit /path/to/file [/path/to/file2 ...]`

`Error: 

    The file you are trying to submit cannot be found.

        /path/to/file`

**Comment by aryananta** [comment]
i have the same problem with R track

`exercism submit hello-world.R`

but still come 

Error: This solution could not be found

any clues ?

**Comment by NobbZ** [comment]
The *file* or the *solution*? This wording is important.

If the *file* hasn't been found, please check the folder contents if you perhaps misspelled it or are in the wrong folder.

If the *solution* hasn't been found, please check `$(exercism workspace)/r/hello-world/.exercism/metadata.json` if the `id` field matches the ID in the `url` field, and if the `handle` corresponds to your exercism username. Last but not least, also verify thet the ID in that file is the same as displayed in your browsers URL bar when you visit the exercises page.

If your problem is indeed related to the *solution* rather then the *file*, please open a new issue linking and quoting this comment.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
