### ISSUE TITLE
Getting errors in catch.hpp

### ISSUE THREAD

**Issue by glucu** [exercism/exercism#5572]
After successfully downloading the Isogram exercise in C++, I am seeing 7 errors that are the same: 

![err](https://user-images.githubusercontent.com/33062621/124201009-7190cb00-da9c-11eb-9801-d39ba2a2b738.PNG)

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
