### ISSUE TITLE
Step-by-step guide on solving exercism exercises 

### ISSUE THREAD

**Issue by mlawso33-code** [exercism/exercism#5575]
Completed the CLI download and everything but not understanding how to open the exercise after downloading the exercise to my folder. I started a new file, completed the exercise and tried to submit, but it says "not in the workspace". So i'm not understanding if I'm going about this the proper way to submit code.

**Comment by CyanCoding** [comment]
Hey! I just started using Exercism as well. When you download the project, like with `exercism download --exercise=hamming --track=go`, it should output the folder that it downloads to. All of the files you need are in that folder. In my case, it creates several files and you can get started right away. I like to use [Atom](https://atom.io/) because I can open the folder as a project, edit my file, and run tests in the command line all in one app.

You don't have to worry about creating files because the main files are already there for you - including the program's entry point. Once you're finished testing, just run the command `exercism submit [filename]` and refresh the page.

**Comment by glennj** [comment]
If you type `exercism configure` you should see what exercism think your workspace is. You can change it with `exercism configure --workspace /my/preferred/workspace/directory`

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
