### ISSUE TITLE
Problem downloading: HTTP response to HTTPS client

### ISSUE THREAD

**Issue by duke-of-spacingham** [exercism/exercism#5583]
Hello all,
I'm new on exercism. 
All went well for configuration (with --no-verify flag), but when I try to downloading an exercise, I get this:

_exercism download --exercise=hello-world --track=cpp
Error: Get https://api.exercism.io/v1/solutions/latest?exercise_id=hello-world&track_id=cpp: http: server gave HTTP response to HTTPS client_

Same issue can be seen in the configuration, at the Exercism API reachability:

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           linux
Architecture: amd64

Configuration
----------------
Home:      /home/oferw
Workspace: /home/oferw/exercism
Config:    /home/oferw/.config/exercism
API key:   8b2a*****************************3fe

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 74.9057ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: http: server gave HTTP response to HTTPS client]
    * 243.0201ms

Any idea on how to get over this?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
