### ISSUE TITLE
How do I test the C++ exercism program?

### ISSUE THREAD

**Issue by xxplunderxx** [exercism/exercism#5584]
So I followed the tutorial, and It suggests to use the cmake command to test the build. I downloaded home brew, but when I type the make command to test my program it says "command not found".

I am using terminal on Mac OS.

Thanks.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
