### ISSUE TITLE
What version Exercism use for Golang?

### ISSUE THREAD

**Issue by kokizzu** [exercism/exercism#5591]

**Comment by angelikatyborska** [comment]
Hi! I'm not involved in the track so I don't know for sure, but after a short look at their repository (https://github.com/exercism/go) I found this GitHub workflow https://github.com/exercism/go/blob/main/.github/workflows/exercise-tests.yml#L18-L20 that says it tests exercises on Go version 1.14 and 1.15.

**Comment by SleeplessByte** [comment]
It should probably be upgraded to 1.16, right?

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
