### ISSUE TITLE
Cannot download the exercise

### ISSUE THREAD

**Issue by thanhtungpfiev** [exercism/exercism#5601]
Hi all,
I try to download my exercise but I met this error:
tung.dao@VN-MF10-NC1006F MINGW64 ~/Exercism
$ exercism download --exercise=space-age --track=cpp
Error: net/http: request canceled (Client.Timeout exceeded while reading body)
I am using the latest CLI in Window 10 64bit

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
