### ISSUE TITLE
Odd times on old iterations

### ISSUE THREAD

**Issue by verdammelt** [exercism/exercism#5618]
Perhaps this is only a problem for some old solutions I have in my account but I thought I'd report it anyway.

When viewing the mentoring tab for my published ETL exercise solution (https://exercism.org/tracks/common-lisp/exercises/etl/mentor_discussions) I see:

<img width="750" alt="3days" src="https://user-images.githubusercontent.com/365425/131714859-92b422ba-4df1-44c8-a5f7-8125a57fffa9.png">

The 3 days is DEFINITELY wrong. I haven't touched this solution for a while and the mentor has not been active for at least as long.

Then when I click into mentoring session I see the right hand side looks like:

<img width="587" alt="confused-iteraations" src="https://user-images.githubusercontent.com/365425/131715001-256a86a1-d27f-4b1d-b91f-d5bd97c76cdc.png">

Notice the mix of 3 & 7 years. I cannot remember which is more likely to be correct but either could be.

Feel free to just close this if this is only a problem for old solutions like this; and please let me know if further information is needed.

**Comment by kytrinyx** [comment]
I wonder if this is the same issue as #5771.

(Also: 👋 Hi Mark, it's been a while!)

**Comment by iHiD** [comment]
This would be an ETL issue (3 days before the day of this issue was ETL). The records were created then, so they got that timestamp. I also suspect the "3 yrs" is a different ETL issue from the previous ETL! So I think we can probably close this - I feel like trying to fix this data now is probably going to cause us more pain than good. Sorry, Mark!

**Comment by verdammelt** [comment]
OK, I'll close it.

Also 👋 @kytrinyx it has been a while!
