### ISSUE TITLE
Wrong elapsed time on reputation drop down list.

### ISSUE THREAD

**Issue by lasarohedvig** [exercism/exercism#5620]
A few seconds after publishing a solution I clicked on the reputation points button and the first entry, corresponding to the just-published solution, says it was published 14 hours ago. 14, by the way, is the current hour in my time zone at the time when the bug appeared.

![image](https://user-images.githubusercontent.com/49382569/131715546-d2ff2125-3cea-44cf-9f70-3c432f3045e8.png)

**Comment by kntsoriano** [comment]
@iHiD @ErikSchierboom Storing the `earned_on` column as a date and not a datetime leads to this bug. When we store it as a date, we remove the timezone information.

**Comment by ErikSchierboom** [comment]
I think it should be doable. I don't recall why this was made a `date` and not a `datetime` to be honest.

**Comment by iHiD** [comment]
The`cacheable_rendering_data` in `app/models/user/reputation_token.rb` should be `reputation_token.created_at`, not `reputation_token.earned_on`. And in JS it should be `createdAt`, not `earnedOn` - `earned_on` should be solely used for the calculations around reputation periods, where being a date is lots lots faster due to indexes.
