### ISSUE TITLE
Awaiting Student default "Sort by recent first" would be more helpful than oldest

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#5688]
I find myself wanting to look at recent discussions much more often than wanting to look at discussions from over a year ago. Having to change it every time I go to Awaiting Students is getting annoying. Just sayin'.

**Comment by bobahop** [comment]
The same might be said of "Finished", but I don't find myself going there much at all.

**Comment by bobahop** [comment]
Inbox makes sense to have oldest first.

**Comment by angelikatyborska** [comment]
I had exactly the same thought. But I would also prefer the inbox to be "recent first" so that they all have the same sorting order, less surprising. But "recent first" is much more useful to me than "oldest first". Because the older the solution, the less value is in checking up on it. The student might have forgotten completely about the platform.

**Comment by iHiD** [comment]
Switch the default order on this pls.
