### ISSUE TITLE
Can't open online editor in any of the Kotlin track exercise

### ISSUE THREAD

**Issue by mnajborowski** [exercism/exercism#5845]
The `Start in editor`/`Continue in editor` button is inactive in every Kotlin track exercise. I could open it at v3 launch, but now I can't and I wonder if that's a known issue (I can't see any open issue filtered by `editor` refering this).

<img width="512" alt="obraz" src="https://user-images.githubusercontent.com/44368870/132582440-14c83d95-25ec-4129-a1ec-a0b0a2c0bae4.png">

**Comment by ErikSchierboom** [comment]
This is due to the fact that the Kotlin test runner has an issue where it can't run without networking (which is how our test runners are being run): https://github.com/exercism/kotlin-test-runner/issues/16 If you think you can help with that, that would be great! See also https://github.com/exercism/kotlin-test-runner/pull/20#issuecomment-839803030

In short, the fact that the button was enabled at launch was a bug on our part.

Once https://github.com/exercism/kotlin-test-runner/issues/16 has been fixed, we'll re-enable the button.
