### ISSUE TITLE
[Mentoring status] After the student answered mentor's feedback, the status is still 'action on you'

### ISSUE THREAD

**Issue by Nerwosolek** [exercism/exercism#5876]
After the student answered mentor's feedback, the status is still 'action on you' - I don't remember the exact phrase.
It looks like it didn't took the student's answer into the consideration of mentoring status.

**Comment by jmrunkle** [comment]
Sounds like a duplicate of https://github.com/exercism/exercism/issues/5812

**Comment by Nerwosolek** [comment]
In my case the solution passed the tests, if you meant this.

**Comment by jmrunkle** [comment]
My solution also passed the tests. I think the bug is that the action is "on the student" until they upload a new iteration even though they may not need to based on the comments they gave back to the mentor.

**Comment by Nerwosolek** [comment]
Yeah. The flow is uncertain for me here. You might be right - maybe it is legacy from v2 where the mentor needed to approve the solution, which unapproved meant to be iterated. Now both sides can end discussion. And as the mentoring is requested for specific question from the student it is not directly connected with the solution itself. Maybe the flow should be generally rethinked?

**Comment by jmrunkle** [comment]
I am reasonably sure that it is not currently able to distinguish between:

1. a student who responded to their mentor saying "yeah, great advice, let me upload a new iteration following that advice"; and
2. a student saying something like "that's an interesting point, I have more questions or otherwise do not think we should do that because of X"

The mentors certainly get a notice when the student posts a new comment. If it does not require the mentor to act, they can "remove from inbox" until the student acts again. There should be something similar for the student's side of things and that seems to be missing.

**Comment by Nerwosolek** [comment]
I believe the button "It's student's turn" solves the issue?

**Comment by Nerwosolek** [comment]
Now student's answer changes mentoring side to mentor.

**Comment by Nerwosolek** [comment]
It's proper ping pong now with texts also, not only with iterations.
