### ISSUE TITLE
Who should we use for swag?

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5962]
- They need to dropship (ie do the work of producing/shipping)
- I don't mind using different suppliers for different things.
- They need to be ethical (environment, labour, etc)
- A range of price-points would be nice.

---

## T-Shirts
- https://teemill.com/

**Comment by SleeplessByte** [comment]
<https://store.dftba.com/> seems to be the one that most of the creators I follow use. <https://shop-eu.kurzgesagt.org/> forexample is also DFTBA.

It's by John Green who is very environment-focused. Also see <https://www.shippingnerds.com/>

**Comment by SaschaMann** [comment]
Maybe as a consideration: instead of selling things all the time, run campaigns on certain items that are only produced once a certain threshold has been used.

---

JuliaCon uses https://www.bonfire.com/

---

DFTBA's shipping is complete and utter garbage in my experience. Absurdly expensive yet takes several months.

**Comment by SleeplessByte** [comment]
Shipping on dftba is long indeed. I do like bonfire too.

**Comment by w0rd-driven** [comment]
I don’t know if they fit exactly since they seem to be tailored to giveaways but I know the people behind https://www.useslingshot.com/ and they've been phenomenal.

**Comment by SaschaMann** [comment]
https://www.teepublic.com/ has been mentioned on the Julia Zulip.
