### ISSUE TITLE
Copy to clipboard does not work in qutebrowser

### ISSUE THREAD

**Issue by mcastorina** [exercism/exercism#5979]
First off, nice work with the redesign! The website looks really nice and I think it's a smart move to make mentor requests on a per-exercise basis.

That being said, the "copy to clipboard" feature for working locally (via CLI) does not work with my browser `qutebrowser v2.3.1` (running on `x86_64 GNU/Linux`). Normally I wouldn't open an issue just for this, but because the full text isn't displayed I cannot get the command any other way.

**Comment by angelikatyborska** [comment]
Hi! I must say I never heard of this browser. Given the long list of specific requirements that need to be installed for this browser to run, and the unusual UI (for a browser), we might have trouble trying to reproduce this. Could you describe in more detail what "doesn't work" means? How are you trying to copy to the clipboard? What happens when you try, what did you expect to happen?

I'm going to consider two scenarios from the top of my head. Please excuse me if I'm saying obvious or ridiculous things, I have no idea about this specific browser, but I want to help.

First, is it because you don't have a mouse pointer in this browser? In a more conventional browser, you can navigate the page by pressing "tab" to focus the next focusable element and then "click" it by pressing "space". Is there a similar way to navigate in your browser? If yes, what happens when you try to "click" the button?

Here's how it works in my Firefox, a gif:

![2021-09-29 00 28 54](https://user-images.githubusercontent.com/7852553/135174502-8dc96138-0778-4c17-8d98-b27ded58813b.gif)

Second, if you do have a mouse pointer or any other way of selecting text easily, in many browsers content hidden with the CSS style `overflow: hidden; text-overflow: ellipsis;` (which is the case here) can actually be selected and copy-pasted in full even though you cannot see it.

Here's how it works in my Firefox, a gif:

![2021-09-29 00 21 23](https://user-images.githubusercontent.com/7852553/135174543-959dba1f-5dee-4a3c-9c5f-1fc6bb42597c.gif)

**Comment by mcastorina** [comment]
Thanks for the detailed response!

qutebrowser does have a mouse pointer and you can click on links / buttons like normal browsers. When I click with the mouse pointer nothing happens. There is no "Copied" pop up like in your gif. The same thing happens when I try your suggestion of tabbing over and hitting space or enter (no "Copied" pop up).

Highlighting and copying and pasting (like your second gif) does work, though, so thank you!

I may be mistaken, but I believe the copy button worked in the previous version of the website. Perhaps this is just an issue with qutebrowser though.

**Comment by mcastorina** [comment]
Okay it turns out it is a qutebrowser configuration problem on my end. Oops.

See https://github.com/qutebrowser/qutebrowser/issues/6719 for the solution.

Thanks again for the help @angelikatyborska !
