### ISSUE TITLE
[Badges] "Anybody there?" badge not awarded after completing "Hello, World!" in five languages

### ISSUE THREAD

**Issue by squeakyboots** [exercism/exercism#5985]
Despite having completed "Hello, World!" in five languages no badge was rewarded. For an example, see this profile:
https://exercism.org/profiles/squeakyboots/solutions?criteria=hello

![image](https://user-images.githubusercontent.com/11595454/135349153-8bd78bde-1879-425a-b8a9-c6b5b3dd53c7.png)

The badge seems to be defined [here](https://github.com/exercism/website/blob/bcd9cd532138fdc9277f8474159e6ca333e6ae7d/app/models/badges/anybody_there_badge.rb), suggesting it should be granted upon completing "Hello, World!" in five languages.

**Comment by squeakyboots** [comment]
@iHiD I still don't have my badge after logging off/on, is the job to fix it being ran later?

![image](https://user-images.githubusercontent.com/11595454/135521048-42029af5-0234-4d5a-ac2e-174842ea1d33.png)

**Comment by iHiD** [comment]
Urgh. The website wasn't deploying as our GitHub Actions Runner was out of HDD space, so the badges didn't get assigned. I've just fixed that. It's deploying now. Then I'll rerun things. Thanks for the alert!

If you've still not got this in an hour from now, please tell me :)

**Comment by Eddie-Hartman** [comment]
@iHiD I was looking through issues and rather than create a new one, I thought I could just comment on this one. I have a few questions.

1. Is there any way to see the list of badges that we have not earned yet? I see this: https://github.com/exercism/website/tree/bcd9cd532138fdc9277f8474159e6ca333e6ae7d/app/models/badges as a list, so it seems like there aren't many in there, but it would be nice to know from the UI in some way. I also appear to be missing the "Growth Mindset" badge.
2. Is there a better place to ask general questions like this rather than open a new issue? I have a few other questions/comments, but don't want to bog down a closed issue. (Ex, Adding a new badge for completing a track/syllabus and one for completing all current exercises, being able to sort community answers by stars/lines.)

As a side note, I'm really enjoying v3 and was really concerned when I got started that the site was being rebuilt. Looking forward to what you all have coming for Exercism for Teams in 2022.

**Comment by iHiD** [comment]
@Eddie-Hartman Thanks for the encouraging words! 🙂 

1. No, deliberately not a list at this time, so that badges are pleasant surprises rather than things people grind for. Might change our minds later down the line, but for. now, I didn't want to encourage that grinding behaviour.
2. Not yet. Opening new issues here is fine. Eventually we'll have a better solution :)

Regarding you missing the growth mindset badge, I'll take a look. Ping me again in a couple of days if I've not sorted it :)
