### ISSUE TITLE
Private mentoring use the regular mentoring slots - but only when one is available

### ISSUE THREAD

**Issue by szabgab** [exercism/exercism#6093]
As far as I could understand private mentoring requests do NOT normally do not use mentoring slots and thus are not limited. However, as reported by one of my students, if the student has open slots or if a used mentoring slot is freed by ending the discussion then the ongoing private mentoring occupies the now free mentoring slot.

This feels to be a bit inconsistent.

I wonder if either of this behavior is considered to be a bug or if this is the intention.

**Comment by iHiD** [comment]
I think it's a bug. Thanks for reporting :)

**Comment by kotp** [comment]
Bumped here… 🐫

**Comment by fricova** [comment]
I love exercism but I find this bug somewhat frustrating. Since I don't have enough reputation, I can't get mentored by my friend. It is not clear to me what I should do to get private mentoring, it doesn't mention what the threshold is re: reputation.

**Comment by kotp** [comment]
@fricova You have said that you are not able to get mentoring, even private mentoring.  I am curious as to what you have tried specifically and what the result was specifically.

For example, if I tried to get private mentoring, I might print the page with my printer and mail it to my friend.  They might respond by penning in comments in the margins, or on the back of the mailed exercise.  But this might not work, because for whatever reason I never go the response in the mail.

So if you have tried private mentoring (I am assuming unofficial, since you have differentiated official and private), please let us know what that means.  Also let us know what you have done to try to get official mentoring, and describe how that failed as well, if you can.

Every student, those with 0 reputation, and those with 1000 reputation should be able to get official mentoring, it is the purpose of the platform.  So the idea that you are not able to is very troubling.  (Getting private (official) mentoring might be reputation based, but probably should not be, and there are always unofficial ways, such as described above that can be done).  I am very interested in what you have tried and how that has failed for you.

**Comment by SleeplessByte** [comment]
@kotp whilst you help Michaela with this, a few things to check:

- any of the mentoring slots filled?
- web or CLI?
- mentoring on practice or concept exercises (latter being not [yet if ever] possible via web, former always possible)?

**Comment by iHiD** [comment]
@fricova If you click on the mentoring tab on the exercise, do you see the box on the right? If not, could you send a screenshot pls? If you can't click on the mentoring tab, could you send a screenshot of that pls? Thanks :)

<img width="1437" alt="Screenshot 2022-06-18 at 17 18 56" src="https://user-images.githubusercontent.com/286476/174447512-ee808c9f-9288-4034-943d-9853476981b5.png">

**Comment by iHiD** [comment]
@kotp @fricova Means private mentoring as in through the UI on the RHS above, not through the queues. (I'm going to close collapse your comment as I think it'll add confusion to the conversation currently)

**Comment by kotp** [comment]
@iHiD thank you, I am glad they confirmed it was through the private mentoring interface, though it seemed like they indicated more than only private. The goal was clear for "private mentoring" in the latter paragraph, but the first paragraph indicated "official or private".
