### ISSUE TITLE
Fsharp: Bug in Test

### ISSUE THREAD

**Issue by draptik** [exercism/exercism#6095]
Discussion here:

https://twitter.com/exercism_io/status/1456027867993812999

**Comment by draptik** [comment]
I already described the bug once.

**Comment by kotp** [comment]
So we do not have to go to other platforms, etc.:

@draptik writes:
> Is this a bug or a different point of view?
![image](https://user-images.githubusercontent.com/16747/140268727-72a26fa0-1fd6-4ab9-bc90-a7339a8b3969.png)

**Comment by angelikatyborska** [comment]
@draptik The function `remainingMinutesInOven` is only supposed to take one argument, and your takes 2. I don't know F#, but I assume currying occurs here, and when the tests apply a single argument to a 2-argument function, it creates a curried one-argument function instead of raising an error (https://fsharpforfunandprofit.com/posts/currying/) and that why the test result is what it is.

Btw. make sure to actually implement the function using the argument given, not hardcoding `15` 🙂

**Comment by ErikSchierboom** [comment]
@draptik Angelika is totally correct. I've also mentioned this on twitter: https://twitter.com/ErikSchierboom/status/1456018749388169227?s=20

This is not a bug in the test, but in the implementation.
