### ISSUE TITLE
Flaky "TESTS TIMED OUT" in the Java track

### ISSUE THREAD

**Issue by andreaTP** [exercism/exercism#6097]
Hi and thanks for the amazing platform!
Starting yesterday I'm observing some flakiness when submitting results with the CLI:

 - submit a solution
 - it fails with "tests timed out"
 - re-submit N times
 - it passes
 
 Unfortunately, I don't know how to access logs or information to debug the issue any further.

**Comment by iHiD** [comment]
@andreaTP Thanks for the nice message.  The Java test-runner is a little flakey because Gradle takes **so** long to compile and so sometimes it times out. There's been quite a lot of work on it but we've struggled to get it faster. (You can see the code here: https://github.com/exercism/java-test-runner/)

@ErikSchierboom Do we have any more ideas of what we're doing to improve things here, or are we a bit stuck at this stage?

**Comment by ErikSchierboom** [comment]
We're stuck at this point. I've also attempted to optimize the speed of the Kotlin test runner (see [this issue](https://github.com/exercism/kotlin-test-runner/issues/30)), but have failed to do so. The Groovy test runner is also slow. The one thing they all have in common is that they're running Gradle under Docker. I'm hopeful that if someone manages to fix the performance in one test runner, things might be better in all of them.

**Comment by andreaTP** [comment]
I might be wrong, but I have a quick question: are you caching dependencies?

**Comment by ErikSchierboom** [comment]
We are. As a matter of fact, we _must_ cache dependencies as the test runner runs without networking.

**Comment by andreaTP** [comment]
Thanks @ErikSchierboom for the answer, I might try to have a look 🙂

**Comment by ErikSchierboom** [comment]
Brilliant! That would be much appreciated.

**Comment by ErikSchierboom** [comment]
I think we can close this now! 🥳

**Comment by andreaTP** [comment]
YaY 🎉
