### ISSUE TITLE
Create new track for [LANGUAGE]

### ISSUE THREAD

**Issue by GauriParhad** [exercism/exercism#6116]
I want solution for Car Assemble! Problem. I am not able to go further and solve it

**Comment by kotp** [comment]
What track @exercism/gnu-apl ?  But the way to get help there is probably to submit a solution that is partially done, and request mentoring there so that a mentor can help you out.

**Comment by angelikatyborska** [comment]
@GauriParhad I second what @kotp says. Also make sure to read all of the hints that are available for learning exercises.

However, if you are absolutely sure that you need to cheat, all of the exercises are open source and very easy to find in this GitHub organization. Here is a list for you of all solutions to exercises called "Cars Assemble!" (because you didn't tell us which programing language you mean):

- [babashka](https://github.com/exercism/babashka/blob/main/exercises/concept/cars-assemble/.meta/exemplar.clj)
- [clojure](https://github.com/exercism/clojure/blob/main/exercises/concept/cars-assemble/.meta/exemplar.clj)
- [java](https://github.com/exercism/java/blob/main/exercises/concept/cars-assemble/.meta/src/reference/java/CarsAssemble.java)
- [f#](https://github.com/exercism/fsharp/blob/main/exercises/concept/cars-assemble/.meta/Exemplar.fs)
- [c#](https://github.com/exercism/csharp/blob/main/exercises/concept/cars-assemble/.meta/Exemplar.cs)
- [go](https://github.com/exercism/go/blob/main/exercises/concept/cars-assemble/.meta/exemplar.go)

Btw. it would be nice if you could rename your issue to something more meaningful than "Create new track for [LANGUAGE]". Issue titles are crucial for open source maintainers to figure out what needs their attention.

**Comment by kotp** [comment]
_cheat_ is probably too strong a word here.  If you learn something by seeing some example of a solution then how is that cheating?  If you feel like you have cheated yourself, apologize to your self and come up with another way that does not make you feel bad.  Many of the solutions (for the practice exercises) are not even necessarily idiomatic, they are "proof of concept" so seeing them only means that you have seen a solution, rather then seeing "the best or only way to do so".

**Comment by iHiD** [comment]
I'm going to close this a it's not something the Exercism team can action.
