### ISSUE TITLE
hello world test error in exercism

### ISSUE THREAD

**Issue by supersagar1999** [exercism/exercism#6173]
![image](https://user-images.githubusercontent.com/96127160/147565638-a2b8c7c1-1457-484c-acef-7e6d0fba7ce4.png)

i cannot figure out what is the error..can someone help me?

**Comment by pwadsworth** [comment]
Try removing the function call hello(). The tests will do that.

**Comment by glennj** [comment]
Read the instructions again carefully. The objective is not to **print** the string, the goal is to **return** it.

**Comment by BethanyG** [comment]
To explain a little more about the test output:

```python
self.assertEqual(hello(), "Hello, World!")
```

Means that the test runner is _calling_ your `hello()` function.  It is running the code `hello()`.  It _expects_ to get a string == "Hello, World!" handed back.  

However, since you used `print()` in your function - (_`print()` writes to standard_out -- "the terminal" -- instead of handing over to a requestor_), what the test runner got back was `None`.   `None` != "Hello, World!", so the test failed.   You can see that the test runner captured what got "printed" and wrote it into the `Your Output` box -- but that wasn't the same as having the string **_returned_** from the function.

`None` is the default function return for any function that doesn't use the `return` keyword followed by some value.  Its Python's way of saying _"ok - that ran without error, moving on now..."_.

The [stub](https://github.com/exercism/python/blob/main/exercises/practice/hello-world/hello_world.py) for this exercise that either downloads via the CLI, or shows up in the code window on the website shows a `return` from the `hello()` function.   The expectation is that you would replace the _incorrect_ string with a _correct_ one - not re-write the function to make it `print()`.  

None of the problems on the Python track for exercism (_currently_) will ever require that you `print()` something out to the terminal for the tests.  All of the tests expect `function` or `class`  `returns`.  We're thinking of adding some exercises that do deal with standard_in and standard_out -- but we haven't gotten to them.

For more on Python basics, I suggest the [Guido's Gorgeous Lasagna](https://exercism.org/tracks/python/concepts/basics) exercise or the [Python Documentation Tutorial](https://docs.python.org/3/tutorial/).

**Comment by supersagar1999** [comment]
thank you everyone! issue solved :)
