### ISSUE TITLE
Why does Exercism test for state mutation?

### ISSUE THREAD

**Issue by arnthorsnaer** [exercism/exercism#6180]
In JS track Bird Watcher exercise Test 9 is testing for object equality. The only way for me to pass the test is to mutate the array. My initial solution where I returned a new array with the modified value triggers this test failure. It means that my map solution was not accepted. Is this intended behaviour?

```
const birdsPerDay = [2, 0, 1, 4, 1, 3, 0];
expect(Object.is(fixBirdCountLog(birdsPerDay), birdsPerDay)).toBe(true);
```

```
Error: expect(received).toBe(expected) // Object.is equality
Expected: true
Received: false
```

**Comment by angelikatyborska** [comment]
Yes, this is on purpose. The instructions (https://github.com/exercism/javascript/blob/main/exercises/concept/bird-watcher/.docs/instructions.md#3-fix-a-counting-mistake) say:

> 3. Fix a counting mistake
> (...)
> returns that same array


And the test description (https://github.com/exercism/javascript/blob/main/exercises/concept/bird-watcher/bird-watcher.spec.js#L56) also states that that is exactly the purpose of the test: 

> test('does not create a new array'

As for the reasoning behind this, I am going to take a guess that this is to nudge students into using a "for" loop instead of something like `Array.map` because this exercise is a learning exercise for "for" loops (but I wasn't personally involved in designing it, so it's just my guess - @exercism/javascript would know better).

**Comment by junedev** [comment]
Can someone move this ticket into exercism/javascript please?

@arnthorsnaer As @angelikatyborska already mentioned, in this learning exercise you are supposed to use for loops for all 3 tasks. The test indeed exists to discourage the use of `map`. Please keep in mind that learning exercises exist to practice or demonstrate your knowledge of one specific concept, in this case `for-loops`. This is different from practice exercises where you are ask to solve them the best way you possibly can.

**Comment by arnthorsnaer** [comment]
While I respect the goal of the exercise (using `for` loops) and also the intention of the test 9 to motivate the use of for loops, I think there are some unwanted effects. For example someone *can* use a `for` loop to solve this without mutating state. However I can't think of any alternatives to this so perhaps it's an acceptable constraint.

Thank you @junedev and @angelikatyborska for your quick and thoughtful replies. I will close the issue but of course anyone who maintains exercism/javascript will probably see this and take action if they feel it's warranted.
