### ISSUE TITLE
Privat mentor 

### ISSUE THREAD

**Issue by annepig** [exercism/exercism#6203]
Hi , 

Can you help me step - by - step , how I can get a mentor? I have the username of the one I would like it to be

Best 

Anne-Katrine

**Comment by kotp** [comment]
Hello @annepig and I am glad that there is a mentor that you are finding helpful.

If you have the mentor's contact information, if you communicate with them off platform, you could request a mentor by sharing the mentor link with them.

![request_mentoring_by_friend](https://user-images.githubusercontent.com/16747/150712619-6ee5d80e-36ba-4548-a4df-33e5c42cf214.png)

Notice the pull down next to "Request mentoring" and then click on the clipboard, and get that link to your mentor.  Get this to your hoped for mentor, and they can get started.

If you only know this mentor because of your interaction on platform, it might be nice to go back to an exercise where they did mentor you, and ask them if it is OK to send them a mentor link for the exercise you want them to mentor.  Let them know what the exercise is, because at the moment we click on that link, but we do not know what exercise it is.

Please let me know if that helped, or if there is something more that I can help figure out with you.

The current information in your request does not give a track, so I can not at the moment even alert the track mentors that you are wanting attention.  So having the mentor username here as well as the track language would be helpful.

**Comment by kotp** [comment]
Closing as this is now 3 weeks old, and I am hoping that it was helpful.  Leaving it open will not change that, but feel free to let me know if you need more information.  Let us know if it was helpful!
