### ISSUE TITLE
Python / Little Sister's Vocabulary - output = test output, but still fails? :(

### ISSUE THREAD

**Issue by spyingcyclops** [exercism/exercism#6204]
Hi,
Newbie here, so this is likely my error, but I cannot get my head around why the tests are failing. My output looks identical to expected output from test. I can't get it submitted, so can't access mentoring... :(

Might be a bug in the test? Likely not, but at this stage, I'm willing to try anything... Thanks!!

[pythone/exercises/little-sisters-vocabulary](https://exercism.org/tracks/python/exercises/little-sisters-vocab/)

function:

```python
def make_word_groups(vocab_words):
    prefix = vocab_words.pop(0)
    longwords = []
    for i in vocab_words:
        longwords.append(prefix + i)
        x = " :: ".join(longwords)
    print(prefix + " :: " + x)
```
```text
TEST FAILURE
AssertionError: None != 'auto :: autodidactic :: autograph :: aut[95 chars]aphy' : Expected auto :: autodidactic :: autograph :: automate :: autochrome :: autocentric :: autocomplete :: autoecholalia :: autoencoder :: autobiography 
```

but got something else instead.

```plain
YOUR OUTPUT

auto :: autodidactic :: autograph :: automate :: autochrome :: autocentric :: autocomplete :: autoecholalia :: autoencoder :: autobiography
```

**Comment by BethanyG** [comment]
Hi @spyingcyclops 👋🏽 

Python maintainer here.  Thanks for logging this issue. 🌟   Two quick notes:

1.  If you need help with anything related to the Python track or exercises, you can always open an issue in the [Python Repo](https://github.com/exercism/python).  We're happy to answer questions there, and provide tips and help.
2.  If you are ever stuck with an exercise in the UI, and can't access a mentor, it is possible to use the [exercism CLI](https://exercism.org/docs/using/solving-exercises/working-locally) and upload a partial solution to request mentoring.   So if you would rather not file an issue in Git Hub, that is one additional way to get unstuck.

Now for your issue.  It is indeed confusing -- because you **have** produced data that should pass the tests (_good work, you!_).  But if you take a closer look at the complaints from the test runner you'll see:

`AssertionError: None != 'auto :: autodidactic :: autograph :: aut[95 chars]aphy'`

This error means that when the tests called your `make_word_groups()` function, the result (_data_) that was given back to the calling code was the value `None`.   `None` was not the expected value to be returned. 

`None` in Python is the default `return` value for a function that does not otherwise have an explicit `return` statement defined.  And your function _**doesn't**_ have a `return` statement defined.  Instead, the final line of the function has a `print()` statement.  

`print()` sends output to `stdout` -- "standard out" -- which on many systems displays in the terminal or REPL, but can also be a file.  Our tests aren't designed to check/run against `stdout`.  Instead, they require explicit `return` statements, so that the data is given directly back to the process that calls the function or class.  Right now, for all of our exercises, we leave `stdout` (`print()`) for the coder to use for debugging.

Notice that the UI shows that `YOUR OUTPUT == auto :: autodidactic :: autograph :: automate :: autochrome :: autocentric :: autocomplete :: autoecholalia :: autoencoder :: autobiography`.  That means that our test runner captured what was printed in the terminal, and transferred it back out to the UI, assuming that you wanted to see that for debugging.

The good news?  _This is probably a really simple fix!_.  I suspect that if you change your code to:

```python
def make_word_groups(vocab_words):
    prefix = vocab_words.pop(0)
    longwords = []
    
    for i in vocab_words:
        longwords.append(prefix + i)
    
   x = " :: ".join(longwords)
   return  prefix + " :: " + x
```

You'll be getting the tests to pass in no time.  😄   However, should you encounter more issues, please ping me -- we can work through them together.

**Comment by spyingcyclops** [comment]
Hey BethanyG,
thank you so much for the explanation. I followed your advice, and of
course it passed :)
So I just need to pay more attention to the output of my code - return vs
print.

Thank you, and kudos to the exercism team - this is an awesome initiative.

Cheers

SpyingCyclops

**Comment by ErikSchierboom** [comment]
Great! Thanks @BethanyG
