### ISSUE TITLE
Create new track for [HTML/CSS]

### ISSUE THREAD

**Issue by Rubio6321** [exercism/exercism#6224]

**Comment by Rubio6321** [comment]
I was looking around the website and I saw that there is no part about HTML & CSS. I would appreciate Support for HTML & CSS.

**Comment by kytrinyx** [comment]
Thanks for the suggestion @Rubio6321.

Exercism's current goal and scope is to help people become fluent in programming languages. HTML and CSS aren't generally considered programming languages, as they're used to define what should be in a page, and what it should look like, but not what it should actively *do*, and therefore they fall outside of the scope of Exercism.

Some people will argue that CSS is a programming language because it is turing complete. Since it's not actually used that way in practice (or only within a _very_ limited scope), we've decided to consider it "not a programming language" for our purposes.
