### ISSUE TITLE
Centralized enable comments settings

### ISSUE THREAD

**Issue by DeepspaceFreelancer** [exercism/exercism#6279]
I can enable comments for each exercise, but there is no way to have it enabled by default.

There is this article how to do it:

* https://exercism.org/blog/introducing-community-comments

but could not find it or it is broken.

Please update the article about the current possibilities.

**Comment by angelikatyborska** [comment]
Hi! Thanks for the input. It's definitely valid, and a lot of people agree with you - there are already similar issues: https://github.com/exercism/exercism/issues/5953 and https://github.com/exercism/exercism/issues/5987

Feel free to add your opinions there and subscribe to them to get updates. I'm going to close this one because we want to avoid duplicates.
