### ISSUE TITLE
Trouble with Fruit Picker project

### ISSUE THREAD

**Issue by leerohrer1** [exercism/exercism#6317]
Hello, 

I'm not sure if there's a problem with the project or if I'm doing something wrong, but when I try to throw a new error, I get this message: 
![Screenshot 2022-04-05 08 37 39](https://user-images.githubusercontent.com/99694297/161768464-fb275acf-f465-4d98-92f3-6129bc43038b.png). 

I read that I should not have to download anything (here: 
![Screenshot 2022-04-05 08 43 57](https://user-images.githubusercontent.com/99694297/161768661-6eacc8d4-32c5-4006-98e7-e2d5b329ea8a.png) ), but I may misunderstand!

Are you able to offer any guidance for me to move forward with the project?

Thank you!
Lee

**Comment by SleeplessByte** [comment]
New experimental features _are_ enabled, but not _all_ experimental features. This particular one is not turned on, because it's not yet in a stable-ish stage in the [TC39 process](https://tc39.es/).

Writing `? throw new Error('...')` isn't idiomatic JavaScript (at the moment), so you'll want to rewrite that to an `if` statement, for example using an early `return` (in this case `throw`):

```javascript
if (expression) {
  throw new Error(...)
}

return expression
```

**Comment by leerohrer1** [comment]
Thank you so much!
