### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by julietugo** [exercism/exercism#6344]
The Readme file of Exercism does not have many details. For a great site like Exercism, it should be clear from the readme file what it does. Visitors should be able to understand what the website is all bout from the information on the readme file.

I want to update and add all the details that should be on the page. I will make it a comprehensive readme page for exercise.

Can this be assigned to me?

Thanks.

**Comment by kytrinyx** [comment]
@julietugo Thank you for your interest in this.

The entry point for people to use Exercism is https://exercism.org/ -- this has been thoroughly designed, discussed, and iterated upon to be a good place to start.

The README is one possible starting point for _contributing_ to Exercism (the more common entry point for contributing is https://exercism.org/contributing). As such, we don't think that it is necessary to explain what Exercism is in the README in this repository. If someone is seeing the README, it's almost certainly because they are familiar with Exercism, and are looking to contribute.

I'm going to close this as `wont-fix`, but if you think there are particular details that should be added, please explain what those details are in the comments below, and we can discuss further.
