### ISSUE TITLE
Lasagna Master Golang Exercise returns exit code 2

### ISSUE THREAD

**Issue by MikeHarris105** [exercism/exercism#6371]
I am enjoying learning go with exercism. I am now trying to do the lasagna master exercise: https://exercism.org/tracks/go/exercises/lasagna-master I think that there is something failing in the exercise as whenever I create a PreparationTime function that returns an int, as is required. This is returned: 
`FAIL	lasagna [build failed]
'/usr/local/go/bin/go test --short --json .' returned exit code 2: exit status 2`
I am trying to complete this test in the editor in the browser. I am using chrome on macos. I have tried pasting some of the community solutions and they also return this error. Is there something that needs fixing on this exercise?

for example:
`func PreparationTime(layer []string, time int) int {
    if time == 0 {
        time = 2
    }
	return len(layer) * time
}`

Returns:
`# lasagna [lasagna.test]
./lasagna_master_test.go:123:28: undefined: Quantities
./lasagna_master_test.go:156:4: undefined: AddSecretIngredient
./lasagna_master_test.go:205:11: undefined: ScaleRecipe
FAIL	lasagna [build failed]
'/usr/local/go/bin/go test --short --json .' returned exit code 2: exit status 2`

**Comment by iHiD** [comment]
(cc @exercism/go)

**Comment by junedev** [comment]
@MikeHarris105 The example and output you shared look correct to me.
Go is a compiled language and what you see there are compiler errors. You can ignore the `FAIL lasagna [build failed] '/usr/local/go/bin/go test --short --json .' returned exit code 2: exit status 2` part, that only means "tests did not compile". Focus on the bit above that. The tests cannot actually be executed yet and the messages there tell you why.

This exercise is the first time you run into this because here the stub (start file) does not contain the function signatures yet. Since the exercise is about functions, providing the signatures did not make sense.

There are two ways to deal with the exercise and the errors you see. You can try to solve the whole exercise first and then run the tests and see what errors you have left at that point. Alternatively, you can first write the minimal code necessary so there are no more compiler errors, i.e. write all the function signatures first and return some value from them so the compiler is happy.

We (the maintainers of the Go track) are aware that we don't have a good introduction to compiled vs interpreted languages and how to deal with compiler errors yet. We haven't found a good place for this content yet. It is something we definitely plan to improve in the future. 

Similar issue discussed here: https://github.com/exercism/go-test-runner/issues/48.

**Comment by MikeHarris105** [comment]
Thank you so much. I am now making progress on the exercise :)

**Comment by junedev** [comment]
@MikeHarris105 Happy to hear that. Would be great if you could close this issue then. (I don't have permissions on this repository to do this for you.)

**Comment by MikeHarris105** [comment]
Thank you for your help
