### ISSUE TITLE
Member Badge

### ISSUE THREAD

**Issue by NhanAZ** [exercism/exercism#6393]
I have lost my Member badge, can I get it back? :<
This is my public profile: https://exercism.org/profiles/NhanAZ/badges

**Comment by iHiD** [comment]
Impressive. No idea! @ErikSchierboom ?

**Comment by ErikSchierboom** [comment]
@iHiD Turns out there are 960 users without this badge. You can find them via: 

```ruby
User.where.not(id: User::AcquiredBadge.where(badge: Bad
ge.find_by(type: 'Badges::MemberBadge')).select(:user_id))
```

There are two paths in where this badge is awarded: the GitHub auth one and the Exercism registration one. It looks like it is not specific to any path:

```ruby
users.partition{|u| u.github_username.nil?}.map(&:size)
=> [358, 602]
```

I've just manually run the badge awarding for @NhanAZ (without the sending an email option) and the badge should now be there again (provided you've revealed it).

@ihid Shall I wait with the others to see if we can figure out the bug?

**Comment by NhanAZ** [comment]
Thank you so much @ErikSchierboom !
The Member badge is back to me.
Looks like my badge got lost as soon as I did a Reset of my account. I'm not sure anymore. :thinking:

**Comment by ErikSchierboom** [comment]
> Looks like my badge got lost as soon as I did a Reset of my account. I'm not sure anymore. 

Ah, that's useful information! Thanks.

**Comment by ErikSchierboom** [comment]
Resetting your account did indeed cause this behavior. I've created a PR to fix this: https://github.com/exercism/website/pull/2698/files

**Comment by ErikSchierboom** [comment]
@iHiD I've run the following script to make sure that for the affected users, all the badges they should have kept have been restored:

```ruby
User
  .where.not(id: User::AcquiredBadge.where(badge: Badge.find_by(type: 'Badges::MemberBadge')).select(:user_id))
  .find_each do |user|
    Badge.find_each do |badge|
        AwardBadgeJob.perform_later(user, badge.name, send_email: false)
    end
end
```
