### ISSUE TITLE
`Community Solutions` Issues

### ISSUE THREAD

**Issue by NhanAZ** [exercism/exercism#6396]
I'm not sure if this is intentional or not?
But I can easily access `Community Solutions` by adding the suffix `/solutions` to the end of the link.

![image](https://user-images.githubusercontent.com/60387689/172229821-3cc8a94b-06a7-44dc-b346-4d4aff2adc8d.png)

**Comment by kytrinyx** [comment]
Yes, this is intentional.

Since Exercism is about individually driven/motivated learning, it is up to each person whether or not they want to look at community solutions before they've solved a problem themselves. We don't add a link to it in the UI since we think that the learning experience is better if you don't look.

I'm going to go ahead and close this, but thanks for taking the time to ask about it!
