### ISSUE TITLE
The Community Solutions are available without solving the exercise

### ISSUE THREAD

**Issue by kstrifonoff** [exercism/exercism#6411]
The "Community Solutions" button is disabled by default, and so I'm guessing I shouldn't be able to see the community's solutions until I've solved the exercise. But actually I can do it by changing the url directly in the browser.

**Repro Steps:**
1.  Start an exercise without a successful solution.
2. Make sure the "Community Solutions" button in the UI is disabled (cannot be clicked).
3. Replace the URL in the browser by adding the path "/solutions", for example: `https://exercism.org/tracks/rust/exercises/sublist` -> `https://exercism.org/tracks/rust/exercises/sublist/solutions`

**Expected:**
1. Community solutions are not available

**Actual:**
1. Community solutions can be seen

**Comment by SleeplessByte** [comment]
Hi there,

Thanks for reporting this. This is expected as explained in https://github.com/exercism/exercism/issues/6378, https://github.com/exercism/exercism/issues/6257, https://github.com/exercism/exercism/issues/5848, https://github.com/exercism/exercism/issues/5398, and originally mentioned that this is a feature in https://github.com/exercism/exercism/issues/5850.

You can always see a "passing example" on github (because it's required for the CI to pass), and we don't mind if people cheat. They ultimately only affect their _own_ experience.

Closing this as a duplicate!
