### ISSUE TITLE
Solutions in Gophers  Gorgeous Lasagna

### ISSUE THREAD

**Issue by wr125** [exercism/exercism#6428]
unable to click on Community Solutions 
![overview](https://user-images.githubusercontent.com/20228047/177174441-9115cef1-76cf-4983-8a62-c038cdd3d7b4.png)
in order to find solutions to complete parameter of the function.

**Comment by kytrinyx** [comment]
Hi @wr125, this is intentional.

The community solutions will be available to look at once you've solved the exercise. The goal here is for you to figure out how to solve the exercise on your own. The community solutions will allow you to compare what you have done to what others have done, which can sometimes provide new insights to learn from.

Are you finding it difficult to solve the exercise on your own?

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, but please do let us know how things go!
