### ISSUE TITLE
When tracks/x/exercises loads, it immediately re-fetches the exercises

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#6505]
It shouldn't do this 🙂

**Comment by SleeplessByte** [comment]
You should, but you should set the timestamp in react-query.

- Set the initial data with a timestamp, and a short `staleTime` (e.g. 5 minutes)
- It won't refetch because it's still fresh (staleTime)
- When you come back to the page from background or different tab after a long time but it's still in memory it will refetch!
