### ISSUE TITLE
Consider not running analyzer/representer for solutions that fail the tests

### ISSUE THREAD

**Issue by junedev** [exercism/exercism#6510]
In a Slack conversation with @ErikSchierboom, he mentioned that we currently always run the analyzer and representer if the track has one, even if the solution does not pass the tests.
Erik shared the following code snippet:
```
def init_services
      Submission::TestRun::Init.(submission) if submission.tests_not_queued? && solution.exercise.has_test_runner?
      Submission::Representation::Init.(submission) if solution.track.has_representer?
      Submission::Analysis::Init.(submission) if solution.track.has_analyzer?
    end
```

This has the advantage that theoretically the tooling could return feedback for failing tests and the waiting time for the feedback after the exercise submission is reduced.

In practice, I am not aware any track provides feedback on code that does not pass tests (or does not even compile in case of compiled languages). Also, if I understand the flow correctly, on the website a student would never see analyzer/representer feedback for something that does not pass the tests as the respective area on the page only shows up after the submission which is not possible with failed tests. (CLI submission might be different.)

Erik also mentioned the analyzer and representer are usually quite fast and I imagine there are a lot more failed test runs than successful ones. That made me wonder whether we could save some resources/money by only running other tools after the test run was successful and accepting that getting the analyzer/representer feedback potentially takes a little bit longer.

**Comment by iHiD** [comment]
Good thing to discuss. Thanks!

The flow is currently optimised to get auto-feedback back to a student ASAP. So they hit "run tests" in the browser, get a pass, hit "Submit" and we want to then give them immediate feedback ideally. If we only run the analyzer/representer once the tests have passed, then we reduce the likelyhood that that feedback is ready for them. This will be even more important with the new flow we're discussing where the feedback is in a modal etc.

If the tests fail, we do cancel the runs of the analyzer and representer if they've not already started, which means we tend to end up with the situation that if we have availability we run all three, but if there is a queue, the others may get cancelled.

It's also worth noting that we don't spawn resources on demand. We have 10 tooling runners that sit there waiting for jobs, so ti doesn't cost us anything to run an extra analysis. The downside is that it puts something else in the queue which slows things for the next person.

When we eventually switch to Lambda (if AWS ever make it so that we can) then I thin this would become really important as it then saves cost. For now, I'm less sure it's a good priority to try to optimise further.

---

> Also, if I understand the flow correctly, on the website a student would never see analyzer/representer feedback for something that does not pass the tests as the respective area on the page only shows up after the submission which is not possible with failed tests. 

This is true for both editor and CLI FYI.

**Comment by junedev** [comment]
I wasn't aware of the cancellation system. With that plus the fixed resources, this is not a priority indeed. Feel free to close the issue.

**Comment by iHiD** [comment]
@junedev I've just revisited this and realised that I've actually already done what your suggesting. The code Erik posted is from when an **Iteration** is created, not a **submission**. You can only create an iteration in the browser once the tests pass, and it's only normal to submit an iteration via the CLI when they pass too. 

For other editor submissions, we only run the tests, not the analyser and the representer too.

So I think a past version of myself did decide to optimise this in that way afterall :)
