### ISSUE TITLE
Feature Discussion: Approaches

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#6520]
_This is my summary of what was discussed on the weekly community call and my opinions on how we should go about implementing it. Please have a read and leave thoughts 🙂_

---

For a while we've been discussing the idea of **"Approaches"** - a feature that shows different approaches to how an exercise can be solved. In the Cohorts we've been trialling, the live-streaming of solving of exercises has been one of the most fun and interesting features and it's become apparent to me that we should try and integrate this more deeply into Exercism. I feel like the intersection of these two things is really interesting. There has been lots of enthusiasm for this (from maintainers, video-creators, and students) and so I'd like to find a really lightweight way to try it out.

Roughly, we're looking at the following features:
- Explain to students different approaches that can be taken, discussing pros/cons/differences for each.
- Watch people solve an exercise using certain approaches and work through their thinking as they go.

An [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) of this seems to me to be the following:
- A tab on an Exercise for Approaches...
- ...containing some overarching information, and maybe an overarching video...
- ...and links to different solutions (each with their own title, commentary and associated video)

We have a lot of this (non-video) content already in students' community solutions and in mentor notes. @glennj and @bobahop discussed on a call recently about how it would be nice to be able to put all their notes somewhere that could be more publicly seen (we're considering a separate wiki-style approach for mentors to see each others' stuff) but I think this is also a great way of extracting student-facing value out of those notes too.

Rather than linking out to community solutions directly, I feel it would be better to embed those solutions alongside an exercise in the track repo - this insulates us against the community solutions changing or being deleted. We can then also have the content stored alongside those solutions in the track repo.

I'd also like to find a way to incorporate different people's approaches and videos, but ensure there's some barrier of quality-control. Ideally we'd have some community-voting system and showcase the best ones, but I feel like that's a lot of work to do upfront, so for now I'd rather we manually curate things.

## A sample spec

A structure might look like this
- `/exercises/practice/bob/`
  - `/approaches`
    - `config.json`
    - `introduction.md`
    - `oop/`
      - `solution.rb`
      - `explanation.md`
    - `functional/`
      - `solution.rb`
      - `explanation.md`

With a `config.json` looking like:
```json
{
  "solutions": {
    "oop": { 
      "uuid": "xxx",
      "authors": ["iHiD", "junedev"],
      "videos": [ 
        {
          "host": "youtube",
          "id": "asd123",
          "title": "Exploring an OOP approach to Bob",
          "description": "A look into how strictly we can adhere to OOP principles while solving Bob."
        }
      ]
    },
    "functional": { 
      "uuid": "yyy",
      "authors": ["erikschierboom"]
    }
  }
}
```

I'm not strong at all on this being **the** structure, but I think it should incorporate at least these elements, with `introduction.md`, a `config.json` and at least one example being the required minimal elements.

## Key questions

- How do we choose which solutions are used? What are the gatekeeping/acceptance rules? Who does that gatekeeping?(e.g. maintainers, mentors, community team)?
- How do we choose which videos get used?  What are the gatekeeping/acceptance rules? Who does that gatekeeping?(e.g. maintainers, mentors, community team)?
- Which tracks want to try prototyping this? (With the knowledge things might change as we evolve!) - I think we'd require one enthusiastic person (probably someone who's mentored quite a bit) per track that wants this.
- What are the questions I've missed? 🙂 

---

**Please let me know you're thoughts!**

**Comment by MatthijsBlom** [comment]
Would Approaches information be available to the student before or after submitting a first passing solution?

Exercism's focus on language fluency rather than problem solving ability suggests _before_, and I'd be fine with that.

---

Approaches exist on at least two levels:

- A 'higher' level: problem-specific but language-**agnostic**
- A 'lower' level: problem-specific language-**specific**

Some problems are heavy on higher-level approaches, like those involving primes, but also the simpler Collatz exercise (i.e. iteration vs. recursion). These problems might benefit from shared-among-language-tracks resources.

Many problems aren't very interesting in themselves, and would be helped most with language-specific resources.

---

> I feel it would be better to embed those solutions alongside an exercise in the track repo

I agree.

> Ideally we'd have some community-voting system and showcase the best [approaches and videos]

This is not my ideal. Or at least I do not have any idea how to do this right, even in principle. I am fearful of a scenario similar to the state of stars in the community solutions right now.

---

> How do we choose which solutions are used? What are the gatekeeping/acceptance rules?

I trust the track maintainers to do a good job at gatekeeping (and organizing).

I expect (i.e. anticipate, _not_ desire) that maintainers and mentors will be the foremost producers of approaches, as their exposure to solution variety is greatest.

**Comment by andrerfcsantos** [comment]
I really like this idea and it will be a great feature of Exercism. Seeing some other people's solution is great, but some solutions really benefit from having an additional explanation attached to it. One site I've seen do this well is [binarysearch](https://binarysearch.com/) where after submitting a solution, each person can attach an explanation to it. I really like that model, and I think "Approaches" could be a curated version of that.

> How do we choose which solutions are used? What are the gatekeeping/acceptance rules? Who does that gatekeeping?(e.g. maintainers, mentors, community team)?

I see this as a potential effort between maintainers and mentors. For some approaches, I see the possibility of new solutions having to be created by maintainers/mentors. This can happen if:

- No student's current solution for the exercise fits into one particular approach.
- We want to change an existing solution to better fit one approach.
- Maybe we want to combine ideas from different solutions to make a "perfect" solution for one approach

However, if we see that for one approach there's already a solution by some student that already fits the approach perfectly, we might want to use that and give credit to the student? How does the attribution works then if the "exemplar" for the approach has to be created by maintainers/mentors?

Another thought related to this: we might want to have a single "exemplar" solution for each approach that we curate, but for exercises that have approaches, maybe we can let each student "tag" their solutions as belonging to one approach?

> How do we choose which videos get used? What are the gatekeeping/acceptance rules? Who does that gatekeeping?(e.g. maintainers, mentors, community team)?

I also see this as a potential effort between maintainers and mentors. The acceptance rules for me would be:

- Video has to be in English. We might also want to add support for other languages, but in that case the videos should have some kind of tag saying its language. I'm thinking of the Elixir track, where I feel a lot of the community is from Brazil and already have some content on youtube, but it's in Portuguese. But I think just accepting English at the start is acceptable. Accepting videos in other languages would also require some mentor/maintainer of that track to also speak that language so they can review it.
- The video should explain the decisions taken and some of the tradeoffs of that particular approach. It shouldn't just show the solution.
- (Optional, but greatly appreciated) Some quick introduction of the problem to provide some context and make sure that everyone is on the same page. The video should assume people watching read the problem description, but a quick "in this problem we have to do x and to do that, we are going to try this approach"

> Which tracks want to try prototyping this?

Count me in to do this for Go :) Depending on the exercise, I might also be able to do some content for Python.

> What are the questions I've missed? 🙂

**How to deal with different approaches that are somewhat related?**

I feel that for some exercises, some approaches are related. An example of this would be when an approach B is an improvement on approach A. There might still be value in showing both approaches, but for approach B we might want to say that is "an improvement" on approach A, and similarly, on approach A, we can say that approach B is better or has tradeoffs in a different direction. Is just saying things like this in the explanation for the approaches enough?

What I'm thinking is that for some situations, we might even want to aggregate several approaches into one explanation. for instance, we can say "to solve X, we can try the really simple approach Y. But the simple approach Y has some problems, that we can fix with approach Z..."

**Should we also allow students' to add their own explanations to solutions?**

I think having some manually-curated approaches for some exercises is great. One thing that we can also do additionally is let students' submit an explanation of their approach in a solution, maybe in addition to tagging their solution as belonging to one approach. I see the following advantages of doing this:

- Readers of the solution could have more insights in the solution they are reading, regardless if the solution was chosen to be manually curated or not.
- A good solution with a good explanation might have more people starring it, and most starred solutions that have explanations might be good candidates for maintainers/mentors to manually curate it.
- If the student already put a good description on a solution, the work for maintainers would be easier, as it would just be a matter of taking the solution and explanation and give it more exposure on the "approaches" tab.

**Comment by bobahop** [comment]
Of course, we already have a mechanism where a student can attach their explanation for the approach they took, which is the comments, which are now turned off by default. Any student who would like to explain themselves can do that now in a non-curated (or, perhaps more accurately, a "community-curated") little forum of comments on their solution. I say "their solution", but it's possible they copied it from elsewhere. They might still be able to explain how it works, though.

To me, an advantage to curated approaches is to address what @junedev and @BethanyG discussed in Slack about teaching problem-solving. Where there _are_ comments for solutions, they often discuss why a particular bit of code was used, or maybe just express an appreciation for an elegant approach without really describing why the approach is elegant (vs. other approaches) or what steps were taken to arrive at it. It occurs to me that approaches don't necessarily have to relate to any particular exercise. I mean, someone could solve some particular problem at work and be particularly pleased with how they did it. There may be some value to presenting their story/video in a place where students could search for the problem outside of it being something related to an exercise. Perhaps that would take it beyond the scope of Exercism, or perhaps it would be an acceptable broadening of Exercism's scope.

**Comment by andrerfcsantos** [comment]
@bobahop I feel that comments are not a good place to put explanations of the solution and I'd prefer to see them highlighted next to the solution in a proper way, similarly to how binarysearch does it. Comments could then be about the solution itself and the explanation and one could have comments disabled, but still have the explanation up.

<details>
<summary>Binarysearch explanation example</summary>
![image](https://user-images.githubusercontent.com/6928620/186354260-06b54853-aeb9-40f2-ae29-1204cc913f4f.png)
The fields "intuition", "implementation", "time complexity" and "space complexity" are present in every explanation. We don't need to be so strict in exercism, but having certain fields could be a good way to guide teaching problem solving.
</details>

**Comment by iHiD** [comment]
- How do we deal with approaches and community solutions competition in the UI
- Approach "widgets" (quick link and a whole solution codeblock)
- Tag submissions with `approach_id`
- After submission, say "You used X approach, check out ABC too"

**Comment by BethanyG** [comment]
@andrerfcsantos @iHiD  -- I would be happy to pilot this on the Python track (_she says in a moment of insanity_).

**Comment by MatthijsBlom** [comment]
@iHiD I cannot make out from your list what is meant by «approach widgets», «`approach_id`». Is there a transcript?

@BethanyG I am insane as well: I'd like to help, but dare not promise anything for perpetual want of energy. I imagine though that authoring of approaches can be outsourced to the numerous Python mentors, who doubtless are already full of ideas.

**Comment by junedev** [comment]
Here my thoughts as mentioned in the call (additional to the notes from Jeremy above) and some more:
* We should think through how approaches would play together with whatever new system we might have for mentor notes. Currently, the content would overlap. At a minimum, the mentor should be able to get to approaches quickly from the mentoring screen as seeing some good solutions already helps a lot with mentoring.
* I strongly feel like approaches should _not_ be only a click away before someone solved the exercise. They should be handled like community solutions are handled today (locked until the exercise was solved). Sidenote: To be fair though, there is an argument to be made that newer research shows that seeing/reading a lot of good solutions to problems is also a very good way of learning something. But still, I think the muddling through on your own and learn that way part is very much was Exercism is built on.
* My favorite UI would be that community solutions are somewhat below the approaches so that we first present the curated, good code.
* It would be good if there would be a way to mark non-idiomatic/fun/wild approaches. I think they are a great part of Exercism but it should be very clear that those approaches should not be used in real life. However, I don't think we should make the label system to fine grained, just one simple tag or icon for distiguishing "real" from "fun" solutions should be enough.
* I like the idea of separating the video content a bit more and making it clear that it might not reflect the latest version of the exercise.
* CI should run against the approaches solutions to make sure they pass the latest tests (or there should be some way to mark them as outdated in the UI if they are not passing anymore as mentioned in the call by someone).
* The folder names for the approaches should be free text, not fixed categories.
* Approaches should only exist for practice exercises. For learning exercises, the exemplar + the introduction should be all the explanation that is needed. If a learning exercises surfaces multiple approaches, that is rather a sign the instructions should clarify what should be practiced.

In terms of product mgmt, I would recommend to not try to do everything at once. Let's start with just the parts we need for showing approaches in the UI. Things like determining approaches, tagging submissions etc can be tackled later on.

**Comment by kotp** [comment]
Having the community solutions is good, but seeing community solutions that look like your own is not as helpful as it could be.  It would be nice, since we are talking about approaches, to be able to look at other solutions that do not look like your own solution, so that you can hopefully see things that you may not know.
