### ISSUE TITLE
PR created by exercism-bot on newly bootstrapped track fails configlet workflow

### ISSUE THREAD

**Issue by glennj** [exercism/exercism#6523]
See https://github.com/exercism/jq/pull/2

**Comment by glennj** [comment]
@ErikSchierboom this  probably belongs on your desk.

**Comment by kytrinyx** [comment]
I will take a look at this one.

**Comment by kytrinyx** [comment]
@glennj I'm thinking that the right move here is to update the "getting started" checklist so that the first item is to add the correct tags. Does that sound reasonable to you? Or were you thinking of something else?

**Comment by kytrinyx** [comment]
Hm, no. You already got `main` sorted so that it passes the linting, so the PR was probably opened against `main` before it was passing.

**Comment by kytrinyx** [comment]
We've fixed the files in the bootstrapping repository for now so that they match what is in the org-wide-files repository.

In the longer term, we're thinking about updating `configlet` to only output warnings about missing tags if a track's status is set to `inactive`: https://github.com/exercism/configlet/issues/601

I'm going to close this, as the actionable bits have been captured elsewhere.

**Comment by glennj** [comment]
Thanks!
