### ISSUE TITLE
add yaml in exercism

### ISSUE THREAD

**Issue by codehangen** [exercism/exercism#6549]
Hi all. 

I would like to help and contribute to this organization. I would like to create a repository here for yaml exercises. *Would it be possible?*

**Comment by kytrinyx** [comment]
Hi @codehangen, thank you so much for wanting to help contribute!

Exercism's current focus is to provide exercises for languages that are generally accepted to be programming languages. Most people consider YAML to be a markup language rather than a programming language. While you it certainly can be useful in automating tasks, it is not a good fit for the type of courses and exercises that we provide at Exercism. (The same is true for JSON, CSS, and HTML, which are also often requested).

As such I'm going to go ahead and close this issue.

Please do check out https://exercism.org/contributing if you want to see if there are some tasks that appeal to you!
