### ISSUE TITLE
Create new track for Haxe

### ISSUE THREAD

**Issue by arctenis** [exercism/exercism#6606]
From official website : Haxe is an open source high-level strictly-typed programming language with a fast optimizing cross-compiler.

Haxe can build cross-platform applications targeting JavaScript, C++, C#, Java, JVM, Python, Lua, PHP, Flash, and allows access to each platform's native capabilities. Haxe has its own VMs (HashLink and NekoVM) but can also run in interpreted mode.

[Website](https://haxe.org/)

**Comment by iHiD** [comment]
Hey! There's already [a haxe track](/exercism/haxe) very close to being launched 🙂 

@ErikSchierboom Could you take a look at what's required to get that over the line pls? It looks like it has enough exercises and a test runner? 

(cc @kytrinyx and @jonathandmiddleton too 🙂)

**Comment by ErikSchierboom** [comment]
Looking at the [new track checklist](https://exercism.org/docs/building/tracks/new), we are indeed very close.
Whilst testing the track, I found a couple of things for which I've created PRs:

- Change indent size to correct default: https://github.com/exercism/haxe/pull/221
- Add contents to shared docs: https://github.com/exercism/haxe/pull/222
- Enable the test runner: https://github.com/exercism/haxe/pull/220
- Fix invalid field name being using in test runner: https://github.com/exercism/haxe-test-runner/pull/15

Once those PRs are merged, I think the track might actually be able to launch. As it has been some time since someone worked on the track, I think it would be a good idea to soft launch the track and ask maintainers to try it out first.
Finding some mentors might be key to a good experience for students too.
There is also a representer that might work, but I haven't yet tested.
