### ISSUE TITLE
Create a track for SQL

### ISSUE THREAD

**Issue by adel3li** [exercism/exercism#6688]

**Comment by glennj** [comment]
Thanks for the request @adel3li 

Creating language tracks on Exercism is done by volunteers, and it requires a large commitment of time. Creating an SQL track is an order of magnitude larger because the current set of exercises aren't particularly relevant for database scenarios: a whole new set of exercises needs to be invented.

There are Exercism contributors who would also like to see an SQL track (or several probably, for different flavours of SQL), but nobody has yet committed to it.

**Comment by adel3li** [comment]
thanks @glennj . well, I am welling to commit to it. what do I have to do?
