### ISSUE TITLE
Should we really have skipped tests in the assignments?

### ISSUE THREAD

**Issue by etrepum** [exercism/exercism#856]
When completing exercises for languages that skip tests, it's easy to forget that you must remove all of the skips. What's the benefit to having these skips at all?

Another reason to remove them would be to make it easier to do continuous integration for our assignments. If we were to do this and leave skips in, we'd have to transform the code in Ruby to remove the lines with skip, in Javascript we'd have to rewrite some functions that start with x, in some other languages we'd have to remove comments (but only the comments that are really code!), etc.

**Comment by iHiD** [comment]
> what if the test runner was just a fail early type thing? You get the same output, but you only get one failure (the first one).

So I think it's **essential** that there is only one test that fails each time. I personally like the whole `skip` approach. I also like the "fail early" test runner that achieves the same thing. However, we would need to write that for each language and that feels maybe like a lot of work?

I've reopened the discussion as a lot has changed over time and it's worth rechecking the thinking from 4 yrs ago :)

**Comment by katrinleinweber** [comment]
Thanks for continuing the discussion :-)

**Comment by j2jensen** [comment]
My two cents:

1. I didn't notice anything in the initial instructions about "how to run tests" (C# or Python track) that mentioned I would need to change the test code to activate the skipped tests, and I submitted my Leap exercise in C# before noticing that tests were being skipped. One of the first Leap submissions I mentored included the tests in their submission, and they hadn't removed the Skips from their tests. So that's two out of the two data points I've seen saying it's not extremely obvious that there's an extra step you're expected to take.
2. The Tests tab in the mentoring interface shows the tests with Skips in them, and if you download a user's solution the tests have skips in them. So in order to do the most basic check that all the tests are passing, mentors have to perform a manual step with every single submission. I'll admit that I resorted to eyeballing the code and assuming they passed all the tests if the logic looked right to me, but there's a decent chance that neither the submitter nor the mentor is actually checking that all tests pass before approving a submission.
3. If we want to promote TDD, it seems like we should encourage users to write their own tests, separate from the ones we're using to "grade" them by. I don't think that's what we're going for, though.
4. If people want to follow a TDD-ish pattern without writing their own tests, they're free to do so. The test results are reported in order, so they can just write a simple solution and watch one test pass, then improve it and watch the next test pass, and so on.
5. If people don't want to follow a TDD-ish pattern, then we're forcing them to take an extra, tedious step to un-skip all the tests. I doubt most users are actually un-skipping one test at a time: they're probably just going into the test file and removing all the Skips before running the tests.
6. When I came here looking for a discussion about skipping, I noticed that the most recent Issue posted was #4455 . I imagine we'll be getting a lot of duplicate issues like this, because having the tests skipped does not appear to be the expected behavior for most users.

So while I recognize the intent in encouraging people to play around with the test class, I think mentioning that they are encouraged to do so in the instructions might be a better approach. And while I understand the desire to avoid hitting people with a barrage of failed test cases right off the bat, I don't think it's that big a deal compared to the down-sides.

**Comment by iHiD** [comment]
Re the documentation, this is something we should probably bake into the actual site better, rather than rely on individual tracks to get right. I don't know how we do that though.

I would recommend trying the hello world in ruby, as if you'd not done exercism before. Just download and run the test file and see what happens. It's quite a good process.

**Comment by iHiD** [comment]
>  I also like the "fail early" test runner that achieves the same thing. However, we would need to write that for each language and that feels maybe like a lot of work?

@kytrinyx What are your thoughts on us spiking this for one or two languages as a prototype to see if it improves things for those languages. If so, we could then have it as a project that the OSS community can roll out for each language?

**Comment by kytrinyx** [comment]
> I'm not sure what the settings are for minitest by default now-a-days. I'm very much for a fail-fast test runner, but as I said above, that feels like a lot of work.

For minitest you have several options, none of them are appropriate for us. Default is "run everything in random order". You can set the tests to be in a deterministic order, but that order happens to be "alphabetical by test name". There is no fail fast.

A few years ago I wrote a plugin for minitest (it was gross, I don't think I even published it) which would allow you to keep the order as "whatever was defined in the file", and which also did fail fast.

I hesitate to suggest that we write our own dependency for something like this, because it means we have to maintain it forever and I am already feeling the weight of maintaining existing code... on the other hand I am convinced that having a way to fail fast in the order defined would be a significantly better user experience than the skipping, which is fraught with all sorts of user experience hurdles.

> We could prepend `z-a` to the test names to have the first test be reported last on the console.

That's a good point. This would work for minitest too, which means that if zenspider would be ok with a flag or something that sets fail-fast, we would all set in Ruby.

**Comment by kenliu** [comment]
Personally I really like that the tests are skipped by default on the ruby track, and it's not very cumbersome to unskip them one at a time (`ctrl-/` to uncomment).

**Comment by blueglyph** [comment]
Redirected here from #301.

I'm with the OP on that one.

TDD is an interesting concept but it's not didactic, doesn't encourage someone to focus on a problem but instead to 'mess around' with code until it finally (or hopefuly?) passes the tests. Whereas a specification of a problem to solve gives a direct understanding of what must be done, and the developer has all the data to think of an architecture and execute it properly.

Also in regards with TDD, what if the test suite are incomplete? Will the developer be happy with himself not using a bit of common sense, but following tests and releasing an incomplete product?

As for the 'noise' mentioned in the 2nd post, that's usually how it works in a real job. You get partial information with a lot of noise, from several people with different priorities, and it's up to you to crystallize a specification and validate it with the stakeholders. But this is another story. Giving a clear problem description is no noise, I encourage you to look at the problems on Hackerrank for a good example. If the problem is not clear or incomplete, they tune it after the feedback, the end result is rather clean and efficient.

They also go one step further (which may answer other concerns in this thread), and hide the actual tests except the first obvious ones. When you encounter a failure, you have to think about what is missing instead of hacking your solution from the test code. It helps with one major problem people have today, they don't pay attention to the problem/task description.

Deducing code from a problem description is also how most interviews are conducted. Watch at the Google interviews, they give a problem, let the person explain how to solve it (the architecture is elaborated), write the code (execution), then add more constraints to the problem to push in one or another direction (Agile-like thinking).

So in the end, I see no positive reason to use TDD, especially in a learning environment. And certainly not with a step-by-step approach, which really seems a recipe for chaotic results: how can you possibly choose the correct tools without knowing the whole story, and by guessing from partial results?

Regarding the test suite, it seems from the discussions that it has two purposes, 1) to let the student verify the answer, and 2) to check the exercise module is working in non-regression tests. Either way, it better be complete from the start, ignoring some of the tests can only lead to problems (but that's already been said).

My 2 cents, I see that it has been discussed at length already.
